# -*- coding: utf-8 -*-
"""
/***************************************************************************
 Calibracion_LAI
                                 A QGIS plugin
 Este modulo permite calibrar todos los parametros asociados al LAI, permite descargar imagenes Modis, interpolar la precipitacion y temperatura para las diferentes coberturas
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2024-07-17
        copyright            : (C) 2024 by The Nature Conservancy
        email                : Miguel.canon@tnc.org
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load Calibracion_LAI class from file Calibracion_LAI.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .Calibracion_LAI import Calibracion_LAI
    return Calibracion_LAI(iface)
