# -*- coding: utf-8 -*-
"""
/***************************************************************************
 Calibracion_LAIDockWidget
                                 A QGIS plugin
 Este modulo permite calibrar todos los parametros asociados al LAI, permite descargar imagenes Modis, interpolar la precipitacion y temperatura para las diferentes coberturas
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2024-07-17
        git sha              : $Format:%H$
        copyright            : (C) 2024 by The Nature Conservancy
        email                : Miguel.canon@tnc.org
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
"""
import sys
import os
import random
import glob
import pandas as pd
import numpy as np
import rasterio
from datetime import datetime
from PyQt5.QtWidgets import QFileDialog, QMessageBox
from qgis.PyQt import QtGui, QtWidgets, uic
from qgis.PyQt.QtCore import pyqtSignal,QTimer, QDate, QObject, QDateTime
from qgis.core import QgsProject, QgsRasterLayer, QgsVectorLayer
from pyproj import Proj
import pyproj
import geopandas as gpd
from pymodis import downmodis
from statsmodels.tsa.seasonal import seasonal_decompose
import statsmodels.api as sm
from affine import Affine
from osgeo import gdal
from rasterio.warp import calculate_default_transform, reproject, Resampling
from .functions.spotpy_setup_LAI import *
import spotpy
import matplotlib.pyplot as plt
from qgis.PyQt.QtWidgets import QGraphicsScene, QVBoxLayout, QPushButton, QHBoxLayout
from matplotlib.backends.backend_qt5agg import FigureCanvasQTAgg
import time


FORM_CLASS, _ = uic.loadUiType(os.path.join(
    os.path.dirname(__file__), 'Calibracion_LAI_dockwidget_base.ui'))

class ProgressSignal(QObject):
    progress = pyqtSignal(int)

import logging
class StreamToLogger:
    def __init__(self, progress_signal):
        self.progress_signal = progress_signal

    def write(self, buf):
        for line in buf.splitlines():
            if line.strip():
                self.handle_line(line)

    def handle_line(self, line):
        # Busca líneas que contengan "of" y actualiza el progreso
        if "of" in line:
            try:
                parts = line.split(',')
                iter_info = parts[0].strip().split()
                iter_num = int(iter_info[0])
                total_num = int(iter_info[2])
                progress = int((iter_num / total_num) * 100)
                self.progress_signal.progress.emit(progress)
            except (ValueError, IndexError):
                pass

    def flush(self):
        pass

class Calibracion_LAIDockWidget(QtWidgets.QDockWidget, FORM_CLASS):

    closingPlugin = pyqtSignal()

    def __init__(self, parent=None):
        """Constructor."""
        super(Calibracion_LAIDockWidget, self).__init__(parent)
        self.setupUi(self)

        # step 1 - descarga imagenes modis
        self.select_output.clicked.connect(self.select_output_path)
        self.Button_Load_Dem.clicked.connect(self.load_dem)
        self.Run_Download.clicked.connect(self.run_download)
        self.Button_Step_2.clicked.connect(self.go_to_step_2)

        # step 2 - procesamiento de datos MODIS
        self.Run_process_modis.clicked.connect(self.run_process_modis_data)
        self.Button_Load_Lulc.clicked.connect(self.load_lulc)
        self.Run_process_Zonal.clicked.connect(self.run_zonal_statistics)
        self.Run_process_Moving.clicked.connect(self.run_process_moving_average)
        self.Button_Load_Stations.clicked.connect(self.load_shapefile_stations)
        self.Button_Load_Excel.clicked.connect(self.load_excel_time_series)
        self.Run_process_Tmax.clicked.connect(self.run_process_tmax)
        self.Run_process_Tmin.clicked.connect(self.run_process_tmin)
        self.Run_process_PT.clicked.connect(self.run_process_pt)
        self.Export_result.clicked.connect(self.save_results_to_excel)

        self.Button_Step_3.clicked.connect(self.go_to_step_3)


        # step 3 - Calibracion
        self.Run_process_LAI.clicked.connect(self.run_process_lai)
        # Conectar los botones de zoom
        self.zoom_in_button.clicked.connect(self.zoom_in)
        self.zoom_out_button.clicked.connect(self.zoom_out)

        self.zoom_in_button_2.clicked.connect(self.zoom_in_2)
        self.zoom_out_button_2.clicked.connect(self.zoom_out_2)


        self.Run_process_LAI_end.clicked.connect(self.run_process_lai_end)
        self.Export_result_2.clicked.connect(self.export_result)

        # Signal de progreso
        self.progress_signal = ProgressSignal()
        self.progress_signal.progress.connect(self.progressBar_process_LAI.setValue)
        self.progress_signal_end = ProgressSignal()
        self.progress_signal_end.progress.connect(self.progressBar_process_LAI_end.setValue)
        self.RESULT = {}
        self.processed_coverages = set()


    # funciones step 1 descarga de imagenes modis

    #### funciones step 1 descarga de imagenes modis #############################

    def select_output_path(self):
        output_path = QFileDialog.getExistingDirectory(self, "Select Output Directory")
        if output_path:
            self.output_path.setText(output_path)

    def load_dem(self):
        dem_path, _ = QFileDialog.getOpenFileName(self, "Select DEM File", "", "Raster files (*.tif *.img *.vrt)")
        if dem_path:
            self.Path_raster.setText(dem_path)
            self.dem_layer = QgsRasterLayer(dem_path, "Digital Elevation Model")
            if not self.dem_layer.isValid():
                QMessageBox.critical(self, "Error", "The selected DEM file is not valid.")
            else:
                QgsProject.instance().addMapLayer(self.dem_layer)

    def create_outputs_folders(self, path_out, name_project):
        main_folders = ['temp']
        inside_folders = ['03-Phenology']

        project_path = os.path.join(path_out, name_project)

        for main_folder in main_folders:
            main_folder_path = os.path.join(project_path, main_folder)
            os.makedirs(main_folder_path, exist_ok=True)

            if main_folder == 'temp':
                for inside_folder in inside_folders:
                    inside_folder_path = os.path.join(main_folder_path, inside_folder)
                    os.makedirs(inside_folder_path, exist_ok=True)

        return project_path

    def run_download(self):
        project_name = self.name_project.text()
        output_path = self.output_path.text()
        dem_path = self.Path_raster.text()
        start_date = self.start_date.date().toString("yyyy-MM-dd")
        end_date = self.end_date.date().toString("yyyy-MM-dd")

        if not project_name or not output_path or not dem_path:
            QMessageBox.warning(self, "Input Error", "Please provide all necessary inputs.")
            return

        project_path = self.create_outputs_folders(output_path, project_name)

        PathOutputs = os.path.join(project_path, 'temp', '03-Phenology', 'MODIS')
        os.makedirs(PathOutputs, exist_ok=True)

        self.DownloadLAI_MODIS(PathOutputs, dem_path, start_date, end_date)

    def DownloadLAI_MODIS(self, PathOutputs, PathRaster, start_date, end_date):
        tiles = self.raster_to_modis_tiles(PathRaster)
        product = "MOD15A2H.061"
        modis_downloader = downmodis.downModis(destinationFolder=PathOutputs,
                                               tiles=tiles,
                                               product=product,
                                               today=end_date,
                                               enddate=start_date,
                                               delta=1,
                                               user='nogales',
                                               password='1121940694No')
        modis_downloader.connect()

        days = modis_downloader.getListDays()
        total_files = len(days)
        self.progressBar_Download.setMaximum(total_files)
        QMessageBox.information(self, "Download to start", "Please keep the window open until the process is finished.")

        for i, day in enumerate(days):
            listAllFiles = modis_downloader.getFilesList(day)
            listFilesDown = modis_downloader.checkDataExist(listAllFiles)
            modis_downloader.dayDownload(day, listFilesDown)
            self.progressBar_Download.setValue(i + 1)

        self.progressBar_Download.setValue(total_files)
        QMessageBox.information(self, "Download Complete", "MODIS LAI data download completed.")

    def raster_to_modis_tiles(self, PathRaster, sample_size=100):
        def lonlat_to_modis_tile(lon, lat):
            tile_width = 10.0
            tile_height = 10.0
            lon_min = -180.0
            lat_max = 90.0
            h = int((lon - lon_min) / tile_width)
            v = int((lat_max - lat) / tile_height)
            return h, v

        with rasterio.open(PathRaster) as src:
            crs = src.crs
            transform = src.transform
            width = src.width
            height = src.height
            sample_coords = [(random.randint(0, height - 1), random.randint(0, width - 1)) for _ in range(sample_size)]
            coords = [rasterio.transform.xy(transform, row, col, offset='center') for row, col in sample_coords]

        if not crs.is_geographic:
            proj_raster = Proj(crs)
            proj_wgs84 = Proj(init="epsg:4326")
            coords = [pyproj.transform(proj_raster, proj_wgs84, x, y) for x, y in coords]

        modis_tiles = set(lonlat_to_modis_tile(lon, lat) for lon, lat in coords)
        return ','.join([f"h{h:02d}v{v:02d}" for h, v in modis_tiles])

    def go_to_step_2(self):
        self.tabWidget.setCurrentIndex(1)
    #### funciones step 2 procesamiento de datos MODIS #############################

    def run_process_modis_data(self):
        PathOutputs = os.path.join(self.output_path.text(),self.name_project.text() , 'temp', '03-Phenology', 'MODIS')
        QMessageBox.information(self, "Process to start", "Please keep the window open until the process is finished.")
        self.process_modis_data(PathOutputs, self.Path_raster.text())
        QMessageBox.information(self, "Process Modis Complete", "MODIS LAI to raster completed.")

    def process_modis_data(self, destination_folder, reference_raster):
        hdf_files = glob.glob(os.path.join(destination_folder, "*.hdf"))

        date_files = {}
        for hdf_file in hdf_files:
            date_str = os.path.basename(hdf_file).split('.')[1][1:8]
            if date_str not in date_files:
                date_files[date_str] = []
            date_files[date_str].append(hdf_file)

        total_files = len(date_files)
        self.progressBar_modis.setMaximum(total_files)

        for i, (date_str, files) in enumerate(date_files.items()):
            vrt_path = os.path.join(destination_folder, f"mosaic_{date_str}.vrt")
            temp_raster = os.path.join(destination_folder, f"temp_raster_{date_str}.tif")
            output_raster = os.path.join(destination_folder, f"MODIS_{date_str}.tif")

            self.convert_mosaic_to_raster(files, vrt_path, temp_raster, subdataset_name='Lai_500m')
            self.resample_to_match(temp_raster, reference_raster, output_raster)

            print(f"Exportado raster: {output_raster}")

            os.remove(vrt_path)
            self.progressBar_modis.setValue(i + 1)

        self.progressBar_modis.setValue(total_files)

    def convert_mosaic_to_raster(self,hdf_files, vrt_path, output_raster, subdataset_name='Lai_500m'):
        subdatasets = [f'HDF4_EOS:EOS_GRID:"{f}":MOD_Grid_MOD15A2H:{subdataset_name}' for f in hdf_files]
        vrt_options = gdal.BuildVRTOptions(separate=False)
        vrt = gdal.BuildVRT(vrt_path, subdatasets, options=vrt_options)

        # Convertir el archivo VRT a un raster GeoTIFF
        gdal.Translate(output_raster, vrt, format='GTiff')

    def resample_to_match(self, src_path, match_path, dst_path):
        with rasterio.open(src_path) as src:
            src_transform = src.transform
            src_crs = src.crs
            src_width = src.width
            src_height = src.height

            with rasterio.open(match_path) as match:
                match_transform = match.transform
                match_crs = match.crs
                match_width = match.width
                match_height = match.height

                if src_crs != match_crs:
                    src_crs = match_crs
                    src_transform, src_width, src_height = calculate_default_transform(
                        src_crs, match_crs, src_width, src_height, *src.bounds)

                kwargs = src.meta.copy()
                kwargs.update({
                    'crs': match_crs,
                    'transform': match_transform,
                    'width': match_width,
                    'height': match_height
                })

                with rasterio.open(dst_path, 'w', **kwargs) as dst:
                    for i in range(1, src.count + 1):
                        reproject(
                            source=rasterio.band(src, i),
                            destination=rasterio.band(dst, i),
                            src_transform=src_transform,
                            src_crs=src_crs,
                            dst_transform=match_transform,
                            dst_crs=match_crs,
                            resampling=Resampling.nearest)

    def load_lulc(self):
        lulc_path, _ = QFileDialog.getOpenFileName(self, "Select LULC File", "", "Raster files (*.tif *.img *.vrt)")
        if lulc_path:
            self.Path_Lulc.setText(lulc_path)
            self.lulc_layer = QgsRasterLayer(lulc_path, "Digital Elevation Model")
            if not self.dem_layer.isValid():
                QMessageBox.critical(self, "Error", "The selected DEM file is not valid.")
            else:
                QgsProject.instance().addMapLayer(self.lulc_layer)

    def run_zonal_statistics(self):
        PathLULC = self.Path_Lulc.text()
        PathOutputs = os.path.join(self.output_path.text(),self.name_project.text(), 'temp', '03-Phenology', 'MODIS')
        PathExcel = os.path.join(self.output_path.text(),self.name_project.text(), 'temp', '03-Phenology', 'TS_LAI_LULC.xlsx')
        QMessageBox.information(self, "Process to start", "Please keep the window open until the process is finished.")
        self.zonal_statistics(PathLULC, PathOutputs, PathExcel)
        QMessageBox.information(self, "Process Complete", "Zonal Statistics completed.")

    def zonal_statistics(self, coverage_raster_path, modis_directory, output_excel_path):
        with rasterio.open(coverage_raster_path) as src:
            coverage_data = src.read(1)
            coverage_meta = src.meta

        coverage_codes = np.unique(coverage_data)
        coverage_codes = coverage_codes[coverage_codes != coverage_meta['nodata']]

        lai_series = {code: [] for code in coverage_codes}
        dates = []

        modis_files = sorted([f for f in os.listdir(modis_directory) if f.startswith('MODIS_') and f.endswith('.tif')])
        total_files = len(modis_files)
        self.progressBar_Zonal.setMaximum(total_files)

        for i, modis_file in enumerate(modis_files):
            date_str = modis_file.split('_')[1].split('.')[0]
            year = int(date_str[:4])
            julian_day = int(date_str[4:])
            date = self.julian_to_date(year, julian_day)
            dates.append(date)
            modis_path = os.path.join(modis_directory, modis_file)

            with rasterio.open(modis_path) as src:
                modis_data = src.read(1)
                modis_meta = src.meta

            for code in coverage_codes:
                mask = coverage_data == code
                if np.any(mask):
                    lai_mean = np.mean(modis_data[mask])
                    lai_series[code].append(lai_mean)
                else:
                    lai_series[code].append(np.nan)

            self.progressBar_Zonal.setValue(i + 1)

        Factor = 0.1
        df = pd.DataFrame(lai_series , index=pd.to_datetime(dates))* Factor
        df.index.name = 'Date'
        df.to_excel(output_excel_path, engine='openpyxl')
        self.progressBar_Zonal.setValue(total_files)

    def julian_to_date(self, year, julian_day):
        date = datetime.strptime(f"{year}{julian_day:03d}", "%Y%j")
        return date

    def run_process_moving_average(self):
        PathExcel = os.path.join(self.output_path.text(),self.name_project.text(), 'temp', '03-Phenology', 'TS_LAI_LULC.xlsx')
        PathExcel1 = os.path.join(self.output_path.text(),self.name_project.text(), 'temp', '03-Phenology', 'TS_LAI_LULC_Movil.xlsx')
        window_size = int(self.Path_WS.text())
        QMessageBox.information(self, "Process to start", "Please keep the window open until the process is finished.")
        self.calculate_moving_average(PathExcel, PathExcel1, window_size)
        QMessageBox.information(self, "Process Complete", "Moving Averange completed.")

    def calculate_moving_average(self, input_excel_path, output_excel_path, window_size):
        df = pd.read_excel(input_excel_path, index_col='Date', parse_dates=True)
        df = df.fillna(df.mean())

        reconstructed_df = pd.DataFrame(index=df.index)

        for col in df.columns[1:]:
            LAI_data = df[col]
            result = seasonal_decompose(LAI_data, model='additive', period=46)
            trend = result.trend
            seasonal = result.seasonal
            reconstructed_series = trend + seasonal
            reconstructed_df[col] = reconstructed_series

        moving_averages = reconstructed_df.rolling(window=window_size).mean()
        moving_averages.to_excel(output_excel_path, engine='openpyxl')

    def load_shapefile_stations(self):
        shapefile_path, _ = QFileDialog.getOpenFileName(self, "Select Shapefile", "", "Shapefiles (*.shp)")
        if shapefile_path:
            self.Path_Shp_Stations.setText(shapefile_path)
            layer = QgsVectorLayer(shapefile_path, "Estaciones", "ogr")
            if not layer.isValid():
                QMessageBox.critical(self, "Error", "No se pudo cargar la capa de estaciones.")
            else:
                QgsProject.instance().addMapLayer(layer)

    def load_excel_time_series(self):
        excel_path, _ = QFileDialog.getOpenFileName(self, "Select Excel File", "", "Excel files (*.xlsx)")
        if excel_path:
            self.Path_excel_time_series.setText(excel_path)

    def run_process_tmax(self):
        elev = self.get_elevation()
        path_df = self.Path_excel_time_series.text()
        path_meta = self.Path_Shp_Stations.text()
        output_excel_path = os.path.join(self.output_path.text(), self.name_project.text(), 'temp', '03-Phenology',
                                  'TAmax.xlsx')


        df_meta = gpd.read_file(path_meta).set_index('codigo')

        df_meta_tmax = df_meta[df_meta['TAmax'] == 1]
        df_inTmax = pd.read_excel(path_df, 'TAmax', index_col=0)
        df_new_Tmax = self.Series_X_Y(df_meta_tmax, df_inTmax, 'TAmax')
        QMessageBox.information(self, "Process to start", "Please keep the window open until the process is finished.")
        progress_signal = ProgressSignal()
        progress_signal.progress.connect(self.progressBar_Tmax.setValue)

        df_out_Tmax = self.temperatura(elev, df_new_Tmax, progress_signal)
        df_out_Tmax.to_excel(output_excel_path, engine='openpyxl')
        QMessageBox.information(self, "Process Complete", "Tmax completed.")
        self.df_out_Tmax = df_out_Tmax

    def run_process_tmin(self):
        elev = self.get_elevation()
        path_df = self.Path_excel_time_series.text()

        path_meta = self.Path_Shp_Stations.text()
        output_excel_path = os.path.join(self.output_path.text(), self.name_project.text(), 'temp', '03-Phenology',
                                  'TAmin.xlsx')


        df_meta = gpd.read_file(path_meta).set_index('codigo')

        df_meta_tmin = df_meta[df_meta['TAmin'] == 1]
        df_in_Tmin = pd.read_excel(path_df, 'TAmin', index_col=0)
        df_new_T_min = self.Series_X_Y(df_meta_tmin, df_in_Tmin, 'TAmin')
        QMessageBox.information(self, "Process to start", "Please keep the window open until the process is finished.")
        progress_signal = ProgressSignal()
        progress_signal.progress.connect(self.progressBar_Tmin.setValue)
        df_out_Tmin = self.temperatura(elev, df_new_T_min, progress_signal)
        df_out_Tmin.to_excel(output_excel_path, engine='openpyxl')
        QMessageBox.information(self, "Process Complete", "Tmin completed.")
        self.df_out_Tmin = df_out_Tmin

    def run_process_pt(self):
        elev = self.get_elevation()
        path_df = self.Path_excel_time_series.text()
        path_meta = self.Path_Shp_Stations.text()
        path_raster = self.Path_Lulc.text()
        output_excel_path = os.path.join(self.output_path.text(), self.name_project.text(), 'temp', '03-Phenology',
                                  'PV.xlsx')


        df_meta = gpd.read_file(path_meta).set_index('codigo')
        df_meta_Pt = df_meta[df_meta['PV'] == 1]
        df_inPt = pd.read_excel(path_df, 'PV', index_col=0)
        df_new_PT = self.Series_X_Y(df_meta_Pt, df_inPt, 'PV')
        QMessageBox.information(self, "Process to start", "Please keep the window open until the process is finished.")
        progress_signal = ProgressSignal()
        progress_signal.progress.connect(self.progressBar_PT.setValue)
        df_out_PT = self.Interpolacion_PT(df_new_PT, path_raster, progress_signal)
        df_out_PT.to_excel(output_excel_path, engine='openpyxl')
        QMessageBox.information(self, "Process Complete", "PT completed.")
        self.df_out_PT = df_out_PT

    def get_elevation(self):
        return self.elevaciones(self.Path_raster.text(), self.Path_Lulc.text())

    def Series_X_Y(self, catalogo, df, var):
        if var == 'TAmax' or var == 'TAmin':
            cols_select = ['y', 'x', 'z']
        else:
            cols_select = ['y', 'x']

        data = df.loc[df.index[0]:].T
        columnas = data.columns
        str_list = [d.strftime('%Y-%m-%d') for d in columnas]
        data.index = [int(d1) for d1 in data.index]
        data.columns = str_list
        df_new = catalogo[cols_select]
        data.index.name = 'codigo'
        df_new.index = [int(d2) for d2 in df_new.index]
        df_new = df_new.merge(data, left_index=True, right_index=True)

        return df_new

    def elevaciones(self, path_dem, path_lulc):
        with rasterio.open(path_lulc) as src:
            coverage_data = src.read(1)
            coverage_meta = src.meta

        with rasterio.open(path_dem) as src:
            Dem_data = src.read(1)
            Dem_meta = src.meta

        coverage_codes = np.unique(coverage_data)
        coverage_codes = coverage_codes[coverage_codes != coverage_meta['nodata']]
        elv_series = {code: [] for code in coverage_codes}
        for code in coverage_codes:
            mask = coverage_data == code
            if np.any(mask):
                lai_mean = np.mean(Dem_data[mask])
                elv_series[code].append(lai_mean)
            else:
                elv_series[code].append(np.nan)

        df_elv = pd.DataFrame(elv_series)
        return df_elv.T

    def temperatura(self, Elevacion, Series_ts, progress_signal=None):
        fechas = Series_ts.columns[3:]

        Series_ts[Series_ts == -999] = np.NAN
        data = Series_ts[fechas].interpolate(axis=1)

        x = Series_ts['z']
        X = sm.add_constant(x, prepend=False)

        Cuencas = Elevacion.index
        df_result = pd.DataFrame(columns=Cuencas, index=fechas)

        total_steps = len(fechas)
        if progress_signal:
            progress_signal.progress.emit(0)

        for i, f in enumerate(fechas):
            print(f)
            model = sm.OLS(data[f], X, missing='drop')
            statistics = model.fit()
            coefficient_A = statistics.params[0]
            coefficient_B = statistics.params[1]

            df_ele_aligned = Elevacion.reindex(Cuencas)
            values = coefficient_A * df_ele_aligned[0] + coefficient_B
            df_result.loc[f] = values

            if progress_signal:
                progress_signal.progress.emit(int((i + 1) / total_steps * 100))

        return df_result

    def IDW(self, x, y, z, nx, ny, xmax, xmin, ymax, ymin, power=2):
        def distancia(x, y, xi, yi):
            obs = np.vstack((x, y)).T
            interpolar = np.vstack((xi, yi)).T
            d0 = np.subtract.outer(obs[:, 0], interpolar[:, 0])
            d1 = np.subtract.outer(obs[:, 1], interpolar[:, 1])
            Md = np.hypot(d0, d1)
            return Md

        def malla(xmax, xmin, ymax, ymin, nx, ny):
            xi = np.linspace(xmin, xmax, nx)
            yi = np.linspace(ymin, ymax, ny)
            xi, yi = np.meshgrid(xi, yi)
            xi, yi = xi.flatten(), yi.flatten()
            return xi, yi

        xi, yi = malla(xmax, xmin, ymax, ymin, nx, ny)
        dist = distancia(x, y, xi, yi)
        W = 1.0 / dist**power
        W /= W.sum(axis=0)
        zi = np.dot(W.T, z)
        zi = zi.reshape(nx, ny)
        return xi, yi, zi

    def pixel(self, xmax, xmin, ymax, ymin, nx, ny):
        pixelWidth = abs(xmin - xmax) / nx
        pixelHeight = abs(ymin - ymax) / ny
        return pixelWidth, pixelHeight

    def Interpolacion_PT(self, Pt_Series, path_raster, progress_signal=None, Nx=None, Ny=None):
        fechas = Pt_Series.columns[2:]

        with rasterio.open(path_raster) as src:
            coverage_data = src.read(1)
            bounds = src.bounds
            coverage_meta = src.meta

        if Nx is None and Ny is None:
            nx = src.shape[0]
            ny = src.shape[1]
        else:
            nx = Nx
            ny = Ny

        coverage_codes = np.unique(coverage_data)
        coverage_codes = coverage_codes[coverage_codes != coverage_meta['nodata']]
        PT_series = {code: [] for code in coverage_codes}

        total_steps = len(fechas)
        if progress_signal:
            progress_signal.progress.emit(0)

        for i, ft in enumerate(fechas[:]):
            print(ft)

            y = Pt_Series['y']
            x = Pt_Series['x']
            z = Pt_Series[ft]

            xmin = bounds.left
            xmax = bounds.right
            ymin = bounds.bottom
            ymax = bounds.top

            xi, yi, zi = self.IDW(x, y, z, nx, ny, xmax, xmin, ymax, ymin)
            pixelW, pixelH = self.pixel(xmax, xmin, ymax, ymin, nx, ny)
            transform = Affine(pixelW, 0.0, xmin, 0.0, -pixelH, ymax)
            nodata = -9999
            zi[np.isnan(zi)] = nodata
            array = np.flipud(zi)
            for code in coverage_codes:
                mask = coverage_data == code
                if np.any(mask):
                    masked_zi = zi[mask]
                    if masked_zi.size > 0:
                        lai_mean = np.mean(masked_zi)
                    else:
                        lai_mean = np.nan
                    PT_series[code].append(lai_mean)
                else:
                    PT_series[code].append(np.nan)

            if progress_signal:
                progress_signal.progress.emit(int((i + 1) / total_steps * 100))

        df = pd.DataFrame(PT_series, index=pd.to_datetime(fechas))
        df.index.name = 'Date'
        return df

    def save_results_to_excel(self):
        path_input =os.path.join(self.output_path.text(), self.name_project.text(), 'temp', '03-Phenology/')

        PathOutput = os.path.join(self.output_path.text(),self.name_project.text(), 'temp', '03-Phenology/')

        files = ['TAmin', 'TAmax', 'PV']
        xlsx = pd.ExcelWriter(PathOutput+'MeteoData.xlsx')
        for file in files:
            df = pd.read_excel(path_input+file+'.xlsx')
            if file == 'PV':
                name = 'P'
            else:
                name = file
            df.to_excel(xlsx, name)
        xlsx.close()
        QMessageBox.information(self, "Process Complete", "Export completed.")

    def go_to_step_3(self):
        self.update_spinBox_values()
        self.tabWidget.setCurrentIndex(2)

    #### funciones step 3 Calibracion #############################

    def update_spinBox_values(self):
        PathProject = os.path.join(self.output_path.text(), self.name_project.text(), 'temp', '03-Phenology')
        P = pd.read_excel(os.path.join(PathProject, 'MeteoData.xlsx'), sheet_name='P')
        P['Date'] = pd.to_datetime(P['Date'], format='%d/%m/%Y')
        P.set_index('Date', inplace=True)
        code_lulc = P.columns

        self.spinBox.clear()  # Limpiar valores existentes
        for value in code_lulc:
            self.spinBox.addItem(str(value))

    def run_process_lai(self):
        # import spotpy_setup_LAI as spotpy_setup
        self.progressBar_process_LAI.setValue(1)

        QMessageBox.information(self, "Start Process", "Parameter scanning process is about to start, ")
        # Obtener los valores de las entradas del usuario
        NumIter = int(self.QNumIter.text())
        period = int(self.QPeriod.text())
        OmitObs = int(self.QOmitObs.text())
        SOS1 = int(self.QSOS1.text())
        SOS2 = int(self.QSOS1_2.text())
        ft_sup_min = float(self.Qft_sup_min.text())
        ft_sup_max = float(self.Qft_sup_max.text())

        PathProject = os.path.join(self.output_path.text(), self.name_project.text(), 'temp', '03-Phenology')

        # Cargar los datos necesarios
        P = pd.read_excel(os.path.join(PathProject, 'MeteoData.xlsx'), sheet_name='P')
        P['Date'] = pd.to_datetime(P['Date'], format='%d/%m/%Y')
        P.set_index('Date', inplace=True)


        Tmin = pd.read_excel(os.path.join(PathProject, 'MeteoData.xlsx'), sheet_name='Tmin')
        Tmin['Date'] = pd.to_datetime(Tmin['Date'], format='%d/%m/%Y')
        Tmin.set_index('Date', inplace=True)

        Tmax = pd.read_excel(os.path.join(PathProject, 'MeteoData.xlsx'), sheet_name='Tmax')
        Tmax['Date'] = pd.to_datetime(Tmax['Date'], format='%d/%m/%Y')
        Tmax.set_index('Date', inplace=True)

        LAI_Obs = pd.read_excel(os.path.join(PathProject, 'TS_LAI_LULC_Movil.xlsx'))
        LAI_Obs['Date'] = pd.to_datetime(LAI_Obs['Date'], format='%d/%m/%Y')
        LAI_Obs = LAI_Obs.dropna()
        LAI_Obs.set_index('Date', inplace=True)

        # Alinear los datos
        id = (Tmin.index >= LAI_Obs.index[0]) & (Tmin.index <= LAI_Obs.index[-1])
        Tmin = Tmin.iloc[id, :]
        Tmax = Tmax.iloc[id, :]
        P = P.iloc[id, :]

        LAI_Obs = pd.merge(pd.DataFrame(index=Tmax.index), LAI_Obs, left_index=True, right_index=True,
                           how='outer').interpolate()

        ETP = 1.0 * (100. * (8.0 / (365.0 * 12.0))) * ((0.46 * (Tmax + Tmin) / 2.0) + 8.13)
        SMI = P / ETP


        # Obtener el valor seleccionado de self.spinBox
        code_lulc = P.columns
        i = code_lulc.tolist().index(int(self.spinBox.currentText()))

        diccio_algorit = {'DDS': 1, 'LHS': 2, 'SCE': 3}
        Algorithm = diccio_algorit[self.Algorithm.currentText()]

        # Límites de parámetros de calibración
        t_inf_min = 5.0
        t_inf_max = 0.99 * np.min((Tmax.iloc[:, i].values + Tmin.iloc[:, i].values) / 2)
        lai_min_min = 0.95 * np.min(LAI_Obs.iloc[:, i])
        lai_min_max = 1.05 * np.min(LAI_Obs.iloc[:, i])
        f_lai_min = 0.95 * np.max(LAI_Obs.iloc[:, i]) / np.min(LAI_Obs.iloc[:, i])
        f_lai_max = 1.05 * np.max(LAI_Obs.iloc[:, i]) / np.min(LAI_Obs.iloc[:, i])
        l1_min = float(self.Ql1_min.text())
        l1_max = float(self.Ql1_max.text())
        l2_min = float(self.Ql2_min.text())
        l2_max = float(self.Ql2_max.text())
        l3_min = float(self.Ql3_min.text())
        l3_max = float(self.Ql3_max.text())
        PUA_Diff = Tmax.iloc[:, i].values - Tmin.iloc[:, i].values
        PUA_P = self.max_sum_in_windows(PUA_Diff, int(period))
        phu_min = PUA_P * 0.9
        phu_max = PUA_P * 1
        fr_phu_sen_min = float(self.Qfr_phu_sen_min.text())
        fr_phu_sen_max = float(self.Qfr_phu_sen_max.text())
        SMIc_min = 0.0
        SMIc_max = np.nanmax(SMI.iloc[:, i].values) * 0.8
        nSMI_min = float(self.QnSMI_min.text())
        nSMI_max = float(self.QnSMI_max.text())
        gdd_c_min = 0.0
        gdd_c_max = PUA_P

        Param_Min = [t_inf_min, ft_sup_min, lai_min_min, f_lai_min, l1_min, l2_min, l3_min, phu_min, fr_phu_sen_min,
                     SMIc_min, nSMI_min, gdd_c_min]
        Param_Max = [t_inf_max, ft_sup_max, lai_min_max, f_lai_max, l1_max, l2_max, l3_max, phu_max, fr_phu_sen_max,
                     SMIc_max, nSMI_max, gdd_c_max]

        Factor_ObjFun = -1 if Algorithm == 1 else 1
        Search_ObjFun = True if Algorithm == 1 else False

        model = VegetationGrowthModel(Param_Min, Param_Max, SOS1, SOS2, LAI_Obs.index.month,
                                                   Tmin.iloc[:, i].values, Tmax.iloc[:, i].values,
                                                   LAI_Obs.iloc[:, i].values, SMI.iloc[:, i].values, OmitObs,
                                                   Factor_ObjFun)
        PathParams = os.path.join(PathProject,   'Params_VegGrowthModel_' + str(code_lulc[i]))

        if Algorithm == 1:
            sampler = spotpy.algorithms.dds(model, dbname=PathParams, dbformat='csv')
        elif Algorithm == 2:
            sampler = spotpy.algorithms.lhs(model, dbname=PathParams, dbformat='csv')
        elif Algorithm == 3:
            sampler = spotpy.algorithms.sceua(model, dbname=PathParams, dbformat='csv')

        # Redirigir stdout
        old_stdout = sys.stdout
        sys.stdout = StreamToLogger(self.progress_signal)

        try:
            sampler.sample(NumIter)
        finally:
            sys.stdout = old_stdout

        self.progress_signal.progress.emit(100)

        results = spotpy.analyser.load_csv_results(PathParams)
        best_params_i = spotpy.analyser.get_best_parameterset(results, maximize=Search_ObjFun)

        Sim = PhenologicalModel(best_params_i[0], SOS1, SOS2, LAI_Obs.index.month, Tmin.iloc[:, i].values,
                                             Tmax.iloc[:, i].values, SMI.iloc[:, i].values)
        Obs = LAI_Obs.iloc[:, i].values

        Part_1 = np.sum((Obs - Sim[1:]) ** 2)
        Part_2 = np.sum((Obs - np.nanmean(Obs)) ** 2)
        NSE = (Part_1 / Part_2)
        print(NSE)

        self.show_graph(Obs, Sim[1:],LAI_Obs.index)
        self.save_graph(Obs, Sim[1:],LAI_Obs.index,'_Initial')
        QMessageBox.information(self, "Process Complete", "Check graph and adjust parameter range...")

    def max_sum_in_windows(self,series, window_size):
        max_sum = -np.inf
        for i in range(len(series) - window_size + 1):
            current_sum = series[i:i + window_size].sum()
            if current_sum > max_sum:
                max_sum = current_sum
        return max_sum

    def zoom_in(self):
        self.graphicsView.scale(1.2, 1.2)

    def zoom_out(self):
        self.graphicsView.scale(0.8, 0.8)

    def zoom_in_2(self):
        self.graphicsView_2.scale(1.2, 1.2)

    def zoom_out_2(self):
        self.graphicsView_2.scale(0.8, 0.8)

    def show_graph(self, Obs, Sim,index):
        name = self.spinBox.currentText()


        graphics_view_size = self.graphicsView.size()
        width = graphics_view_size.width()
        height = graphics_view_size.height()

        # Convertir el tamaño a pulgadas para Matplotlib (1 pulgada = 96 píxeles es una buena aproximación)
        figsize = (width / 96, height / 96)

        # figsize = (13, 8)
        size_line = 1.5
        s_n = 14
        fig, ax = plt.subplots(figsize=figsize)
        ax.plot(index, Obs, color='navy', linewidth=size_line, alpha=0.5, label="Observed LAI")
        ax.plot(index, Sim, color='darkred', linewidth=size_line, linestyle='--', alpha=0.9,label="Simulated LAI")
        ax.set_title('LAI Calibration Initial - lulc :' + str(name), fontsize=s_n + 2, fontweight='bold')
        ax.set_xlabel('Time', fontsize=s_n, fontweight='bold')
        ax.set_ylabel('LAI', fontsize=s_n, fontweight='bold')
        ax.legend(loc=1)
        plt.tight_layout()
        canvas = FigureCanvasQTAgg(fig)
        scene = QGraphicsScene()
        scene.addWidget(canvas)
        self.graphicsView.setScene(scene)
        self.graphicsView.show()

    def show_graph_end(self, Obs, Sim,index):
        name = self.spinBox.currentText()


        graphics_view_size = self.graphicsView.size()
        width = graphics_view_size.width()
        height = graphics_view_size.height()

        # Convertir el tamaño a pulgadas para Matplotlib (1 pulgada = 96 píxeles es una buena aproximación)
        figsize = (width / 96, height / 96)

        # figsize = (13, 8)
        size_line = 1.5
        s_n = 14
        fig, ax = plt.subplots(figsize=figsize)
        ax.plot(index, Obs, color='navy', linewidth=size_line, alpha=0.5, label="Observed LAI")
        ax.plot(index, Sim, color='darkred', linewidth=size_line, linestyle='--', alpha=0.9,label="Simulated LAI")
        ax.set_title('LAI Calibration Final- lulc :' + str(name), fontsize=s_n + 2, fontweight='bold')
        ax.set_xlabel('Time', fontsize=s_n, fontweight='bold')
        ax.set_ylabel('LAI', fontsize=s_n, fontweight='bold')
        ax.legend(loc=1)
        plt.tight_layout()
        canvas = FigureCanvasQTAgg(fig)
        scene = QGraphicsScene()
        scene.addWidget(canvas)
        self.graphicsView_2.setScene(scene)
        self.graphicsView_2.show()

    def save_graph(self, Obs, Sim,index,tipo):
        PathProject = os.path.join(self.output_path.text(), self.name_project.text(), 'temp', '03-Phenology')

        name = self.spinBox.currentText()


        figsize = (13, 8)
        size_line = 1.5
        s_n = 14
        fig, ax = plt.subplots(figsize=figsize)
        ax.plot(index, Obs, color='navy', linewidth=size_line, alpha=0.5, label="Observed LAI")
        ax.plot(index, Sim, color='darkred', linewidth=size_line, linestyle='--', alpha=0.9,label="Simulated LAI")
        ax.set_title('LAI Calibration - lulc :' + str(name), fontsize=s_n + 2, fontweight='bold')
        ax.set_xlabel('Time', fontsize=s_n, fontweight='bold')
        ax.set_ylabel('LAI', fontsize=s_n, fontweight='bold')
        ax.legend(loc=1)
        plt.tight_layout()

        new_folder = os.path.join(PathProject, 'Figuras/')
        os.makedirs(new_folder, exist_ok=True)
        name_out = os.path.join(new_folder, 'Fig_Cal_Lai_lulc_' + str(name)+tipo)

        plt.savefig(name_out , dpi=200)
        plt.close()

    def run_process_lai_end(self):
        QMessageBox.information(self, "Start Process", "LAI calibration process is about to start, wait for its completion., ")
        self.progressBar_process_LAI_end.setValue(1)
        NumIter_END = int(self.QNumIter_end.text())
        period = int(self.QPeriod.text())
        OmitObs = int(self.QOmitObs.text())
        SOS1 = int(self.QSOS1.text())
        SOS2 = int(self.QSOS1_2.text())
        ft_sup_min = float(self.Qft_sup_min.text())
        ft_sup_max = float(self.Qft_sup_max.text())

        PathProject = os.path.join(self.output_path.text(), self.name_project.text(), 'temp', '03-Phenology')

        # Cargar los datos necesarios
        P = pd.read_excel(os.path.join(PathProject, 'MeteoData.xlsx'), sheet_name='P')
        P['Date'] = pd.to_datetime(P['Date'], format='%d/%m/%Y')
        P.set_index('Date', inplace=True)

        Tmin = pd.read_excel(os.path.join(PathProject, 'MeteoData.xlsx'), sheet_name='Tmin')
        Tmin['Date'] = pd.to_datetime(Tmin['Date'], format='%d/%m/%Y')
        Tmin.set_index('Date', inplace=True)

        Tmax = pd.read_excel(os.path.join(PathProject, 'MeteoData.xlsx'), sheet_name='Tmax')
        Tmax['Date'] = pd.to_datetime(Tmax['Date'], format='%d/%m/%Y')
        Tmax.set_index('Date', inplace=True)

        LAI_Obs = pd.read_excel(os.path.join(PathProject, 'TS_LAI_LULC_Movil.xlsx'))
        LAI_Obs['Date'] = pd.to_datetime(LAI_Obs['Date'], format='%d/%m/%Y')
        LAI_Obs = LAI_Obs.dropna()
        LAI_Obs.set_index('Date', inplace=True)

        # Alinear los datos
        id = (Tmin.index >= LAI_Obs.index[0]) & (Tmin.index <= LAI_Obs.index[-1])
        Tmin = Tmin.iloc[id, :]
        Tmax = Tmax.iloc[id, :]
        P = P.iloc[id, :]

        LAI_Obs = pd.merge(pd.DataFrame(index=Tmax.index), LAI_Obs, left_index=True, right_index=True, how='outer').interpolate()

        ETP = 1.0 * (100. * (8.0 / (365.0 * 12.0))) * ((0.46 * (Tmax + Tmin) / 2.0) + 8.13)
        SMI = P / ETP

        # Obtener el valor seleccionado de self.spinBox
        code_lulc = P.columns
        i = code_lulc.tolist().index(int(self.spinBox.currentText()))

        diccio_algorit = {'DDS': 1, 'LHS': 2, 'SCE': 3}
        Algorithm = diccio_algorit[self.Algorithm.currentText()]

        # Límites de parámetros de calibración
        t_inf_min = 5.0
        t_inf_max = 0.99 * np.min((Tmax.iloc[:, i].values + Tmin.iloc[:, i].values) / 2)
        lai_min_min = 0.95 * np.min(LAI_Obs.iloc[:, i])
        lai_min_max = 1.05 * np.min(LAI_Obs.iloc[:, i])
        f_lai_min = 0.95 * np.max(LAI_Obs.iloc[:, i]) / np.min(LAI_Obs.iloc[:, i])
        f_lai_max = 1.05 * np.max(LAI_Obs.iloc[:, i]) / np.min(LAI_Obs.iloc[:, i])
        l1_min = float(self.Ql1_min.text())
        l1_max = float(self.Ql1_max.text())
        l2_min = float(self.Ql2_min.text())
        l2_max = float(self.Ql2_max.text())
        l3_min = float(self.Ql3_min.text())
        l3_max = float(self.Ql3_max.text())
        PUA_Diff = Tmax.iloc[:, i].values - Tmin.iloc[:, i].values
        PUA_P = self.max_sum_in_windows(PUA_Diff, int(period))
        phu_min = PUA_P * 0.9
        phu_max = PUA_P * 1
        fr_phu_sen_min = float(self.Qfr_phu_sen_min.text())
        fr_phu_sen_max = float(self.Qfr_phu_sen_max.text())
        SMIc_min = 0.0
        SMIc_max = np.nanmax(SMI.iloc[:, i].values) * 0.8
        nSMI_min = float(self.QnSMI_min.text())
        nSMI_max = float(self.QnSMI_max.text())
        gdd_c_min = 0.0
        gdd_c_max = PUA_P

        Param_Min = [t_inf_min, ft_sup_min, lai_min_min, f_lai_min, l1_min, l2_min, l3_min, phu_min, fr_phu_sen_min, SMIc_min, nSMI_min, gdd_c_min]
        Param_Max = [t_inf_max, ft_sup_max, lai_min_max, f_lai_max, l1_max, l2_max, l3_max, phu_max, fr_phu_sen_max, SMIc_max, nSMI_max, gdd_c_max]

        Factor_ObjFun = -1 if Algorithm == 1 else 1
        Search_ObjFun = True if Algorithm == 1 else False

        model = VegetationGrowthModel(Param_Min, Param_Max, SOS1, SOS2, LAI_Obs.index.month,
                                      Tmin.iloc[:, i].values, Tmax.iloc[:, i].values,
                                      LAI_Obs.iloc[:, i].values, SMI.iloc[:, i].values, OmitObs,
                                      Factor_ObjFun)
        PathParams = os.path.join(PathProject, 'Params_VegGrowthModel_' + str(code_lulc[i]))

        if Algorithm == 1:
            sampler = spotpy.algorithms.dds(model, dbname=PathParams, dbformat='csv')
        elif Algorithm == 2:
            sampler = spotpy.algorithms.lhs(model, dbname=PathParams, dbformat='csv')
        elif Algorithm == 3:
            sampler = spotpy.algorithms.sceua(model, dbname=PathParams, dbformat='csv')

        self.progress_signal_end.progress.emit(0)

        # Redirigir stdout
        old_stdout = sys.stdout
        sys.stdout = StreamToLogger(self.progress_signal_end)

        try:
            sampler.sample(NumIter_END)
        finally:
            sys.stdout = old_stdout

        self.progress_signal_end.progress.emit(100)

        results = spotpy.analyser.load_csv_results(PathParams)
        best_params = spotpy.analyser.get_best_parameterset(results, maximize=Search_ObjFun)

        self.RESULT[str(code_lulc[i])] = best_params
        self.processed_coverages.add(self.spinBox.currentText())

        Sim_end = PhenologicalModel(best_params[0], SOS1, SOS2, LAI_Obs.index.month, Tmin.iloc[:, i].values,
                                             Tmax.iloc[:, i].values, SMI.iloc[:, i].values)
        Obs_end = LAI_Obs.iloc[:, i].values


        self.show_graph_end(Obs_end, Sim_end[1:],LAI_Obs.index)
        self.save_graph(Obs_end, Sim_end[1:], LAI_Obs.index, '_Final')



        QMessageBox.information(self, "Process Complete", "Completed process, continue with next LULC")

    def export_result(self):
        all_coverages = set(self.spinBox.itemText(i) for i in range(self.spinBox.count()))
        if self.processed_coverages != all_coverages:
            QMessageBox.warning(None, "Export Incomplete", "Not all coverages have been processed yet.")
            return

        PathProject = os.path.join(self.output_path.text(), self.name_project.text(), 'temp', '03-Phenology')
        output_file = os.path.join(PathProject, 'Best_Parametros.xlsx')

        try:
            # Crear un DataFrame vacío para almacenar todos los resultados
            combined_df = pd.DataFrame(columns=self.RESULT.keys())

            for key, values in self.RESULT.items():
                # Convertir cada array en un DataFrame y tomar la primera columna
                value = pd.DataFrame(values)
                try:
                    combined_df[key] = value.T
                except:
                    combined_df[key] = value.T[value.T.columns[0]]

            combined_df.loc['partf_sup'] = combined_df.loc['partf_sup'] * combined_df.loc['part_inf']

            combined_df.loc['parf_lai'] = combined_df.loc['parf_lai'] * combined_df.loc['parlai_min']

            new_index = ['TAinf', 'TAsup', 'LAImin', 'LAImax', 'l1', 'l2', 'l3', 'PHU', 'frPHUsen', 'SMIc', 'nSMI',
                         'pargdd_c']
            combined_df.index = new_index

            # Escribir el DataFrame combinado en una sola hoja del archivo Excel
            with pd.ExcelWriter(output_file) as writer:
                combined_df.to_excel(writer, sheet_name='Best_Parameters', index=True)

            QMessageBox.information(None, "Export Complete", "The parameters have been successfully exported.")
        except Exception as e:
            QMessageBox.critical(None, "Export Failed", f"An error occurred while exporting: {str(e)}")

    def closeEvent(self, event):
        self.closingPlugin.emit()
        event.accept()
