# -*- coding: utf-8 -*-
"""
/***************************************************************************
 QSIGA_CAL
                                 A QGIS plugin
 This plugin allows to configure, calibrate and simulate scenarios in the SIGA-CAL model
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2024-10-01
        copyright            : (C) 2024 by The Nature Conservancy
        email                : miguel.canon@tnc.org
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load QSIGA_CAL class from file QSIGA_CAL.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    # Load plugin
    from .QSIGA_CAL import QSIGA_CAL
    return QSIGA_CAL(iface)
