# -*- coding: utf-8 -*-
"""
/***************************************************************************
 QSIGA_CAL
                                 A QGIS plugin
 This plugin allows to configure, calibrate and simulate scenarios in the SIGA-CAL model
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                              -------------------
        begin                : 2024-10-01
        git sha              : $Format:%H$
        copyright            : (C) 2024 by The Nature Conservancy
        email                : miguel.canon@tnc.org
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
"""
from qgis.PyQt.QtCore import QSettings, QTranslator, QCoreApplication
from qgis.PyQt.QtGui import QIcon
from qgis.PyQt.QtWidgets import QAction

# Initialize Qt resources from file resources.py
from .resources import *
# Import the code for the dialog
from .QSIGA_CAL_dialog import QSigaCalDialog
import os.path
# import Logo_TNC_rc
from qgis.core import QgsMessageLog


from .Plugins.Step_01.Siga_Step_01_Config_dockwidget import Siga_Step_01_ConfigDockWidget
from .Plugins.Step_02.Siga_Step_02_lai_dockwidget import Siga_Step_02_laiDockWidget
from .Plugins.Step_03.Calibracion_Model_dockwidget import Calibracion_ModelDockWidget
from .Plugins.Step_04.Siga_step_04_Priori_dockwidget import Siga_step_04_PrioriDockWidget
from .Plugins.Step_05.siga_step_05_Sim_dockwidget import siga_step_05_SimDockWidget
import logging

LOGGER = logging.getLogger('QSIGA_CAL')

class QSIGA_CAL:
    """QGIS Plugin Implementation."""
    def __init__(self, iface):
        """Constructor for the plugin."""
        self.iface = iface  # Save reference to the QGIS interface
        self.dockwidget = None
        self.dialog = None  # Variable to store the main dialog instance
        self.actions = []
        self.menu = self.tr(u'&QSIGA_CAL')
        self.toolbar = self.iface.addToolBar(u'QSIGA_CAL')
        self.toolbar.setObjectName(u'QSIGA_CAL')

    def tr(self, message):
        """Get the translation for a string using Qt translation API."""
        return QCoreApplication.translate('QSIGA_CAL', message)

    def add_action(
            self, icon_path, text, callback, enabled_flag=True, add_to_menu=True,
            add_to_toolbar=True, status_tip=None, whats_this=None, parent=None):
        """Add an action to the plugin's toolbar."""
        icon = QIcon(icon_path)
        action = QAction(icon, text, parent)
        action.triggered.connect(callback)
        action.setEnabled(enabled_flag)

        if status_tip is not None:
            action.setStatusTip(status_tip)

        if whats_this is not None:
            action.setWhatsThis(whats_this)

        if add_to_toolbar:
            self.toolbar.addAction(action)

        if add_to_menu:
            self.iface.addPluginToMenu(self.menu, action)

        self.actions.append(action)

        return action

    def initGui(self):
        """Create the menu entries and toolbar icons inside the QGIS GUI."""

        plugin_dir = os.path.dirname(__file__)
        icon_path = os.path.join(plugin_dir, 'logos', 'Qsiga.png')  # Cambiar el logo si es necesario

        self.add_action(
            icon_path,
            text=self.tr(u'QSIGA_CAL Configuration'),
            callback=self.run,
            parent=self.iface.mainWindow())

        # icon_path = ':/plugins/QSIGA_CAL/icon.png'
        # self.add_action(
        #     icon_path,
        #     text=self.tr(u'QSIGA_CAL Configuration'),
        #     callback=self.run,
        #     parent=self.iface.mainWindow())

    def unload(self):
        """Remove the plugin menu item and icon from QGIS GUI."""
        for action in self.actions:
            self.iface.removePluginMenu(self.tr(u'&QSIGA_CAL'), action)
            self.iface.removeToolBarIcon(action)
        del self.toolbar

    def run(self):
        """Run method to start the plugin."""
        if self.dialog is None:
            self.dialog = QSigaCalDialog(self.iface)  # Pass iface to the dialog

        # Show the dialog window
        self.dialog.show()
        # Bring the dialog to the front
        self.dialog.raise_()
        self.dialog.activateWindow()

    def open_step_1(self):
        """Cargar el subplugin Step 1."""
        LOGGER.info("Opening Step 1 subplugin.")
        self.step_1_dock = Siga_Step_01_ConfigDockWidget(self.iface)
        self.iface.addDockWidget(Qt.LeftDockWidgetArea, self.step_1_dock)
        self.step_1_dock.show()

    def open_step_2(self):
        """Cargar el subplugin Step 2."""
        LOGGER.info("Opening Step 2 subplugin.")
        self.step_2_dock = Siga_Step_02_laiDockWidget(self.iface)
        self.iface.addDockWidget(Qt.LeftDockWidgetArea, self.step_2_dock)
        self.step_2_dock.show()

    def open_step_3(self):
        """Cargar el subplugin Step 3."""
        LOGGER.info("Opening Step 3 subplugin.")
        self.step_3_dock = Calibracion_ModelDockWidget(self.iface)
        self.iface.addDockWidget(Qt.LeftDockWidgetArea, self.step_3_dock)
        self.step_3_dock.show()


    def open_step_4(self):
        """Cargar el subplugin Step 4."""
        LOGGER.info("Opening Step 4 subplugin.")
        self.step_4_dock = Siga_step_04_PrioriDockWidget(self.iface)
        self.iface.addDockWidget(Qt.LeftDockWidgetArea, self.step_4_dock)
        self.step_4_dock.show()

    def open_step_5(self):
        """Cargar el subplugin Step 4."""
        LOGGER.info("Opening Step 4 subplugin.")
        self.step_5_dock = siga_step_05_SimDockWidget(self.iface)
        self.iface.addDockWidget(Qt.LeftDockWidgetArea, self.step_5_dock)
        self.step_5_dock.show()

