# -*- coding: utf-8 -*-
"""
/***************************************************************************
 Siga_Step_02_laiDockWidget
                                 A QGIS plugin
 This plugin allows to calibrate the LAI using MODIS satellite images
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2024-09-23
        git sha              : $Format:%H$
        copyright            : (C) 2024 by The Nature Conservancy
        email                : miguel.canon@tnc.org
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
"""

import sys
import os
import random
import glob
import json
import requests
from requests.auth import HTTPBasicAuth
import pandas as pd
import numpy as np
import rasterio
from datetime import datetime, timedelta
from dateutil.relativedelta import relativedelta
from PyQt5.QtWidgets import QFileDialog, QMessageBox
from qgis.PyQt import QtGui, QtWidgets, uic
from qgis.PyQt.QtCore import pyqtSignal,QTimer, QDate, QObject, QDateTime
from qgis.core import QgsProject, QgsRasterLayer, QgsVectorLayer, QgsMessageLog, Qgis
from pyproj import Proj
import pyproj
import geopandas as gpd
from pymodis import downmodis
from statsmodels.tsa.seasonal import seasonal_decompose
import statsmodels.api as sm
from affine import Affine
from osgeo import gdal, osr, gdalconst
from rasterio.warp import calculate_default_transform, reproject, Resampling
from ..common_functions.spotpy_setup_LAI import *
import spotpy
import matplotlib.pyplot as plt
from qgis.PyQt.QtWidgets import QGraphicsScene, QVBoxLayout, QPushButton, QHBoxLayout
from matplotlib.backends.backend_qt5agg import FigureCanvasQTAgg
import time
import logging
from urllib.parse import urljoin
import re


FORM_CLASS, _ = uic.loadUiType(os.path.join(
    os.path.dirname(__file__), 'Siga_Step_02_lai_dockwidget_base.ui'))

class ProgressSignal(QObject):
    progress = pyqtSignal(int)
class StreamToLogger:
    def __init__(self, progress_signal):
        self.progress_signal = progress_signal

    def write(self, buf):
        for line in buf.splitlines():
            if line.strip():
                self.handle_line(line)

    def handle_line(self, line):
        # Busca líneas que contengan "of" y actualiza el progreso
        if "of" in line:
            try:
                parts = line.split(',')
                iter_info = parts[0].strip().split()
                iter_num = int(iter_info[0])
                total_num = int(iter_info[2])
                progress = int((iter_num / total_num) * 100)
                self.progress_signal.progress.emit(progress)
            except (ValueError, IndexError):
                pass

    def flush(self):
        pass
class Siga_Step_02_laiDockWidget(QtWidgets.QDockWidget, FORM_CLASS):

    closingPlugin = pyqtSignal()

    def __init__(self, parent=None):
        """Constructor."""
        super(Siga_Step_02_laiDockWidget, self).__init__(parent)
        self.setupUi(self)

        # step 1 - descarga imagenes modis
        self.select_output.clicked.connect(self.select_output_path)
        self.Button_Load_Dem.clicked.connect(self.load_dem)
        self.Run_Download.clicked.connect(self.run_download)
        self.Button_Step_2.clicked.connect(self.go_to_step_2)

        # step 2 - procesamiento de datos MODIS
        self.Run_process_modis.clicked.connect(self.run_process_modis_data)
        self.Button_Load_Lulc.clicked.connect(self.load_lulc)
        self.Run_process_Zonal.clicked.connect(self.run_zonal_statistics)
        self.Run_process_Moving.clicked.connect(self.run_process_moving_average)
        self.Button_Load_Stations.clicked.connect(self.load_shapefile_stations)
        self.Button_Load_Excel.clicked.connect(self.load_excel_time_series)
        self.Run_process_Tmax.clicked.connect(self.run_process_tmax)
        self.Run_process_Tmin.clicked.connect(self.run_process_tmin)
        self.Run_process_PT.clicked.connect(self.run_process_pt)
        self.Export_result.clicked.connect(self.save_results_to_excel)

        self.Button_Step_3.clicked.connect(self.go_to_step_3)


        # step 3 - Calibracion
        self.Run_process_LAI.clicked.connect(self.run_process_lai)
        # Conectar los botones de zoom
        self.zoom_in_button.clicked.connect(self.zoom_in)
        self.zoom_out_button.clicked.connect(self.zoom_out)

        self.zoom_in_button_2.clicked.connect(self.zoom_in_2)
        self.zoom_out_button_2.clicked.connect(self.zoom_out_2)


        self.Run_process_LAI_end.clicked.connect(self.run_process_lai_end)
        self.Export_result_2.clicked.connect(self.export_result)
        self.Button_Finish_1.clicked.connect(self.close_plugin)

        # Signal de progreso
        self.progress_signal = ProgressSignal()
        self.progress_signal.progress.connect(self.progressBar_process_LAI.setValue)
        self.progress_signal_end = ProgressSignal()
        self.progress_signal_end.progress.connect(self.progressBar_process_LAI_end.setValue)
        self.RESULT = {}
        self.processed_coverages = set()

        # Initialize default parameter values for LAI calibration
        self.initialize_default_parameters()

        ### Project State - Auto-save and load project state
        QgsProject.instance().projectSaved.connect(self.save_project_state)
        QgsProject.instance().readProject.connect(self.delayed_load_project_state)

        # Load project state on initialization if project is already open
        # Use QTimer to delay loading until after widget is fully initialized
        if QgsProject.instance().fileName():
            QTimer.singleShot(500, self.load_project_state)

        # Set tooltips for calibration parameter labels
        self.label_38.setToolTip("Factor to determine the maximum temperature at which vegetative development occurs [°C]")
        self.label_32.setToolTip("Shape factor 1 of the sigmoid relationship for maximum LAI fraction [Dimensionless]")
        self.label_33.setToolTip("Shape factor 2 of the sigmoid relationship for maximum LAI fraction [Dimensionless]")
        self.label_34.setToolTip("Shape factor 3 of the sigmoid LAI relationship [Dimensionless]")
        self.label_35.setToolTip("Fraction of potential heat units at which the senescence phase begins [Dimensionless]")
        self.label_36.setToolTip("Number of consecutive days in which the critical soil moisture threshold must be exceeded")

    def initialize_default_parameters(self):
        """
        Initialize default values for LAI calibration parameters.
        These values are loaded when the plugin starts.
        """
        # Default parameter ranges based on typical values
        # Users can modify these based on their specific case

        # ft_sup (fraction superior temperature)
        self.Qft_sup_min.setText("1.0")
        self.Qft_sup_max.setText("10.0")

        # l1, l2, l3 (LAI shape parameters)
        self.Ql1_min.setText("0.0")
        self.Ql1_max.setText("1.0")
        self.Ql2_min.setText("0.0")
        self.Ql2_max.setText("10.0")
        self.Ql3_min.setText("0.0")
        self.Ql3_max.setText("100.0")

        # fr_phu_sen (fraction PHU senescence)
        self.Qfr_phu_sen_min.setText("0.3")
        self.Qfr_phu_sen_max.setText("1.0")

        # nSMI (soil moisture index exponent)
        self.QnSMI_min.setText("1.0")
        self.QnSMI_max.setText("30.0")

        # Default optimization parameters
        self.QNumIter.setText("100")  # Number of iterations for initial scan
        self.QNumIter_end.setText("1000")  # Number of iterations for final calibration
        self.QPeriod.setText("365")  # Period for PHU calculation (days)
        self.QOmitObs.setText("0")  # Number of initial observations to omit
        self.QSOS1.setText("3")  # Start of season month 1 (March)
        self.QSOS1_2.setText("9")  # Start of season month 2 (September)

    def select_output_path(self):
        output_path = QFileDialog.getExistingDirectory(self, "Select Output Directory")
        if output_path:
            self.output_path.setText(output_path)

    def load_dem(self):
        dem_path, _ = QFileDialog.getOpenFileName(self, "Select DEM File", "", "Raster files (*.tif *.img *.vrt)")
        if dem_path:
            self.Path_raster.setText(dem_path)
            self.dem_layer = QgsRasterLayer(dem_path, "Digital Elevation Model")
            if not self.dem_layer.isValid():
                QMessageBox.critical(self, "Error", "The selected DEM file is not valid.")
            else:
                QgsProject.instance().addMapLayer(self.dem_layer)

    def create_outputs_folders(self, path_out, name_project):
        main_folders = ['temp']
        inside_folders = ['03-Phenology']

        project_path = os.path.join(path_out, name_project)

        for main_folder in main_folders:
            main_folder_path = os.path.join(project_path, main_folder)
            os.makedirs(main_folder_path, exist_ok=True)

            if main_folder == 'temp':
                for inside_folder in inside_folders:
                    inside_folder_path = os.path.join(main_folder_path, inside_folder)
                    os.makedirs(inside_folder_path, exist_ok=True)

        return project_path

    def run_download(self):
        project_name = self.name_project.text()
        output_path = self.output_path.text()
        dem_path = self.Path_raster.text()
        start_date = self.start_date.date().toString("yyyy-MM-dd")
        end_date = self.end_date.date().toString("yyyy-MM-dd")

        if not project_name or not output_path or not dem_path:
            QMessageBox.warning(self, "Input Error", "Please provide all necessary inputs.")
            return

        project_path = self.create_outputs_folders(output_path, project_name)

        PathOutputs = os.path.join(project_path, 'temp', '03-Phenology', 'MODIS')
        os.makedirs(PathOutputs, exist_ok=True)

        self.DownloadLAI_MODIS(PathOutputs, dem_path, start_date, end_date)

    def DownloadLAI_MODIS(self, PathOutputs, PathRaster, start_date, end_date):
        """
        Download MODIS LAI data using LAADS DAAC AppKey authentication.
        Supports incremental downloads - existing files are skipped.
        Automatically splits large date ranges into manageable chunks.

        AppKey must be stored in: {project_folder}/temp/earthdata_token.txt
        Get your AppKey from: https://ladsweb.modaps.eosdis.nasa.gov/profile/
        """
        try:
            # Parse dates first to check range
            start = datetime.strptime(start_date, '%Y-%m-%d')
            end = datetime.strptime(end_date, '%Y-%m-%d')

            # Calculate date range in years
            years_range = (end - start).days / 365.25

            # If range > 1 year, split into 1-year blocks for better reliability
            # Based on testing, year-by-year downloads work more consistently
            if years_range > 1:
                return self._download_in_blocks(PathOutputs, PathRaster, start, end, block_years=1)

            # Otherwise, proceed with single download
            return self._download_single_period(PathOutputs, PathRaster, start, end)

        except Exception as e:
            QMessageBox.critical(self, "Download Error",
                               f"Failed to download MODIS data.\n\n" +
                               f"Error: {str(e)}\n\n" +
                               "Check your internet connection and AppKey.")
            import traceback
            traceback.print_exc()

    def _download_in_blocks(self, PathOutputs, PathRaster, start_date, end_date, block_years=1):
        """
        Download MODIS data in blocks for large date ranges.
        Each block shows its own alert and progress bar.
        """
        from dateutil.relativedelta import relativedelta

        blocks = []
        current_start = start_date

        # Create blocks
        while current_start < end_date:
            current_end = min(
                current_start + relativedelta(years=block_years),
                end_date
            )
            blocks.append((current_start, current_end))
            current_start = current_end

        total_blocks = len(blocks)
        total_years = (end_date - start_date).days / 365.25

        # Inform user about block processing
        reply = QMessageBox.question(
            self,
            "Large Date Range Detected",
            f"Date range: {total_years:.1f} years ({start_date.strftime('%Y-%m-%d')} to {end_date.strftime('%Y-%m-%d')})\n\n" +
            f"The download will be split into {total_blocks} periods.\n" +
            f"You will see a progress dialog for each period.\n\n" +
            f"Existing files will be automatically skipped.\n\n" +
            "Continue with download?",
            QMessageBox.Yes | QMessageBox.No
        )

        if reply == QMessageBox.No:
            return

        # Process each block with individual alerts and progress bars
        total_downloaded = 0
        total_failed = 0

        for block_num, (block_start, block_end) in enumerate(blocks, 1):
            # Show alert for this block/year
            year_str = block_start.strftime('%Y')
            QMessageBox.information(
                self,
                f"Downloading Block {block_num}/{total_blocks}",
                f"Starting download for year {year_str}\n\n" +
                f"Period: {block_start.strftime('%Y-%m-%d')} to {block_end.strftime('%Y-%m-%d')}\n\n" +
                "Please wait while files are downloaded..."
            )

            # Download this block with dialogs enabled (shows progress bar)
            result = self._download_single_period(PathOutputs, PathRaster, block_start, block_end, show_dialogs=True)

            if result:
                total_downloaded += result.get('downloaded', 0)
                total_failed += result.get('failed', 0)

        # Final summary
        actual_files = glob.glob(os.path.join(PathOutputs, "*.hdf"))
        actual_count = len(actual_files)

        QMessageBox.information(
            self,
            "All Downloads Complete",
            f"All {total_blocks} periods processed!\n\n" +
            f"Total period: {start_date.strftime('%Y-%m-%d')} to {end_date.strftime('%Y-%m-%d')}\n" +
            f"Files in folder: {actual_count}\n" +
            f"New downloads: {total_downloaded}\n" +
            f"Failed: {total_failed}\n\n" +
            "You can now proceed to Step 2 - Process MODIS Data."
        )

        return {'downloaded': total_downloaded, 'failed': total_failed, 'total': actual_count}

    def _download_single_period(self, PathOutputs, PathRaster, start, end, show_dialogs=True):
        """
        Download MODIS data for a single time period.
        This is the core download logic extracted from the original method.

        Args:
            show_dialogs: If False, suppress QMessageBox dialogs (for block processing)
        """
        try:
            tiles = self.raster_to_modis_tiles(PathRaster)
            product = "MOD15A2H"
            collection = "61"

            # LAADS DAAC base URL
            base_url = f"https://ladsweb.modaps.eosdis.nasa.gov/archive/allData/{collection}/{product}/"

            # Read AppKey from token file
            project_path = os.path.join(self.output_path.text(), self.name_project.text())
            token_file = os.path.join(project_path, 'temp', 'earthdata_token.txt')

            if not os.path.exists(token_file):
                QMessageBox.critical(self, "AppKey Not Found",
                                   f"NASA Earthdata AppKey file not found.\n\n" +
                                   f"Expected location:\n{token_file}\n\n" +
                                   "To get your AppKey:\n" +
                                   "1. Visit: https://ladsweb.modaps.eosdis.nasa.gov/profile/\n" +
                                   "2. Login with your Earthdata credentials\n" +
                                   "3. Click 'Generate Token' to get your AppKey\n" +
                                   "4. Save the AppKey in a text file at the location above\n\n" +
                                   "The token file should contain only the AppKey (one line).")
                return

            # Read AppKey
            try:
                with open(token_file, 'r') as f:
                    app_key = f.read().strip()

                if not app_key:
                    raise ValueError("Token file is empty")

            except Exception as e:
                QMessageBox.critical(self, "Invalid AppKey File",
                                   f"Failed to read AppKey from:\n{token_file}\n\n" +
                                   f"Error: {str(e)}\n\n" +
                                   "Make sure the file contains your NASA Earthdata AppKey.")
                return

            # Create session with AppKey authentication
            session = requests.Session()
            headers = {'Authorization': f'Bearer {app_key}'}
            session.headers.update(headers)

            # Generate list of dates (every 8 days for MOD15A2H)
            date_list = []
            current_date = start
            while current_date <= end:
                date_list.append(current_date)
                current_date += timedelta(days=8)

            if not date_list:
                QMessageBox.warning(self, "No Dates", "No valid dates in the specified range.")
                return

            # Check for existing files
            existing_files = glob.glob(os.path.join(PathOutputs, "*.hdf"))
            existing_count = len(existing_files)

            # Collect files to download (skip existing ones)
            files_to_download = []

            for date in date_list:
                year = date.strftime('%Y')
                doy = date.strftime('%j')  # Day of year
                date_url = f"{base_url}{year}/{doy}/"

                try:
                    response = session.get(date_url, timeout=30)

                    if response.status_code == 200:
                        html = response.text

                        # Check for authentication failure
                        if 'Earthdata Login' in html or '<title>Login' in html:
                            QMessageBox.critical(self, "Authentication Failed",
                                               "NASA Earthdata authentication failed.\n\n" +
                                               "Your AppKey may be invalid or expired.\n\n" +
                                               "Please update your token file with a new AppKey from:\n" +
                                               "https://ladsweb.modaps.eosdis.nasa.gov/profile/")
                            return

                        # Find all HDF files matching our tiles
                        for tile in tiles.split(','):
                            tile = tile.strip()
                            # Pattern: MOD15A2H.A2010001.h10v09.061.*.hdf
                            pattern = f'{product}\\.A{year}{doy}\\.{tile}\\.[0-9]+\\.[0-9]+\\.hdf'
                            matches = re.findall(pattern, html)

                            # Remove duplicates (HTML may list files multiple times)
                            matches = list(set(matches))

                            for filename in matches:
                                output_path = os.path.join(PathOutputs, filename)

                                # Skip if file already exists and is valid (incremental download)
                                if os.path.exists(output_path) and os.path.getsize(output_path) > 50000:
                                    continue

                                file_url = urljoin(date_url, filename)
                                files_to_download.append({
                                    'url': file_url,
                                    'filename': filename,
                                    'date': date.strftime('%Y-%m-%d')
                                })

                except:
                    pass  # Silently skip errors during file discovery

            # Check if we need to download anything
            if not files_to_download:
                date_range_str = f"{start.strftime('%Y-%m-%d')} to {end.strftime('%Y-%m-%d')}"
                if existing_count > 0:
                    # Don't show message for block downloads, just return stats
                    print(f"Block {date_range_str}: All {existing_count} files already exist, skipping.")
                else:
                    print(f"Block {date_range_str}: No new data found.")

                # Return stats even when nothing to download
                return {'downloaded': 0, 'failed': 0, 'total': existing_count}

            # Download files
            total_files = len(files_to_download)
            self.progressBar_Download.setMaximum(total_files)

            if show_dialogs:
                msg = f"Found {total_files} new files to download.\n\n"
                if existing_count > 0:
                    msg += f"Existing files (will be skipped): {existing_count}\n\n"
                msg += "Please keep the window open until complete."
                QMessageBox.information(self, "Download Starting", msg)
            else:
                # Just print to console for block downloads
                print(f"Downloading {total_files} new files... (Existing: {existing_count})")

            downloaded = 0
            failed = 0

            for i, file_info in enumerate(files_to_download):
                try:
                    file_url = file_info['url']
                    filename = file_info['filename']
                    output_path = os.path.join(PathOutputs, filename)

                    # Download file
                    response = session.get(file_url, stream=True, timeout=60)

                    if response.status_code == 200:
                        # Check if we got HTML (authentication error) instead of binary data
                        content_type = response.headers.get('Content-Type', '')

                        if 'text/html' in content_type:
                            # Authentication failed, got HTML instead of HDF
                            failed += 1
                            continue

                        with open(output_path, 'wb') as f:
                            for chunk in response.iter_content(chunk_size=8192):
                                if chunk:  # filter out keep-alive chunks
                                    f.write(chunk)

                        # Verify file was downloaded and has content (at least 50KB for valid HDF)
                        if os.path.exists(output_path) and os.path.getsize(output_path) > 50000:
                            downloaded += 1
                        else:
                            failed += 1
                            if os.path.exists(output_path):
                                os.remove(output_path)  # Remove invalid file
                    else:
                        failed += 1

                except Exception as e:
                    failed += 1

                self.progressBar_Download.setValue(i + 1)

            # Summary - count actual files in folder
            self.progressBar_Download.setValue(total_files)

            actual_files = glob.glob(os.path.join(PathOutputs, "*.hdf"))
            actual_count = len(actual_files)

            if show_dialogs:
                summary_msg = (f"Download Complete!\n\n" +
                              f"Attempted: {total_files}\n" +
                              f"Successfully downloaded: {downloaded}\n" +
                              f"Failed: {failed}\n" +
                              f"Previously existing: {existing_count}\n\n" +
                              f"Total HDF files in folder: {actual_count}\n\n" +
                              f"Output folder:\n{PathOutputs}")

                if failed > 0:
                    QMessageBox.warning(self, "Download Complete with Errors", summary_msg)
                else:
                    QMessageBox.information(self, "Download Complete", summary_msg)
            else:
                # Just print summary for block downloads
                print(f"Block completed: Downloaded {downloaded}, Failed {failed}, Total in folder: {actual_count}")

            # Return statistics for block processing
            return {'downloaded': downloaded, 'failed': failed, 'total': actual_count}

        except Exception as e:
            QMessageBox.critical(self, "Download Error",
                               f"Failed to download MODIS data.\n\n" +
                               f"Error: {str(e)}\n\n" +
                               "Verify credentials and data availability at:\n" +
                               "https://ladsweb.modaps.eosdis.nasa.gov/search/")

    def raster_to_modis_tiles(self, PathRaster, sample_size=100):
        def lonlat_to_modis_tile(lon, lat):
            tile_width = 10.0
            tile_height = 10.0
            lon_min = -180.0
            lat_max = 90.0
            h = int(np.round((lon - lon_min) / tile_width, 0))
            v = int(np.round((lat_max - lat) / tile_height, 0))
            return h, v

        from pyproj import Transformer, CRS
        with rasterio.open(PathRaster) as src:
            crs = src.crs
            transform = src.transform
            width = src.width
            height = src.height
            sample_coords = [(random.randint(0, height - 1), random.randint(0, width - 1)) for _ in range(sample_size)]
            coords = [rasterio.transform.xy(transform, row, col, offset='center') for row, col in sample_coords]

        if not crs.is_geographic:
            transformer = Transformer.from_crs(crs, CRS.from_epsg(4326), always_xy=True)
            coords = [transformer.transform(x, y) for x, y in coords]

            # proj_raster = Proj(crs)
            # proj_wgs84 = Proj(init="epsg:4326")
            # coords = [pyproj.transform(proj_raster, proj_wgs84, x, y) for x, y in coords]

        modis_tiles = set(lonlat_to_modis_tile(lon, lat) for lon, lat in coords)
        return ','.join([f"h{h:02d}v{v:02d}" for h, v in modis_tiles])

    def go_to_step_2(self):
        self.toolBox.setCurrentIndex(1)

    #### funciones step 2 procesamiento de datos MODIS #############################

    def run_process_modis_data(self):
        try:
            PathOutputs = os.path.join(self.output_path.text(), self.name_project.text(), 'temp', '03-Phenology', 'MODIS')

            # Verify paths exist
            if not os.path.exists(PathOutputs):
                QMessageBox.critical(self, "Error",
                                   f"MODIS data folder not found:\n{PathOutputs}\n\n" +
                                   "Please download MODIS data first (Step 1).")
                return

            # Determine reference raster - prefer DEM if available, otherwise use LULC
            reference_raster = None
            reference_name = None

            # Check if DEM is available (preferred)
            if self.Path_raster.text() and os.path.exists(self.Path_raster.text()):
                reference_raster = self.Path_raster.text()
                reference_name = "DEM"
            # Fall back to LULC
            elif self.Path_Lulc.text() and os.path.exists(self.Path_Lulc.text()):
                reference_raster = self.Path_Lulc.text()
                reference_name = "LULC"
            else:
                QMessageBox.critical(self, "Error",
                                   "Reference raster not found.\n\n" +
                                   "Please load either:\n" +
                                   "  - DEM raster (preferred)\n" +
                                   "  - LULC raster (alternative)\n\n" +
                                   "The MODIS files will be resampled to match this reference.")
                return

            # Count HDF files
            hdf_count = len(glob.glob(os.path.join(PathOutputs, "*.hdf")))
            if hdf_count == 0:
                QMessageBox.warning(self, "No Data",
                                  f"No HDF files found in:\n{PathOutputs}\n\n" +
                                  "Please download MODIS data first (Step 1).")
                return

            QMessageBox.information(self, "Process Starting",
                                  f"Processing {hdf_count} HDF files.\n\n" +
                                  f"Reference raster: {reference_name}\n" +
                                  f"File: {os.path.basename(reference_raster)}\n\n" +
                                  "Please keep the window open until the process is finished.\n\n" +
                                  "Progress will be shown in the Python Console.")

            self.process_modis_data(PathOutputs, reference_raster)

            QMessageBox.information(self, "Process Complete",
                                  "MODIS LAI data converted to raster successfully!")

        except Exception as e:
            QMessageBox.critical(self, "Processing Error",
                               f"Failed to process MODIS data.\n\n" +
                               f"Error: {str(e)}\n\n" +
                               "Check the Python Console for detailed information.")
            import traceback
            traceback.print_exc()

    def process_modis_data(self, destination_folder, reference_raster):
        """
        Process MODIS HDF files: group by date, create mosaics, and resample.
        """
        hdf_files = glob.glob(os.path.join(destination_folder, "*.hdf"))

        if not hdf_files:
            raise ValueError("No HDF files found in destination folder")

        # Group files by date
        date_files = {}
        for hdf_file in hdf_files:
            basename = os.path.basename(hdf_file)
            parts = basename.split('.')
            if len(parts) >= 2:
                date_str = parts[1][1:]  # Remove 'A' prefix
                if date_str not in date_files:
                    date_files[date_str] = []
                date_files[date_str].append(hdf_file)

        total_dates = len(date_files)
        self.progressBar_modis.setMaximum(total_dates)

        processed = 0
        failed = 0
        first_error = None

        for i, (date_str, files) in enumerate(sorted(date_files.items())):
            try:
                vrt_path = os.path.join(destination_folder, f"mosaic_{date_str}.vrt")
                temp_raster = os.path.join(destination_folder, f"temp_raster_{date_str}.tif")
                output_raster = os.path.join(destination_folder, f"MODIS_{date_str}.tif")

                # Convert HDF to mosaic
                self.convert_mosaic_to_raster(files, vrt_path, temp_raster, subdataset_name='Lai_500m')

                # Resample to match reference
                self.resample_to_match(temp_raster, reference_raster, output_raster)

                # Cleanup temporary files
                if os.path.exists(vrt_path):
                    os.remove(vrt_path)
                if os.path.exists(temp_raster):
                    os.remove(temp_raster)

                processed += 1

            except Exception as e:
                failed += 1
                if first_error is None:
                    first_error = str(e)

            self.progressBar_modis.setValue(i + 1)

        self.progressBar_modis.setValue(total_dates)

        if failed > 0:
            raise Exception(f"Processing completed with errors.\n\n" +
                          f"Processed: {processed}/{total_dates}\n" +
                          f"Failed: {failed}/{total_dates}\n\n" +
                          f"First error: {first_error}")

    def convert_mosaic_to_raster(self, hdf_files, vrt_path, output_raster, subdataset_name='Lai_500m'):
        """
        Convert HDF files to GeoTIFF mosaic using GDAL VRT.
        Uses direct subdataset paths without opening files first.
        """
        # Diagnostic: Test if first HDF file can be opened
        if hdf_files:
            test_file = hdf_files[0]
            print(f"DEBUG: Testing first HDF file: {os.path.basename(test_file)}")
            print(f"DEBUG: File size: {os.path.getsize(test_file)} bytes")

            # Try to open HDF file to get subdatasets
            gdal.PushErrorHandler('CPLQuietErrorHandler')
            test_ds = gdal.Open(test_file, gdal.GA_ReadOnly)
            gdal_error = gdal.GetLastErrorMsg()
            gdal.PopErrorHandler()

            if test_ds is None:
                print(f"DEBUG: Cannot open HDF file - GDAL Error: {gdal_error}")
                raise ValueError(f"Cannot open HDF files. GDAL Error: {gdal_error}\n\n" +
                               "This usually means HDF4 driver is not available or files are corrupted.")
            else:
                subdatasets = test_ds.GetSubDatasets()
                print(f"DEBUG: Found {len(subdatasets)} subdatasets")
                if subdatasets:
                    for i, (name, desc) in enumerate(subdatasets[:3]):
                        print(f"DEBUG: Subdataset {i+1}: {name}")
                test_ds = None

        # Build subdataset paths directly
        subdatasets = [f'HDF4_EOS:EOS_GRID:"{f}":MOD_Grid_MOD15A2H:{subdataset_name}' for f in hdf_files]

        print(f"DEBUG: Building VRT with {len(subdatasets)} subdatasets")
        print(f"DEBUG: First subdataset path: {subdatasets[0] if subdatasets else 'None'}")

        # Build VRT
        vrt_options = gdal.BuildVRTOptions(separate=False)

        gdal.PushErrorHandler('CPLQuietErrorHandler')
        vrt = gdal.BuildVRT(vrt_path, subdatasets, options=vrt_options)
        build_error = gdal.GetLastErrorMsg()
        gdal.PopErrorHandler()

        if vrt is None:
            print(f"DEBUG: gdal.BuildVRT failed - Error: {build_error}")
            raise ValueError(f"Failed to create VRT file.\n\nGDAL Error: {build_error}\n\n" +
                           f"VRT path: {vrt_path}\n" +
                           f"Number of subdatasets: {len(subdatasets)}")

        print(f"DEBUG: VRT created successfully - Size: {vrt.RasterXSize}x{vrt.RasterYSize}")

        # Close VRT to flush to disk
        vrt.FlushCache()
        vrt = None

        # Convert VRT to GeoTIFF using the file path
        result = gdal.Translate(output_raster, vrt_path, format='GTiff')

        if result is None:
            raise ValueError("Failed to convert VRT to GeoTIFF")

        result.FlushCache()
        result = None

        print(f"DEBUG: Successfully created {os.path.basename(output_raster)}")

    def resample_to_match(self, src_path, match_path, dst_path):
        with rasterio.open(src_path) as src:
            src_transform = src.transform
            src_crs = src.crs
            src_width = src.width
            src_height = src.height

            with rasterio.open(match_path) as match:
                match_transform = match.transform
                match_crs = match.crs
                match_width = match.width
                match_height = match.height

                if src_crs != match_crs:
                    src_crs = match_crs
                    src_transform, src_width, src_height = calculate_default_transform(
                        src_crs, match_crs, src_width, src_height, *src.bounds)

                kwargs = src.meta.copy()
                kwargs.update({
                    'crs': match_crs,
                    'transform': match_transform,
                    'width': match_width,
                    'height': match_height
                })

                with rasterio.open(dst_path, 'w', **kwargs) as dst:
                    for i in range(1, src.count + 1):
                        reproject(
                            source=rasterio.band(src, i),
                            destination=rasterio.band(dst, i),
                            src_transform=src_transform,
                            src_crs=src_crs,
                            dst_transform=match_transform,
                            dst_crs=match_crs,
                            resampling=Resampling.nearest)

    def load_lulc(self):
        # Get suggested path from Step 1
        project_name = self.name_project.text() if self.name_project.text() else ""
        output_path = self.output_path.text() if self.output_path.text() else ""

        # Set initial directory to Step 1 output if available
        initial_dir = ""
        if project_name and output_path:
            step1_mapas = os.path.join(output_path, project_name, "Entradas", "Mapas")
            if os.path.exists(step1_mapas):
                initial_dir = step1_mapas

        lulc_path, _ = QFileDialog.getOpenFileName(
            self,
            "Select LULC File (use clc.tif from Step 1)",
            initial_dir,
            "Raster files (*.tif *.img *.vrt)"
        )

        if lulc_path:
            self.Path_Lulc.setText(lulc_path)
            self.lulc_layer = QgsRasterLayer(lulc_path, "LULC")

            if not self.lulc_layer.isValid():
                QMessageBox.critical(self, "Error", "The selected LULC file is not valid.")
                return

            # Add to map
            QgsProject.instance().addMapLayer(self.lulc_layer)

            # Check if user selected the clc.tif from Step 1
            filename = os.path.basename(lulc_path)
            if filename != "clc.tif":
                QMessageBox.warning(
                    self,
                    "LULC File Warning",
                    f"You selected: {filename}\n\n" +
                    "RECOMMENDATION:\n" +
                    "For best results, use the 'clc.tif' file created in Step 1.\n" +
                    "This file has been resampled to match your DEM extent and resolution.\n\n" +
                    f"Expected location:\n" +
                    f"{project_name}/Entradas/Mapas/clc.tif\n\n" +
                    "If you use a different file, make sure it has the same\n" +
                    "extent and resolution as your DEM."
                )

    def run_zonal_statistics(self):
        PathLULC = self.Path_Lulc.text()
        PathOutputs = os.path.join(self.output_path.text(),self.name_project.text(), 'temp', '03-Phenology', 'MODIS')
        PathExcel = os.path.join(self.output_path.text(),self.name_project.text(), 'temp', '03-Phenology', 'TS_LAI_LULC.xlsx')
        QMessageBox.information(self, "Process to start", "Please keep the window open until the process is finished.")
        self.zonal_statistics(PathLULC, PathOutputs, PathExcel)
        QMessageBox.information(self, "Process Complete", "Zonal Statistics completed.")

    def zonal_statistics(self, coverage_raster_path, modis_directory, output_excel_path):
        """
        Calculate zonal statistics for each land cover class from MODIS LAI data.
        MODIS rasters must have the same extent and resolution as the coverage raster.
        """
        with rasterio.open(coverage_raster_path) as src:
            coverage_data = src.read(1)
            coverage_meta = src.meta
            coverage_shape = coverage_data.shape

        print(f"Coverage raster shape: {coverage_shape}")

        coverage_codes = np.unique(coverage_data)
        coverage_codes = coverage_codes[coverage_codes != coverage_meta['nodata']]

        lai_series = {code: [] for code in coverage_codes}
        dates = []

        modis_files = sorted([f for f in os.listdir(modis_directory) if f.startswith('MODIS_') and f.endswith('.tif')])
        total_files = len(modis_files)

        if total_files == 0:
            raise ValueError(f"No MODIS files found in:\n{modis_directory}\n\n" +
                           "Expected files with pattern: MODIS_*.tif")

        self.progressBar_Zonal.setMaximum(total_files)

        for i, modis_file in enumerate(modis_files):
            date_str = modis_file.split('_')[1].split('.')[0]
            year = int(date_str[:4])
            julian_day = int(date_str[4:])
            date = self.julian_to_date(year, julian_day)
            dates.append(date)
            modis_path = os.path.join(modis_directory, modis_file)

            with rasterio.open(modis_path) as src:
                modis_data = src.read(1)
                modis_meta = src.meta
                modis_shape = modis_data.shape

            # Verify dimensions match
            if modis_shape != coverage_shape:
                # Get project path for suggested clc.tif location
                project_name = self.name_project.text() if hasattr(self, 'name_project') else "your_project"
                output_path = self.output_path.text() if hasattr(self, 'output_path') else ""
                suggested_clc = os.path.join(output_path, project_name, "Entradas", "Mapas", "clc.tif") if output_path else ""

                error_msg = (
                    f"Dimension Mismatch Error\n\n" +
                    f"Coverage raster shape: {coverage_shape}\n" +
                    f"MODIS raster shape: {modis_shape}\n" +
                    f"File with error: {modis_file}\n\n" +
                    f"SOLUTION:\n" +
                    f"You must use the resampled land cover file from Step 1.\n\n"
                )

                if suggested_clc and os.path.exists(suggested_clc):
                    error_msg += (
                        f"Use this file as LULC:\n" +
                        f"{suggested_clc}\n\n" +
                        f"This file was created during Step 1 and has the correct\n" +
                        f"extent and resolution matching the DEM.\n\n"
                    )
                else:
                    error_msg += (
                        f"Expected location:\n" +
                        f"{project_name}/Entradas/Mapas/clc.tif\n\n" +
                        f"This file should have been created in Step 1.\n" +
                        f"If it doesn't exist, please complete Step 1 first.\n\n"
                    )

                error_msg += (
                    f"Steps to fix:\n" +
                    f"1. Load the correct clc.tif file (from Step 1)\n" +
                    f"2. Delete all MODIS_*.tif files from:\n" +
                    f"   {modis_directory}\n" +
                    f"3. Re-run 'Process MODIS Data'\n" +
                    f"4. Then run 'Zonal Statistics' again"
                )

                raise ValueError(error_msg)

            for code in coverage_codes:
                mask = coverage_data == code
                if np.any(mask):
                    lai_mean = np.mean(modis_data[mask])
                    lai_series[code].append(lai_mean)
                else:
                    lai_series[code].append(np.nan)

            self.progressBar_Zonal.setValue(i + 1)

        Factor = 0.1
        df = pd.DataFrame(lai_series , index=pd.to_datetime(dates))* Factor
        df.index.name = 'Date'
        df.to_excel(output_excel_path, engine='openpyxl')
        self.progressBar_Zonal.setValue(total_files)

    def julian_to_date(self, year, julian_day):
        date = datetime.strptime(f"{year}{julian_day:03d}", "%Y%j")
        return date

    def run_process_moving_average(self):
        PathExcel = os.path.join(self.output_path.text(),self.name_project.text(), 'temp', '03-Phenology', 'TS_LAI_LULC.xlsx')
        PathExcel1 = os.path.join(self.output_path.text(),self.name_project.text(), 'temp', '03-Phenology', 'TS_LAI_LULC_Movil.xlsx')
        window_size = int(self.Path_WS.text())
        QMessageBox.information(self, "Process to start", "Please keep the window open until the process is finished.")
        self.calculate_moving_average(PathExcel, PathExcel1, window_size)
        QMessageBox.information(self, "Process Complete", "Moving Average completed.")

    def calculate_moving_average(self, input_excel_path, output_excel_path, window_size):
        df = pd.read_excel(input_excel_path, index_col='Date', parse_dates=True)
        df = df.fillna(df.mean())

        reconstructed_df = pd.DataFrame(index=df.index)
        self.progressBar_Moving.setMaximum(len(df.columns[0:]))
        ii=1
        for col in df.columns[0:]:
            LAI_data = df[col]
            result = seasonal_decompose(LAI_data, model='additive', period=46)
            trend = result.trend
            seasonal = result.seasonal
            reconstructed_series = trend + seasonal
            reconstructed_df[col] = reconstructed_series
            ii+=1
            self.progressBar_Moving.setValue(ii + 1)
        self.progressBar_Moving.setValue(len(df.columns[0:]))
        moving_averages = reconstructed_df.rolling(window=window_size).mean()
        moving_averages.to_excel(output_excel_path, engine='openpyxl')

    def _find_column_case_insensitive(self, dataframe, column_name):
        """
        Find a column in a dataframe with case-insensitive matching.

        Args:
            dataframe: pandas/geopandas DataFrame
            column_name: target column name (e.g., 'codigo')

        Returns:
            Actual column name from dataframe

        Raises:
            KeyError: if column not found
        """
        # Create mapping of lowercase column names to actual names
        column_map = {col.lower(): col for col in dataframe.columns}

        # Search for target column (case-insensitive)
        target_lower = column_name.lower()

        if target_lower in column_map:
            return column_map[target_lower]
        else:
            raise KeyError(
                f"Column '{column_name}' not found in shapefile.\n\n" +
                f"Available columns: {', '.join(dataframe.columns)}\n\n" +
                f"Please make sure your stations shapefile has a column\n" +
                f"named 'codigo', 'Codigo', or 'CODIGO' with station IDs."
            )

    def load_shapefile_stations(self):
        shapefile_path, _ = QFileDialog.getOpenFileName(self, "Select Shapefile", "", "Shapefiles (*.shp)")
        if shapefile_path:
            self.Path_Shp_Stations.setText(shapefile_path)
            layer = QgsVectorLayer(shapefile_path, "Estaciones", "ogr")
            if not layer.isValid():
                QMessageBox.critical(self, "Error", "Could not load stations layer.")
            else:
                QgsProject.instance().addMapLayer(layer)

    def load_excel_time_series(self):
        excel_path, _ = QFileDialog.getOpenFileName(self, "Select Excel File", "", "Excel files (*.xlsx)")
        if excel_path:
            self.Path_excel_time_series.setText(excel_path)

    def run_process_tmax(self):
        elev = self.get_elevation()
        path_df = self.Path_excel_time_series.text()
        path_meta = self.Path_Shp_Stations.text()
        output_excel_path = os.path.join(self.output_path.text(), self.name_project.text(), 'temp', '03-Phenology',
                                  'TAmax.xlsx')

        # Read shapefile and find 'codigo' column (case-insensitive)
        df_meta = gpd.read_file(path_meta)
        codigo_col = self._find_column_case_insensitive(df_meta, 'codigo')
        df_meta = df_meta.set_index(codigo_col)

        df_meta_tmax = df_meta[df_meta['Tamax'] == 1]
        df_inTmax = pd.read_excel(path_df, 'Tamax', index_col=0)
        # df_inTmax = df_inTmax.apply(pd.to_numeric, errors='coerce')
        df_new_Tmax = self.Series_X_Y(df_meta_tmax, df_inTmax, 'Tamax')
        QMessageBox.information(self, "Process to start", "Please keep the window open until the process is finished.")
        progress_signal = ProgressSignal()
        progress_signal.progress.connect(self.progressBar_Tmax.setValue)

        df_out_Tmax = self.temperatura(elev, df_new_Tmax, progress_signal)
        df_out_Tmax.to_excel(output_excel_path, engine='openpyxl')
        QMessageBox.information(self, "Process Complete", "Tmax completed.")
        self.df_out_Tmax = df_out_Tmax

    def run_process_tmin(self):
        elev = self.get_elevation()
        path_df = self.Path_excel_time_series.text()

        path_meta = self.Path_Shp_Stations.text()
        output_excel_path = os.path.join(self.output_path.text(), self.name_project.text(), 'temp', '03-Phenology',
                                  'Tamin.xlsx')

        # Read shapefile and find 'codigo' column (case-insensitive)
        df_meta = gpd.read_file(path_meta)
        codigo_col = self._find_column_case_insensitive(df_meta, 'codigo')
        df_meta = df_meta.set_index(codigo_col)

        df_meta_tmin = df_meta[df_meta['Tamin'] == 1]
        df_in_Tmin = pd.read_excel(path_df, 'Tamin', index_col=0)

        # df_in_Tmin = df_in_Tmin.apply(pd.to_numeric, errors='coerce')
        df_new_T_min = self.Series_X_Y(df_meta_tmin, df_in_Tmin, 'Tamin')
        QMessageBox.information(self, "Process to start", "Please keep the window open until the process is finished.")
        progress_signal = ProgressSignal()
        progress_signal.progress.connect(self.progressBar_Tmin.setValue)
        df_out_Tmin = self.temperatura(elev, df_new_T_min, progress_signal)
        df_out_Tmin.to_excel(output_excel_path, engine='openpyxl')
        QMessageBox.information(self, "Process Complete", "Tmin completed.")
        self.df_out_Tmin = df_out_Tmin

    def run_process_pt(self):
        elev = self.get_elevation()
        path_df = self.Path_excel_time_series.text()
        path_meta = self.Path_Shp_Stations.text()
        path_raster = self.Path_Lulc.text()
        output_excel_path = os.path.join(self.output_path.text(), self.name_project.text(), 'temp', '03-Phenology',
                                  'PV.xlsx')

        # Read shapefile and find 'codigo' column (case-insensitive)
        df_meta = gpd.read_file(path_meta)
        codigo_col = self._find_column_case_insensitive(df_meta, 'codigo')
        df_meta = df_meta.set_index(codigo_col)
        df_meta_Pt = df_meta[df_meta['PV'] == 1]
        df_inPt = pd.read_excel(path_df, 'PV', index_col=0)
        df_new_PT = self.Series_X_Y(df_meta_Pt, df_inPt, 'PV')
        QMessageBox.information(self, "Process to start", "Please keep the window open until the process is finished.")
        progress_signal = ProgressSignal()
        progress_signal.progress.connect(self.progressBar_PT.setValue)
        df_out_PT = self.Interpolacion_PT(df_new_PT, path_raster, progress_signal)
        df_out_PT.to_excel(output_excel_path, engine='openpyxl')
        QMessageBox.information(self, "Process Complete", "PT completed.")
        self.df_out_PT = df_out_PT

    def get_elevation(self):
        return self.elevaciones(self.Path_raster.text(), self.Path_Lulc.text())

    def Series_X_Y(self, catalogo, df, var):
        """
        Merge station catalog with time series data.

        Args:
            catalogo: GeoDataFrame with station metadata (indexed by 'codigo')
            df: DataFrame with time series data (Date as index, station names as columns)
            var: Variable type ('Tamax', 'Tamin', or 'PV')

        Returns:
            DataFrame with station coordinates and time series data
        """
        if var == 'Tamax' or var == 'Tamin':
            cols_select = ['y', 'x', 'z']
        else:
            cols_select = ['y', 'x']

        # Transpose: rows become station names, columns become dates
        data = df.loc[df.index[0]:].T
        columnas = data.columns
        str_list = [d.strftime('%Y-%m-%d') for d in columnas]

        # Keep station codes as strings (they can be numeric or alphanumeric)
        # data.index is now the station names from Excel columns
        data.columns = str_list
        data.index.name = 'codigo'

        # Get station coordinates from catalog
        df_new = catalogo[cols_select].copy()

        # Merge using string-based index (no conversion to int)
        # This works for both numeric codes (e.g., "12345") and alphanumeric (e.g., "M0045", "Chanlud_M")
        df_new = df_new.merge(data, left_index=True, right_index=True, how='inner')

        if len(df_new) == 0:
            # No matches found - provide helpful error message
            catalog_codes = set(catalogo.index.astype(str))
            excel_codes = set(data.index.astype(str))

            raise ValueError(
                f"No matching station codes found between shapefile and Excel.\n\n" +
                f"Shapefile codes (first 10): {list(catalog_codes)[:10]}\n\n" +
                f"Excel columns (first 10): {list(excel_codes)[:10]}\n\n" +
                f"Make sure the station codes in the shapefile 'Codigo' column\n" +
                f"match the column names in the Excel file.\n\n" +
                f"Common in both: {catalog_codes & excel_codes if catalog_codes & excel_codes else 'None'}"
            )

        return df_new

    def elevaciones(self, path_dem, path_lulc):
        """
        Calculate mean elevation for each land cover class.
        Properly handles NoData values in both LULC and DEM rasters.
        """
        # Read LULC raster
        with rasterio.open(path_lulc) as src:
            coverage_data = src.read(1)
            coverage_meta = src.meta
            coverage_nodata = coverage_meta.get('nodata')

        # Read DEM raster
        with rasterio.open(path_dem) as src:
            Dem_data = src.read(1)
            Dem_meta = src.meta
            dem_nodata = Dem_meta.get('nodata')

        # Verify dimensions match
        if coverage_data.shape != Dem_data.shape:
            QgsMessageLog.logMessage(
                f"Dimension mismatch: LULC {coverage_data.shape} vs DEM {Dem_data.shape}",
                "QSIGA_CAL",
                Qgis.Warning
            )
            raise ValueError(
                f"Dimension mismatch!\n" +
                f"  LULC shape: {coverage_data.shape}\n" +
                f"  DEM shape: {Dem_data.shape}\n" +
                f"Rasters must have the same dimensions."
            )

        # Get unique land cover codes (excluding NoData)
        coverage_codes = np.unique(coverage_data)
        if coverage_nodata is not None:
            coverage_codes = coverage_codes[coverage_codes != coverage_nodata]

        # Calculate mean elevation for each land cover class
        elv_series = {code: [] for code in coverage_codes}
        nodata_count = 0

        for code in coverage_codes:
            # Create mask for this land cover class
            lulc_mask = coverage_data == code

            if not np.any(lulc_mask):
                # No pixels with this land cover code
                elv_series[code].append(np.nan)
                continue

            # Get DEM values for this land cover class
            dem_values = Dem_data[lulc_mask]

            # Filter out NoData values from DEM
            if dem_nodata is not None:
                # Create valid data mask (exclude NoData)
                valid_mask = dem_values != dem_nodata
                dem_values_valid = dem_values[valid_mask]
            else:
                dem_values_valid = dem_values

            # Also filter out NaN values (in case DEM has them)
            dem_values_valid = dem_values_valid[~np.isnan(dem_values_valid)]

            # Calculate mean elevation
            if len(dem_values_valid) > 0:
                elv_mean = np.mean(dem_values_valid)
                elv_series[code].append(elv_mean)

                # Count NoData pixels for logging
                total_pixels = len(dem_values)
                valid_pixels = len(dem_values_valid)
                nodata_pixels = total_pixels - valid_pixels

                if nodata_pixels > 0:
                    nodata_pct = (nodata_pixels / total_pixels) * 100
                    if nodata_pct > 10:  # Log if > 10% NoData
                        nodata_count += 1
            else:
                # All DEM values are NoData for this land cover class
                elv_series[code].append(np.nan)
                nodata_count += 1

        # Log warnings about NoData
        if nodata_count > 0:
            QgsMessageLog.logMessage(
                f"{nodata_count} land cover classes have significant NoData in DEM",
                "QSIGA_CAL",
                Qgis.Warning
            )

        df_elv = pd.DataFrame(elv_series)

        # Check for NaN values
        nan_count = df_elv.T[0].isna().sum()
        if nan_count > 0:
            QgsMessageLog.logMessage(
                f"WARNING: {nan_count} land cover classes have NaN elevation",
                "QSIGA_CAL",
                Qgis.Warning
            )

        return df_elv.T

    def temperatura(self, Elevacion, Series_ts, progress_signal=None):
        fechas = Series_ts.columns[3:]

        Series_ts.replace(-9999, np.nan, inplace=True)
        data = Series_ts[fechas].interpolate(axis=1)


        x = Series_ts['z']
        if x.isna().any():
            raise ValueError("La columna 'z' contiene valores NaN. Por favor, maneja estos valores")
        else:
            X = sm.add_constant(x, prepend=False)

        Cuencas = Elevacion.index
        df_result = pd.DataFrame(columns=Cuencas, index=fechas)

        total_steps = len(fechas)
        if progress_signal:
            progress_signal.progress.emit(0)

        for i, f in enumerate(fechas):
            print(f)

            valid_index = data[f].dropna().index
            model = sm.OLS(data[f].loc[valid_index], X.loc[valid_index], missing='drop')

            # model = sm.OLS(data[f], X, missing='drop')
            statistics = model.fit()
            coefficient_A = statistics.params[0]
            coefficient_B = statistics.params[1]

            df_ele_aligned = Elevacion.reindex(Cuencas)
            values = coefficient_A * df_ele_aligned[0] + coefficient_B
            df_result.loc[f] = values

            if progress_signal:
                progress_signal.progress.emit(int((i + 1) / total_steps * 100))

        return df_result



    def IDW(self, x, y, z, input_dem, power=2):

        def LoadRaster( file_name):
            g = gdal.Open(file_name, gdalconst.GA_ReadOnly)
            g.GetRasterBand(1)
            nodatavalue = g.GetRasterBand(1).GetNoDataValue()
            cols, rows = g.RasterXSize, g.RasterYSize
            geotransform = g.GetGeoTransform()
            xmin = geotransform[0]
            ymax = geotransform[3]
            pixelWidth = geotransform[1]
            pixelHeight = geotransform[5]
            xmax = xmin + (cols * pixelWidth)
            ymin = ymax + (rows * pixelHeight)
            grid = g.ReadAsArray(0, 0, cols, rows)
            return grid, nodatavalue, cols, rows, xmin, xmax, ymin, ymax
        def distancia2(x, y, xi, yi):
            obs = np.vstack((x, y)).T
            interpolar = np.vstack((xi, yi)).T
            d0 = np.subtract.outer(obs[:, 0], interpolar[:, 0])
            d1 = np.subtract.outer(obs[:, 1], interpolar[:, 1])
            Md = np.hypot(d0, d1)
            return Md

        def distancia(x, y, xi, yi):
            obs = np.vstack((x, y)).T
            interpolar = np.vstack((xi, yi)).T
            d0 = np.subtract.outer(obs[:, 0], interpolar[:, 0])
            d1 = np.subtract.outer(obs[:, 1], interpolar[:, 1])
            return np.hypot(d0, d1)
        def malla2(xmax, xmin, ymax, ymin, nx, ny):
            xi = np.linspace(xmin, xmax, nx)
            yi = np.linspace(ymin, ymax, ny)
            xi, yi = np.meshgrid(xi, yi)
            xi, yi = xi.flatten(), yi.flatten()
            return xi, yi

        def malla(input_dem):
            dem_ds = gdal.Open(input_dem)
            geotransform = dem_ds.GetGeoTransform()
            cols = dem_ds.RasterXSize
            rows = dem_ds.RasterYSize
            xmin = geotransform[0]
            ymax = geotransform[3]
            pixelWidth = geotransform[1]
            pixelHeight = geotransform[5]

            # Generate coordinates for each pixel
            xi = np.array([xmin + i * pixelWidth for i in range(cols)])
            yi = np.array([ymax + j * pixelHeight for j in range(rows)])
            xi, yi = np.meshgrid(xi, yi)
            return xi.flatten(), yi.flatten()

        # xi, yi = malla(xmax, xmin, ymax, ymin, nx, ny)
        xi, yi = malla(input_dem)
        dem, _, cols, rows, _, _, _, _ = LoadRaster(input_dem)
        dist = distancia(x, y, xi, yi)
        W = 1.0 / dist**power
        W /= W.sum(axis=0)
        zi = np.dot(W.T, z)
        zi = zi.reshape(rows, cols)
        return xi, yi, zi

    def pixel(self, xmax, xmin, ymax, ymin, nx, ny):
        pixelWidth = abs(xmin - xmax) / nx
        pixelHeight = abs(ymin - ymax) / ny
        return pixelWidth, pixelHeight

    def Interpolacion_PT(self, Pt_Series, path_raster, progress_signal=None, Nx=None, Ny=None):
        fechas = Pt_Series.columns[2:]

        Pt_Series.replace(-9999, np.nan, inplace=True)
        y = Pt_Series['y']
        x = Pt_Series['x']

        Pt_Series = Pt_Series[fechas].interpolate(axis=0)
        with rasterio.open(path_raster) as src:
            coverage_data = src.read(1)
            bounds = src.bounds
            coverage_meta = src.meta

        if Nx is None and Ny is None:
            nx = src.shape[0]
            ny = src.shape[1]
        else:
            nx = Nx
            ny = Ny

        coverage_codes = np.unique(coverage_data)
        coverage_codes = coverage_codes[coverage_codes != coverage_meta['nodata']]
        PT_series = {code: [] for code in coverage_codes}

        total_steps = len(fechas)
        if progress_signal:
            progress_signal.progress.emit(0)

        for i, ft in enumerate(fechas[:]):
            print(ft)


            z = Pt_Series[ft]

            xmin = bounds.left
            xmax = bounds.right
            ymin = bounds.bottom
            ymax = bounds.top

            # xi, yi, zi = self.IDW(x, y, z, nx, ny, xmax, xmin, ymax, ymin)
            xi, yi, zi = self.IDW(x, y, z, path_raster)
            # pixelW, pixelH = self.pixel(xmax, xmin, ymax, ymin, nx, ny)
            # transform = Affine(pixelW, 0.0, xmin, 0.0, -pixelH, ymax)
            nodata = -9999
            # zi[np.isnan(zi)] = nodata
            array = np.flipud(zi)
            for code in coverage_codes:
                mask = coverage_data == code
                if np.any(mask):
                    masked_zi = zi[mask]
                    if masked_zi.size > 0:
                        lai_mean = np.mean(masked_zi)
                    else:
                        lai_mean =  np.nan
                    PT_series[code].append(lai_mean)
                else:
                    PT_series[code].append(np.nan)

            if progress_signal:
                progress_signal.progress.emit(int((i + 1) / total_steps * 100))

        df = pd.DataFrame(PT_series, index=pd.to_datetime(fechas))
        df.index.name = 'Date'
        return df

    def save_results_to_excel(self):
        path_input =os.path.join(self.output_path.text(), self.name_project.text(), 'temp', '03-Phenology/')

        PathOutput = os.path.join(self.output_path.text(),self.name_project.text(), 'temp', '03-Phenology/')

        files = ['TAmin', 'TAmax', 'PV']
        xlsx = pd.ExcelWriter(PathOutput+'MeteoData.xlsx')
        index= pd.read_excel(path_input + 'PV' + '.xlsx',index_col=0).index
        for file in files:
            df = pd.read_excel(path_input+file+'.xlsx',index_col=0)
            df.index=index
            if file == 'PV':
                name = 'P'
            else:
                name = file

            df.to_excel(xlsx, name)
        xlsx.close()
        QMessageBox.information(self, "Process Complete", "Export completed.")

    def go_to_step_3(self):
        self.update_spinBox_values()
        self.toolBox.setCurrentIndex(2)

    #### funciones step 3 Calibracion #############################

    def update_spinBox_values(self):
        PathProject = os.path.join(self.output_path.text(), self.name_project.text(), 'temp', '03-Phenology')
        P = pd.read_excel(os.path.join(PathProject, 'MeteoData.xlsx'), sheet_name='P')
        P['Date'] = pd.to_datetime(P['Date'], format='%d/%m/%Y')
        P.set_index('Date', inplace=True)
        code_lulc = P.columns

        # Filter OUT artificial/urban land covers (Corine Land Cover: 100-199)
        # Only natural/agricultural covers (NOT in range 100-199) can be calibrated
        code_lulc_natural = [col for col in code_lulc if isinstance(col, (int, float)) and not (100 <= col <= 199)]

        self.spinBox.clear()  # Limpiar valores existentes
        for value in code_lulc_natural:
            self.spinBox.addItem(str(int(value)))

    def run_process_lai(self):
        # import spotpy_setup_LAI as spotpy_setup
        self.progressBar_process_LAI.setValue(1)

        QMessageBox.information(self, "Start Process", "Parameter scanning process is about to start, ")
        # Obtener los valores de las entradas del usuario
        NumIter = int(self.QNumIter.text())
        period = int(self.QPeriod.text())
        OmitObs = int(self.QOmitObs.text())
        SOS1 = int(self.QSOS1.text())
        SOS2 = int(self.QSOS1_2.text())
        ft_sup_min = float(self.Qft_sup_min.text())
        ft_sup_max = float(self.Qft_sup_max.text())

        PathProject = os.path.join(self.output_path.text(), self.name_project.text(), 'temp', '03-Phenology')

        # Cargar los datos necesarios
        P = pd.read_excel(os.path.join(PathProject, 'MeteoData.xlsx'), sheet_name='P')
        P['Date'] = pd.to_datetime(P['Date'], format='%d/%m/%Y')
        P.set_index('Date', inplace=True)


        Tmin = pd.read_excel(os.path.join(PathProject, 'MeteoData.xlsx'), sheet_name='TAmin')
        Tmin['Date'] = pd.to_datetime(Tmin['Date'], format='%d/%m/%Y')
        Tmin.set_index('Date', inplace=True)

        Tmax = pd.read_excel(os.path.join(PathProject, 'MeteoData.xlsx'), sheet_name='TAmax')
        Tmax['Date'] = pd.to_datetime(Tmax['Date'], format='%d/%m/%Y')
        Tmax.set_index('Date', inplace=True)

        LAI_Obs = pd.read_excel(os.path.join(PathProject, 'TS_LAI_LULC_Movil.xlsx'))
        LAI_Obs['Date'] = pd.to_datetime(LAI_Obs['Date'], format='%d/%m/%Y')
        LAI_Obs = LAI_Obs.dropna()
        LAI_Obs.set_index('Date', inplace=True)

        # Alinear los datos
        id = (Tmin.index >= LAI_Obs.index[0]) & (Tmin.index <= LAI_Obs.index[-1])
        Tmin = Tmin.iloc[id, :]
        Tmax = Tmax.iloc[id, :]
        P = P.iloc[id, :]

        LAI_Obs = pd.merge(pd.DataFrame(index=Tmax.index), LAI_Obs, left_index=True, right_index=True,
                           how='outer').interpolate()

        ETP = 1.0 * (100. * (8.0 / (365.0 * 12.0))) * ((0.46 * (Tmax + Tmin) / 2.0) + 8.13)
        SMI = P / ETP

        # Get the selected land cover from spinBox (excludes 100-199 urban/artificial covers)
        code_lulc = P.columns
        i = code_lulc.tolist().index(int(self.spinBox.currentText()))

        diccio_algorit = {'DDS': 1, 'LHS': 2, 'SCE': 3}
        Algorithm = diccio_algorit[self.Algorithm.currentText()]

        # Límites de parámetros de calibración
        t_inf_min = 5.0
        t_inf_max = 0.99 * np.min((Tmax.iloc[:, i].values + Tmin.iloc[:, i].values) / 2)
        lai_min_min = 0.95 * np.min(LAI_Obs.iloc[:, i])
        lai_min_max = 1.05 * np.min(LAI_Obs.iloc[:, i])
        f_lai_min = 0.95 * np.max(LAI_Obs.iloc[:, i]) / np.min(LAI_Obs.iloc[:, i])
        f_lai_max = 1.05 * np.max(LAI_Obs.iloc[:, i]) / np.min(LAI_Obs.iloc[:, i])
        l1_min = float(self.Ql1_min.text())
        l1_max = float(self.Ql1_max.text())
        l2_min = float(self.Ql2_min.text())
        l2_max = float(self.Ql2_max.text())
        l3_min = float(self.Ql3_min.text())
        l3_max = float(self.Ql3_max.text())
        PUA_Diff = Tmax.iloc[:, i].values - Tmin.iloc[:, i].values
        PUA_P = self.max_sum_in_windows(PUA_Diff, int(period))
        phu_min = PUA_P * 0.9
        phu_max = PUA_P * 1
        fr_phu_sen_min = float(self.Qfr_phu_sen_min.text())
        fr_phu_sen_max = float(self.Qfr_phu_sen_max.text())
        SMIc_min = 0.0
        SMIc_max = np.nanmax(SMI.iloc[:, i].values) * 0.8
        nSMI_min = float(self.QnSMI_min.text())
        nSMI_max = float(self.QnSMI_max.text())
        gdd_c_min = 0.0
        gdd_c_max = PUA_P

        Param_Min = [t_inf_min, ft_sup_min, lai_min_min, f_lai_min, l1_min, l2_min, l3_min, phu_min, fr_phu_sen_min,
                     SMIc_min, nSMI_min, gdd_c_min]
        Param_Max = [t_inf_max, ft_sup_max, lai_min_max, f_lai_max, l1_max, l2_max, l3_max, phu_max, fr_phu_sen_max,
                     SMIc_max, nSMI_max, gdd_c_max]

        Factor_ObjFun = -1 if Algorithm == 1 else 1
        Search_ObjFun = True if Algorithm == 1 else False

        model = VegetationGrowthModel(Param_Min, Param_Max, SOS1, SOS2, LAI_Obs.index.month,
                                                   Tmin.iloc[:, i].values, Tmax.iloc[:, i].values,
                                                   LAI_Obs.iloc[:, i].values, SMI.iloc[:, i].values, OmitObs,
                                                   Factor_ObjFun)
        PathParams = os.path.join(PathProject,   'Params_VegGrowthModel_' + str(code_lulc[i]))

        if Algorithm == 1:
            sampler = spotpy.algorithms.dds(model, dbname=PathParams, dbformat='csv')
        elif Algorithm == 2:
            sampler = spotpy.algorithms.lhs(model, dbname=PathParams, dbformat='csv')
        elif Algorithm == 3:
            sampler = spotpy.algorithms.sceua(model, dbname=PathParams, dbformat='csv')

        # Redirigir stdout
        old_stdout = sys.stdout
        sys.stdout = StreamToLogger(self.progress_signal)

        try:
            sampler.sample(NumIter)
        finally:
            sys.stdout = old_stdout

        self.progress_signal.progress.emit(100)

        results = spotpy.analyser.load_csv_results(PathParams)
        best_params_i = spotpy.analyser.get_best_parameterset(results, maximize=Search_ObjFun)

        Sim = PhenologicalModel(best_params_i[0], SOS1, SOS2, LAI_Obs.index.month, Tmin.iloc[:, i].values,
                                             Tmax.iloc[:, i].values, SMI.iloc[:, i].values)
        Obs = LAI_Obs.iloc[:, i].values  # ✅ CORREGIDO: Usa la cobertura seleccionada

        Part_1 = np.sum((Obs - Sim[1:]) ** 2)
        Part_2 = np.sum((Obs - np.nanmean(Obs)) ** 2)
        NSE = (Part_1 / Part_2)
        print(NSE)

        self.show_graph(Obs, Sim[1:],LAI_Obs.index)
        self.save_graph(Obs, Sim[1:],LAI_Obs.index,'_Initial')
        QMessageBox.information(self, "Process Complete", "Check graph and adjust parameter range...")

    def max_sum_in_windows(self,series, window_size):
        max_sum = -np.inf
        for i in range(len(series) - window_size + 1):
            current_sum = series[i:i + window_size].sum()
            if current_sum > max_sum:
                max_sum = current_sum
        return max_sum

    def zoom_in(self):
        self.graphicsView.scale(1.2, 1.2)

    def zoom_out(self):
        self.graphicsView.scale(0.8, 0.8)

    def zoom_in_2(self):
        self.graphicsView_2.scale(1.2, 1.2)

    def zoom_out_2(self):
        self.graphicsView_2.scale(0.8, 0.8)

    def show_graph(self, Obs, Sim,index):
        name = self.spinBox.currentText()


        graphics_view_size = self.graphicsView.size()
        width = graphics_view_size.width()
        height = graphics_view_size.height()

        # Convertir el tamaño a pulgadas para Matplotlib (1 pulgada = 96 píxeles es una buena aproximación)
        figsize = (width / 96, height / 96)

        # figsize = (13, 8)
        size_line = 1.5
        s_n = 14
        fig, ax = plt.subplots(figsize=figsize)
        ax.plot(index, Obs, color='navy', linewidth=size_line, alpha=0.5, label="Observed LAI")
        ax.plot(index, Sim, color='darkred', linewidth=size_line, linestyle='--', alpha=0.9,label="Simulated LAI")
        ax.set_title('LAI Calibration Initial - lulc :' + str(name), fontsize=s_n + 2, fontweight='bold')
        ax.set_xlabel('Time', fontsize=s_n, fontweight='bold')
        ax.set_ylabel('LAI', fontsize=s_n, fontweight='bold')
        ax.legend(loc=1)
        plt.tight_layout()
        canvas = FigureCanvasQTAgg(fig)
        scene = QGraphicsScene()
        scene.addWidget(canvas)
        self.graphicsView.setScene(scene)
        self.graphicsView.show()

    def show_graph_end(self, Obs, Sim,index):
        name = self.spinBox.currentText()


        graphics_view_size = self.graphicsView.size()
        width = graphics_view_size.width()
        height = graphics_view_size.height()

        # Convertir el tamaño a pulgadas para Matplotlib (1 pulgada = 96 píxeles es una buena aproximación)
        figsize = (width / 96, height / 96)

        # figsize = (13, 8)
        size_line = 1.5
        s_n = 14
        fig, ax = plt.subplots(figsize=figsize)
        ax.plot(index, Obs, color='navy', linewidth=size_line, alpha=0.5, label="Observed LAI")
        ax.plot(index, Sim, color='darkred', linewidth=size_line, linestyle='--', alpha=0.9,label="Simulated LAI")
        ax.set_title('LAI Calibration Final- lulc :' + str(name), fontsize=s_n + 2, fontweight='bold')
        ax.set_xlabel('Time', fontsize=s_n, fontweight='bold')
        ax.set_ylabel('LAI', fontsize=s_n, fontweight='bold')
        ax.legend(loc=1)
        plt.tight_layout()
        canvas = FigureCanvasQTAgg(fig)
        scene = QGraphicsScene()
        scene.addWidget(canvas)
        self.graphicsView_2.setScene(scene)
        self.graphicsView_2.show()

    def save_graph(self, Obs, Sim,index,tipo):
        PathProject = os.path.join(self.output_path.text(), self.name_project.text(), 'temp', '03-Phenology')

        name = self.spinBox.currentText()


        figsize = (13, 8)
        size_line = 1.5
        s_n = 14
        fig, ax = plt.subplots(figsize=figsize)
        ax.plot(index, Obs, color='navy', linewidth=size_line, alpha=0.5, label="Observed LAI")
        ax.plot(index, Sim, color='darkred', linewidth=size_line, linestyle='--', alpha=0.9,label="Simulated LAI")
        ax.set_title('LAI Calibration - lulc :' + str(name), fontsize=s_n + 2, fontweight='bold')
        ax.set_xlabel('Time', fontsize=s_n, fontweight='bold')
        ax.set_ylabel('LAI', fontsize=s_n, fontweight='bold')
        ax.legend(loc=1)
        plt.tight_layout()

        new_folder = os.path.join(PathProject, 'Figuras/')
        os.makedirs(new_folder, exist_ok=True)
        name_out = os.path.join(new_folder, 'Fig_Cal_Lai_lulc_' + str(name)+tipo)

        plt.savefig(name_out , dpi=200)
        plt.close()

    def run_process_lai_end(self):
        QMessageBox.information(self, "Start Process", "LAI calibration process is about to start, wait for its completion., ")
        self.progressBar_process_LAI_end.setValue(1)
        NumIter_END = int(self.QNumIter_end.text())
        period = int(self.QPeriod.text())
        OmitObs = int(self.QOmitObs.text())
        SOS1 = int(self.QSOS1.text())
        SOS2 = int(self.QSOS1_2.text())
        ft_sup_min = float(self.Qft_sup_min.text())
        ft_sup_max = float(self.Qft_sup_max.text())

        PathProject = os.path.join(self.output_path.text(), self.name_project.text(), 'temp', '03-Phenology')

        # Cargar los datos necesarios
        P = pd.read_excel(os.path.join(PathProject, 'MeteoData.xlsx'), sheet_name='P')
        P['Date'] = pd.to_datetime(P['Date'], format='%d/%m/%Y')
        P.set_index('Date', inplace=True)

        Tmin = pd.read_excel(os.path.join(PathProject, 'MeteoData.xlsx'), sheet_name='TAmin')
        Tmin['Date'] = pd.to_datetime(Tmin['Date'], format='%d/%m/%Y')
        Tmin.set_index('Date', inplace=True)

        Tmax = pd.read_excel(os.path.join(PathProject, 'MeteoData.xlsx'), sheet_name='TAmax')
        Tmax['Date'] = pd.to_datetime(Tmax['Date'], format='%d/%m/%Y')
        Tmax.set_index('Date', inplace=True)

        LAI_Obs = pd.read_excel(os.path.join(PathProject, 'TS_LAI_LULC_Movil.xlsx'))
        LAI_Obs['Date'] = pd.to_datetime(LAI_Obs['Date'], format='%d/%m/%Y')
        LAI_Obs = LAI_Obs.dropna()
        LAI_Obs.set_index('Date', inplace=True)

        # Alinear los datos
        id = (Tmin.index >= LAI_Obs.index[0]) & (Tmin.index <= LAI_Obs.index[-1])
        Tmin = Tmin.iloc[id, :]
        Tmax = Tmax.iloc[id, :]
        P = P.iloc[id, :]

        LAI_Obs = pd.merge(pd.DataFrame(index=Tmax.index), LAI_Obs, left_index=True, right_index=True,
                           how='outer').interpolate()

        ETP = 1.0 * (100. * (8.0 / (365.0 * 12.0))) * ((0.46 * (Tmax + Tmin) / 2.0) + 8.13)
        SMI = P / ETP

        # Get the selected land cover from spinBox (excludes 100-199 urban/artificial covers)
        code_lulc = P.columns
        i = code_lulc.tolist().index(int(self.spinBox.currentText()))

        diccio_algorit = {'DDS': 1, 'LHS': 2, 'SCE': 3}
        Algorithm = diccio_algorit[self.Algorithm.currentText()]

        # Límites de parámetros de calibración
        t_inf_min = 5.0
        t_inf_max = 0.99 * np.min((Tmax.iloc[:, i].values + Tmin.iloc[:, i].values) / 2)
        lai_min_min = 0.95 * np.min(LAI_Obs.iloc[:, i])
        lai_min_max = 1.05 * np.min(LAI_Obs.iloc[:, i])
        f_lai_min = 0.95 * np.max(LAI_Obs.iloc[:, i]) / np.min(LAI_Obs.iloc[:, i])
        f_lai_max = 1.05 * np.max(LAI_Obs.iloc[:, i]) / np.min(LAI_Obs.iloc[:, i])
        l1_min = float(self.Ql1_min.text())
        l1_max = float(self.Ql1_max.text())
        l2_min = float(self.Ql2_min.text())
        l2_max = float(self.Ql2_max.text())
        l3_min = float(self.Ql3_min.text())
        l3_max = float(self.Ql3_max.text())
        PUA_Diff = Tmax.iloc[:, i].values - Tmin.iloc[:, i].values
        PUA_P = self.max_sum_in_windows(PUA_Diff, int(period))
        phu_min = PUA_P * 0.9
        phu_max = PUA_P * 1
        fr_phu_sen_min = float(self.Qfr_phu_sen_min.text())
        fr_phu_sen_max = float(self.Qfr_phu_sen_max.text())
        SMIc_min = 0.0
        SMIc_max = np.nanmax(SMI.iloc[:, i].values) * 0.8
        nSMI_min = float(self.QnSMI_min.text())
        nSMI_max = float(self.QnSMI_max.text())
        gdd_c_min = 0.0
        gdd_c_max = PUA_P

        Param_Min = [t_inf_min, ft_sup_min, lai_min_min, f_lai_min, l1_min, l2_min, l3_min, phu_min, fr_phu_sen_min, SMIc_min, nSMI_min, gdd_c_min]
        Param_Max = [t_inf_max, ft_sup_max, lai_min_max, f_lai_max, l1_max, l2_max, l3_max, phu_max, fr_phu_sen_max, SMIc_max, nSMI_max, gdd_c_max]

        Factor_ObjFun = -1 if Algorithm == 1 else 1
        Search_ObjFun = True if Algorithm == 1 else False

        model = VegetationGrowthModel(Param_Min, Param_Max, SOS1, SOS2, LAI_Obs.index.month,
                                      Tmin.iloc[:, i].values, Tmax.iloc[:, i].values,
                                      LAI_Obs.iloc[:, i].values, SMI.iloc[:, i].values, OmitObs,  # ✅ CORREGIDO: Usa columna i
                                      Factor_ObjFun)
        PathParams = os.path.join(PathProject, 'Params_VegGrowthModel_' + str(code_lulc[i]))

        if Algorithm == 1:
            sampler = spotpy.algorithms.dds(model, dbname=PathParams, dbformat='csv')
        elif Algorithm == 2:
            sampler = spotpy.algorithms.lhs(model, dbname=PathParams, dbformat='csv')
        elif Algorithm == 3:
            sampler = spotpy.algorithms.sceua(model, dbname=PathParams, dbformat='csv')

        self.progress_signal_end.progress.emit(0)

        # Redirigir stdout
        old_stdout = sys.stdout
        sys.stdout = StreamToLogger(self.progress_signal_end)

        try:
            sampler.sample(NumIter_END)
        finally:
            sys.stdout = old_stdout

        self.progress_signal_end.progress.emit(100)

        results = spotpy.analyser.load_csv_results(PathParams)
        best_params = spotpy.analyser.get_best_parameterset(results, maximize=Search_ObjFun)

        self.RESULT[str(code_lulc[i])] = best_params
        self.processed_coverages.add(self.spinBox.currentText())

        Sim_end = PhenologicalModel(best_params[0], SOS1, SOS2, LAI_Obs.index.month, Tmin.iloc[:, i].values,
                                             Tmax.iloc[:, i].values, SMI.iloc[:, i].values)
        Obs_end = LAI_Obs.iloc[:, i].values  # ✅ CORREGIDO: Usa la cobertura seleccionada


        self.show_graph_end(Obs_end, Sim_end[1:],LAI_Obs.index)
        self.save_graph(Obs_end, Sim_end[1:], LAI_Obs.index, '_Final')



        QMessageBox.information(self, "Process Complete", "Completed process, continue with next LULC")

    def export_result(self):
        all_coverages = set(self.spinBox.itemText(i) for i in range(self.spinBox.count()))
        if self.processed_coverages != all_coverages:
            QMessageBox.warning(None, "Export Incomplete", "Not all coverages have been processed yet.")
            return

        PathProject = os.path.join(self.output_path.text(), self.name_project.text(), 'temp', '03-Phenology')
        output_file = os.path.join(PathProject, 'Best_Parametros.xlsx')

        try:
            # Crear un DataFrame vacío para almacenar todos los resultados
            combined_df = pd.DataFrame(columns=self.RESULT.keys())

            for key, values in self.RESULT.items():
                # Convertir cada array en un DataFrame y tomar la primera columna
                value = pd.DataFrame(values)
                try:
                    combined_df[key] = value.T
                except:
                    combined_df[key] = value.T[value.T.columns[0]]

            combined_df.loc['partf_sup'] = combined_df.loc['partf_sup'] * combined_df.loc['part_inf']

            combined_df.loc['parf_lai'] = combined_df.loc['parf_lai'] * combined_df.loc['parlai_min']

            new_index = ['TAinf', 'TAsup', 'LAImin', 'LAImax', 'l1', 'l2', 'l3', 'PHU', 'frPHUsen', 'SMIc', 'nSMI',
                         'pargdd_c']
            combined_df.index = new_index

            # Escribir el DataFrame combinado en una sola hoja del archivo Excel
            with pd.ExcelWriter(output_file) as writer:
                combined_df.to_excel(writer, sheet_name='Best_Parameters', index=True)

            QMessageBox.information(None, "Export Complete", "The parameters have been successfully exported.")
        except Exception as e:
            QMessageBox.critical(None, "Export Failed", f"An error occurred while exporting: {str(e)}")

    #### Project State Management ############################
    def save_project_state(self):
        """
        Save the current state of the plugin to QGIS project variables.
        This is called automatically when the QGIS project is saved.
        """
        try:
            project = QgsProject.instance()

            QgsMessageLog.logMessage("QSIGA_CAL Step 02: Saving project state...", "QSIGA_CAL", Qgis.Info)

            # Create a dictionary with all the state information
            state = {
                # Step 1 - Download MODIS
                'name_project': self.name_project.text(),
                'output_path': self.output_path.text(),
                'Path_raster': self.Path_raster.text(),  # Corrected from Path_Dem
                'start_date': self.start_date.date().toString('yyyy-MM-dd'),
                'end_date': self.end_date.date().toString('yyyy-MM-dd'),

                # Step 2 - Process MODIS
                'Path_Lulc': self.Path_Lulc.text(),
                'Path_Shp_Stations': self.Path_Shp_Stations.text(),
                'Path_excel_time_series': self.Path_excel_time_series.text(),
                'Path_WS': self.Path_WS.text(),

                # Step 3 - Calibration
                'spinBox_currentText': self.spinBox.currentText(),
                'spinBox_currentIndex': self.spinBox.currentIndex(),

                # Current toolbox page
                'current_toolbox_index': self.toolBox.currentIndex()
            }

            # Save state as JSON string in project variables
            project.writeEntry('QSIGA_CAL_Step02', 'plugin_state', json.dumps(state))

            msg = f"Project state saved: {state['name_project']} at {state['output_path']}"
            QgsMessageLog.logMessage(msg, "QSIGA_CAL", Qgis.Success)
            print(f"QSIGA_CAL Step 02: {msg}")

        except Exception as e:
            error_msg = f"Error saving Step 02 project state: {e}"
            QgsMessageLog.logMessage(error_msg, "QSIGA_CAL", Qgis.Critical)
            print(error_msg)
            import traceback
            traceback.print_exc()

    def delayed_load_project_state(self):
        """
        Delayed project state loading using QTimer.
        This is called when readProject signal is emitted.
        Uses QTimer to wait for plugin to be fully initialized.
        """
        # Wait 500ms before loading to ensure widget is ready
        QTimer.singleShot(500, self.load_project_state)

    def load_project_state(self):
        """
        Load the plugin state from QGIS project variables.
        This is called automatically when a QGIS project is opened.
        """
        try:
            project = QgsProject.instance()

            QgsMessageLog.logMessage("QSIGA_CAL Step 02: Loading project state...", "QSIGA_CAL", Qgis.Info)

            # Read state from project variables
            state_json, success = project.readEntry('QSIGA_CAL_Step02', 'plugin_state')

            if not success or not state_json:
                QgsMessageLog.logMessage("QSIGA_CAL Step 02: No saved state found", "QSIGA_CAL", Qgis.Warning)
                return

            state = json.loads(state_json)

            QgsMessageLog.logMessage(f"Found saved state with {len(state)} items", "QSIGA_CAL", Qgis.Info)

            # Restore Step 1 - Download MODIS
            if 'name_project' in state and state['name_project']:
                self.name_project.setText(state['name_project'])
            if 'output_path' in state and state['output_path']:
                self.output_path.setText(state['output_path'])

            # Support both old (Path_Dem) and new (Path_raster) field names
            if 'Path_raster' in state and state['Path_raster']:
                self.Path_raster.setText(state['Path_raster'])
            elif 'Path_Dem' in state and state['Path_Dem']:  # Backward compatibility
                self.Path_raster.setText(state['Path_Dem'])

            if 'start_date' in state and state['start_date']:
                self.start_date.setDate(QDate.fromString(state['start_date'], 'yyyy-MM-dd'))
            if 'end_date' in state and state['end_date']:
                self.end_date.setDate(QDate.fromString(state['end_date'], 'yyyy-MM-dd'))

            # Restore Step 2 - Process MODIS
            if 'Path_Lulc' in state and state['Path_Lulc']:
                self.Path_Lulc.setText(state['Path_Lulc'])
            if 'Path_Shp_Stations' in state and state['Path_Shp_Stations']:
                self.Path_Shp_Stations.setText(state['Path_Shp_Stations'])
            if 'Path_excel_time_series' in state and state['Path_excel_time_series']:
                self.Path_excel_time_series.setText(state['Path_excel_time_series'])
            if 'Path_WS' in state and state['Path_WS']:
                self.Path_WS.setText(state['Path_WS'])

            # Restore Step 3 - Calibration spinBox selection
            # Need to populate spinBox first before restoring selection
            if 'current_toolbox_index' in state and state['current_toolbox_index'] == 2:
                # User was on calibration page, restore spinBox values
                try:
                    self.update_spinBox_values()  # Populate spinBox with available coverages

                    # Restore selected coverage by text (more reliable than index)
                    if 'spinBox_currentText' in state and state['spinBox_currentText']:
                        index = self.spinBox.findText(state['spinBox_currentText'])
                        if index >= 0:
                            self.spinBox.setCurrentIndex(index)
                            QgsMessageLog.logMessage(f"Restored spinBox selection: {state['spinBox_currentText']}", "QSIGA_CAL", Qgis.Info)
                    elif 'spinBox_currentIndex' in state and state['spinBox_currentIndex'] >= 0:
                        # Fallback to index if text not available
                        if state['spinBox_currentIndex'] < self.spinBox.count():
                            self.spinBox.setCurrentIndex(state['spinBox_currentIndex'])
                except Exception as e:
                    QgsMessageLog.logMessage(f"Could not restore spinBox selection: {e}", "QSIGA_CAL", Qgis.Warning)

            # Restore current toolbox page
            if 'current_toolbox_index' in state:
                self.toolBox.setCurrentIndex(state['current_toolbox_index'])

            msg = f"Project state loaded: {state.get('name_project', 'Unknown')}"
            QgsMessageLog.logMessage(msg, "QSIGA_CAL", Qgis.Success)
            print(f"QSIGA_CAL Step 02: {msg}")

        except Exception as e:
            error_msg = f"Error loading Step 02 project state: {e}"
            QgsMessageLog.logMessage(error_msg, "QSIGA_CAL", Qgis.Critical)
            print(error_msg)
            import traceback
            traceback.print_exc()

    def close_plugin(self):
        """Close the plugin when Button_Finish_1 is clicked."""
        self.close()

    def closeEvent(self, event):
        self.closingPlugin.emit()
        event.accept()
