# -*- coding: utf-8 -*-
"""
/***************************************************************************
 siga_step_05_Sim
                                 A QGIS plugin
 plugin to simulate different scenarios with the sigacal model
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2024-11-12
        copyright            : (C) 2024 by The Nature Conservancy
        email                : miguel.canon@tnc.org
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load siga_step_05_Sim class from file siga_step_05_Sim.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .siga_step_05_Sim import siga_step_05_Sim
    return siga_step_05_Sim(iface)
