# -*- coding: utf-8 -*-
"""
/***************************************************************************
 siga_step_05_SimDockWidget
                                 A QGIS plugin
 plugin to simulate different scenarios with the sigacal model
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2024-11-12
        git sha              : $Format:%H$
        copyright            : (C) 2024 by The Nature Conservancy
        email                : miguel.canon@tnc.org
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
"""

import os

from qgis.PyQt import QtGui, QtWidgets, uic
from qgis.PyQt.QtCore import pyqtSignal
from qgis.utils import iface
from PyQt5.QtWidgets import QFileDialog, QMessageBox
from qgis.core import QgsRasterLayer, QgsProject
from .functions.ficheros import Ficheros, create_outputs_folders, copiar_archivo
from .functions.Functions_Raster import resample_to_match
from .functions import Fuctions_Simulations as simu
import shutil


FORM_CLASS, _ = uic.loadUiType(os.path.join(
    os.path.dirname(__file__), 'siga_step_05_Sim_dockwidget_base.ui'))


class siga_step_05_SimDockWidget(QtWidgets.QDockWidget, FORM_CLASS):

    closingPlugin = pyqtSignal()

    def __init__(self, parent=None):
        """Constructor."""
        super(siga_step_05_SimDockWidget, self).__init__(parent)
        self.setupUi(self)
        self.iface = iface

        #### Step 1 creacion de proyecto #############################
        # Connect signals to slots
        self.select_output.clicked.connect(self.select_output_folder)
        self.Button_Step_s1.clicked.connect(self.create_folders)

        #### Step 2 Simulacion Estatica #############################

        self.Yes.toggled.connect(self.toggle_path_edit)
        self.no.toggled.connect(self.toggle_path_edit)

        # Deshabilitar QLineEdit por defecto
        self.LULC_PATH.setEnabled(False)

        self.Create_folder_NbS.clicked.connect(self.Copy_maps_new_escenario)

        self.select_LULC.clicked.connect(self.select_portafolio_data)

        self.Create_new_Lulc.clicked.connect(self.Export_lulc)


        self.Create_File_Exe.clicked.connect(lambda: self.create_file_execution(
            self.name_scenario_Nbs.text(),
            self.name_Execution_Nbs.text(),
            self.start_date_s_nbs,
            self.end_date_s_nbs
        ))

        self.Run_Simulation_NbS.clicked.connect(
            lambda: self.Run_simulations(self.name_Execution_Nbs.text(), self.name_scenario_Nbs.text()))

    #### Funciones Step 1 creacion de proyecto #############################
    def select_output_folder(self):
        # Abrir un diálogo para seleccionar la carpeta de salida
        output_path = QtWidgets.QFileDialog.getExistingDirectory(self, "Select Output Folder")
        if output_path:
            self.output_path.setText(output_path)

    def create_folders(self):
        # Obtener los valores de los campos de texto
        name_project = self.name_project.text()
        name_scenario = self.name_scenario.text()
        Name_Basin = self.Name_Basin.text()
        output_path = self.output_path.text()

        if name_project and output_path:
            # Definir las rutas
            NameProcessCal = os.path.join(output_path, name_project, 'temp', '05-Prioritization')

            # Crear las carpetas necesarias
            os.makedirs(NameProcessCal, exist_ok=True)
            folders = ['DATA','FIGURES','RESULTS']
            for folder in folders:
                new_filder = os.path.join(output_path, name_project, 'temp', '04-Calibration',folder)
                os.makedirs(new_filder, exist_ok=True)

            # Llamar a la función para crear las carpetas de salida
            create_outputs_folders(output_path, name_project, name_scenario)

            ruta_origen = os.path.join(os.path.dirname(__file__), 'bin', 'cnvrtr.exe')

            ruta_origen_exe = os.path.join(os.path.dirname(__file__), 'bin', 'SIGA.exe')
            ruta_destino = output_path + os.path.sep

            # Copiar el archivo necesario
            copiar_archivo(ruta_origen, ruta_destino)

            copiar_archivo(ruta_origen_exe, ruta_destino)

            QtWidgets.QMessageBox.information(self, "Success", "Folders created successfully!")
            # Move to the next widget
            self.toolBox.setCurrentIndex(1)
        else:
            QtWidgets.QMessageBox.warning(self, "Input Error", "Please provide project name and output path.")

    #### Funciones Step 2 simulation  #############################
    def toggle_path_edit(self):
        """
        Habilita o deshabilita el QLineEdit según el QRadioButton seleccionado.
        También puede llamar a una función específica dependiendo de la selección.
        """
        if self.Yes.isChecked():
            self.LULC_PATH.setEnabled(True)  # Habilitar el QLineEdit
        else:
            self.LULC_PATH.setEnabled(False) # Deshabilitar el QLineEdit

    def select_portafolio_data(self):

        dem_path, _ = QFileDialog.getOpenFileName(self, "select file LULC", "", "Files .TIF (*.tif)")
        if dem_path:
            self.LULC_PATH.setText(dem_path)  # Actualizar QLineEdit Path_Dem
            self.load_raster_layer(dem_path, "LULC")

    def load_raster_layer(self, path, layer_name):
        """Load raster layer into QGIS."""
        layer = QgsRasterLayer(path, layer_name)
        if not layer.isValid():
            QMessageBox.critical(self, "Error", f"File could not be loaded {layer_name}.")
        else:
            QgsProject.instance().addMapLayer(layer)

    def Copy_maps_new_escenario(self):


        name_project = self.name_project.text()
        name_scenario_i = self.name_scenario_initial.text()
        Name_Basin = self.Name_Basin.text()
        new_escenario = self.name_scenario_Nbs.text()
        output_path = self.output_path.text()


        origen = os.path.join(output_path, name_project, 'entradas', 'mapas', name_scenario_i)

        destino = os.path.join(output_path, name_project, 'entradas', 'mapas', new_escenario)
        if self.Yes.isChecked():
            lista_archivos = ['arcillas.tif', 'arenas.tif', 'idCiclo.tif', 'idQ.tif', 'ki.tif', 'limos.tif', 'MO.tif',
                              'P_usle.tif'
                , 'paramo.tif', 'prioridad.tif', 'Q5a.tif', 'transicion.tif', 'Zs.tif', 'K_usle.tif']
        else:
            lista_archivos = ['arcillas.tif', 'arenas.tif', 'idCiclo.tif', 'idQ.tif', 'ki.tif', 'limos.tif', 'MO.tif',
                              'P_usle.tif'
                , 'paramo.tif', 'prioridad.tif', 'Q5a.tif', 'transicion.tif', 'Zs.tif', 'K_usle.tif','CLC.tif']
        os.makedirs(destino, exist_ok=True)

        archivos_copiados = []
        archivos_no_encontrados = []

        # Recorrer la lista de archivos especificada
        for archivo in lista_archivos:
            ruta_archivo_origen = os.path.join(origen, archivo)

            try:
                # Verificar si el archivo existe en el origen
                if os.path.exists(ruta_archivo_origen):
                    # Copiar el archivo al destino
                    shutil.copy2(ruta_archivo_origen, destino)
                    archivos_copiados.append(archivo)
                    print(f"Archivo '{archivo}' copiado exitosamente a {destino}.")
                else:
                    archivos_no_encontrados.append(archivo)
                    QtWidgets.QMessageBox.warning(self, "Error", f"file {archivo} not found.")

            except Exception as e:
                QtWidgets.QMessageBox.warning(self, "Error", f"An error occurred while copying the file  {archivo} not found.{e}")

        QtWidgets.QMessageBox.information(self, "Copy maps Files","All the .tif files were copied.")

    def Export_lulc(self):

        name_project = self.name_project.text()
        name_scenario = self.name_scenario.text()
        Name_Basin = self.Name_Basin.text()
        output_path = self.output_path.text()
        new_scenario = self.name_scenario_Nbs.text()


        path_reference =  os.path.join(output_path, name_project, 'entradas', 'mapas', name_scenario,'CLC.tif')
        new_path = os.path.join(output_path, name_project, 'entradas', 'mapas', new_scenario)
        os.makedirs(new_path,exist_ok=True)

        raster_path = self.LULC_PATH.text()
        resample_to_match(raster_path, path_reference,new_path+'/CLC.tif' )


    def create_file_execution(self,escenario,file_Exe,start_date, end_date):
        # Obtener los valores de los campos de texto
        name_project = self.name_project.text()
        name_scenario = escenario
        Name_Basin = self.Name_Basin.text()
        ProjectPath = self.output_path.text()
        calibration_file_name = self.name_calibration_file.text()
        DateStart = start_date.date().toString("yyyy-MM-dd")
        DateEnd = end_date.date().toString("yyyy-MM-dd")

        name_file_exe = file_Exe

        NameSIGAModel = 'Calidad'
        paso_temporal_dias = '1'
        modelo_geotecnico = '0'
        pH_cuencacaliente = '0'

        if NameSIGAModel == 'Hy':
            tipo_ejecucion = '1'
        elif NameSIGAModel == 'Sed':
            tipo_ejecucion = '2'
        else:
            tipo_ejecucion = '3'
            if (NameSIGAModel == 'WQ_NT') | (NameSIGAModel == 'WQ_NO') | (NameSIGAModel == 'WQ_NH4') | (
                    NameSIGAModel == 'WQ_NO3'):
                NameSIGAModel1 = 'WQ_N'
            elif (NameSIGAModel == 'WQ_PT') | (NameSIGAModel == 'WQ_PO') | (NameSIGAModel == 'WQ_PI'):
                NameSIGAModel1 = 'WQ_P'
            else:
                NameSIGAModel1 = NameSIGAModel

        NameSceExe = name_scenario
        fecha_inicio = ' '.join(DateStart.split('-'))
        fecha_fin = ' '.join(DateEnd.split('-'))
        archivo_topologia = f'Topology_{name_project}.txt'
        archivo_Tmin = 'series_Tamin.txt'
        archivo_Tmax = 'series_Tamax.txt'
        archivo_HR = 'series_HR.txt'
        archivo_RS = 'series_RS.txt'
        archivo_PV = 'series_PV.txt'
        archivo_Ux = 'series_Ux.txt'
        archivo_Uy = 'series_Uy.txt'
        archivo_Qdesc = 'NA'
        archivo_Qcapt = 'NA'
        archivo_Qarc = 'NA'
        archivo_Qlim = 'NA'
        archivo_Qare = 'NA'
        archivo_movmasa = 'NA'
        archivo_fact_cal = calibration_file_name
        archivo_muestreador = 'muestreador.txt'
        archivo_tasrest = 'series_TasRest.txt'
        archivo_vertimientos = 'vertimientos.txt'
        archivo_ciclo_cargas = 'ciclos.txt'
        archivo_condiciones_frontera = 'BoundaryCondition.txt'
        # Configurar clase de ficheros

        DicFic = Ficheros(ruta_cuenca_SIGA=os.path.join(ProjectPath, name_project, 'entradas' + os.path.sep),
                          archivo_ejecucion=name_file_exe,
                          escenario=NameSceExe,
                          fecha_inicio=fecha_inicio,
                          fecha_fin=fecha_fin,
                          paso_temporal_dias=paso_temporal_dias,
                          archivo_topologia=archivo_topologia,
                          archivo_Tmin=archivo_Tmin,
                          archivo_Tmax=archivo_Tmax,
                          archivo_HR=archivo_HR,
                          archivo_RS=archivo_RS,
                          archivo_PV=archivo_PV,
                          archivo_Ux=archivo_Ux,
                          archivo_Uy=archivo_Uy,
                          archivo_Qdesc=archivo_Qdesc,
                          archivo_Qcapt=archivo_Qcapt,
                          archivo_Qarc=archivo_Qarc,
                          archivo_Qlim=archivo_Qlim,
                          archivo_Qare=archivo_Qare,
                          archivo_movmasa=archivo_movmasa,
                          archivo_fact_cal=archivo_fact_cal,
                          archivo_muestreador=archivo_muestreador,
                          archivo_tasrest=archivo_tasrest,
                          archivo_vertimientos=archivo_vertimientos,
                          archivo_ciclo_cargas=archivo_ciclo_cargas,
                          archivo_condiciones_frontera=archivo_condiciones_frontera,
                          tipo_ejecucion=tipo_ejecucion,
                          modelo_geotecnico=modelo_geotecnico,
                          pH_cuencacaliente=pH_cuencacaliente)

        # Crear archivo de ejecución para calibración
        DicFic.crear_archivo_ejecucion()

        QtWidgets.QMessageBox.information(self, "Creation of execution file",
                                          "the file was created correctly.")


    def Run_simulations(self,file_Exe,escenario):

        QMessageBox.information(self, "Simulation to start", "Please keep wait until the process is finished.")
        name_project = self.name_project.text()
        name_file_exe = file_Exe
        name_scenario = escenario
        PathExeSIGA         = os.path.join('bin','SIGA.exe')
        ProjectPath = self.output_path.text()

        simu.ExeSIGAModel_General(ProjectPath, name_project, name_file_exe, PathExeSIGA, name_scenario)

        QMessageBox.information(self, "Simulation Complete",   f"Scenario simulation: '{name_scenario}' is finished.")


    def closeEvent(self, event):
        self.closingPlugin.emit()
        event.accept()
