# -*- coding: utf-8 -*-
"""
/***************************************************************************
 SigaConfiguracionTNC
                                 A QGIS plugin
 Plugin para configuracion de archivos necesarios para ejecucion de SIGA - CAL
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2024-06-17
        copyright            : (C) 2024 by The Nature Consernvacy
        email                : jonathan.nogales@tnc.org
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load SigaConfiguracionTNC class from file SigaConfiguracionTNC.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .SigaConfiguracionTNC import SigaConfiguracionTNC
    return SigaConfiguracionTNC(iface)
