# -*- coding: utf-8 -*-
"""
/***************************************************************************
 Calibracion_ModelDockWidget
                                 A QGIS plugin
 Este plugin se enfoca en el proceso de calibracion de los modelos Hidrologicos, sedimentos y de calidad de agua de SIGA-CAL
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2024-07-31
        git sha              : $Format:%H$
        copyright            : (C) 2024 by The Nature Conservancy
        email                : miguel.canon@tnc.org
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
"""

import sys
import os
import spotpy
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from PyQt5.QtCore import pyqtSignal, QObject
from PyQt5.QtWidgets import QFileDialog, QMessageBox
from qgis.PyQt import QtWidgets, uic
from .functions.ficheros import Ficheros, copiar_archivo, create_outputs_folders
from .functions import spotpy_setup_SIGA as spotpy_setup
from qgis.core import QgsMessageLog, Qgis
from subprocess import Popen, PIPE
from matplotlib.backends.backend_qt5agg import FigureCanvasQTAgg as FigureCanvas
from matplotlib.backends.backend_qt5agg import FigureCanvasQTAgg
import scipy.stats
from qgis.PyQt.QtWidgets import QGraphicsScene, QVBoxLayout, QPushButton, QHBoxLayout
from PyQt5.QtCore import pyqtSignal, QTimer
import time
import os
import shutil
import zipfile


class ProgressSignal(QObject):
    progress = pyqtSignal(int)

def performance(NameFunObj, FacObjF,Obs, Sim):

    if NameFunObj == 'NASH':
        # Metrica 1 - Coefficient of determination
        Part_1 = np.nansum((Obs - Sim) ** 2)
        Part_2 = np.nansum((Obs - np.nanmean(Obs)) ** 2)
        ObjFun = FacObjF * (Part_1 / Part_2)
    elif NameFunObj == 'IoAd':
        Part_1 = np.nansum((Obs - Sim) ** 2)
        Part_2 = np.nansum((np.abs((Obs - np.nanmean(Obs))) + np.abs((Sim - np.nanmean(Obs)))) ** 2)
        ObjFun = FacObjF * (Part_1 / Part_2)
    elif NameFunObj == 'EAN':
        Part_1 = np.nansum(np.abs(Obs - Sim))
        Part_2 = np.nansum(np.abs(Obs - np.nanmedian(Obs)))
        ObjFun = FacObjF * (Part_1 / Part_2)
    elif NameFunObj == 'r':
        ObjFun = FacObjF * spotpy.objectivefunctions.correlationcoefficient(Obs, Sim)
    elif NameFunObj == 'R2':
        ObjFun = FacObjF * spotpy.objectivefunctions.rsquared(Obs, Sim)
    elif NameFunObj == 'MSE':
        ObjFun = FacObjF * spotpy.objectivefunctions.mse(Obs, Sim)
    elif NameFunObj == 'RMSE':
        ObjFun = FacObjF * spotpy.objectivefunctions.rmse(Obs, Sim)
    elif NameFunObj == 'RRMSE':
        ObjFun = FacObjF * spotpy.objectivefunctions.rrmse(Obs, Sim)
    elif NameFunObj == 'COMPOS':
        # Metrica 1 - Coefficient of determination
        Part_1 = np.nansum((Obs - np.nanmean(Obs)) * (Sim - np.nanmean(Sim)))
        Part_2 = np.nansum((Obs - np.nanmean(Obs)) ** 2) * np.nansum((Sim - np.nanmean(Sim)) ** 2)
        RSqr = (Part_1 / np.sqrt(Part_2)) ** 2

        # Metrica 2 - Nash–Sutcliffe coefficient
        Part_1 = np.nansum((Obs - Sim) ** 2)
        Part_2 = np.nansum((Obs - np.nanmean(Obs)) ** 2)
        NSE = (Part_1 / Part_2)

        # Metrica 3 - Index of agreement
        Part_2 = np.nansum((np.abs((Obs - np.nanmean(Obs))) + np.abs((Sim - np.nanmean(Obs)))) ** 2)
        IoAd = (Part_1 / Part_2)

        # Metrica 4 - Error absoluto normalizado
        Part_1 = np.nansum(np.abs(Obs - Sim))
        Part_2 = np.nansum(np.abs(Obs - np.nanmedian(Obs)))
        NAE = (Part_1 / Part_2)

        # La función objetivo es una combinación lineal de las métricas anteriores donde los pesos que se asignan son
        # los siguientes:
        # RSqr:  0.2
        # NSE:   0.4
        # IoAd:  0.2
        # NAE:   0.2
        ObjFun = FacObjF * ((0.2 * (1 - RSqr)) + (0.4 * NSE) + (0.2 * IoAd) + (0.2 * NAE))
    elif NameFunObj == 't-Student':
        t_stat, p_valor = scipy.stats.ttest_ind(Obs, Sim)
        ObjFun = FacObjF * t_stat
    return ObjFun

def compress_all_folders_in_directory(directory_path, output_zip):
    # Obtener todas las carpetas en el directorio especificado
    folder_paths = [os.path.join(directory_path, folder) for folder in os.listdir(directory_path) if os.path.isdir(os.path.join(directory_path, folder))]

    # Crear un archivo ZIP
    with zipfile.ZipFile(output_zip, 'w', zipfile.ZIP_DEFLATED) as zipf:
        for folder in folder_paths:
            # Recorrer todas las carpetas y archivos en la ruta dada
            for root, dirs, files in os.walk(folder):
                for file in files:
                    # Agregar cada archivo al ZIP
                    file_path = os.path.join(root, file)
                    zipf.write(file_path, os.path.relpath(file_path, directory_path))

    # Eliminar las carpetas originales
    for folder in folder_paths:
        shutil.rmtree(folder)
class QGISLogger:
    def write(self, message):
        QgsMessageLog.logMessage(message.strip(), 'Calibracion_Model', Qgis.Info)

    def flush(self):
        pass


FORM_CLASS, _ = uic.loadUiType(os.path.join(
    os.path.dirname(__file__), 'Calibracion_Model_dockwidget_base.ui'))


class Calibracion_ModelDockWidget(QtWidgets.QDockWidget, FORM_CLASS):

    closingPlugin = pyqtSignal()

    def __init__(self,iface, parent=None):
        """Constructor."""
        super(Calibracion_ModelDockWidget, self).__init__(parent)
        self.iface = iface
        self.setupUi(self)

        #### Step 1 creacion de proyecto #############################
        # Connect signals to slots
        self.select_output.clicked.connect(self.select_output_folder)
        self.Create_Folders.clicked.connect(self.create_folders)
        self.Next_Step_2.clicked.connect(lambda: self.toolBox.setCurrentIndex(1))

        #### Step 2 calibracion hIDROLOGIA #############################
        self.Run_process_Hydro_Cal.clicked.connect(self.run_process_cal)
        self.Plot_G.clicked.connect(self.plot_graph)

        self.zoom_in_button.clicked.connect(lambda: self.zoom_in(self.graphicsView_H))
        self.zoom_out_button.clicked.connect(lambda: self.zoom_out(self.graphicsView_H))

        self.Next_Step_3.clicked.connect(lambda: self.toolBox.setCurrentIndex(2))


        #### Step 3 Validacion hIDROLOGIA #############################
        self.Run_process_Hydro_Val.clicked.connect(self.Run_process_val)
        self.Plot_G_Val.clicked.connect(self.plot_sim_obs)

        self.zoom_in_button_Val.clicked.connect(lambda: self.zoom_in(self.graphicsView_H_Val))
        self.zoom_out_button_Val.clicked.connect(lambda: self.zoom_out(self.graphicsView_H_Val))

        self.Next_Step_6.clicked.connect(lambda: self.toolBox.setCurrentIndex(3))

        #### Step 4 calibracion Sedimentos #############################
        self.Run_process_Cal_S.clicked.connect(self.run_process_cal)
        self.Plot_G_S.clicked.connect(self.plot_graph_S)

        self.zoom_in_button_S.clicked.connect(lambda: self.zoom_in(self.graphicsView_S))
        self.zoom_out_button_S.clicked.connect(lambda: self.zoom_out(self.graphicsView_S))

        self.Next_Step_4.clicked.connect(lambda: self.toolBox.setCurrentIndex(4))

        #### Step 5 calibracion calidad de agua#############################

        self.Run_process_Cal_WQ.clicked.connect(self.run_process_cal)
        self.Plot_G_WQ.clicked.connect(self.plot_graph_WQ)

        self.zoom_in_button_WQ.clicked.connect(lambda: self.zoom_in(self.graphicsView_WQ))
        self.zoom_out_button_WQ.clicked.connect(lambda: self.zoom_out(self.graphicsView_WQ))


    #### Funciones Step 1 creacion de proyecto #############################
    def select_output_folder(self):
        # Abrir un diálogo para seleccionar la carpeta de salida
        output_path = QtWidgets.QFileDialog.getExistingDirectory(self, "Select Output Folder")
        if output_path:
            self.output_path.setText(output_path)

    def create_folders(self):
        # Obtener los valores de los campos de texto
        name_project = self.name_project.text()
        name_scenario = self.name_scenario.text()
        Name_Basin = self.Name_Basin.text()
        output_path = self.output_path.text()

        # Coordenada Este (X) del punto de cierre de la cuenca
        X = self.X_coor.text()#4815750

        # Coordenada Norte (Y) del punto de cierre de la cuenca
        Y = self.X_coor.text()#2195750

        # Definir las rutas
        NameProcessCal = os.path.join(output_path, name_project, 'temp', '04-Calibration')


        ruta_origen = os.path.join(os.path.dirname(__file__),'bin', 'cnvrtr.exe')

        ruta_origen_exe = os.path.join(os.path.dirname(__file__),'bin', 'SIGA.exe')
        ruta_destino = output_path + os.path.sep

        # Crear las carpetas necesarias
        os.makedirs(NameProcessCal, exist_ok=True)

        # Copiar el archivo necesario
        copiar_archivo(ruta_origen, ruta_destino)

        copiar_archivo(ruta_origen_exe, ruta_destino)

        # Llamar a la función para crear las carpetas de salida
        create_outputs_folders(output_path, name_project, name_scenario)

        QtWidgets.QMessageBox.information(self, "Success", "Folders created successfully!")


    #### Funciones Step 2 Hidrologia #############################

    def run_process_cal(self):
        # Redirigir la salida a la consola de QGIS para ver todos los mensajes
        sys.stdout = QGISLogger()
        sys.stderr = QGISLogger()

        if self.toolBox.currentIndex() == 1:  # Suponiendo que "Step2" es la segunda página, índice 1
            self.tipo_model = 'Hy'
            DateStart = self.start_date.date().toString("yyyy-MM-dd")
            DateEnd = self.end_date.date().toString("yyyy-MM-dd")
            Algorithm = self.Algorithm.currentText()
            NameFunObj = self.Metricas.currentText()
            NumIter = int(self.QNumIter.text())
            TypeFobjCal = self.Tipo_Funcion.currentText()
            out_file_zip = os.path.join(self.output_path.text(), self.name_project.text(), 'salidas', self.name_scenario.text(),'Hydrological_files.zip')



        elif self.toolBox.currentIndex() == 3:
            self.tipo_model = 'Sed'
            DateStart = self.start_date_S.date().toString("yyyy-MM-dd")
            DateEnd = self.end_date_S.date().toString("yyyy-MM-dd")
            Algorithm = self.Algorithm_S.currentText()
            NameFunObj = self.Metricas_S.currentText()
            NumIter = int(self.QNumIter_S.text())
            TypeFobjCal = self.Tipo_Funcion_S.currentText()
            out_file_zip = os.path.join(self.output_path.text(), self.name_project.text(), 'salidas',
                                        self.name_scenario.text(), 'Sediments_files.zip')

        elif self.toolBox.currentIndex() == 4:
            Diccionario_WQ = {'Nitrogeno Total NT':'WQ_NT','Nitrogeno Organico NO':'WQ_NO','Nitrogeno Amoniaca NH4':'WQ_NH4',
                              'Nitratos NO3':'WQ_NO3','Fosforo Total':'WQ_PT', 'Fosforo Organico':'WQ_PO',
                              'Fosforo Inorganico':'WQ_PI','DBO':'WQ_DBO','Oxigeno Disuelto':'WQ_OD',
                              'Coliformes Totales':' WQ_CT','E. Coli':'WQ_EColi','Temperatura':'WQ_T','Conductividad Co':'WQ_Co',
                              'pH':'WQ_pH'}


            self.tipo_model = Diccionario_WQ[self.comboBox_M_WQ.currentText()]
            DateStart = self.start_date_WQ.date().toString("yyyy-MM-dd")
            DateEnd = self.end_date_WQ.date().toString("yyyy-MM-dd")
            Algorithm = self.Algorithm_WQ.currentText()
            NameFunObj = self.Metricas_WQ.currentText()
            NumIter = int(self.QNumIter_WQ.text())
            TypeFobjCal = self.Tipo_Funcion_WQ.currentText()
            out_file_zip = os.path.join(self.output_path.text(), self.name_project.text(), 'salidas',
                                        self.name_scenario.text(), Diccionario_WQ[self.comboBox_M_WQ.currentText()]+'.zip')

        try:
            QMessageBox.information(self, "Process to start",
                                    "Please keep the window open until the process is finished.")

            # Obtener los valores de los campos de texto y otros widgets

            NameSIGAModel = self.tipo_model #'Hy'
            name_project = self.name_project.text()
            name_scenario = self.name_scenario.text()
            BasinName = self.Name_Basin.text()
            output_path = self.output_path.text()
            ProjectPath = output_path
            NameSIGAFolder = name_project
            NameProcessCal = os.path.join(output_path, name_project, 'temp', '04-Calibration')

            NameSceExeUser = name_scenario

            JSONPath = 'functions/Diccionario_ficheros.json'

            print('Número de interaciones:', NumIter)



            # Tipo de calibración [Time Series = 0 | t-Student = 1]
            dict_tipo = {'Time Series': 0, 't-Student': 1}

            TypeFobjCal = dict_tipo[TypeFobjCal]

            # Definir el algoritmo y la métrica
            diccio_algorit = {'DDS': 1, 'LHS': 2, 'SCE': 3}
            Algorithm = diccio_algorit[Algorithm]

            diccionario_metricas = {
                'Nash–Sutcliffe coefficient (1-NASH)': 'NASH',
                'Index of agreement': 'IoAd',
                'Normalized absolute error': 'NSE',
                'Correlation Coefficient': 'r',
                'Coefficient of Determination': 'R2',
                'Mean Squared Error': 'MSE',
                'Root Mean Squared Error': 'RMSE',
                'Mean Absolute Error': 'MAE',
                'Relative Root Mean Squared Error': 'RRMSE',
                'Composite function (NASH - IA - EAN)': 'COMPOS',
                't-Student':'t-student'

            }

            if self.Tipo_Funcion.currentText() == 't-Student':
                self.NameFunObj = 't-Student'
            else:

                self.NameFunObj = diccionario_metricas[self.Metricas_WQ.currentText()]

            # Cantidad de datos iniciales que se omiten para la evaluación de la función objetivo
            OmitObs = 30



            # # Coordenada Este (X) del punto de cierre de la cuenca
            X = self.X_coor.text()
            # # Coordenada Norte (Y) del punto de cierre de la cuenca
            Y = self.Y_coor.text()

            # Nombre del archivo donde se almacenan todas las evaluaciones del modelo
            NameResultsCal = 'Params_Evaluation_' + NameSIGAModel

            # ----------------------------------------------------------------------------------------------------------------------
            # Parámetros por defecto para el proceso de calibración
            # Nota: Estos parámetros no son modificables por el usuario
            # ----------------------------------------------------------------------------------------------------------------------

            NameObsData = 'ObsData.xlsx'
            NameFileParams = 'Params.xlsx'
            NameSampler = 'Sampler_Calibration_QGIS.txt'
            NameCalibration = 'Parameters_Calibration_QGIS.txt'
            NameExe = 'Scenario_Calibration_QGIS.txt'
            PathExeSIGA = os.path.join('bin', 'SIGA.exe')#os.path.dirname(__file__),

            print('Donde está el ejecutable:', PathExeSIGA)
            paso_temporal_dias = '1'
            modelo_geotecnico = '0'
            pH_cuencacaliente = '0'

            if NameSIGAModel == 'Hy':
                tipo_ejecucion = '1'
                NameSIGAModel1 = NameSIGAModel
            elif NameSIGAModel == 'Sed':
                tipo_ejecucion = '2'
                NameSIGAModel1 = NameSIGAModel
            else:
                tipo_ejecucion = '3'
                if (NameSIGAModel == 'WQ_NT') | (NameSIGAModel == 'WQ_NO') | (NameSIGAModel == 'WQ_NH4') | (
                        NameSIGAModel == 'WQ_NO3'):
                    NameSIGAModel1 = 'WQ_N'
                elif (NameSIGAModel == 'WQ_PT') | (NameSIGAModel == 'WQ_PO') | (NameSIGAModel == 'WQ_PI'):
                    NameSIGAModel1 = 'WQ_P'
                else:
                    NameSIGAModel1 = NameSIGAModel

            # ----------------------------------------------------------------------------------------------------------------------
            # Límites de parámetros de calibración
            # ----------------------------------------------------------------------------------------------------------------------

            # Leer parámetros de calibración
            Data = pd.read_excel(os.path.join(NameProcessCal, 'DATA', NameFileParams), sheet_name=NameSIGAModel1)
            Param_Min = Data['Min'].values * (Data['Status'].values == 1) + Data['Default'].values * (
                        Data['Status'].values == 0)
            Param_Max = Data['Max'].values * (Data['Status'].values == 1) + Data['Default'].values * (
                        Data['Status'].values == 0)

            # ----------------------------------------------------------------------------------------------------------------------
            # Leer datos observador y modificar archivo de muestreo
            # ----------------------------------------------------------------------------------------------------------------------
            # Ruta archivo de datos observados
            FileName = os.path.join(NameProcessCal, 'DATA', NameObsData)

            # Catalogo
            Catalog = pd.read_excel(FileName, sheet_name='Catalog', index_col=0)
            Catalog = Catalog[Catalog[NameSIGAModel] == 1]

            # Crear un vector de fechas
            Date = pd.date_range(start=DateStart.replace('/', '-'), end=DateEnd.replace('/', '-'), freq='D')

            # Series de caudales para calibración
            TS_Obs = pd.read_excel(FileName, sheet_name=NameSIGAModel)


            # Convertir a una lista si prefieres el formato de lista en lugar de un objeto pandas
            TS_Obs['Date'] = pd.to_datetime(TS_Obs['Date'].values, format='%d/%m/%Y')
            TS_Obs.set_index('Date', inplace=True)
            TS_Obs = pd.merge(pd.DataFrame(index=Date), TS_Obs, left_index=True, right_index=True, how='outer')

            # ----------------------------------------------------------------------------------------------------------------------
            # Modificar archivo de puntos de control
            # ----------------------------------------------------------------------------------------------------------------------
            path_plugin = os.path.dirname(__file__)
            spotpy_setup.Modify_csvMuestreador_CP(JSONPath, NameSIGAFolder, Catalog, NameSIGAModel, X, Y)
            spotpy_setup.Create_SamplerFile(ProjectPath, JSONPath, NameSIGAFolder, NameSampler)

            # ----------------------------------------------------------------------------------------------------------------------
            # Configuración del archivo de ejecución de SIGA. Estos parámetros de configurar internamente en el plugin
            # ----------------------------------------------------------------------------------------------------------------------

            NameSceExe = NameSceExeUser
            fecha_inicio = ' '.join(DateStart.split('-'))
            fecha_fin = ' '.join(DateEnd.split('-'))
            archivo_topologia = 'Topology_' + BasinName + '.txt'
            archivo_Tmin = 'TimeSeries_TAmin_' + BasinName + '.txt'
            archivo_Tmax = 'TimeSeries_TAmax_' + BasinName + '.txt'
            archivo_HR = 'TimeSeries_HR_' + BasinName + '.txt'
            archivo_RS = 'TimeSeries_RS_' + BasinName + '.txt'
            archivo_PV = 'TimeSeries_PVer_' + BasinName + '.txt'
            archivo_Ux = 'TimeSeries_Ux_' + BasinName + '.txt'
            archivo_Uy = 'TimeSeries_Uy_' + BasinName + '.txt'
            archivo_Qdesc = 'NA'
            archivo_Qcapt = 'NA'
            archivo_Qarc = 'NA'
            archivo_Qlim = 'NA'
            archivo_Qare = 'NA'
            archivo_movmasa = 'NA'
            archivo_fact_cal = NameCalibration
            archivo_muestreador = NameSampler
            archivo_tasrest = 'TimeSeries_TasRest_' + BasinName + '.txt'
            archivo_vertimientos = 'Dumpings_' + BasinName + '.txt'
            archivo_ciclo_cargas = 'LoadCycle_' + BasinName + '.txt'
            archivo_condiciones_frontera = 'BoundaryCondition_' + BasinName + '.txt'

            # Configurar clase de ficheros
            DicFic = Ficheros(ruta_cuenca_SIGA=os.path.join(ProjectPath, NameSIGAFolder, 'entradas' + os.path.sep),
                              archivo_ejecucion=NameExe,
                              escenario=NameSceExe,
                              fecha_inicio=fecha_inicio,
                              fecha_fin=fecha_fin,
                              paso_temporal_dias=paso_temporal_dias,
                              archivo_topologia=archivo_topologia,
                              archivo_Tmin=archivo_Tmin,
                              archivo_Tmax=archivo_Tmax,
                              archivo_HR=archivo_HR,
                              archivo_RS=archivo_RS,
                              archivo_PV=archivo_PV,
                              archivo_Ux=archivo_Ux,
                              archivo_Uy=archivo_Uy,
                              archivo_Qdesc=archivo_Qdesc,
                              archivo_Qcapt=archivo_Qcapt,
                              archivo_Qarc=archivo_Qarc,
                              archivo_Qlim=archivo_Qlim,
                              archivo_Qare=archivo_Qare,
                              archivo_movmasa=archivo_movmasa,
                              archivo_fact_cal=archivo_fact_cal,
                              archivo_muestreador=archivo_muestreador,
                              archivo_tasrest=archivo_tasrest,
                              archivo_vertimientos=archivo_vertimientos,
                              archivo_ciclo_cargas=archivo_ciclo_cargas,
                              archivo_condiciones_frontera=archivo_condiciones_frontera,
                              tipo_ejecucion=tipo_ejecucion,
                              modelo_geotecnico=modelo_geotecnico,
                              pH_cuencacaliente=pH_cuencacaliente)

            # Crear archivo de ejecución para calibración
            DicFic.crear_archivo_ejecucion()

            # ----------------------------------------------------------------------------------------------------------------------
            # Proceso de optimización
            # ----------------------------------------------------------------------------------------------------------------------

            if (Algorithm == 1):
                Factor_ObjFun = -1
                Search_ObjFun = True
            else:
                Factor_ObjFun = 1
                Search_ObjFun = False

            # Configurar modelo en estructura SPOTPY para la calibración
            model = spotpy_setup.Cal_SIGA(
                Param_Min,
                Param_Max,
                ProjectPath,
                JSONPath,
                NameSIGAFolder,
                NameCalibration,
                NameExe,
                NameSceExe,
                TS_Obs,
                OmitObs,
                Factor_ObjFun,
                TypeFobjCal,
                PathExeSIGA,
                NameSIGAModel,
                NameFunObj
            )
            # Path folder para guardar los parámetros
            PathParams = os.path.join(NameProcessCal, 'RESULTS', NameResultsCal)

            # Configurar algoritmo de calibración

            if Algorithm == 1:
                sampler = spotpy.algorithms.dds(model, dbname=PathParams, dbformat='csv')
            elif Algorithm == 2:
                sampler = spotpy.algorithms.lhs(model, dbname=PathParams, dbformat='csv')
            elif Algorithm == 3:
                sampler = spotpy.algorithms.sceua(model, dbname=PathParams, dbformat='csv')




            sampler.sample(NumIter)



            results = spotpy.analyser.load_csv_results(PathParams)
            best_params = spotpy.analyser.get_best_parameterset(results,maximize=Search_ObjFun)
            Params = best_params.view(float)[1:len(Param_Min) + 1]

            # ----------------------------------------------------------------------------------------------------------------------
            # Simular con mejores parámetros
            # ----------------------------------------------------------------------------------------------------------------------
            # Extraer series
            NameVarSIGA = spotpy_setup.Select_NameVarSIGA(NameSIGAModel)
            TS_Sim, S_S4, TS_S4 = spotpy_setup.simulationSIGA(
                Params,
                ProjectPath,
                JSONPath,
                NameSIGAFolder,
                NameSIGAModel,
                NameVarSIGA,
                NameSceExe,
                NameExe,
                PathExeSIGA,
                NameCalibration,
                TS_Obs
            )

            stations = TS_Sim.columns

            if self.toolBox.currentIndex() == 1:
                self.comboBox.clear()  # Limpiar valores existentes
                for value in stations:
                    self.comboBox.addItem(str(value))

            elif self.toolBox.currentIndex() == 3:
                self.comboBox_S.clear()  # Limpiar valores existentes
                for value in stations:
                    self.comboBox_S.addItem(str(value))
            elif self.toolBox.currentIndex() == 4:
                self.comboBox_WQ.clear()  # Limpiar valores existentes
                for value in stations:
                    self.comboBox_WQ.addItem(str(value))


            self.obs = TS_Obs
            self.sim = TS_Sim
            self.TS_S4 = TS_S4

            print('xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx',NameFunObj)
            # self.NameFunObj =NameFunObj
            self.Factor_ObjFun= Factor_ObjFun


            path_files = os.path.join(self.output_path.text(), self.name_project.text(), 'salidas', self.name_scenario.text())

            compress_all_folders_in_directory(path_files,out_file_zip )


            QMessageBox.information(self, "Process Complete", "Process completed")

        except Exception as e:
            QgsMessageLog.logMessage(f'Error: {str(e)}', 'Calibracion_Model', Qgis.Critical)
        finally:
            sys.stdout = sys.__stdout__
            sys.stderr = sys.__stderr__

    def Run_process_val(self):
        sys.stdout = QGISLogger()
        sys.stderr = QGISLogger()

        try:
            QMessageBox.information(self, "Process to start",
                                    "Please keep the window open until the process is finished.")

            DateStart = self.start_date_val.date().toString("yyyy-MM-dd")
            DateEnd = self.end_date_val.date().toString("yyyy-MM-dd")


            NameSIGAModel = self.tipo_model  # 'Hy'
            name_project = self.name_project.text()
            name_scenario = self.name_scenario.text()
            BasinName = self.Name_Basin.text()
            output_path = self.output_path.text()
            ProjectPath = output_path
            NameSIGAFolder = name_project
            NameProcessCal = os.path.join(output_path, name_project, 'temp', '04-Calibration')

            NameSceExeUser = name_scenario

            JSONPath = 'functions/Diccionario_ficheros.json'
            NameResultsCal = 'Params_Evaluation_' + NameSIGAModel
            NameObsData = 'ObsData.xlsx'
            NameFileParams = 'Params.xlsx'
            NameSampler = 'Sampler_Calibration_QGIS.txt'
            NameCalibration = 'Parameters_Calibration_QGIS.txt'
            NameExe = 'Scenario_Validacion_QGIS.txt'
            PathExeSIGA = os.path.join('bin', 'SIGA.exe')  # os.path.dirname(__file__),

            paso_temporal_dias = '1'
            modelo_geotecnico = '0'
            pH_cuencacaliente = '0'

            if NameSIGAModel == 'Hy':
                tipo_ejecucion = '1'
                NameSIGAModel1 = NameSIGAModel
            elif NameSIGAModel == 'Sed':
                tipo_ejecucion = '2'
                NameSIGAModel1 = NameSIGAModel
            else:
                tipo_ejecucion = '3'
                if (NameSIGAModel == 'WQ_NT') | (NameSIGAModel == 'WQ_NO') | (NameSIGAModel == 'WQ_NH4') | (
                        NameSIGAModel == 'WQ_NO3'):
                    NameSIGAModel1 = 'WQ_N'
                elif (NameSIGAModel == 'WQ_PT') | (NameSIGAModel == 'WQ_PO') | (NameSIGAModel == 'WQ_PI'):
                    NameSIGAModel1 = 'WQ_P'
                else:
                    NameSIGAModel1 = NameSIGAModel

            # ----------------------------------------------------------------------------------------------------------------------
            # Leer datos observador y modificar archivo de muestreo
            # ----------------------------------------------------------------------------------------------------------------------

            # Leer parámetros de calibración
            Data = pd.read_excel(os.path.join(NameProcessCal, 'DATA', NameFileParams), sheet_name=NameSIGAModel1)
            Param_Min = Data['Min'].values * (Data['Status'].values == 1) + Data['Default'].values * (
                    Data['Status'].values == 0)
            Param_Max = Data['Max'].values * (Data['Status'].values == 1) + Data['Default'].values * (
                    Data['Status'].values == 0)

            # Ruta archivo de datos observados
            FileName = os.path.join(NameProcessCal, 'DATA', NameObsData)

            # Catalogo
            Catalog = pd.read_excel(FileName, sheet_name='Catalog', index_col=0)
            Catalog = Catalog[Catalog[NameSIGAModel] == 1]

            # Crear un vector de fechas
            Date = pd.date_range(start=DateStart.replace('/', '-'), end=DateEnd.replace('/', '-'), freq='D')

            # Series de caudales para calibración
            TS_Obs = pd.read_excel(FileName, sheet_name=NameSIGAModel)

            # Convertir a una lista si prefieres el formato de lista en lugar de un objeto pandas
            TS_Obs['Date'] = pd.to_datetime(TS_Obs['Date'].values, format='%d/%m/%Y')
            TS_Obs.set_index('Date', inplace=True)
            TS_Obs = pd.merge(pd.DataFrame(index=Date), TS_Obs, left_index=True, right_index=True, how='outer')

            # Configuración del archivo de ejecución de SIGA. Estos parámetros de configurar internamente en el plugin
            # ----------------------------------------------------------------------------------------------------------------------
            # ----------------------------------------------------------------------------------------------------------------------

            NameSceExe = NameSceExeUser
            fecha_inicio = ' '.join(DateStart.split('-'))
            fecha_fin = ' '.join(DateEnd.split('-'))
            archivo_topologia = 'Topology_' + BasinName + '.txt'
            archivo_Tmin = 'TimeSeries_TAmin_' + BasinName + '.txt'
            archivo_Tmax = 'TimeSeries_TAmax_' + BasinName + '.txt'
            archivo_HR = 'TimeSeries_HR_' + BasinName + '.txt'
            archivo_RS = 'TimeSeries_RS_' + BasinName + '.txt'
            archivo_PV = 'TimeSeries_PVer_' + BasinName + '.txt'
            archivo_Ux = 'TimeSeries_Ux_' + BasinName + '.txt'
            archivo_Uy = 'TimeSeries_Uy_' + BasinName + '.txt'
            archivo_Qdesc = 'NA'
            archivo_Qcapt = 'NA'
            archivo_Qarc = 'NA'
            archivo_Qlim = 'NA'
            archivo_Qare = 'NA'
            archivo_movmasa = 'NA'
            archivo_fact_cal = NameCalibration
            archivo_muestreador = NameSampler
            archivo_tasrest = 'TimeSeries_TasRest_' + BasinName + '.txt'
            archivo_vertimientos = 'Dumpings_' + BasinName + '.txt'
            archivo_ciclo_cargas = 'LoadCycle_' + BasinName + '.txt'
            archivo_condiciones_frontera = 'BoundaryCondition_' + BasinName + '.txt'

            # Configurar clase de ficheros
            DicFic = Ficheros(ruta_cuenca_SIGA=os.path.join(ProjectPath, NameSIGAFolder, 'entradas' + os.path.sep),
                              archivo_ejecucion=NameExe,
                              escenario=NameSceExe,
                              fecha_inicio=fecha_inicio,
                              fecha_fin=fecha_fin,
                              paso_temporal_dias=paso_temporal_dias,
                              archivo_topologia=archivo_topologia,
                              archivo_Tmin=archivo_Tmin,
                              archivo_Tmax=archivo_Tmax,
                              archivo_HR=archivo_HR,
                              archivo_RS=archivo_RS,
                              archivo_PV=archivo_PV,
                              archivo_Ux=archivo_Ux,
                              archivo_Uy=archivo_Uy,
                              archivo_Qdesc=archivo_Qdesc,
                              archivo_Qcapt=archivo_Qcapt,
                              archivo_Qarc=archivo_Qarc,
                              archivo_Qlim=archivo_Qlim,
                              archivo_Qare=archivo_Qare,
                              archivo_movmasa=archivo_movmasa,
                              archivo_fact_cal=archivo_fact_cal,
                              archivo_muestreador=archivo_muestreador,
                              archivo_tasrest=archivo_tasrest,
                              archivo_vertimientos=archivo_vertimientos,
                              archivo_ciclo_cargas=archivo_ciclo_cargas,
                              archivo_condiciones_frontera=archivo_condiciones_frontera,
                              tipo_ejecucion=tipo_ejecucion,
                              modelo_geotecnico=modelo_geotecnico,
                              pH_cuencacaliente=pH_cuencacaliente)

            # Crear archivo de ejecución para calibración
            DicFic.crear_archivo_ejecucion()

            # Definir el algoritmo y la métrica
            diccio_algorit = {'DDS': 1, 'LHS': 2, 'SCE': 3}

            Algorithm = self.Algorithm.currentText()
            Algorithm = diccio_algorit[Algorithm]

            if (Algorithm == 1):
                Factor_ObjFun = -1
                Search_ObjFun = True
            else:
                Factor_ObjFun = 1
                Search_ObjFun = False

            # Path folder para guardar los parámetros
            PathParams = os.path.join(NameProcessCal, 'RESULTS', NameResultsCal)
            results = spotpy.analyser.load_csv_results(PathParams)
            best_params = spotpy.analyser.get_best_parameterset(results, maximize=Search_ObjFun)
            Params = best_params.view(float)[1:len(Param_Min) + 1]
            NameVarSIGA = spotpy_setup.Select_NameVarSIGA(NameSIGAModel)


            TS_Sim, S_S4, TS_S4 = spotpy_setup.simulationSIGA(
                Params,
                ProjectPath,
                JSONPath,
                NameSIGAFolder,
                NameSIGAModel,
                NameVarSIGA,
                NameSceExe,
                NameExe,
                PathExeSIGA,
                NameCalibration,
                TS_Obs
            )
            stations = TS_Sim.columns
            if self.toolBox.currentIndex() == 2:
                self.comboBox_Val.clear()  # Limpiar valores existentes
                for value in stations:
                    self.comboBox_Val.addItem(str(value))

            self.obs = TS_Obs
            self.sim = TS_Sim
            self.TS_S4 = TS_S4


            path_files = os.path.join(self.output_path.text(), self.name_project.text(), 'salidas',
                                      self.name_scenario.text())

            out_file_zip = os.path.join(self.output_path.text(), self.name_project.text(), 'salidas',
                                        self.name_scenario.text(), 'VHydrological_Validation_files.zip')

            compress_all_folders_in_directory(path_files, out_file_zip)

            QMessageBox.information(self, "Process Complete", "Process completed")

        except Exception as e:
            QgsMessageLog.logMessage(f'Error: {str(e)}', 'Calibracion_Model', Qgis.Critical)
        finally:
            sys.stdout = sys.__stdout__
            sys.stderr = sys.__stderr__


    def plot_graph(self):
        # Obtener la opción seleccionada en el QRadioButton
        if self.Plot_sim_obs.isChecked():
            self.plot_sim_obs()
        elif self.plot_tank.isChecked():
            self.Plot_tank()

    def plot_graph_S(self):
        # Obtener la opción seleccionada en el QRadioButton
        if self.Plot_sim_obs_S.isChecked():
            self.plot_sim_obs()
        elif self.Plot_Box_S.isChecked():
            self.boxplot_function()

    def plot_graph_WQ(self):
        # Obtener la opción seleccionada en el QRadioButton
        if self.Plot_sim_obs_WQ.isChecked():
            self.plot_sim_obs()
        elif self.Plot_BoxPlot_WQ.isChecked():
            self.boxplot_function()

    def boxplot_function(self):

        if self.toolBox.currentIndex() == 3:
            self.graphicsView = self.graphicsView_S
            name_title_B = 'Boxplot observed vs.simulated: Sediment'
            out_fig = f'Sediment_calibration'
            y_label = 'Sed mg/l'
            self.Peformance = self.Peformance_S
            name = self.comboBox_S.currentText()

        elif self.toolBox.currentIndex() == 4:

            Diccionario_WQ = {'Nitrogeno Total NT':'WQ_NT','Nitrogeno Organico NO':'WQ_NO','Nitrogeno Amoniaca NH4':'WQ_NH4',
                              'Nitratos NO3':'WQ_NO3','Fosforo Total':'WQ_PT', 'Fosforo Organico':'WQ_PO',
                              'Fosforo Inorganico':'WQ_PI','DBO':'WQ_DBO','Oxigeno Disuelto':'WQ_OD',
                              'Coliformes Totales':' WQ_CT','E. Coli':'WQ_EColi','Temperatura':'WQ_T','Conductividad Co':'WQ_Co',
                              'pH':'WQ_pH'}

            self.graphicsView = self.graphicsView_WQ
            name_title_B = 'WQ Boxplot observed vs.simulated '+Diccionario_WQ[self.comboBox_M_WQ.currentText()]
            out_fig = f'Box_plot_'+Diccionario_WQ[self.comboBox_M_WQ.currentText()]
            y_label = Diccionario_WQ[self.comboBox_M_WQ.currentText()]+' mg/l'
            self.Peformance = self.Peformance_WQ
            name = self.comboBox_WQ.currentText()
        try:
            # Configurar la figura para mostrar en QGIS
            graphics_view_size = self.graphicsView.size()
            width = graphics_view_size.width()
            height = graphics_view_size.height()
            display_figsize = (width / 96, height / 96)

            size_line = 1.5
            s_n = 14
            stations =self.obs.columns
            # Crear figura para guardar con tamaño figsize = (13, 8)
            fig_save, ax_save = plt.subplots(figsize=(13, 8))
            positions_sim = range(len(stations))
            box_sim = ax_save.boxplot(self.sim.dropna().values, positions=positions_sim, widths=0.3, patch_artist=True,
                                 boxprops=dict(facecolor="darkred", color="darkred"),
                                 medianprops=dict(color="black"),
                                 whiskerprops=dict(color="darkred"),
                                 capprops=dict(color="darkred"),
                                 flierprops=dict(markerfacecolor='darkred', marker='o', color='darkred', alpha=0.5))

            # Crear box plots para Observaciones
            positions_obs = [p + 0.4 for p in positions_sim]
            box_obs = ax_save.boxplot(self.obs.dropna().values, positions=positions_obs, widths=0.3, patch_artist=True,
                                 boxprops=dict(facecolor="navy", color="navy"),
                                 medianprops=dict(color="black"),
                                 whiskerprops=dict(color="navy"),
                                 capprops=dict(color="navy"),
                                 flierprops=dict(markerfacecolor='navy', marker='o', color='navy', alpha=0.5))
            ax_save.set_title(name_title_B , fontsize=s_n + 2, fontweight='bold')
            ax_save.set_xlabel('Time', fontsize=s_n, fontweight='bold')
            ax_save.set_ylabel(y_label, fontsize=s_n, fontweight='bold')

            # Configurar el eje X con los nombres de las estaciones
            # Crear la leyenda manualmente
            import matplotlib.patches as mpatches
            red_patch = mpatches.Patch(color='darkred', label='Simulated')
            blue_patch = mpatches.Patch(color='navy', label='Observed')
            ax_save.legend(handles=[red_patch, blue_patch], loc='upper right')
            plt.tight_layout()
            # Guardar la figura con tamaño 13x8
            PathProject = os.path.join(self.output_path.text(), self.name_project.text(), 'temp', '04-Calibration', 'FIGURES')
            os.makedirs(PathProject, exist_ok=True)
            fig_save.savefig(os.path.join(PathProject, out_fig+f'_{name}.png'))


            # Crear figura para mostrar en QGIS con tamaño ajustado al gráfico
            fig_display, ax_display = plt.subplots(figsize=display_figsize)
            box_sim = ax_display.boxplot(self.sim.dropna().values, positions=positions_sim, widths=0.3, patch_artist=True,
                                 boxprops=dict(facecolor="darkred", color="darkred"),
                                 medianprops=dict(color="black"),
                                 whiskerprops=dict(color="darkred"),
                                 capprops=dict(color="darkred"),
                                 flierprops=dict(markerfacecolor='darkred', marker='o', color='darkred', alpha=0.5))

            # Crear box plots para Observaciones
            positions_obs = [p + 0.4 for p in positions_sim]
            box_obs = ax_display.boxplot(self.obs.dropna().values, positions=positions_obs, widths=0.3, patch_artist=True,
                                 boxprops=dict(facecolor="navy", color="navy"),
                                 medianprops=dict(color="black"),
                                 whiskerprops=dict(color="navy"),
                                 capprops=dict(color="navy"),
                                 flierprops=dict(markerfacecolor='navy', marker='o', color='navy', alpha=0.5))
            ax_display.set_title(name_title_B , fontsize=s_n + 2, fontweight='bold')
            ax_display.set_xlabel('Time', fontsize=s_n, fontweight='bold')
            ax_display.set_ylabel(y_label, fontsize=s_n, fontweight='bold')
            red_patch = mpatches.Patch(color='darkred', label='Simulated')
            blue_patch = mpatches.Patch(color='navy', label='Observed')
            ax_save.legend(handles=[red_patch, blue_patch], loc='upper right')
            plt.tight_layout()


            # Mostrar la figura en graphicsView_7
            self.show_performance(self.NameFunObj, self.Factor_ObjFun, self.obs[name], self.sim[name], self.Peformance)
            self.display_figure(fig_display,self.graphicsView)
        except:
            self.show_performance(self.NameFunObj, self.Factor_ObjFun, self.obs[name], self.sim[name], self.Peformance)

    def plot_sim_obs(self):

        if self.toolBox.currentIndex() == 1:
            self.graphicsView = self.graphicsView_H
            name_title = 'Hydrological Calibration: '
            out_fig = f'Hydrological_calibration'
            y_label = 'Flow m$^3$/s'
            self.Peformance = self.Peformance_H
            name = self.comboBox.currentText()

        elif self.toolBox.currentIndex() == 2:
            self.graphicsView = self.graphicsView_H_Val
            name_title = 'Hydrological Validation: '
            out_fig = f'Hydrological_Validation'
            y_label = 'Flow m$^3$/s'
            self.Peformance = self.Peformance_H_val
            name = self.comboBox_Val.currentText()

        elif self.toolBox.currentIndex() == 3:
            self.graphicsView = self.graphicsView_S
            name_title = 'Sediment Calibration: '
            out_fig = f'Sediment_calibration'
            y_label = 'Sed mg/l'
            self.Peformance = self.Peformance_S
            name = self.comboBox_S.currentText()

        elif self.toolBox.currentIndex() == 4:

            Diccionario_WQ = {'Nitrogeno Total NT':'WQ_NT','Nitrogeno Organico NO':'WQ_NO','Nitrogeno Amoniaca NH4':'WQ_NH4',
                              'Nitratos NO3':'WQ_NO3','Fosforo Total':'WQ_PT', 'Fosforo Organico':'WQ_PO',
                              'Fosforo Inorganico':'WQ_PI','DBO':'WQ_DBO','Oxigeno Disuelto':'WQ_OD',
                              'Coliformes Totales':' WQ_CT','E. Coli':'WQ_EColi','Temperatura':'WQ_T','Conductividad Co':'WQ_Co',
                              'pH':'WQ_pH'}

            self.graphicsView = self.graphicsView_WQ
            name_title = 'WQ Calibration '+Diccionario_WQ[self.comboBox_M_WQ.currentText()]
            out_fig = f'WQ_calibration'+Diccionario_WQ[self.comboBox_M_WQ.currentText()]
            y_label = Diccionario_WQ[self.comboBox_M_WQ.currentText()]+' mg/l'
            self.Peformance = self.Peformance_WQ
            name = self.comboBox_WQ.currentText()



        try:
            # Obtener el nombre seleccionado en el comboBox

            # Configurar la figura para mostrar en QGIS
            graphics_view_size = self.graphicsView.size()
            width = graphics_view_size.width()
            height = graphics_view_size.height()
            display_figsize = (width / 96, height / 96)

            size_line = 1.5
            s_n = 14

            # Crear figura para guardar con tamaño figsize = (13, 8)
            fig_save, ax_save = plt.subplots(figsize=(13, 8))
            ax_save.plot(self.obs.index, self.obs[name], color='navy', linewidth=size_line, alpha=0.5, label="Observed Flow")
            ax_save.plot(self.obs.index, self.sim[name], color='darkred', linewidth=size_line, linestyle='--', alpha=0.9, label="Simulated Flow")
            ax_save.set_title(name_title  + str(name), fontsize=s_n + 2, fontweight='bold')
            ax_save.set_xlabel('Time', fontsize=s_n, fontweight='bold')
            ax_save.set_ylabel(y_label, fontsize=s_n, fontweight='bold')
            ax_save.legend(loc=1)

            # Guardar la figura con tamaño 13x8
            PathProject = os.path.join(self.output_path.text(), self.name_project.text(), 'temp', '04-Calibration', 'FIGURES')
            os.makedirs(PathProject, exist_ok=True)
            fig_save.savefig(os.path.join(PathProject, out_fig+f'_{name}.png'))

            # Crear figura para mostrar en QGIS con tamaño ajustado al gráfico
            fig_display, ax_display = plt.subplots(figsize=display_figsize)
            ax_display.plot(self.obs.index, self.obs[name], color='navy', linewidth=size_line, alpha=0.5, label="Observed Flow")
            ax_display.plot(self.obs.index, self.sim[name], color='darkred', linewidth=size_line, linestyle='--', alpha=0.9, label="Simulated Flow")
            ax_display.set_title(name_title + str(name), fontsize=s_n + 2, fontweight='bold')
            ax_display.set_xlabel('Time', fontsize=s_n, fontweight='bold')
            ax_display.set_ylabel(y_label, fontsize=s_n, fontweight='bold')
            ax_display.legend(loc=1)
            plt.tight_layout()
            # Mostrar la figura en graphicsView_7
            self.show_performance(self.NameFunObj, self.Factor_ObjFun, self.obs[name], self.sim[name], self.Peformance)
            self.display_figure(fig_display,self.graphicsView)
        except:
            self.show_performance(self.NameFunObj, self.Factor_ObjFun, self.obs[name], self.sim[name], self.Peformance)

    def Plot_tank(self):

        if self.toolBox.currentIndex() == 1:
            self.graphicsView = self.graphicsView_H
        # Obtener el nombre seleccionado en el comboBox
        name = self.comboBox.currentText()

        # Configurar la figura para mostrar en QGIS
        graphics_view_size = self.graphicsView.size()
        width = graphics_view_size.width()
        height = graphics_view_size.height()
        display_figsize = (width / 96, height / 96)

        size_line = 1.5
        s_n = 14

        # Crear figura para guardar con tamaño figsize = (13, 8)
        fig_save, ax_save = plt.subplots(figsize=(13, 8))
        slope, intercept, r_value, p_value, std_err = scipy.stats.linregress(
            np.arange(0, len(self.TS_S4['S4(m)']), 1), self.TS_S4['S4(m)'] * 1000)
        ax_save.plot(self.TS_S4['S4(m)'].values * 1000, color='darkred', linewidth=size_line, linestyle='--', alpha=0.9, label="Simulated tank")
        ax_save.plot(np.arange(0, len(self.TS_S4['S4(m)']), 1), slope * np.arange(0, len(self.TS_S4['S4(m)']), 1) + intercept,
                     color='navy', linewidth=size_line, alpha=0.9, label="Slope")
        ax_save.set_title('Hydrological Calibration - Tank S4', fontsize=s_n + 2, fontweight='bold')
        ax_save.grid()
        ax_save.legend(loc=1)

        # Guardar la figura con tamaño 13x8
        PathProject = os.path.join(self.output_path.text(), self.name_project.text(), 'temp', '04-Calibration', 'FIGURES')
        os.makedirs(PathProject, exist_ok=True)
        fig_save.savefig(os.path.join(PathProject, f'Tank_4_{name}.png'))

        # Crear figura para mostrar en QGIS con tamaño ajustado al gráfico
        fig_display, ax_display = plt.subplots(figsize=display_figsize)
        ax_display.plot(self.TS_S4['S4(m)'].values * 1000, color='darkred', linewidth=size_line, linestyle='--', alpha=0.9, label="Simulated tank")
        ax_display.plot(np.arange(0, len(self.TS_S4['S4(m)']), 1), slope * np.arange(0, len(self.TS_S4['S4(m)']), 1) + intercept,
                        color='navy', linewidth=size_line, alpha=0.9, label="Slope")
        ax_display.set_title('Hydrological Calibration - Tank S4', fontsize=s_n + 2, fontweight='bold')
        ax_display.grid()
        ax_display.legend(loc=1)
        plt.tight_layout()
        # Mostrar la figura en graphicsView_7
        self.display_figure(fig_display,self.graphicsView)

    def zoom_in(self, graphics_view):
        graphics_view.scale(1.2, 1.2)

    def zoom_out(self, graphics_view):
        graphics_view.scale(0.8, 0.8)

    def show_performance (self,NameFunObj, FacObjF, Obs, Sim,plainTextEdit):
        resultado = performance(NameFunObj, FacObjF, Obs, Sim)

        plainTextEdit.setPlainText(f"{NameFunObj}: {np.round(resultado,2)}")

    def display_figure(self, figure, graphics_view):
        # Crear un canvas para mostrar la figura
        canvas = FigureCanvasQTAgg(figure)
        scene = QGraphicsScene()
        scene.addWidget(canvas)

        # Configurar la escena en el graphics_view proporcionado
        graphics_view.setScene(scene)
        graphics_view.show()

    def closeEvent(self, event):
        self.closingPlugin.emit()
        event.accept()



