# -*- coding: utf-8 -*-
"""
/***************************************************************************
 QSIGA_CALDialog
                                 A QGIS plugin
 This plugin allows to configure, calibrate and simulate scenarios in the SIGA-CAL model
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2024-10-01
        git sha              : $Format:%H$
        copyright            : (C) 2024 by The Nature Conservancy
        email                : miguel.canon@tnc.org
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
"""

import os
#import Logo_TNC_rc
from qgis.PyQt import uic
from qgis.PyQt import QtWidgets
from PyQt5.QtWidgets import QDialog
from .Plugins.Step_01.Siga_Step_01_Config import Siga_Step_01_Config
from .Plugins.Step_02.Siga_Step_02_lai import Siga_Step_02_lai
from .Plugins.Step_03.Calibracion_Model import Calibracion_Model
from .Plugins.Step_04.Siga_step_04_Priori import Siga_step_04_Priori
from .Plugins.Step_05.siga_step_05_Sim import siga_step_05_Sim
from PyQt5.QtGui import QPixmap

# This loads your .ui file so that PyQt can populate your plugin with the elements from Qt Designer
FORM_CLASS, _ = uic.loadUiType(os.path.join(
    os.path.dirname(__file__), 'QSIGA_CAL_dialog_base.ui'))

class QSigaCalDialog(QDialog, FORM_CLASS):
    def __init__(self, iface, parent=None):
        super(QSigaCalDialog, self).__init__(parent)
        self.iface = iface  # Guardamos la referencia de iface
        self.setupUi(self)
	# Definir la ruta del plugin para acceder a los logos
        self.plugin_dir = os.path.dirname(__file__)

        # Rutas de los logos
        logo_n4w_path = os.path.join(self.plugin_dir, 'logos', 'N4W Logo_Tagline Logo Colour.png')
        logo_pegasys_path = os.path.join(self.plugin_dir, 'logos', 'Pegasys Logo.ai')
        logo_tnc_path = os.path.join(self.plugin_dir, 'logos', 'TNCLogoPrimary_RGB.png')
        logo_qsiga_path = os.path.join(self.plugin_dir, 'logos', 'Qsiga.png')
        logo_gotta_path = os.path.join(self.plugin_dir, 'logos', 'gotta-blue.png')

        # Asignar los logos a los QLabel correspondientes
        self.label_n4w.setPixmap(QPixmap(logo_n4w_path))
        self.label_Pega.setPixmap(QPixmap(logo_pegasys_path))
        self.label_tnc.setPixmap(QPixmap(logo_tnc_path))
        self.label_5.setPixmap(QPixmap(logo_qsiga_path))

        self.label_gotta.setPixmap(QPixmap(logo_gotta_path))




        self.plugin_step_01 = None  # Variable para la instancia del subplugin
        self.plugin_step_02 = None  # Variable para la instancia del subplugin
        self.Step_1.clicked.connect(self.open_step_1)
        self.Step_2.clicked.connect(self.open_step_2)
        self.Step_3.clicked.connect(self.open_step_3)
        self.Step_4.clicked.connect(self.open_step_4)
        self.Step_5.clicked.connect(self.open_step_5)

    def open_step_1(self):
        # Asegurarse de que el subplugin está inicializado
        # if self.plugin_step_01 is None:
        #     self.plugin_step_01 = Siga_Step_01_Config(self.iface)
        self.plugin_step_01 = Siga_Step_01_Config(self.iface)

        # Llamar al método que abre el dock widget del subplugin
        self.plugin_step_01.open_dockwidget()

    def open_step_2(self):
        # Asegurarse de que el subplugin está inicializado
        # if self.plugin_step_01 is None:
        #     self.plugin_step_01 = Siga_Step_01_Config(self.iface)
        self.plugin_step_02 = Siga_Step_02_lai(self.iface)

        # Llamar al método que abre el dock widget del subplugin
        self.plugin_step_02.open_dockwidget_step02()


    def open_step_3(self):
        # Asegurarse de que el subplugin está inicializado
        # if self.plugin_step_01 is None:
        #     self.plugin_step_01 = Siga_Step_01_Config(self.iface)
        self.plugin_step_03 = Calibracion_Model(self.iface)

        # Llamar al método que abre el dock widget del subplugin
        self.plugin_step_03.open_dockwidget_step03()

    def open_step_4(self):
        # Asegurarse de que el subplugin está inicializado
        # if self.plugin_step_01 is None:
        #     self.plugin_step_01 = Siga_Step_01_Config(self.iface)
        self.plugin_step_04 = Siga_step_04_Priori(self.iface)

        # Llamar al método que abre el dock widget del subplugin
        self.plugin_step_04.open_dockwidget_step04()

    def open_step_5(self):
        # Asegurarse de que el subplugin está inicializado
        # if self.plugin_step_01 is None:
        #     self.plugin_step_01 = Siga_Step_01_Config(self.iface)
        self.plugin_step_05 = siga_step_05_Sim(self.iface)

        # Llamar al método que abre el dock widget del subplugin
        self.plugin_step_05.open_dockwidget_step05()
# class QSIGA_CALDialog(QtWidgets.QDialog, FORM_CLASS):
#     def __init__(self, parent=None):
#         """Constructor."""
#         super(QSIGA_CALDialog, self).__init__(parent)
#         # Set up the user interface from Designer through FORM_CLASS.
#         # After self.setupUi() you can access any designer object by doing
#         # self.<objectname>, and you can use autoconnect slots - see
#         # http://qt-project.org/doc/qt-4.8/designer-using-a-ui-file.html
#         # #widgets-and-dialogs-with-auto-connect
#         self.setupUi(self)
