# -*- coding: utf-8 -*-
"""
/***************************************************************************
 Calibracion_Model
                                 A QGIS plugin
 Este plugin se enfoca en el proceso de calibracion de los modelos Hidrologicos, sedimentos y de calidad de agua de SIGA-CAL
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2024-07-31
        copyright            : (C) 2024 by The Nature Conservancy
        email                : miguel.canon@tnc.org
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load Calibracion_Model class from file Calibracion_Model.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .Calibracion_Model import Calibracion_Model
    return Calibracion_Model(iface)
