# -*- coding: utf-8 -*-
"""
/***************************************************************************
 Calibracion_ModelDockWidget
                                 A QGIS plugin
 Este plugin se enfoca en el proceso de calibracion de los modelos Hidrologicos, sedimentos y de calidad de agua de SIGA-CAL
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2024-07-31
        git sha              : $Format:%H$
        copyright            : (C) 2024 by The Nature Conservancy
        email                : miguel.canon@tnc.org
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
"""

import sys
import os
import spotpy
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from PyQt5.QtCore import pyqtSignal, QObject, QDate, Qt, QTimer
from PyQt5.QtWidgets import QFileDialog, QMessageBox
from qgis.PyQt import QtWidgets, uic
from ..common_functions.ficheros import Ficheros, copiar_archivo, create_outputs_folders
from ..common_functions import spotpy_setup_SIGA as spotpy_setup
from qgis.core import QgsMessageLog, Qgis, QgsProject
import json
from subprocess import Popen, PIPE
from matplotlib.backends.backend_qt5agg import FigureCanvasQTAgg
import scipy.stats
from qgis.PyQt.QtWidgets import QGraphicsScene, QVBoxLayout, QPushButton, QHBoxLayout
import time
import shutil
import zipfile
from ..common_functions.sensitivity_analysis_complete import SensitivityAnalyzer


class ProgressSignal(QObject):
    progress = pyqtSignal(int)

def performance(NameFunObj, FacObjF, Obs, Sim):
    """
    Calcula la métrica de rendimiento en su forma ORIGINAL (sin transformación para optimización).
    Esta función devuelve los valores que el usuario espera ver.

    Parameters:
    -----------
    NameFunObj : str
        Nombre de la función objetivo
    FacObjF : float
        Factor de transformación (NO se usa aquí, solo para compatibilidad)
    Obs : array
        Valores observados
    Sim : array
        Valores simulados

    Returns:
    --------
    float
        Valor de la métrica en su forma original
    """

    if NameFunObj == 'NASH':
        # Nash-Sutcliffe: valores entre -∞ y 1 (1 es perfecto)
        Part_1 = np.nansum((Obs - Sim) ** 2)
        Part_2 = np.nansum((Obs - np.nanmean(Obs)) ** 2)
        ObjFun = 1 - (Part_1 / Part_2)

    elif NameFunObj == 'IoAd':
        # Index of Agreement: valores entre 0 y 1 (1 es perfecto)
        Part_1 = np.nansum((Obs - Sim) ** 2)
        Part_2 = np.nansum((np.abs((Obs - np.nanmean(Obs))) + np.abs((Sim - np.nanmean(Obs)))) ** 2)
        ObjFun = 1 - (Part_1 / Part_2)

    elif NameFunObj == 'EAN':
        # Error Absoluto Normalizado: valores menores son mejores
        Part_1 = np.nansum(np.abs(Obs - Sim))
        Part_2 = np.nansum(np.abs(Obs - np.nanmedian(Obs)))
        ObjFun = Part_1 / Part_2

    elif NameFunObj == 'r':
        # Coeficiente de correlación: valores entre -1 y 1 (1 es perfecto)
        ObjFun = spotpy.objectivefunctions.correlationcoefficient(Obs, Sim)

    elif NameFunObj == 'R2':
        # Coeficiente de determinación: valores entre 0 y 1 (1 es perfecto)
        ObjFun = spotpy.objectivefunctions.rsquared(Obs, Sim)

    elif NameFunObj == 'MSE':
        # Error Cuadrático Medio: valores menores son mejores
        ObjFun = spotpy.objectivefunctions.mse(Obs, Sim)

    elif NameFunObj == 'RMSE':
        # Raíz del Error Cuadrático Medio: valores menores son mejores
        ObjFun = spotpy.objectivefunctions.rmse(Obs, Sim)

    elif NameFunObj == 'RRMSE':
        # Error Cuadrático Medio Relativo: valores menores son mejores
        ObjFun = spotpy.objectivefunctions.rrmse(Obs, Sim)

    elif NameFunObj == 'COMPOS':
        # Función compuesta: valores menores son mejores
        # Metrica 1 - Coefficient of determination
        Part_1 = np.nansum((Obs - np.nanmean(Obs)) * (Sim - np.nanmean(Sim)))
        Part_2 = np.nansum((Obs - np.nanmean(Obs)) ** 2) * np.nansum((Sim - np.nanmean(Sim)) ** 2)
        RSqr = (Part_1 / np.sqrt(Part_2)) ** 2

        # Metrica 2 - Nash–Sutcliffe coefficient
        Part_1 = np.nansum((Obs - Sim) ** 2)
        Part_2 = np.nansum((Obs - np.nanmean(Obs)) ** 2)
        NSE = (Part_1 / Part_2)

        # Metrica 3 - Index of agreement
        Part_2 = np.nansum((np.abs((Obs - np.nanmean(Obs))) + np.abs((Sim - np.nanmean(Obs)))) ** 2)
        IoAd = (Part_1 / Part_2)

        # Metrica 4 - Error absoluto normalizado
        Part_1 = np.nansum(np.abs(Obs - Sim))
        Part_2 = np.nansum(np.abs(Obs - np.nanmedian(Obs)))
        NAE = (Part_1 / Part_2)

        # Valor sin transformar (forma original para el usuario)
        ObjFun = ((0.2 * (1 - RSqr)) + (0.4 * NSE) + (0.2 * IoAd) + (0.2 * NAE))

    elif NameFunObj == 't-Student':
        # t-Student: puede ser positivo o negativo
        t_stat, p_valor = scipy.stats.ttest_ind(Obs, Sim)
        ObjFun = t_stat

    return ObjFun

def compress_all_folders_in_directory(directory_path, output_zip):
    # Obtener todas las carpetas en el directorio especificado
    folder_paths = [os.path.join(directory_path, folder) for folder in os.listdir(directory_path) if os.path.isdir(os.path.join(directory_path, folder))]

    # Crear un archivo ZIP
    with zipfile.ZipFile(output_zip, 'w', zipfile.ZIP_DEFLATED) as zipf:
        for folder in folder_paths:
            # Recorrer todas las carpetas y archivos en la ruta dada
            for root, dirs, files in os.walk(folder):
                for file in files:
                    # Agregar cada archivo al ZIP
                    file_path = os.path.join(root, file)
                    zipf.write(file_path, os.path.relpath(file_path, directory_path))

    # Eliminar las carpetas originales
    for folder in folder_paths:
        shutil.rmtree(folder)
class QGISLogger:
    def write(self, message):
        QgsMessageLog.logMessage(message.strip(), 'Calibracion_Model', Qgis.Info)

    def flush(self):
        pass


FORM_CLASS, _ = uic.loadUiType(os.path.join(
    os.path.dirname(__file__), 'Calibracion_Model_dockwidget_base.ui'))


class Calibracion_ModelDockWidget(QtWidgets.QDockWidget, FORM_CLASS):

    closingPlugin = pyqtSignal()

    def __init__(self,iface, parent=None):
        """Constructor."""
        super(Calibracion_ModelDockWidget, self).__init__(parent)
        self.iface = iface
        self.setupUi(self)

        #### Step 1 creacion de proyecto #############################
        # Connect signals to slots
        self.select_output.clicked.connect(self.select_output_folder)
        self.Create_Folders.clicked.connect(self.create_folders)
        self.Next_Step_2.clicked.connect(lambda: self.toolBox.setCurrentIndex(1))

        #### Step 2 calibracion hIDROLOGIA #############################
        self.Run_process_Hydro_Cal.clicked.connect(self.run_process_cal)
        self.Plot_G.clicked.connect(self.plot_graph)

        self.zoom_in_button.clicked.connect(lambda: self.zoom_in(self.graphicsView_H))
        self.zoom_out_button.clicked.connect(lambda: self.zoom_out(self.graphicsView_H))

        self.Next_Step_3.clicked.connect(lambda: self.toolBox.setCurrentIndex(2))


        #### Step 3 Validacion hIDROLOGIA #############################
        self.Run_process_Hydro_Val.clicked.connect(self.Run_process_val)
        self.Plot_G_Val.clicked.connect(self.plot_sim_obs)

        self.zoom_in_button_Val.clicked.connect(lambda: self.zoom_in(self.graphicsView_H_Val))
        self.zoom_out_button_Val.clicked.connect(lambda: self.zoom_out(self.graphicsView_H_Val))

        self.Next_Step_6.clicked.connect(lambda: self.toolBox.setCurrentIndex(3))

        #### Step 4 calibracion Sedimentos #############################
        self.Run_process_Cal_S.clicked.connect(self.run_process_cal)
        self.Plot_G_S.clicked.connect(self.plot_graph_S)

        self.zoom_in_button_S.clicked.connect(lambda: self.zoom_in(self.graphicsView_S))
        self.zoom_out_button_S.clicked.connect(lambda: self.zoom_out(self.graphicsView_S))

        self.Next_Step_4.clicked.connect(lambda: self.toolBox.setCurrentIndex(4))

        #### Step 5 calibracion calidad de agua#############################

        self.Run_process_Cal_WQ.clicked.connect(self.run_process_cal)
        self.Plot_G_WQ.clicked.connect(self.plot_graph_WQ)

        self.zoom_in_button_WQ.clicked.connect(lambda: self.zoom_in(self.graphicsView_WQ))
        self.zoom_out_button_WQ.clicked.connect(lambda: self.zoom_out(self.graphicsView_WQ))
        
        self.Next_Step_5.clicked.connect(lambda: self.toolBox.setCurrentIndex(5))
        #### Step 6 Sensitivity Analysis #############################
        self.Plot_sensy.clicked.connect(self.plot_sensitivity_analysis)
        self.zoom_in_button_WQ_2.clicked.connect(lambda: self.zoom_in(self.graphicsView_WQ_2))
        self.zoom_out_button_WQ_2.clicked.connect(lambda: self.zoom_out(self.graphicsView_WQ_2))
        self.Button_Finish_1.clicked.connect(self.close_plugin)

        ### Base Files - Carpeta externa para archivos CSV
        self.Check_Base_File.toggled.connect(self.toggle_base_files)
        self.select_base_files.clicked.connect(self.select_base_files_folder)

        ### Project State - Auto-save and load project state
        QgsProject.instance().projectSaved.connect(self.save_project_state)
        QgsProject.instance().readProject.connect(self.load_project_state)

        # Load project state on initialization if project is already open
        if QgsProject.instance().fileName():
            self.load_project_state()


    #### Funciones Generales - Base Files ############################
    def toggle_base_files(self):
        """Enable/disable base files controls based on checkbox state."""
        is_checked = self.Check_Base_File.isChecked()
        self.select_base_files.setEnabled(is_checked)
        self.path_base_files.setEnabled(is_checked)

        # If unchecked, clear the path
        if not is_checked:
            self.path_base_files.clear()

    def select_base_files_folder(self):
        """Open dialog to select base files folder."""
        folder = QtWidgets.QFileDialog.getExistingDirectory(self, "Select Base Files Folder")
        if folder:
            self.path_base_files.setText(folder)
            QMessageBox.information(self, "Success", f"Base files folder set to: {folder}")

    def get_base_csv_path(self, subfolder=''):
        """
        Get the base CSV path based on user selection.

        Parameters:
        -----------
        subfolder : str
            Subfolder within base path (e.g., 'muestreador', 'calibracion')

        Returns:
        --------
        str
            Full path to the base CSV folder
        """
        if self.Check_Base_File.isChecked() and self.path_base_files.text():
            # Use external folder
            base_path = self.path_base_files.text()
            if subfolder:
                return os.path.join(base_path, subfolder)
            return base_path
        else:
            # Use internal archivos_csv folder from Step_01
            parent_dir = os.path.abspath(os.path.join(os.path.dirname(__file__), os.pardir))
            subplugin1_dir = os.path.join(parent_dir, 'Step_01')
            base_path = os.path.join(subplugin1_dir, 'archivos_csv')
            if subfolder:
                return os.path.join(base_path, subfolder)
            return base_path

    #### Funciones Generales - Project State Management ############################
    def save_project_state(self):
        """
        Save the current state of the plugin to QGIS project variables.
        This is called automatically when the QGIS project is saved.
        """
        try:
            project = QgsProject.instance()

            # Create a dictionary with all the state information
            state = {
                # Step 1 - Project configuration
                'output_path': self.output_path.text(),
                'name_project': self.name_project.text(),
                'name_scenario': self.name_scenario.text(),
                'Name_Basin': self.Name_Basin.text(),
                'X_coor': self.X_coor.text(),
                'Y_coor': self.Y_coor.text(),

                # Step 2 - Hydrological Calibration
                'Algorithm': self.Algorithm.currentText(),
                'Metricas': self.Metricas.currentText(),
                'QNumIter': self.QNumIter.text(),
                'Tipo_Funcion': self.Tipo_Funcion.currentText(),
                'start_date': self.start_date.date().toString("yyyy-MM-dd"),
                'end_date': self.end_date.date().toString("yyyy-MM-dd"),
                'Training_Period': self.Training_Period.text(),

                # Step 3 - Hydrological Validation
                'start_date_val': self.start_date_val.date().toString("yyyy-MM-dd"),
                'end_date_val': self.end_date_val.date().toString("yyyy-MM-dd"),

                # Step 4 - Sediment Calibration
                'Algorithm_S': self.Algorithm_S.currentText(),
                'Metricas_S': self.Metricas_S.currentText(),
                'QNumIter_S': self.QNumIter_S.text(),
                'Tipo_Funcion_S': self.Tipo_Funcion_S.currentText(),
                'start_date_S': self.start_date_S.date().toString("yyyy-MM-dd"),
                'end_date_S': self.end_date_S.date().toString("yyyy-MM-dd"),
                'Training_Period_2': self.Training_Period_2.text(),

                # Step 5 - Water Quality Calibration
                'Algorithm_WQ': self.Algorithm_WQ.currentText(),
                'Metricas_WQ': self.Metricas_WQ.currentText(),
                'QNumIter_WQ': self.QNumIter_WQ.text(),
                'Tipo_Funcion_WQ': self.Tipo_Funcion_WQ.currentText(),
                'start_date_WQ': self.start_date_WQ.date().toString("yyyy-MM-dd"),
                'end_date_WQ': self.end_date_WQ.date().toString("yyyy-MM-dd"),
                'Training_Period_3': self.Training_Period_3.text(),
                'comboBox_M_WQ': self.comboBox_M_WQ.currentText(),

                # Base Files
                'Check_Base_File': self.Check_Base_File.isChecked(),
                'path_base_files': self.path_base_files.text(),

                # Current toolbox page
                'current_toolbox_index': self.toolBox.currentIndex()
            }

            # Save state as JSON string in project variables
            project.writeEntry('QSIGA_CAL_CALIBRATION', 'plugin_state', json.dumps(state))

        except Exception as e:
            print(f"Error saving project state: {e}")

    def load_project_state(self):
        """
        Load the plugin state from QGIS project variables.
        This is called automatically when a QGIS project is opened.
        """
        try:
            project = QgsProject.instance()

            # Read state from project variables
            state_json, success = project.readEntry('QSIGA_CAL_CALIBRATION', 'plugin_state')

            if not success or not state_json:
                return

            state = json.loads(state_json)

            # Restore Step 1 - Project configuration
            if 'output_path' in state:
                self.output_path.setText(state['output_path'])
            if 'name_project' in state:
                self.name_project.setText(state['name_project'])
            if 'name_scenario' in state:
                self.name_scenario.setText(state['name_scenario'])
            if 'Name_Basin' in state:
                self.Name_Basin.setText(state['Name_Basin'])
            if 'X_coor' in state:
                self.X_coor.setText(state['X_coor'])
            if 'Y_coor' in state:
                self.Y_coor.setText(state['Y_coor'])

            # Restore Step 2 - Hydrological Calibration
            if 'Algorithm' in state:
                index = self.Algorithm.findText(state['Algorithm'])
                if index >= 0:
                    self.Algorithm.setCurrentIndex(index)
            if 'Metricas' in state:
                index = self.Metricas.findText(state['Metricas'])
                if index >= 0:
                    self.Metricas.setCurrentIndex(index)
            if 'QNumIter' in state:
                self.QNumIter.setText(state['QNumIter'])
            if 'Tipo_Funcion' in state:
                index = self.Tipo_Funcion.findText(state['Tipo_Funcion'])
                if index >= 0:
                    self.Tipo_Funcion.setCurrentIndex(index)
            if 'start_date' in state:
                date = QDate.fromString(state['start_date'], "yyyy-MM-dd")
                self.start_date.setDate(date)
            if 'end_date' in state:
                date = QDate.fromString(state['end_date'], "yyyy-MM-dd")
                self.end_date.setDate(date)
            if 'Training_Period' in state:
                self.Training_Period.setText(state['Training_Period'])

            # Restore Step 3 - Hydrological Validation
            if 'start_date_val' in state:
                date = QDate.fromString(state['start_date_val'], "yyyy-MM-dd")
                self.start_date_val.setDate(date)
            if 'end_date_val' in state:
                date = QDate.fromString(state['end_date_val'], "yyyy-MM-dd")
                self.end_date_val.setDate(date)

            # Restore Step 4 - Sediment Calibration
            if 'Algorithm_S' in state:
                index = self.Algorithm_S.findText(state['Algorithm_S'])
                if index >= 0:
                    self.Algorithm_S.setCurrentIndex(index)
            if 'Metricas_S' in state:
                index = self.Metricas_S.findText(state['Metricas_S'])
                if index >= 0:
                    self.Metricas_S.setCurrentIndex(index)
            if 'QNumIter_S' in state:
                self.QNumIter_S.setText(state['QNumIter_S'])
            if 'Tipo_Funcion_S' in state:
                index = self.Tipo_Funcion_S.findText(state['Tipo_Funcion_S'])
                if index >= 0:
                    self.Tipo_Funcion_S.setCurrentIndex(index)
            if 'start_date_S' in state:
                date = QDate.fromString(state['start_date_S'], "yyyy-MM-dd")
                self.start_date_S.setDate(date)
            if 'end_date_S' in state:
                date = QDate.fromString(state['end_date_S'], "yyyy-MM-dd")
                self.end_date_S.setDate(date)
            if 'Training_Period_2' in state:
                self.Training_Period_2.setText(state['Training_Period_2'])

            # Restore Step 5 - Water Quality Calibration
            if 'Algorithm_WQ' in state:
                index = self.Algorithm_WQ.findText(state['Algorithm_WQ'])
                if index >= 0:
                    self.Algorithm_WQ.setCurrentIndex(index)
            if 'Metricas_WQ' in state:
                index = self.Metricas_WQ.findText(state['Metricas_WQ'])
                if index >= 0:
                    self.Metricas_WQ.setCurrentIndex(index)
            if 'QNumIter_WQ' in state:
                self.QNumIter_WQ.setText(state['QNumIter_WQ'])
            if 'Tipo_Funcion_WQ' in state:
                index = self.Tipo_Funcion_WQ.findText(state['Tipo_Funcion_WQ'])
                if index >= 0:
                    self.Tipo_Funcion_WQ.setCurrentIndex(index)
            if 'start_date_WQ' in state:
                date = QDate.fromString(state['start_date_WQ'], "yyyy-MM-dd")
                self.start_date_WQ.setDate(date)
            if 'end_date_WQ' in state:
                date = QDate.fromString(state['end_date_WQ'], "yyyy-MM-dd")
                self.end_date_WQ.setDate(date)
            if 'Training_Period_3' in state:
                self.Training_Period_3.setText(state['Training_Period_3'])
            if 'comboBox_M_WQ' in state:
                index = self.comboBox_M_WQ.findText(state['comboBox_M_WQ'])
                if index >= 0:
                    self.comboBox_M_WQ.setCurrentIndex(index)

            # Restore Base Files
            if 'Check_Base_File' in state:
                self.Check_Base_File.setChecked(state['Check_Base_File'])
            if 'path_base_files' in state:
                self.path_base_files.setText(state['path_base_files'])

            # Restore current toolbox page
            if 'current_toolbox_index' in state:
                self.toolBox.setCurrentIndex(state['current_toolbox_index'])

            print("QSIGA_CAL_CALIBRATION: Project state loaded successfully")

        except Exception as e:
            print(f"Error loading project state: {e}")

    #### Funciones Step 1 creacion de proyecto #############################
    def select_output_folder(self):
        # Abrir un diálogo para seleccionar la carpeta de salida
        output_path = QtWidgets.QFileDialog.getExistingDirectory(self, "Select Output Folder")
        if output_path:
            self.output_path.setText(output_path)

    def create_folders(self):
        # Obtener los valores de los campos de texto
        name_project = self.name_project.text()
        name_scenario = self.name_scenario.text()
        Name_Basin = self.Name_Basin.text()
        output_path = self.output_path.text()

        # Coordenada Este (X) del punto de cierre de la cuenca
        X = self.X_coor.text()#4815750

        # Coordenada Norte (Y) del punto de cierre de la cuenca
        Y = self.X_coor.text()#2195750

        # Definir las rutas
        NameProcessCal = os.path.join(output_path, name_project, 'temp', '04-Calibration')


        ruta_origen = os.path.join(os.path.dirname(__file__),'bin', 'cnvrtr.exe')

        ruta_origen_exe = os.path.join(os.path.dirname(__file__),'bin', 'SIGA.exe')
        ruta_destino = output_path + os.path.sep

        # Crear las carpetas necesarias
        os.makedirs(NameProcessCal, exist_ok=True)
        folders = ['DATA','FIGURES','RESULTS']
        for folder in folders:
            new_filder = os.path.join(output_path, name_project, 'temp', '04-Calibration',folder)
            os.makedirs(new_filder, exist_ok=True)

        # Copiar archivos de la carpeta DATA del plugin a la carpeta DATA del proyecto
        source_data_folder = os.path.join(os.path.dirname(__file__), 'Data', 'DATA')
        destination_data_folder = os.path.join(output_path, name_project, 'temp', '04-Calibration', 'DATA')

        if os.path.exists(source_data_folder):
            # Copiar todos los archivos de la carpeta DATA
            for filename in os.listdir(source_data_folder):
                source_file = os.path.join(source_data_folder, filename)
                destination_file = os.path.join(destination_data_folder, filename)

                # Solo copiar archivos (no directorios)
                if os.path.isfile(source_file):
                    shutil.copy2(source_file, destination_file)
                    print(f"Archivo copiado: {filename}")

        # Copiar el archivo necesario
        copiar_archivo(ruta_origen, ruta_destino)

        copiar_archivo(ruta_origen_exe, ruta_destino)

        # Llamar a la función para crear las carpetas de salida
        create_outputs_folders(output_path, name_project, name_scenario)

        QtWidgets.QMessageBox.information(self, "Success", "Folders created successfully!")


    #### Funciones Step 2 Hidrologia #############################

    def run_process_cal(self):
        # Redirigir la salida a la consola de QGIS para ver todos los mensajes
        sys.stdout = QGISLogger()
        sys.stderr = QGISLogger()

        if self.toolBox.currentIndex() == 1:  # Suponiendo que "Step2" es la segunda página, índice 1
            self.tipo_model = 'Hy'
            DateStart = self.start_date.date().toString("yyyy-MM-dd")
            DateEnd = self.end_date.date().toString("yyyy-MM-dd")
            Algorithm = self.Algorithm.currentText()
            NameFunObj = self.Metricas.currentText()
            OmitObs = int(self.Training_Period.text()) #30
            NumIter = int(self.QNumIter.text())
            TypeFobjCal = self.Tipo_Funcion.currentText()
            out_file_zip = os.path.join(self.output_path.text(), self.name_project.text(), 'salidas', self.name_scenario.text(),'Hydrological_files.zip')



        elif self.toolBox.currentIndex() == 3:
            self.tipo_model = 'Sed'
            DateStart = self.start_date_S.date().toString("yyyy-MM-dd")
            DateEnd = self.end_date_S.date().toString("yyyy-MM-dd")
            Algorithm = self.Algorithm_S.currentText()
            NameFunObj = self.Metricas_S.currentText()
            NumIter = int(self.QNumIter_S.text())
            OmitObs = int(self.Training_Period_2.text())
            TypeFobjCal = self.Tipo_Funcion_S.currentText()
            out_file_zip = os.path.join(self.output_path.text(), self.name_project.text(), 'salidas',
                                        self.name_scenario.text(), 'Sediments_files.zip')

        elif self.toolBox.currentIndex() == 4:
            Diccionario_WQ = {'Nitrogeno Total NT':'WQ_NT','Nitrogeno Organico NO':'WQ_NO','Nitrogeno Amoniaca NH4':'WQ_NH4',
                              'Nitratos NO3':'WQ_NO3','Fosforo Total':'WQ_PT', 'Fosforo Organico':'WQ_PO',
                              'Fosforo Inorganico':'WQ_PI','DBO':'WQ_DBO','Oxigeno Disuelto':'WQ_OD',
                              'Coliformes Totales':' WQ_CT','E. Coli':'WQ_EColi','Temperatura':'WQ_T','Conductividad Co':'WQ_Co',
                              'pH':'WQ_pH'}


            self.tipo_model = Diccionario_WQ[self.comboBox_M_WQ.currentText()]
            DateStart = self.start_date_WQ.date().toString("yyyy-MM-dd")
            DateEnd = self.end_date_WQ.date().toString("yyyy-MM-dd")
            Algorithm = self.Algorithm_WQ.currentText()
            NameFunObj = self.Metricas_WQ.currentText()
            NumIter = int(self.QNumIter_WQ.text())
            OmitObs = int(self.Training_Period_3.text())
            TypeFobjCal = self.Tipo_Funcion_WQ.currentText()
            out_file_zip = os.path.join(self.output_path.text(), self.name_project.text(), 'salidas',
                                        self.name_scenario.text(), Diccionario_WQ[self.comboBox_M_WQ.currentText()]+'.zip')

        try:
            QMessageBox.information(self, "Process to start",
                                    "Please keep the window open until the process is finished.")

            # Obtener los valores de los campos de texto y otros widgets

            NameSIGAModel = self.tipo_model #'Hy'
            name_project = self.name_project.text()
            name_scenario = self.name_scenario.text()
            BasinName = self.Name_Basin.text()
            output_path = self.output_path.text()
            ProjectPath = output_path
            NameSIGAFolder = name_project
            NameProcessCal = os.path.join(output_path, name_project, 'temp', '04-Calibration')

            NameSceExeUser = name_scenario

            JSONPath = os.path.join(os.path.dirname(os.path.dirname(__file__)), 'common_functions', 'Diccionario_ficheros.json')

            print('Número de interaciones:', NumIter)



            # Tipo de calibración [Time Series = 0 | t-Student = 1]
            dict_tipo = {'Time Series': 0, 't-Student': 1}

            TypeFobjCal = dict_tipo[TypeFobjCal]

            # Definir el algoritmo y la métrica
            diccio_algorit = {'DDS': 1, 'LHS': 2, 'SCE': 3}
            Algorithm = diccio_algorit[Algorithm]

            diccionario_metricas = {
                'Nash–Sutcliffe coefficient (1-NASH)': 'NASH',
                'Index of agreement': 'IoAd',
                'Normalized absolute error': 'EAN',
                'Correlation Coefficient': 'r',
                'Coefficient of Determination': 'R2',
                'Mean Squared Error': 'MSE',
                'Root Mean Squared Error': 'RMSE',
                'Mean Absolute Error': 'MAE',
                'Relative Root Mean Squared Error': 'RRMSE',
                'Composite function (NASH - IA - EAN)': 'COMPOS',
                't-Student':'t-Student'

            }

            # Convertir el nombre de la métrica del ComboBox al código interno
            NameFunObj = diccionario_metricas.get(NameFunObj, 'NASH')

            # Cantidad de datos iniciales que se omiten para la evaluación de la función objetivo




            # # Coordenada Este (X) del punto de cierre de la cuenca
            X = self.X_coor.text()
            # # Coordenada Norte (Y) del punto de cierre de la cuenca
            Y = self.Y_coor.text()

            # Nombre del archivo donde se almacenan todas las evaluaciones del modelo
            NameResultsCal = 'Params_Evaluation_' + NameSIGAModel

            # ----------------------------------------------------------------------------------------------------------------------
            # Parámetros por defecto para el proceso de calibración
            # Nota: Estos parámetros no son modificables por el usuario
            # ----------------------------------------------------------------------------------------------------------------------

            NameObsData = 'ObsData.xlsx'
            NameFileParams = 'Params.xlsx'
            NameSampler = 'Sampler_Calibration_QGIS.txt'
            NameCalibration = 'Parameters_Calibration_QGIS.txt'
            NameExe = 'Scenario_Calibration_QGIS.txt'
            PathExeSIGA = os.path.join('bin', 'SIGA.exe')#os.path.dirname(__file__),

            print('Donde está el ejecutable:', PathExeSIGA)
            paso_temporal_dias = '1'
            modelo_geotecnico = '0'
            pH_cuencacaliente = '0'

            if NameSIGAModel == 'Hy':
                tipo_ejecucion = '1'
                NameSIGAModel1 = NameSIGAModel
            elif NameSIGAModel == 'Sed':
                tipo_ejecucion = '2'
                NameSIGAModel1 = NameSIGAModel
            else:
                tipo_ejecucion = '3'
                if (NameSIGAModel == 'WQ_NT') | (NameSIGAModel == 'WQ_NO') | (NameSIGAModel == 'WQ_NH4') | (
                        NameSIGAModel == 'WQ_NO3'):
                    NameSIGAModel1 = 'WQ_N'
                elif (NameSIGAModel == 'WQ_PT') | (NameSIGAModel == 'WQ_PO') | (NameSIGAModel == 'WQ_PI'):
                    NameSIGAModel1 = 'WQ_P'
                else:
                    NameSIGAModel1 = NameSIGAModel

            # ----------------------------------------------------------------------------------------------------------------------
            # Límites de parámetros de calibración
            # ----------------------------------------------------------------------------------------------------------------------

            # Leer parámetros de calibración
            Data = pd.read_excel(os.path.join(NameProcessCal, 'DATA', NameFileParams), sheet_name=NameSIGAModel1)
            Param_Min = Data['Min'].values * (Data['Status'].values == 1) + Data['Default'].values * (
                        Data['Status'].values == 0)
            Param_Max = Data['Max'].values * (Data['Status'].values == 1) + Data['Default'].values * (
                        Data['Status'].values == 0)

            # ----------------------------------------------------------------------------------------------------------------------
            # Leer datos observador y modificar archivo de muestreo
            # ----------------------------------------------------------------------------------------------------------------------
            # Ruta archivo de datos observados
            FileName = os.path.join(NameProcessCal, 'DATA', NameObsData)

            # Catalogo
            Catalog = pd.read_excel(FileName, sheet_name='Catalog', index_col=0)
            Catalog = Catalog[Catalog[NameSIGAModel] == 1]

            # Crear un vector de fechas
            Date = pd.date_range(start=DateStart.replace('/', '-'), end=DateEnd.replace('/', '-'), freq='D')

            # Series de caudales para calibración
            TS_Obs = pd.read_excel(FileName, sheet_name=NameSIGAModel)


            # Convertir a una lista si prefieres el formato de lista en lugar de un objeto pandas
            TS_Obs['Date'] = pd.to_datetime(TS_Obs['Date'].values, format='%d/%m/%Y')
            TS_Obs.set_index('Date', inplace=True)
            TS_Obs = pd.merge(pd.DataFrame(index=Date), TS_Obs, left_index=True, right_index=True, how='outer').loc[DateStart.replace('/','-'):DateEnd.replace('/','-')]

            # ----------------------------------------------------------------------------------------------------------------------
            # Modificar archivo de puntos de control
            # ----------------------------------------------------------------------------------------------------------------------
            path_plugin = os.path.dirname(__file__)

            # Obtener la ruta base de archivos CSV (solo si el usuario seleccionó carpeta externa)
            base_csv_path = None
            if self.Check_Base_File.isChecked() and self.path_base_files.text():
                base_csv_path = self.path_base_files.text()

            spotpy_setup.Modify_csvMuestreador_CP(JSONPath, NameSIGAFolder, Catalog, NameSIGAModel, X, Y, BaseCSVPath=base_csv_path)
            spotpy_setup.Create_SamplerFile(ProjectPath, JSONPath, NameSIGAFolder, NameSampler, BaseCSVPath=base_csv_path)

            # ----------------------------------------------------------------------------------------------------------------------
            # Configuración del archivo de ejecución de SIGA. Estos parámetros de configurar internamente en el plugin
            # ----------------------------------------------------------------------------------------------------------------------

            NameSceExe = NameSceExeUser
            fecha_inicio = ' '.join(DateStart.split('-'))
            fecha_fin = ' '.join(DateEnd.split('-'))
            archivo_topologia = f'Topology_{name_project}.txt'
            archivo_Tmin = 'TimeSeries_Tamin.txt'
            archivo_Tmax = 'TimeSeries_Tamax.txt'
            archivo_HR = 'TimeSeries_HR.txt'
            archivo_RS = 'TimeSeries_RS.txt'
            archivo_PV = 'TimeSeries_PV.txt'
            archivo_Ux = 'TimeSeries_Ux.txt'
            archivo_Uy = 'TimeSeries_Uy.txt'

            # Verificar si existen archivos de descarga y captación (opcionales)
            path_qdesc = os.path.join(ProjectPath, NameSIGAFolder, 'entradas', 'series', 'TimeSeries_Qdesc.txt')
            path_qcapt = os.path.join(ProjectPath, NameSIGAFolder, 'entradas', 'series', 'TimeSeries_Qcapt.txt')
            archivo_Qdesc = 'TimeSeries_Qdesc.txt' if os.path.exists(path_qdesc) else 'NA'
            archivo_Qcapt = 'TimeSeries_Qcapt.txt' if os.path.exists(path_qcapt) else 'NA'

            archivo_Qarc = 'NA'
            archivo_Qlim = 'NA'
            archivo_Qare = 'NA'
            archivo_movmasa = 'NA'
            archivo_fact_cal = NameCalibration
            archivo_muestreador = NameSampler
            archivo_tasrest = 'TimeSeries_TasRest.txt'
            archivo_vertimientos = f'Dumpings_{name_project}.txt'
            archivo_ciclo_cargas = 'LoadCycle.txt'
            archivo_condiciones_frontera = 'CF_BoundaryCondition.txt'

            # Configurar clase de ficheros
            DicFic = Ficheros(ruta_cuenca_SIGA=os.path.join(ProjectPath, NameSIGAFolder, 'entradas' + os.path.sep),
                              archivo_ejecucion=NameExe,
                              escenario=NameSceExe,
                              fecha_inicio=fecha_inicio,
                              fecha_fin=fecha_fin,
                              paso_temporal_dias=paso_temporal_dias,
                              archivo_topologia=archivo_topologia,
                              archivo_Tmin=archivo_Tmin,
                              archivo_Tmax=archivo_Tmax,
                              archivo_HR=archivo_HR,
                              archivo_RS=archivo_RS,
                              archivo_PV=archivo_PV,
                              archivo_Ux=archivo_Ux,
                              archivo_Uy=archivo_Uy,
                              archivo_Qdesc=archivo_Qdesc,
                              archivo_Qcapt=archivo_Qcapt,
                              archivo_Qarc=archivo_Qarc,
                              archivo_Qlim=archivo_Qlim,
                              archivo_Qare=archivo_Qare,
                              archivo_movmasa=archivo_movmasa,
                              archivo_fact_cal=archivo_fact_cal,
                              archivo_muestreador=archivo_muestreador,
                              archivo_tasrest=archivo_tasrest,
                              archivo_vertimientos=archivo_vertimientos,
                              archivo_ciclo_cargas=archivo_ciclo_cargas,
                              archivo_condiciones_frontera=archivo_condiciones_frontera,
                              tipo_ejecucion=tipo_ejecucion,
                              modelo_geotecnico=modelo_geotecnico,
                              pH_cuencacaliente=pH_cuencacaliente)

            # Crear archivo de ejecución para calibración
            DicFic.crear_archivo_ejecucion()

            # ----------------------------------------------------------------------------------------------------------------------
            # Proceso de optimización
            # ----------------------------------------------------------------------------------------------------------------------

            if (Algorithm == 1):
                Factor_ObjFun = -1
                Search_ObjFun = True
            else:
                Factor_ObjFun = 1
                Search_ObjFun = False

            # Configurar modelo en estructura SPOTPY para la calibración
            model = spotpy_setup.Cal_SIGA(
                Param_Min,
                Param_Max,
                ProjectPath,
                JSONPath,
                NameSIGAFolder,
                NameCalibration,
                NameExe,
                NameSceExe,
                TS_Obs,
                OmitObs,
                Factor_ObjFun,
                TypeFobjCal,
                PathExeSIGA,
                NameSIGAModel,
                NameFunObj,
                BaseCSVPath=base_csv_path
            )
            # Path folder para guardar los parámetros
            PathParams = os.path.join(NameProcessCal, 'RESULTS', NameResultsCal)

            # Configurar algoritmo de calibración

            if Algorithm == 1:
                sampler = spotpy.algorithms.dds(model, dbname=PathParams, dbformat='csv')
            elif Algorithm == 2:
                sampler = spotpy.algorithms.lhs(model, dbname=PathParams, dbformat='csv')
            elif Algorithm == 3:
                sampler = spotpy.algorithms.sceua(model, dbname=PathParams, dbformat='csv')




            sampler.sample(NumIter)

            # ----------------------------------------------------------------------------------------------------------------------
            # Crear archivo con métricas originales para el usuario
            # ----------------------------------------------------------------------------------------------------------------------
            # Leer el archivo generado por SPOTPY (con valores transformados)
            results_df_transformed = pd.read_csv(PathParams + '.csv')

            # Crear una copia para el usuario con valores originales
            results_df_user = results_df_transformed.copy()

            # Convertir columna 'like1' a valores originales según la métrica
            if NameFunObj == 'NASH':
                # like1 transformado: FacObjF * (Part_1 / Part_2) donde NASH = 1 - (Part_1 / Part_2)
                # NASH original = 1 - (like1 / FacObjF)
                results_df_user['like1'] = 1 - (results_df_user['like1'] / Factor_ObjFun)
            elif NameFunObj == 'IoAd':
                # like1 transformado: FacObjF * (Part_1 / Part_2) donde IoAd = 1 - (Part_1 / Part_2)
                # IoAd original = 1 - (like1 / FacObjF)
                results_df_user['like1'] = 1 - (results_df_user['like1'] / Factor_ObjFun)
            elif NameFunObj in ['r', 'R2']:
                # like1 transformado: FacObjF * métrica
                # Métrica original = like1 / FacObjF
                results_df_user['like1'] = results_df_user['like1'] / Factor_ObjFun
            elif NameFunObj in ['EAN', 'MSE', 'RMSE', 'RRMSE', 'COMPOS']:
                # Estas métricas: like1 transformado = FacObjF * métrica
                # Métrica original = like1 / FacObjF
                results_df_user['like1'] = results_df_user['like1'] / Factor_ObjFun
            elif NameFunObj == 't-Student':
                # t-Student: like1 transformado = FacObjF * t_stat
                # t_stat original = like1 / FacObjF
                results_df_user['like1'] = results_df_user['like1'] / Factor_ObjFun

            # Guardar archivo para el usuario con valores originales
            results_df_user.to_csv(PathParams + '_user.csv', index=False)

            # SPOTPY lee el archivo ORIGINAL (con transformación) para seleccionar el mejor
            results = spotpy.analyser.load_csv_results(PathParams)
            best_params = spotpy.analyser.get_best_parameterset(results, maximize=Search_ObjFun)
            Params = best_params.view(float)[1:len(Param_Min) + 1]

            # ----------------------------------------------------------------------------------------------------------------------
            # Simular con mejores parámetros
            # ----------------------------------------------------------------------------------------------------------------------
            # Extraer series
            NameVarSIGA = spotpy_setup.Select_NameVarSIGA(NameSIGAModel)

            # Obtener la ruta base de archivos CSV (solo si el usuario seleccionó carpeta externa)
            base_csv_path = None
            if self.Check_Base_File.isChecked() and self.path_base_files.text():
                base_csv_path = self.path_base_files.text()

            TS_Sim, S_S4, TS_S4 = spotpy_setup.simulationSIGA(
                Params,
                ProjectPath,
                JSONPath,
                NameSIGAFolder,
                NameSIGAModel,
                NameVarSIGA,
                NameSceExe,
                NameExe,
                PathExeSIGA,
                NameCalibration,
                TS_Obs,
                BaseCSVPath=base_csv_path
            )

            stations = TS_Sim.columns

            if self.toolBox.currentIndex() == 1:
                self.comboBox.clear()  # Limpiar valores existentes
                for value in stations:
                    self.comboBox.addItem(str(value))

            elif self.toolBox.currentIndex() == 3:
                self.comboBox_S.clear()  # Limpiar valores existentes
                for value in stations:
                    self.comboBox_S.addItem(str(value))
            elif self.toolBox.currentIndex() == 4:
                self.comboBox_WQ.clear()  # Limpiar valores existentes
                for value in stations:
                    self.comboBox_WQ.addItem(str(value))


            self.obs = TS_Obs
            self.sim = TS_Sim
            self.TS_S4 = TS_S4

            # Guardar la métrica y el factor para mostrar en las gráficas
            self.NameFunObj = NameFunObj
            self.Factor_ObjFun = Factor_ObjFun

            # Comprimir archivos de simulación
            path_files = os.path.join(self.output_path.text(), self.name_project.text(), 'salidas', self.name_scenario.text())
            compress_all_folders_in_directory(path_files, out_file_zip)

            QMessageBox.information(self, "Process Complete", "Process completed")

        except Exception as e:
            QgsMessageLog.logMessage(f'Error: {str(e)}', 'Calibracion_Model', Qgis.Critical)
        finally:
            sys.stdout = sys.__stdout__
            sys.stderr = sys.__stderr__

    def Run_process_val(self):
        sys.stdout = QGISLogger()
        sys.stderr = QGISLogger()

        try:
            QMessageBox.information(self, "Process to start",
                                    "Please keep the window open until the process is finished.")

            DateStart = self.start_date_val.date().toString("yyyy-MM-dd")
            DateEnd = self.end_date_val.date().toString("yyyy-MM-dd")

            self.tipo_model = 'Hy'
            NameSIGAModel = self.tipo_model  # 'Hy'
            name_project = self.name_project.text()
            name_scenario = self.name_scenario.text()
            BasinName = self.Name_Basin.text()
            output_path = self.output_path.text()
            ProjectPath = output_path
            NameSIGAFolder = name_project
            NameProcessCal = os.path.join(output_path, name_project, 'temp', '04-Calibration')

            NameSceExeUser = name_scenario

            JSONPath = os.path.join(os.path.dirname(os.path.dirname(__file__)), 'common_functions', 'Diccionario_ficheros.json')
            NameResultsCal = 'Params_Evaluation_' + NameSIGAModel
            NameObsData = 'ObsData.xlsx'
            NameFileParams = 'Params.xlsx'
            NameSampler = 'Sampler_Calibration_QGIS.txt'
            NameCalibration = 'Parameters_Calibration_QGIS.txt'
            NameExe = 'Scenario_Validacion_QGIS.txt'
            PathExeSIGA = os.path.join('bin', 'SIGA.exe')  # os.path.dirname(__file__),

            paso_temporal_dias = '1'
            modelo_geotecnico = '0'
            pH_cuencacaliente = '0'

            if NameSIGAModel == 'Hy':
                tipo_ejecucion = '1'
                NameSIGAModel1 = NameSIGAModel
            elif NameSIGAModel == 'Sed':
                tipo_ejecucion = '2'
                NameSIGAModel1 = NameSIGAModel
            else:
                tipo_ejecucion = '3'
                if (NameSIGAModel == 'WQ_NT') | (NameSIGAModel == 'WQ_NO') | (NameSIGAModel == 'WQ_NH4') | (
                        NameSIGAModel == 'WQ_NO3'):
                    NameSIGAModel1 = 'WQ_N'
                elif (NameSIGAModel == 'WQ_PT') | (NameSIGAModel == 'WQ_PO') | (NameSIGAModel == 'WQ_PI'):
                    NameSIGAModel1 = 'WQ_P'
                else:
                    NameSIGAModel1 = NameSIGAModel

            # ----------------------------------------------------------------------------------------------------------------------
            # Leer datos observador y modificar archivo de muestreo
            # ----------------------------------------------------------------------------------------------------------------------

            # Leer parámetros de calibración
            Data = pd.read_excel(os.path.join(NameProcessCal, 'DATA', NameFileParams), sheet_name=NameSIGAModel1)
            Param_Min = Data['Min'].values * (Data['Status'].values == 1) + Data['Default'].values * (
                    Data['Status'].values == 0)
            Param_Max = Data['Max'].values * (Data['Status'].values == 1) + Data['Default'].values * (
                    Data['Status'].values == 0)

            # Ruta archivo de datos observados
            FileName = os.path.join(NameProcessCal, 'DATA', NameObsData)

            # Catalogo
            Catalog = pd.read_excel(FileName, sheet_name='Catalog', index_col=0)
            Catalog = Catalog[Catalog[NameSIGAModel] == 1]

            # Crear un vector de fechas
            Date = pd.date_range(start=DateStart.replace('/', '-'), end=DateEnd.replace('/', '-'), freq='D')

            # Series de caudales para calibración
            TS_Obs = pd.read_excel(FileName, sheet_name=NameSIGAModel)

            # Convertir a una lista si prefieres el formato de lista en lugar de un objeto pandas
            TS_Obs['Date'] = pd.to_datetime(TS_Obs['Date'].values, format='%d/%m/%Y')
            TS_Obs.set_index('Date', inplace=True)
            # Filtrar solo al período de validación usando inner join
            TS_Obs = pd.merge(pd.DataFrame(index=Date), TS_Obs, left_index=True, right_index=True, how='inner')

            # Configuración del archivo de ejecución de SIGA. Estos parámetros de configurar internamente en el plugin
            # ----------------------------------------------------------------------------------------------------------------------
            # ----------------------------------------------------------------------------------------------------------------------

            NameSceExe = NameSceExeUser
            fecha_inicio = ' '.join(DateStart.split('-'))
            fecha_fin = ' '.join(DateEnd.split('-'))
            archivo_topologia = f'Topology_{name_project}.txt'
            archivo_Tmin = 'TimeSeries_Tamin.txt'
            archivo_Tmax = 'TimeSeries_Tamax.txt'
            archivo_HR = 'TimeSeries_HR.txt'
            archivo_RS = 'TimeSeries_RS.txt'
            archivo_PV = 'TimeSeries_PV.txt'
            archivo_Ux = 'TimeSeries_Ux.txt'
            archivo_Uy = 'TimeSeries_Uy.txt'

            # Verificar si existen archivos de descarga y captación (opcionales)
            # Si el archivo existe, lo incluimos; si no existe, usamos 'NA'
            path_qdesc = os.path.join(ProjectPath, NameSIGAFolder, 'entradas', 'series', 'TimeSeries_Qdesc.txt')
            path_qcapt = os.path.join(ProjectPath, NameSIGAFolder, 'entradas', 'series', 'TimeSeries_Qcapt.txt')
            archivo_Qdesc = 'TimeSeries_Qdesc.txt' if os.path.exists(path_qdesc) else 'NA'
            archivo_Qcapt = 'TimeSeries_Qcapt.txt' if os.path.exists(path_qcapt) else 'NA'

            archivo_Qarc = 'NA'
            archivo_Qlim = 'NA'
            archivo_Qare = 'NA'
            archivo_movmasa = 'NA'
            archivo_fact_cal = NameCalibration
            archivo_muestreador = NameSampler
            archivo_tasrest = 'TimeSeries_TasRest.txt'
            archivo_vertimientos = f'Dumpings_{name_project}.txt'
            archivo_ciclo_cargas = 'LoadCycle.txt'
            archivo_condiciones_frontera = 'CF_BoundaryCondition.txt'

            # Configurar clase de ficheros
            DicFic = Ficheros(ruta_cuenca_SIGA=os.path.join(ProjectPath, NameSIGAFolder, 'entradas' + os.path.sep),
                              archivo_ejecucion=NameExe,
                              escenario=NameSceExe,
                              fecha_inicio=fecha_inicio,
                              fecha_fin=fecha_fin,
                              paso_temporal_dias=paso_temporal_dias,
                              archivo_topologia=archivo_topologia,
                              archivo_Tmin=archivo_Tmin,
                              archivo_Tmax=archivo_Tmax,
                              archivo_HR=archivo_HR,
                              archivo_RS=archivo_RS,
                              archivo_PV=archivo_PV,
                              archivo_Ux=archivo_Ux,
                              archivo_Uy=archivo_Uy,
                              archivo_Qdesc=archivo_Qdesc,
                              archivo_Qcapt=archivo_Qcapt,
                              archivo_Qarc=archivo_Qarc,
                              archivo_Qlim=archivo_Qlim,
                              archivo_Qare=archivo_Qare,
                              archivo_movmasa=archivo_movmasa,
                              archivo_fact_cal=archivo_fact_cal,
                              archivo_muestreador=archivo_muestreador,
                              archivo_tasrest=archivo_tasrest,
                              archivo_vertimientos=archivo_vertimientos,
                              archivo_ciclo_cargas=archivo_ciclo_cargas,
                              archivo_condiciones_frontera=archivo_condiciones_frontera,
                              tipo_ejecucion=tipo_ejecucion,
                              modelo_geotecnico=modelo_geotecnico,
                              pH_cuencacaliente=pH_cuencacaliente)

            # Crear archivo de ejecución para calibración
            DicFic.crear_archivo_ejecucion()

            # Definir el algoritmo y la métrica
            diccio_algorit = {'DDS': 1, 'LHS': 2, 'SCE': 3}

            Algorithm = self.Algorithm.currentText()
            Algorithm = diccio_algorit[Algorithm]

            if (Algorithm == 1):
                Factor_ObjFun = -1
                Search_ObjFun = True
            else:
                Factor_ObjFun = 1
                Search_ObjFun = False

            # Path folder para guardar los parámetros
            PathParams = os.path.join(NameProcessCal, 'RESULTS', NameResultsCal)
            results = spotpy.analyser.load_csv_results(PathParams)
            best_params = spotpy.analyser.get_best_parameterset(results, maximize=Search_ObjFun)
            Params = best_params.view(float)[1:len(Param_Min) + 1]
            NameVarSIGA = spotpy_setup.Select_NameVarSIGA(NameSIGAModel)

            # Obtener la ruta base de archivos CSV (solo si el usuario seleccionó carpeta externa)
            base_csv_path = None
            if self.Check_Base_File.isChecked() and self.path_base_files.text():
                base_csv_path = self.path_base_files.text()

            TS_Sim, S_S4, TS_S4 = spotpy_setup.simulationSIGA(
                Params,
                ProjectPath,
                JSONPath,
                NameSIGAFolder,
                NameSIGAModel,
                NameVarSIGA,
                NameSceExe,
                NameExe,
                PathExeSIGA,
                NameCalibration,
                TS_Obs,
                BaseCSVPath=base_csv_path
            )
            stations = TS_Sim.columns
            if self.toolBox.currentIndex() == 2:
                self.comboBox_Val.clear()  # Limpiar valores existentes
                for value in stations:
                    self.comboBox_Val.addItem(str(value))

            self.obs = TS_Obs
            self.sim = TS_Sim
            self.TS_S4 = TS_S4

            # Guardar el nombre de la función objetivo y el factor para mostrar el performance correctamente
            diccionario_metricas = {
                'Nash–Sutcliffe coefficient (1-NASH)': 'NASH',
                'Index of agreement': 'IoAd',
                'Normalized absolute error': 'EAN',
                'Correlation Coefficient': 'r',
                'Coefficient of Determination': 'R2',
                'Mean Squared Error': 'MSE',
                'Root Mean Squared Error': 'RMSE',
                'Mean Absolute Error': 'MAE',
                'Relative Root Mean Squared Error': 'RRMSE',
                'Composite function (NASH - IA - EAN)': 'COMPOS',
                't-Student':'t-Student'
            }
            self.NameFunObj = diccionario_metricas.get(self.Metricas.currentText(), 'NASH')
            self.Factor_ObjFun = Factor_ObjFun

            path_files = os.path.join(self.output_path.text(), self.name_project.text(), 'salidas',
                                      self.name_scenario.text())

            out_file_zip = os.path.join(self.output_path.text(), self.name_project.text(), 'salidas',
                                        self.name_scenario.text(), 'VHydrological_Validation_files.zip')

            compress_all_folders_in_directory(path_files, out_file_zip)

            QMessageBox.information(self, "Process Complete", "Process completed")

        except Exception as e:
            QgsMessageLog.logMessage(f'Error: {str(e)}', 'Calibracion_Model', Qgis.Critical)
        finally:
            sys.stdout = sys.__stdout__
            sys.stderr = sys.__stderr__


    def plot_graph(self):
        # Obtener la opción seleccionada en el QRadioButton
        if self.Plot_sim_obs.isChecked():
            self.plot_sim_obs()
        elif self.plot_tank.isChecked():
            self.Plot_tank()

    def plot_graph_S(self):
        # Obtener la opción seleccionada en el QRadioButton
        if self.Plot_sim_obs_S.isChecked():
            self.plot_sim_obs()
        elif self.Plot_Box_S.isChecked():
            self.boxplot_function()

    def plot_graph_WQ(self):
        # Obtener la opción seleccionada en el QRadioButton
        if self.Plot_sim_obs_WQ.isChecked():
            self.plot_sim_obs()
        elif self.Plot_BoxPlot_WQ.isChecked():
            self.boxplot_function()

    def boxplot_function(self):

        if self.toolBox.currentIndex() == 3:
            self.graphicsView = self.graphicsView_S
            name_title_B = 'Boxplot observed vs.simulated: Sediment'
            out_fig = f'Sediment_calibration'
            y_label = 'Sed mg/l'
            self.Peformance = self.Peformance_S
            name = self.comboBox_S.currentText()

        elif self.toolBox.currentIndex() == 4:

            Diccionario_WQ = {'Nitrogeno Total NT':'WQ_NT','Nitrogeno Organico NO':'WQ_NO','Nitrogeno Amoniaca NH4':'WQ_NH4',
                              'Nitratos NO3':'WQ_NO3','Fosforo Total':'WQ_PT', 'Fosforo Organico':'WQ_PO',
                              'Fosforo Inorganico':'WQ_PI','DBO':'WQ_DBO','Oxigeno Disuelto':'WQ_OD',
                              'Coliformes Totales':' WQ_CT','E. Coli':'WQ_EColi','Temperatura':'WQ_T','Conductividad Co':'WQ_Co',
                              'pH':'WQ_pH'}

            self.graphicsView = self.graphicsView_WQ
            name_title_B = 'WQ Boxplot observed vs.simulated '+Diccionario_WQ[self.comboBox_M_WQ.currentText()]
            out_fig = f'Box_plot_'+Diccionario_WQ[self.comboBox_M_WQ.currentText()]
            y_label = Diccionario_WQ[self.comboBox_M_WQ.currentText()]+' mg/l'
            self.Peformance = self.Peformance_WQ
            name = self.comboBox_WQ.currentText()
        try:
            # Configurar la figura para mostrar en QGIS
            graphics_view_size = self.graphicsView.size()
            width = graphics_view_size.width()
            height = graphics_view_size.height()
            display_figsize = (width / 96, height / 96)

            size_line = 1.5
            s_n = 14
            stations =self.obs.columns
            # Crear figura para guardar con tamaño figsize = (13, 8)
            fig_save, ax_save = plt.subplots(figsize=(13, 8))
            positions_sim = range(len(stations))
            box_sim = ax_save.boxplot(self.sim.dropna().values, positions=positions_sim, widths=0.3, patch_artist=True,
                                 boxprops=dict(facecolor="darkred", color="darkred"),
                                 medianprops=dict(color="black"),
                                 whiskerprops=dict(color="darkred"),
                                 capprops=dict(color="darkred"),
                                 flierprops=dict(markerfacecolor='darkred', marker='o', color='darkred', alpha=0.5))

            # Crear box plots para Observaciones
            positions_obs = [p + 0.4 for p in positions_sim]
            box_obs = ax_save.boxplot(self.obs.dropna().values, positions=positions_obs, widths=0.3, patch_artist=True,
                                 boxprops=dict(facecolor="navy", color="navy"),
                                 medianprops=dict(color="black"),
                                 whiskerprops=dict(color="navy"),
                                 capprops=dict(color="navy"),
                                 flierprops=dict(markerfacecolor='navy', marker='o', color='navy', alpha=0.5))
            ax_save.set_title(name_title_B , fontsize=s_n + 2, fontweight='bold')
            ax_save.set_xlabel('Time', fontsize=s_n, fontweight='bold')
            ax_save.set_ylabel(y_label, fontsize=s_n, fontweight='bold')

            # Configurar el eje X con los nombres de las estaciones
            # Crear la leyenda manualmente
            import matplotlib.patches as mpatches
            red_patch = mpatches.Patch(color='darkred', label='Simulated')
            blue_patch = mpatches.Patch(color='navy', label='Observed')
            ax_save.legend(handles=[red_patch, blue_patch], loc='upper right')
            plt.tight_layout()
            # Guardar la figura con tamaño 13x8
            PathProject = os.path.join(self.output_path.text(), self.name_project.text(), 'temp', '04-Calibration', 'FIGURES')
            os.makedirs(PathProject, exist_ok=True)
            fig_save.savefig(os.path.join(PathProject, out_fig+f'_{name}.png'))


            # Crear figura para mostrar en QGIS con tamaño ajustado al gráfico
            fig_display, ax_display = plt.subplots(figsize=display_figsize)
            box_sim = ax_display.boxplot(self.sim.dropna().values, positions=positions_sim, widths=0.3, patch_artist=True,
                                 boxprops=dict(facecolor="darkred", color="darkred"),
                                 medianprops=dict(color="black"),
                                 whiskerprops=dict(color="darkred"),
                                 capprops=dict(color="darkred"),
                                 flierprops=dict(markerfacecolor='darkred', marker='o', color='darkred', alpha=0.5))

            # Crear box plots para Observaciones
            positions_obs = [p + 0.4 for p in positions_sim]
            box_obs = ax_display.boxplot(self.obs.dropna().values, positions=positions_obs, widths=0.3, patch_artist=True,
                                 boxprops=dict(facecolor="navy", color="navy"),
                                 medianprops=dict(color="black"),
                                 whiskerprops=dict(color="navy"),
                                 capprops=dict(color="navy"),
                                 flierprops=dict(markerfacecolor='navy', marker='o', color='navy', alpha=0.5))
            ax_display.set_title(name_title_B , fontsize=s_n + 2, fontweight='bold')
            ax_display.set_xlabel('Time', fontsize=s_n, fontweight='bold')
            ax_display.set_ylabel(y_label, fontsize=s_n, fontweight='bold')
            red_patch = mpatches.Patch(color='darkred', label='Simulated')
            blue_patch = mpatches.Patch(color='navy', label='Observed')
            ax_save.legend(handles=[red_patch, blue_patch], loc='upper right')
            plt.tight_layout()


            # Mostrar la figura en graphicsView_7
            self.show_performance(self.NameFunObj, self.Factor_ObjFun, self.obs[name], self.sim[name], self.Peformance)
            self.display_figure(fig_display,self.graphicsView)
        except:
            self.show_performance(self.NameFunObj, self.Factor_ObjFun, self.obs[name], self.sim[name], self.Peformance)

    def plot_sim_obs(self):

        if self.toolBox.currentIndex() == 1:
            self.graphicsView = self.graphicsView_H
            name_title = 'Hydrological Calibration: '
            out_fig = f'Hydrological_calibration'
            y_label = 'Flow m$^3$/s'
            self.Peformance = self.Peformance_H
            name = self.comboBox.currentText()

        elif self.toolBox.currentIndex() == 2:
            self.graphicsView = self.graphicsView_H_Val
            name_title = 'Hydrological Validation: '
            out_fig = f'Hydrological_Validation'
            y_label = 'Flow m$^3$/s'
            self.Peformance = self.Peformance_H_val
            name = self.comboBox_Val.currentText()

        elif self.toolBox.currentIndex() == 3:
            self.graphicsView = self.graphicsView_S
            name_title = 'Sediment Calibration: '
            out_fig = f'Sediment_calibration'
            y_label = 'Sed mg/l'
            self.Peformance = self.Peformance_S
            name = self.comboBox_S.currentText()

        elif self.toolBox.currentIndex() == 4:

            Diccionario_WQ = {'Nitrogeno Total NT':'WQ_NT','Nitrogeno Organico NO':'WQ_NO','Nitrogeno Amoniaca NH4':'WQ_NH4',
                              'Nitratos NO3':'WQ_NO3','Fosforo Total':'WQ_PT', 'Fosforo Organico':'WQ_PO',
                              'Fosforo Inorganico':'WQ_PI','DBO':'WQ_DBO','Oxigeno Disuelto':'WQ_OD',
                              'Coliformes Totales':' WQ_CT','E. Coli':'WQ_EColi','Temperatura':'WQ_T','Conductividad Co':'WQ_Co',
                              'pH':'WQ_pH'}

            self.graphicsView = self.graphicsView_WQ
            name_title = 'WQ Calibration '+Diccionario_WQ[self.comboBox_M_WQ.currentText()]
            out_fig = f'WQ_calibration'+Diccionario_WQ[self.comboBox_M_WQ.currentText()]
            y_label = Diccionario_WQ[self.comboBox_M_WQ.currentText()]+' mg/l'
            self.Peformance = self.Peformance_WQ
            name = self.comboBox_WQ.currentText()



        try:
            # Obtener el nombre seleccionado en el comboBox

            # Configurar la figura para mostrar en QGIS
            graphics_view_size = self.graphicsView.size()
            width = graphics_view_size.width()
            height = graphics_view_size.height()
            display_figsize = (width / 96, height / 96)

            size_line = 1.5
            s_n = 14

            # Para calibración: omitir período de calentamiento
            # Para validación: mostrar todo el período de validación
            if self.toolBox.currentIndex() == 2:
                # Validación: usar todo el rango de fechas de validación
                TS_Obs = self.obs
                TS_Sim = self.sim
            else:
                # Calibración: omitir período de calentamiento
                OmitObs = int(self.Training_Period.text())
                new_Date = self.sim.index[OmitObs:][0]
                TS_Obs = self.obs.loc[new_Date:]
                TS_Sim = self.sim.loc[new_Date:]


            # Crear figura para guardar con tamaño figsize = (13, 8)
            fig_save, ax_save = plt.subplots(figsize=(13, 8)) #buscarme
            # ax_save.plot(self.obs.index, self.obs[name], color='navy', linewidth=size_line, alpha=0.5, label="Observed Flow")
            # ax_save.plot(self.obs.index, self.sim[name], color='darkred', linewidth=size_line, linestyle='--', alpha=0.9, label="Simulated Flow")
            ax_save.plot(TS_Obs.index, TS_Obs[name], color='navy', linewidth=size_line, alpha=0.5, label="Observed Flow")
            ax_save.plot(TS_Obs.index, TS_Sim[name], color='darkred', linewidth=size_line, linestyle='--', alpha=0.9, label="Simulated Flow")
            ax_save.set_title(name_title  + str(name), fontsize=s_n + 2, fontweight='bold')
            ax_save.set_xlabel('Time', fontsize=s_n, fontweight='bold')
            ax_save.set_ylabel(y_label, fontsize=s_n, fontweight='bold')
            ax_save.legend(loc=1)

            # Guardar la figura con tamaño 13x8
            PathProject = os.path.join(self.output_path.text(), self.name_project.text(), 'temp', '04-Calibration', 'FIGURES')
            os.makedirs(PathProject, exist_ok=True)
            fig_save.savefig(os.path.join(PathProject, out_fig+f'_{name}.png'))

            # Crear figura para mostrar en QGIS con tamaño ajustado al gráfico
            fig_display, ax_display = plt.subplots(figsize=display_figsize)
            # ax_display.plot(self.obs.index, self.obs[name], color='navy', linewidth=size_line, alpha=0.5, label="Observed Flow")
            # ax_display.plot(self.obs.index, self.sim[name], color='darkred', linewidth=size_line, linestyle='--', alpha=0.9, label="Simulated Flow")

            ax_display.plot(TS_Obs.index, TS_Obs[name], color='navy', linewidth=size_line, alpha=0.5, label="Observed Flow")
            ax_display.plot(TS_Obs.index, TS_Sim[name], color='darkred', linewidth=size_line, linestyle='--', alpha=0.9, label="Simulated Flow")
            ax_display.set_title(name_title + str(name), fontsize=s_n + 2, fontweight='bold')
            ax_display.set_xlabel('Time', fontsize=s_n, fontweight='bold')
            ax_display.set_ylabel(y_label, fontsize=s_n, fontweight='bold')
            ax_display.legend(loc=1)
            plt.tight_layout()
            # Mostrar la figura en graphicsView_7
            # Usar las series filtradas (TS_Obs y TS_Sim) para calcular el performance
            self.show_performance(self.NameFunObj, self.Factor_ObjFun, TS_Obs[name], TS_Sim[name], self.Peformance)
            self.display_figure(fig_display,self.graphicsView)
        except:
            # En caso de error, intentar con las series filtradas
            try:
                self.show_performance(self.NameFunObj, self.Factor_ObjFun, TS_Obs[name], TS_Sim[name], self.Peformance)
            except:
                pass

    def Plot_tank(self):

        if self.toolBox.currentIndex() == 1:
            self.graphicsView = self.graphicsView_H
        # Obtener el nombre seleccionado en el comboBox
        name = self.comboBox.currentText()

        # Configurar la figura para mostrar en QGIS
        graphics_view_size = self.graphicsView.size()
        width = graphics_view_size.width()
        height = graphics_view_size.height()
        display_figsize = (width / 96, height / 96)

        size_line = 1.5
        s_n = 14

        # Crear figura para guardar con tamaño figsize = (13, 8)
        fig_save, ax_save = plt.subplots(figsize=(13, 8))
        slope, intercept, r_value, p_value, std_err = scipy.stats.linregress(
            np.arange(0, len(self.TS_S4['S4(m)']), 1), self.TS_S4['S4(m)'] * 1000)
        ax_save.plot(self.TS_S4['S4(m)'].values * 1000, color='darkred', linewidth=size_line, linestyle='--', alpha=0.9, label="Simulated tank")
        ax_save.plot(np.arange(0, len(self.TS_S4['S4(m)']), 1), slope * np.arange(0, len(self.TS_S4['S4(m)']), 1) + intercept,
                     color='navy', linewidth=size_line, alpha=0.9, label="Slope")
        ax_save.set_title('Hydrological Calibration - Tank S4', fontsize=s_n + 2, fontweight='bold')
        ax_save.grid()
        ax_save.legend(loc=1)

        # Guardar la figura con tamaño 13x8
        PathProject = os.path.join(self.output_path.text(), self.name_project.text(), 'temp', '04-Calibration', 'FIGURES')
        os.makedirs(PathProject, exist_ok=True)
        fig_save.savefig(os.path.join(PathProject, f'Tank_4_{name}.png'))

        # Crear figura para mostrar en QGIS con tamaño ajustado al gráfico
        fig_display, ax_display = plt.subplots(figsize=display_figsize)
        ax_display.plot(self.TS_S4['S4(m)'].values * 1000, color='darkred', linewidth=size_line, linestyle='--', alpha=0.9, label="Simulated tank")
        ax_display.plot(np.arange(0, len(self.TS_S4['S4(m)']), 1), slope * np.arange(0, len(self.TS_S4['S4(m)']), 1) + intercept,
                        color='navy', linewidth=size_line, alpha=0.9, label="Slope")
        ax_display.set_title('Hydrological Calibration - Tank S4', fontsize=s_n + 2, fontweight='bold')
        ax_display.grid()
        ax_display.legend(loc=1)
        plt.tight_layout()
        # Mostrar la figura en graphicsView_7
        self.display_figure(fig_display,self.graphicsView)

    def zoom_in(self, graphics_view):
        graphics_view.scale(1.2, 1.2)

    def zoom_out(self, graphics_view):
        graphics_view.scale(0.8, 0.8)

    def show_performance (self,NameFunObj, FacObjF, Obs, Sim,plainTextEdit):
        resultado = performance(NameFunObj, FacObjF, Obs, Sim)

        plainTextEdit.setPlainText(f"{NameFunObj}: {np.round(resultado,2)}")

    def display_figure(self, figure, graphics_view):
        # Crear un canvas para mostrar la figura
        canvas = FigureCanvasQTAgg(figure)
        scene = QGraphicsScene()
        scene.addWidget(canvas)

        # Configurar la escena en el graphics_view proporcionado
        graphics_view.setScene(scene)
        graphics_view.show()

    #### Step 6 Funciones de Análisis de Sensibilidad #############################
    def plot_sensitivity_analysis(self):
        """
        Genera gráficos de análisis de sensibilidad basados en la selección del usuario
        """
        try:
            # Obtener valores de configuración
            output_path = self.output_path.text()
            name_project = self.name_project.text()

            # Validar que los campos no estén vacíos
            if not output_path or not name_project:
                QMessageBox.warning(self, "Warning", "Please configure the project first (Step 1)")
                return

            # Ruta del archivo de entrada
            input_file = os.path.join(output_path, name_project, 'temp', '04-Calibration', 'RESULTS', 'Params_Evaluation_Hy.csv')

            # Verificar que el archivo existe
            if not os.path.exists(input_file):
                QMessageBox.warning(self, "Warning", f"File not found: {input_file}\nPlease run the calibration process first.")
                return

            # Ruta de salida
            output_dir = os.path.join(output_path, name_project, 'temp', '04-Calibration', 'sensitivity_results')

            # Crear directorio si no existe
            os.makedirs(output_dir, exist_ok=True)

            # Obtener el tipo de gráfico seleccionado
            selected_chart = self.Type_Fig.currentText()

            # Mapeo de nombres de UI a métodos de la clase
            chart_mapping = {
                'All Plots': 'all',
                'Boxplot': 'chart_1_parameter_boxplots',
                'Scatter Plot': 'chart_2_scatter_parameters_vs_simulations',
                'Correlation heatmap': 'chart_3_correlation_heatmap',
                'histograms': 'chart_4_histograms',
                'Time series': 'chart_5_time_series',
                'Sensitivity indices': 'chart_6_sensitivity_indices',
                'Violin plots': 'chart_7_violin_plots',
                'Parallel coordinates': 'chart_8_parallel_coordinates',
                'Tornado plot': 'chart_9_tornado_plot'
            }

            # Informar al usuario
            QMessageBox.information(self, "Processing",
                                   "Generating sensitivity analysis charts. This may take a few moments...")

            # Crear analizador
            analyzer = SensitivityAnalyzer(input_file, output_dir)
            analyzer.load_data()

            # Generar gráficos según la selección
            if selected_chart == 'All Plots':
                # Generar todos los gráficos
                analyzer.chart_1_parameter_boxplots()
                analyzer.chart_2_scatter_parameters_vs_simulations()
                analyzer.chart_3_correlation_heatmap()
                analyzer.chart_4_histograms()
                analyzer.chart_5_time_series()
                analyzer.chart_6_sensitivity_indices()
                analyzer.chart_7_violin_plots()
                analyzer.chart_8_parallel_coordinates()
                analyzer.chart_9_tornado_plot()
                analyzer.generate_summary_report()

                # Mostrar el primer gráfico (boxplot)
                chart_to_display = os.path.join(output_dir, '01_parameter_boxplots.png')
            else:
                # Generar solo el gráfico seleccionado
                chart_method = chart_mapping[selected_chart]
                method = getattr(analyzer, chart_method)
                method()

                # También generar la tabla de sensibilidad y el reporte si se selecciona "Sensitivity indices"
                if selected_chart == 'Sensitivity indices':
                    # Este método ya genera la tabla automáticamente
                    pass

                # Generar reporte de resumen
                analyzer.generate_summary_report()

                # Determinar qué archivo mostrar
                chart_files = {
                    'chart_1_parameter_boxplots': '01_parameter_boxplots.png',
                    'chart_2_scatter_parameters_vs_simulations': '02_scatter_parameters_vs_simulations.png',
                    'chart_3_correlation_heatmap': '03_correlation_heatmap.png',
                    'chart_4_histograms': '04a_parameter_histograms.png',
                    'chart_5_time_series': '05_time_series.png',
                    'chart_6_sensitivity_indices': '06_sensitivity_indices.png',
                    'chart_7_violin_plots': '07_violin_plots.png',
                    'chart_8_parallel_coordinates': '08_parallel_coordinates.png',
                    'chart_9_tornado_plot': '09_tornado_plot.png'
                }
                chart_to_display = os.path.join(output_dir, chart_files[chart_method])

            # Mostrar el gráfico en graphicsView_WQ_2
            self.display_sensitivity_chart(chart_to_display)

            # Mensaje de éxito
            QMessageBox.information(self, "Success",
                                   f"Sensitivity analysis completed!\nResults saved in:\n{output_dir}")

        except Exception as e:
            QMessageBox.critical(self, "Error", f"Error generating sensitivity analysis:\n{str(e)}")
            QgsMessageLog.logMessage(f'Error in sensitivity analysis: {str(e)}', 'Calibracion_Model', Qgis.Critical)

    def display_sensitivity_chart(self, image_path):
        """
        Muestra un gráfico de sensibilidad en graphicsView_WQ_2
        """
        try:
            from PyQt5.QtGui import QPixmap
            from PyQt5.QtWidgets import QGraphicsPixmapItem

            # Verificar que el archivo existe
            if not os.path.exists(image_path):
                QMessageBox.warning(self, "Warning", f"Chart file not found: {image_path}")
                return

            # Cargar la imagen
            pixmap = QPixmap(image_path)

            # Escalar la imagen para que se ajuste al tamaño del QGraphicsView
            graphics_view_size = self.graphicsView_WQ_2.size()
            scaled_pixmap = pixmap.scaled(graphics_view_size, Qt.KeepAspectRatio, Qt.SmoothTransformation)

            # Crear escena y agregar la imagen
            scene = QGraphicsScene()
            pixmap_item = QGraphicsPixmapItem(scaled_pixmap)
            scene.addItem(pixmap_item)

            # Configurar la escena en el graphics_view
            self.graphicsView_WQ_2.setScene(scene)
            self.graphicsView_WQ_2.show()

        except Exception as e:
            QMessageBox.critical(self, "Error", f"Error displaying chart:\n{str(e)}")
            QgsMessageLog.logMessage(f'Error displaying chart: {str(e)}', 'Calibracion_Model', Qgis.Critical)

    def close_plugin(self):
        """
        Cierra el plugin y el dockwidget
        """
        try:
            self.close()
        except Exception as e:
            QgsMessageLog.logMessage(f'Error closing plugin: {str(e)}', 'Calibracion_Model', Qgis.Critical)

    def closeEvent(self, event):
        self.closingPlugin.emit()
        event.accept()



