# -*- coding: utf-8 -*-
"""
/***************************************************************************
 Siga_Step_01_Config
                                 A QGIS plugin
 This plugin generates the previous configuration for the execution of the model. 
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2024-09-23
        copyright            : (C) 2024 by The Nature Conservancy
        email                : miguel.canon@tnc.org
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load Siga_Step_01_Config class from file Siga_Step_01_Config.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .Siga_Step_01_Config import Siga_Step_01_Config
    return Siga_Step_01_Config(iface)
