# -*- coding: utf-8 -*-
"""
/***************************************************************************
 Siga_Step_01_ConfigDockWidget
                                 A QGIS plugin
 This plugin generates the previous configuration for the execution of the model. 
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2024-09-23
        git sha              : $Format:%H$
        copyright            : (C) 2024 by The Nature Conservancy
        email                : miguel.canon@tnc.org
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
"""

import os
import sys
import json
import numpy as np
import pandas as pd
import rasterio
from rasterio.enums import Resampling
from osgeo import gdal
from numba import config
import processing
from pysheds.grid import Grid
from qgis.PyQt import QtGui, QtWidgets, uic
from qgis.PyQt.QtCore import pyqtSignal
from PyQt5.QtCore import QVariant
from PyQt5.QtGui import QColor
from PyQt5.QtWidgets import QFileDialog, QMessageBox, QTableWidgetItem, QInputDialog
from qgis.core import (
    QgsRasterLayer, QgsProject, QgsVectorLayer, QgsFillSymbol,
    QgsColorRampShader, QgsSingleBandPseudoColorRenderer, QgsRasterShader,
    QgsProcessingFeedback, QgsField, QgsFeature, QgsGeometry, QgsPointXY,
    QgsVectorFileWriter, QgsCoordinateReferenceSystem
)
from qgis.gui import QgsMapToolEmitPoint, QgsMapTool
from qgis.utils import iface
from ..common_functions.ficheros import create_outputs_folders, Ficheros
from ..common_functions.Functions_Raster import (
    resample_to_match, Erodability, PolyponToRaster,
    shp_to_csv_muestreador, multiformat_to_csv_muestreador, read_multiformat_file
)

FORM_CLASS, _ = uic.loadUiType(os.path.join(
    os.path.dirname(__file__), 'Siga_Step_01_Config_dockwidget_base.ui'))


class Siga_Step_01_ConfigDockWidget(QtWidgets.QDockWidget, FORM_CLASS):

    closingPlugin = pyqtSignal()

    def __init__(self, parent=None):
        """Constructor."""
        super(Siga_Step_01_ConfigDockWidget, self).__init__(parent)



        self.setupUi(self)
        self.iface = iface



        #### Step 1 creacion de proyecto #############################
        # Connect signals to slots
        self.select_output.clicked.connect(self.select_output_folder)
        self.Button_Step_1.clicked.connect(self.create_project_folders)

        #### Step 2 Delimitacion Cuenca #############################
        self.Button_Load_Dem.clicked.connect(self.select_dem)  # Conectar botón Button_Load_Dem
        self.Button_Run_Dem.clicked.connect(self.run_dem_processes)
        self.Button_Run_Basin.clicked.connect(self.run_basin_processes)
        self.Button_Step_2.clicked.connect(self.move_to_topologia)

        # Create a map tool to capture mouse clicks
        self.point_tool = QgsMapToolEmitPoint(self.iface.mapCanvas())
        self.point_tool.canvasClicked.connect(self.set_coordinates)

        self.X_coor.mousePressEvent = self.activate_point_tool
        self.Y_coor.mousePressEvent = self.activate_point_tool

        #### Step 3 Topologia #############################
        self.Check_Embalse.toggled.connect(self.toggle_topology_inputs)
        self.Check_Cabeceras.toggled.connect(self.toggle_topology_inputs)
        self.Check_Nbs.toggled.connect(self.toggle_topology_inputs)

        self.Button_Load_Embalse.clicked.connect(lambda: self.select_shp(self.Path_Shp_Embalse))
        self.Button_Load_Cabeceras.clicked.connect(lambda: self.select_shp(self.Path_Shp_Cabeceras))
        self.Button_Load_NbS.clicked.connect(lambda: self.select_raster_file(self.Path_Raster_Nbs))
        self.Button_Run_Topo.clicked.connect(self.run_topology_processes)
        self.Button_Step_3.clicked.connect(self.move_to_series_de_tiempo)

        #### Step 4 Series de Tiempo #############################
        self.Button_Load_Stations.clicked.connect(self.load_shapefile_layer)
        self.Button_Load_Excel.clicked.connect(self.load_excel_file)
        self.Button_Run_Series.clicked.connect(self.run_series_processes)
        self.Button_Step_4.clicked.connect(self.move_to_mapas)

        #### Step 5 Mapas #############################
        # Conectar botones
        self.Button_Load_arenas.clicked.connect(lambda: self.load_and_resample_raster(self.Path_Raster_arenas, "arenas.tif"))
        self.Button_Load_limos.clicked.connect(lambda: self.load_and_resample_raster(self.Path_Raster_limos, "limos.tif"))
        self.Button_Load_arcillas.clicked.connect(lambda: self.load_and_resample_raster(self.Path_Raster_arcillas, "arcillas.tif"))
        self.Button_Load_OM.clicked.connect(lambda: self.load_and_resample_raster(self.Path_Raster_OM, "MO.tif"))
        self.Button_Load_Profundidad.clicked.connect(lambda: self.load_and_resample_raster(self.Path_Raster_Profundidad, "Zs.tif"))
        self.Button_Load_Usle_P.clicked.connect(lambda: self.load_and_resample_raster(self.Path_Raster_Usle_P, "P_usle.tif"))
        self.Button_Load_Usle_K.clicked.connect(lambda: self.load_and_resample_raster(self.Path_Raster_Usle_K, "K_usle.tif"))

        #base de datos
        self.zip_file_path = os.path.join(os.path.dirname(__file__), 'DATABASE.zip')

        self.Button_Load_arena_gdb.clicked.connect(lambda: self.load_and_resample_raster_from_zip(self.zip_file_path, "Sand/Sand.tif", "arenas.tif"))
        self.Button_Load_limos_gdb.clicked.connect(lambda: self.load_and_resample_raster_from_zip(self.zip_file_path, "Silt/Silt.tif", "limos.tif"))
        self.Button_Load_arcillas_gdb.clicked.connect(lambda: self.load_and_resample_raster_from_zip(self.zip_file_path, "Clay/Clay.tif", "arcillas.tif"))
        self.Button_Load_OM_gdb.clicked.connect( lambda: self.load_and_resample_raster_from_zip(self.zip_file_path, "OM/OM.tif", "MO.tif"))
        self.Button_Load_Profundidad_gdb.clicked.connect(lambda: self.load_and_resample_raster_from_zip(self.zip_file_path, "Zs/Zs.tif", "Zs.tif"))
        self.Button_Load_K_gdb.clicked.connect(lambda: self.load_and_resample_raster_from_zip(self.zip_file_path, "K/K.tif", "K_usle.tif"))

        self.Button_Load_LULC.clicked.connect(self.load_lulc_raster)
        self.Button_Estimacion_Usle_P.clicked.connect(self.create_usle_p_raster)
        self.Button_Estimacion_Usle_K.clicked.connect(self.run_erodability)
        self.Button_Step_5.clicked.connect(self.move_to_next_step)

        #### Step 6 Mapas 1 #############################

        self.Button_Load_idCiclo.clicked.connect(lambda: self.load_and_resample_raster(self.Path_Raster_idCiclo, 'idCiclo.tif'))
        self.Button_Load_idQ.clicked.connect(lambda: self.load_and_resample_raster(self.Path_Raster_idQ, 'idQ.tif'))
        self.Button_Load_ki.clicked.connect(lambda: self.load_and_resample_raster(self.Path_Raster_ki, 'ki.tif'))
        self.Button_Load_phi.clicked.connect(lambda: self.load_and_resample_raster(self.Path_Raster_phi, 'phi.tif'))
        self.Button_Load_C.clicked.connect(lambda: self.load_and_resample_raster(self.Path_Raster_C, 'c.tif'))
        self.Button_Load_Q5a.clicked.connect(lambda: self.load_and_resample_raster(self.Path_Raster_Q5a, 'Q5a.tif'))

        self.Button_Load_Paramos.clicked.connect(self.load_paramos_raster)

        self.Button_Estimacion_ki.clicked.connect(lambda: self.load_and_resample_raster_from_zip_op2(self.zip_file_path,"Ki/Ki.tif", 'Ki.tif'))
        self.Button_Estimacion_idCiclo.clicked.connect(self.create_idciclo_raster)
        self.Button_Estimacion_idQ.clicked.connect(self.create_idq_raster)
        self.Button_Run_P_T.clicked.connect(self.create_prioridad_transicion_rasters)

        self.Button_Step_6.clicked.connect(lambda: self.toolBox.setCurrentIndex(6))

        ### step 7 muestreador y  step 8 modulos

        # Conectar botones para Step 7 Muestreador
        self.Button_Load_Points.clicked.connect(self.load_shp_points)
        self.Button_Load_tramos.clicked.connect(self.load_shp_tramos)
        self.Button_Run_Muestreador.clicked.connect(self.run_muestreador)

        # Conectar botones de Modulos 8
        self.Button_Load_Mov_mass.clicked.connect(self.load_mov_mass)
        self.Button_Load_Vertimientos.clicked.connect(self.load_vertimientos)

        self.Button_Load_boundary.clicked.connect(self.load_boundary)
        self.Button_Load_Ciclos.clicked.connect(self.load_ciclos)
        self.Button_Run_Modulos.clicked.connect(self.run_modulos)



        self.Button_Step_8.clicked.connect(lambda: self.toolBox.setCurrentIndex(7))

        ### step 8 Calibracion 1

        self.Button_Load_Weather.clicked.connect(lambda: self.load_excel_file_cal(self.Path_Excel_Weather))
        self.Button_Load_Restauration.clicked.connect(lambda: self.load_excel_file_cal(self.Path_Excel_Restauration))
        self.Button_Load_Phenologic.clicked.connect(lambda: self.load_excel_file_cal(self.Path_Excel_Phenologic))
        self.Button_Load_hydrologic.clicked.connect(lambda: self.load_excel_file_cal(self.Path_Excel_hydrologic))
        self.Button_Load_Sediments.clicked.connect(lambda: self.load_excel_file_cal(self.Path_Excel_Sediments))
        self.Button_Load_geotechnical.clicked.connect(lambda: self.load_excel_file_cal(self.Path_Excel_geotechnical))
        self.Button_Load_Diffuse.clicked.connect(lambda: self.load_excel_file_cal(self.Path_Excel_Diffuse))
        self.Button_Load_DBO.clicked.connect(lambda: self.load_excel_file_cal(self.Path_Excel_DBO))
        self.Button_Load_Reaeration.clicked.connect(lambda: self.load_excel_file_cal(self.Path_Excel_Reaeration))
        self.Button_Load_EColi.clicked.connect(lambda: self.load_excel_file_cal(self.Path_Excel_Ecoli))
        self.Button_Load_Nitrogen.clicked.connect(lambda: self.load_excel_file_cal(self.Path_Excel_Nitrogen))
        self.Button_Load_Phosphorus.clicked.connect(lambda: self.load_excel_file_cal(self.Path_Excel_Phosphorus))

        self.Button_Run_Parms_Cal.clicked.connect(self.run_parametros_cal)

        self.Button_Step_9.clicked.connect(lambda: self.toolBox.setCurrentIndex(8))


        ### step 9 Calibracion 2
        self.Button_Load_Tcoliforms.clicked.connect(lambda: self.load_excel_file_cal(self.Path_Excel_Tcoliforms))
        self.Button_Load_Turbidity.clicked.connect(lambda: self.load_excel_file_cal(self.Path_Excel_Turbidity))
        self.Button_Load_Conductividad.clicked.connect(lambda: self.load_excel_file_cal(self.Path_Excel_Conductividad))
        self.Button_Load_SST.clicked.connect(lambda: self.load_excel_file_cal(self.Path_Excel_SST))
        self.Button_Load_T_Correction.clicked.connect(lambda: self.load_excel_file_cal(self.Path_Excel_T_Correction))
        self.Button_Load_Temperature.clicked.connect(lambda: self.load_excel_file_cal(self.Path_Excel_Temperature))
        self.Button_Load_ADZQUASAR.clicked.connect(lambda: self.load_excel_file_cal(self.Path_Excel_ADZQUASAR))
        self.Button_Load_Ph.clicked.connect(lambda: self.load_excel_file_cal(self.Path_Excel_Ph))

        self.Button_Run_Parms_Cal_All.clicked.connect(self.run_parametros_cal2)

        ### Boton Finish - Cerrar Plugin
        self.Button_Finish_1.clicked.connect(self.close_plugin)

        ### Base Files - Carpeta externa para archivos CSV
        self.Check_Base_File.toggled.connect(self.toggle_base_files)
        self.select_base_files.clicked.connect(self.select_base_files_folder)

        ### Project State - Auto-save and load project state
        QgsProject.instance().projectSaved.connect(self.save_project_state)
        QgsProject.instance().readProject.connect(self.load_project_state)

        # Load project state on initialization if project is already open
        if QgsProject.instance().fileName():
            self.load_project_state()


    #### Funciones Generales - Base Files ############################
    def toggle_base_files(self):
        """Enable/disable base files controls based on checkbox state."""
        is_checked = self.Check_Base_File.isChecked()
        self.select_base_files.setEnabled(is_checked)
        self.path_base_files.setEnabled(is_checked)

        # If unchecked, clear the path
        if not is_checked:
            self.path_base_files.clear()

    def select_base_files_folder(self):
        """Open dialog to select base files folder."""
        folder = QtWidgets.QFileDialog.getExistingDirectory(self, "Select Base Files Folder")
        if folder:
            self.path_base_files.setText(folder)
            self.show_message("Success", f"Base files folder set to: {folder}")

    def get_base_csv_path(self, subfolder=''):
        """
        Get the base CSV path based on user selection.

        Parameters:
        -----------
        subfolder : str
            Subfolder within base path (e.g., 'muestreador', 'calibracion')

        Returns:
        --------
        str
            Full path to the base CSV folder
        """
        if self.Check_Base_File.isChecked() and self.path_base_files.text():
            # Use external folder
            base_path = self.path_base_files.text()
            if subfolder:
                return os.path.join(base_path, subfolder)
            return base_path
        else:
            # Use internal archivos_csv folder
            base_path = os.path.join(os.path.dirname(__file__), 'archivos_csv')
            if subfolder:
                return os.path.join(base_path, subfolder)
            return base_path

    #### Funciones Generales - Project State Management ############################
    def save_project_state(self):
        """
        Save the current state of the plugin to QGIS project variables.
        This is called automatically when the QGIS project is saved.
        """
        try:
            project = QgsProject.instance()

            # Create a dictionary with all the state information
            state = {
                # Step 1 - Project creation
                'output_path': self.output_path.text(),
                'name_project': self.name_project.text(),
                'name_scenario': self.name_scenario.text(),

                # Step 2 - Basin delimitation
                'Path_Dem': self.Path_Dem.text(),
                'Threshold': self.Threshold.text(),
                'X_coor': self.X_coor.text(),
                'Y_coor': self.Y_coor.text(),

                # Step 3 - Topology
                'Check_Nbs': self.Check_Nbs.isChecked(),
                'Check_Embalse': self.Check_Embalse.isChecked(),
                'Check_Cabeceras': self.Check_Cabeceras.isChecked(),
                'Path_Shp_Embalse': self.Path_Shp_Embalse.text(),
                'Path_Shp_Cabeceras': self.Path_Shp_Cabeceras.text(),

                # Step 4 - Time series
                'Path_Shp_Stations': self.Path_Shp_Stations.text(),
                'Path_excel_time_series': self.Path_excel_time_series.text(),

                # Step 5 - Maps
                'Path_Raster_arenas': self.Path_Raster_arenas.text(),
                'Path_Raster_limos': self.Path_Raster_limos.text(),
                'Path_Raster_arcillas': self.Path_Raster_arcillas.text(),
                'Path_Raster_OM': self.Path_Raster_OM.text(),
                'Path_Raster_LULC': self.Path_Raster_LULC.text(),

                # Step 6 - Maps 1
                'Path_Raster_Paramos': self.Path_Raster_Paramos.text(),

                # Step 7 - Sampler
                'Path_shp_points': self.Path_shp_points.text(),
                'Path_shp_tramos': self.Path_shp_tramos.text(),

                # Step 8 - Modules
                'Path_excel_Mov_mass': self.Path_excel_Mov_mass.text(),
                'Path_excel_Vertimientos': self.Path_excel_Vertimientos.text(),
                'Path_excel_boundary': self.Path_excel_boundary.text(),
                'Path_excel_Ciclos': self.Path_excel_Ciclos.text(),

                # Step 9 - Calibration Part 1
                'Check_Weather': self.Check_Weather.isChecked(),
                'Path_Excel_Weather': self.Path_Excel_Weather.text(),
                'Check_restoration': self.Check_restoration.isChecked(),
                'Path_Excel_Restauration': self.Path_Excel_Restauration.text(),
                'Check_Phenologic': self.Check_Phenologic.isChecked(),
                'Path_Excel_Phenologic': self.Path_Excel_Phenologic.text(),
                'Check_hydrologic': self.Check_hydrologic.isChecked(),
                'Path_Excel_hydrologic': self.Path_Excel_hydrologic.text(),
                'Check_Sediments': self.Check_Sediments.isChecked(),
                'Path_Excel_Sediments': self.Path_Excel_Sediments.text(),
                'Check_geotechnical': self.Check_geotechnical.isChecked(),
                'Path_Excel_geotechnical': self.Path_Excel_geotechnical.text(),
                'Check_Diffuse': self.Check_Diffuse.isChecked(),
                'Path_Excel_Diffuse': self.Path_Excel_Diffuse.text(),
                'Check_DBO': self.Check_DBO.isChecked(),
                'Path_Excel_DBO': self.Path_Excel_DBO.text(),
                'Check_Reaeration': self.Check_Reaeration.isChecked(),
                'Path_Excel_Reaeration': self.Path_Excel_Reaeration.text(),
                'Check_EColi': self.Check_EColi.isChecked(),
                'Path_Excel_Ecoli': self.Path_Excel_Ecoli.text(),
                'Check_Nitrogen': self.Check_Nitrogen.isChecked(),
                'Path_Excel_Nitrogen': self.Path_Excel_Nitrogen.text(),
                'Check_Phosphorus': self.Check_Phosphorus.isChecked(),
                'Path_Excel_Phosphorus': self.Path_Excel_Phosphorus.text(),

                # Step 10 - Calibration Part 2
                'Check_Tcoliforms': self.Check_Tcoliforms.isChecked(),
                'Path_Excel_Tcoliforms': self.Path_Excel_Tcoliforms.text(),
                'Check_Turbidity': self.Check_Turbidity.isChecked(),
                'Path_Excel_Turbidity': self.Path_Excel_Turbidity.text(),
                'Check_Conductividad': self.Check_Conductividad.isChecked(),
                'Path_Excel_Conductividad': self.Path_Excel_Conductividad.text(),
                'Check_SST': self.Check_SST.isChecked(),
                'Path_Excel_SST': self.Path_Excel_SST.text(),
                'Check_T_Correction': self.Check_T_Correction.isChecked(),
                'Path_Excel_T_Correction': self.Path_Excel_T_Correction.text(),
                'Check_Temperature': self.Check_Temperature.isChecked(),
                'Path_Excel_Temperature': self.Path_Excel_Temperature.text(),
                'Check_ADZQUASAR': self.Check_ADZQUASAR.isChecked(),
                'Path_Excel_ADZQUASAR': self.Path_Excel_ADZQUASAR.text(),
                'Check_Ph': self.Check_Ph.isChecked(),
                'Path_Excel_Ph': self.Path_Excel_Ph.text(),

                # Base Files
                'Check_Base_File': self.Check_Base_File.isChecked(),
                'path_base_files': self.path_base_files.text(),

                # Current toolbox page
                'current_toolbox_index': self.toolBox.currentIndex()
            }

            # Save state as JSON string in project variables
            project.writeEntry('QSIGA_CAL', 'plugin_state', json.dumps(state))

        except Exception as e:
            print(f"Error saving project state: {e}")

    def load_project_state(self):
        """
        Load the plugin state from QGIS project variables.
        This is called automatically when a QGIS project is opened.
        """
        try:
            project = QgsProject.instance()

            # Read state from project variables
            state_json, success = project.readEntry('QSIGA_CAL', 'plugin_state')

            if not success or not state_json:
                return

            state = json.loads(state_json)

            # Restore Step 1 - Project creation
            if 'output_path' in state:
                self.output_path.setText(state['output_path'])
            if 'name_project' in state:
                self.name_project.setText(state['name_project'])
            if 'name_scenario' in state:
                self.name_scenario.setText(state['name_scenario'])

            # Restore Step 2 - Basin delimitation
            if 'Path_Dem' in state:
                self.Path_Dem.setText(state['Path_Dem'])
            if 'Threshold' in state:
                self.Threshold.setText(state['Threshold'])
            if 'X_coor' in state:
                self.X_coor.setText(state['X_coor'])
            if 'Y_coor' in state:
                self.Y_coor.setText(state['Y_coor'])

            # Restore Step 3 - Topology
            if 'Check_Nbs' in state:
                self.Check_Nbs.setChecked(state['Check_Nbs'])
            if 'Check_Embalse' in state:
                self.Check_Embalse.setChecked(state['Check_Embalse'])
            if 'Check_Cabeceras' in state:
                self.Check_Cabeceras.setChecked(state['Check_Cabeceras'])
            if 'Path_Shp_Embalse' in state:
                self.Path_Shp_Embalse.setText(state['Path_Shp_Embalse'])
            if 'Path_Shp_Cabeceras' in state:
                self.Path_Shp_Cabeceras.setText(state['Path_Shp_Cabeceras'])

            # Restore Step 4 - Time series
            if 'Path_Shp_Stations' in state:
                self.Path_Shp_Stations.setText(state['Path_Shp_Stations'])
            if 'Path_excel_time_series' in state:
                self.Path_excel_time_series.setText(state['Path_excel_time_series'])

            # Restore Step 5 - Maps
            if 'Path_Raster_arenas' in state:
                self.Path_Raster_arenas.setText(state['Path_Raster_arenas'])
            if 'Path_Raster_limos' in state:
                self.Path_Raster_limos.setText(state['Path_Raster_limos'])
            if 'Path_Raster_arcillas' in state:
                self.Path_Raster_arcillas.setText(state['Path_Raster_arcillas'])
            if 'Path_Raster_OM' in state:
                self.Path_Raster_OM.setText(state['Path_Raster_OM'])
            if 'Path_Raster_LULC' in state:
                self.Path_Raster_LULC.setText(state['Path_Raster_LULC'])

            # Restore Step 6 - Maps 1
            if 'Path_Raster_Paramos' in state:
                self.Path_Raster_Paramos.setText(state['Path_Raster_Paramos'])

            # Restore Step 7 - Sampler
            if 'Path_shp_points' in state:
                self.Path_shp_points.setText(state['Path_shp_points'])
            if 'Path_shp_tramos' in state:
                self.Path_shp_tramos.setText(state['Path_shp_tramos'])

            # Restore Step 8 - Modules
            if 'Path_excel_Mov_mass' in state:
                self.Path_excel_Mov_mass.setText(state['Path_excel_Mov_mass'])
            if 'Path_excel_Vertimientos' in state:
                self.Path_excel_Vertimientos.setText(state['Path_excel_Vertimientos'])
            if 'Path_excel_boundary' in state:
                self.Path_excel_boundary.setText(state['Path_excel_boundary'])
            if 'Path_excel_Ciclos' in state:
                self.Path_excel_Ciclos.setText(state['Path_excel_Ciclos'])

            # Restore Step 9 - Calibration Part 1
            if 'Check_Weather' in state:
                self.Check_Weather.setChecked(state['Check_Weather'])
            if 'Path_Excel_Weather' in state:
                self.Path_Excel_Weather.setText(state['Path_Excel_Weather'])
            if 'Check_restoration' in state:
                self.Check_restoration.setChecked(state['Check_restoration'])
            if 'Path_Excel_Restauration' in state:
                self.Path_Excel_Restauration.setText(state['Path_Excel_Restauration'])
            if 'Check_Phenologic' in state:
                self.Check_Phenologic.setChecked(state['Check_Phenologic'])
            if 'Path_Excel_Phenologic' in state:
                self.Path_Excel_Phenologic.setText(state['Path_Excel_Phenologic'])
            if 'Check_hydrologic' in state:
                self.Check_hydrologic.setChecked(state['Check_hydrologic'])
            if 'Path_Excel_hydrologic' in state:
                self.Path_Excel_hydrologic.setText(state['Path_Excel_hydrologic'])
            if 'Check_Sediments' in state:
                self.Check_Sediments.setChecked(state['Check_Sediments'])
            if 'Path_Excel_Sediments' in state:
                self.Path_Excel_Sediments.setText(state['Path_Excel_Sediments'])
            if 'Check_geotechnical' in state:
                self.Check_geotechnical.setChecked(state['Check_geotechnical'])
            if 'Path_Excel_geotechnical' in state:
                self.Path_Excel_geotechnical.setText(state['Path_Excel_geotechnical'])
            if 'Check_Diffuse' in state:
                self.Check_Diffuse.setChecked(state['Check_Diffuse'])
            if 'Path_Excel_Diffuse' in state:
                self.Path_Excel_Diffuse.setText(state['Path_Excel_Diffuse'])
            if 'Check_DBO' in state:
                self.Check_DBO.setChecked(state['Check_DBO'])
            if 'Path_Excel_DBO' in state:
                self.Path_Excel_DBO.setText(state['Path_Excel_DBO'])
            if 'Check_Reaeration' in state:
                self.Check_Reaeration.setChecked(state['Check_Reaeration'])
            if 'Path_Excel_Reaeration' in state:
                self.Path_Excel_Reaeration.setText(state['Path_Excel_Reaeration'])
            if 'Check_EColi' in state:
                self.Check_EColi.setChecked(state['Check_EColi'])
            if 'Path_Excel_Ecoli' in state:
                self.Path_Excel_Ecoli.setText(state['Path_Excel_Ecoli'])
            if 'Check_Nitrogen' in state:
                self.Check_Nitrogen.setChecked(state['Check_Nitrogen'])
            if 'Path_Excel_Nitrogen' in state:
                self.Path_Excel_Nitrogen.setText(state['Path_Excel_Nitrogen'])
            if 'Check_Phosphorus' in state:
                self.Check_Phosphorus.setChecked(state['Check_Phosphorus'])
            if 'Path_Excel_Phosphorus' in state:
                self.Path_Excel_Phosphorus.setText(state['Path_Excel_Phosphorus'])

            # Restore Step 10 - Calibration Part 2
            if 'Check_Tcoliforms' in state:
                self.Check_Tcoliforms.setChecked(state['Check_Tcoliforms'])
            if 'Path_Excel_Tcoliforms' in state:
                self.Path_Excel_Tcoliforms.setText(state['Path_Excel_Tcoliforms'])
            if 'Check_Turbidity' in state:
                self.Check_Turbidity.setChecked(state['Check_Turbidity'])
            if 'Path_Excel_Turbidity' in state:
                self.Path_Excel_Turbidity.setText(state['Path_Excel_Turbidity'])
            if 'Check_Conductividad' in state:
                self.Check_Conductividad.setChecked(state['Check_Conductividad'])
            if 'Path_Excel_Conductividad' in state:
                self.Path_Excel_Conductividad.setText(state['Path_Excel_Conductividad'])
            if 'Check_SST' in state:
                self.Check_SST.setChecked(state['Check_SST'])
            if 'Path_Excel_SST' in state:
                self.Path_Excel_SST.setText(state['Path_Excel_SST'])
            if 'Check_T_Correction' in state:
                self.Check_T_Correction.setChecked(state['Check_T_Correction'])
            if 'Path_Excel_T_Correction' in state:
                self.Path_Excel_T_Correction.setText(state['Path_Excel_T_Correction'])
            if 'Check_Temperature' in state:
                self.Check_Temperature.setChecked(state['Check_Temperature'])
            if 'Path_Excel_Temperature' in state:
                self.Path_Excel_Temperature.setText(state['Path_Excel_Temperature'])
            if 'Check_ADZQUASAR' in state:
                self.Check_ADZQUASAR.setChecked(state['Check_ADZQUASAR'])
            if 'Path_Excel_ADZQUASAR' in state:
                self.Path_Excel_ADZQUASAR.setText(state['Path_Excel_ADZQUASAR'])
            if 'Check_Ph' in state:
                self.Check_Ph.setChecked(state['Check_Ph'])
            if 'Path_Excel_Ph' in state:
                self.Path_Excel_Ph.setText(state['Path_Excel_Ph'])

            # Restore Base Files
            if 'Check_Base_File' in state:
                self.Check_Base_File.setChecked(state['Check_Base_File'])
            if 'path_base_files' in state:
                self.path_base_files.setText(state['path_base_files'])

            # Restore current toolbox page
            if 'current_toolbox_index' in state:
                self.toolBox.setCurrentIndex(state['current_toolbox_index'])

            print("QSIGA_CAL: Project state loaded successfully")

        except Exception as e:
            print(f"Error loading project state: {e}")

    #### Funciones Step 1 creacion de proyecto #############################
    def select_output_folder(self):
        """Open a dialog to select the output folder."""
        folder = QtWidgets.QFileDialog.getExistingDirectory(self, "Select Output Folder")
        if folder:
            self.output_path.setText(folder)

    def create_project_folders(self):
        """Create the project folders based on user input and move to the next widget."""
        name_project = self.name_project.text()
        name_scenario = self.name_scenario.text()
        output_path = self.output_path.text()

        if name_project and output_path:
            create_outputs_folders(output_path, name_project, name_scenario)
            QtWidgets.QMessageBox.information(self, "Success", "Project folders created successfully.")
            # Move to the next widget
            self.toolBox.setCurrentIndex(1)
        else:
            QtWidgets.QMessageBox.warning(self, "Input Error", "Please provide project name and output path.")

    #### Funciones Step 2 Delimitacion Cuenca #############################

    def set_coordinates(self, point):
        self.X_coor.setText(str(point.x()))
        self.Y_coor.setText(str(point.y()))

    def activate_point_tool(self, event):
        self.iface.mapCanvas().setMapTool(self.point_tool)

    def select_dem(self):
        """Select DEM file and load it into QGIS."""
        dem_path, _ = QFileDialog.getOpenFileName(self, "Select DEM file", "", "TIF Files (*.tif)")
        if dem_path:
            self.Path_Dem.setText(dem_path)  # Actualizar QLineEdit Path_Dem
            self.load_raster_layer(dem_path, "DEM")

    def load_raster_layer(self, path, layer_name):
        """Load raster layer into QGIS."""
        layer = QgsRasterLayer(path, layer_name)
        if not layer.isValid():
            QMessageBox.critical(self, "Error", f"Failed to load layer {layer_name}.")
        else:
            QgsProject.instance().addMapLayer(layer)

    def run_dem_processes(self):
        """Run DEM processes and save results."""
        dem_path = self.Path_Dem.text()
        threshold = float(self.Threshold.text())
        output_folder = os.path.join(self.output_path.text(), self.name_project.text(), 'temp',
                                     '01_Delimitacion_Cuenca')

        if not os.path.exists(output_folder):
            os.makedirs(output_folder)

        grid = Grid.from_raster(dem_path, data_name='dem')
        raw_dem = grid.read_raster(dem_path)

        # flooded_dem = grid.fill_depressions(raw_dem)
        # dem = grid.resolve_flats(flooded_dem)
        dem = raw_dem
        dirmap = (8, 9, 6, 3, 2, 1, 4, 7)
        flow_dir = grid.flowdir(dem, dirmap=dirmap)

        flow_accum = grid.accumulation(flow_dir, dirmap=dirmap)

        pixel_area = (grid.viewfinder.dy_dx[0] * grid.viewfinder.dy_dx[0]) / 1E6
        accum_area = flow_accum * pixel_area
        network = (accum_area > threshold) * 1

        # Save results
        dem_path = os.path.join(output_folder, 'DEM.tif')
        flow_dir_path = os.path.join(output_folder, 'FlowDir.tif')
        flow_accum_path = os.path.join(output_folder, 'FlowAccum.tif')
        flow_accum_areas_path = os.path.join(output_folder, 'FlowAccumarea.tif')
        network_path = os.path.join(output_folder, 'Network.tif')

        grid.to_raster(dem, dem_path)
        grid.to_raster(flow_dir, flow_dir_path)
        grid.to_raster(flow_accum, flow_accum_path)
        grid.to_raster(accum_area, flow_accum_areas_path)
        grid.to_raster(network, network_path)

        # Load FlowAccum and Network into QGIS
        flow_accum_layer = QgsRasterLayer(flow_accum_path, "Flow Accumulation")
        network_layer = QgsRasterLayer(network_path, "Network")

        # if flow_accum_layer.isValid():
        #     QgsProject.instance().addMapLayer(flow_accum_layer)

        if network_layer.isValid():
            shader = QgsRasterShader()
            color_ramp = QgsColorRampShader()
            color_ramp.setColorRampType(QgsColorRampShader.Interpolated)
            color_ramp_item_list = [QgsColorRampShader.ColorRampItem(1, QColor(0, 0, 255))]
            color_ramp.setColorRampItemList(color_ramp_item_list)
            shader.setRasterShaderFunction(color_ramp)
            renderer = QgsSingleBandPseudoColorRenderer(network_layer.dataProvider(), 1, shader)
            network_layer.setRenderer(renderer)
            QgsProject.instance().addMapLayer(network_layer)

    def run_basin_processes(self):
        """Run basin delineation processes."""
        x_coor = float(self.X_coor.text())
        y_coor = float(self.Y_coor.text())
        output_folder = os.path.join(self.output_path.text(), self.name_project.text(), 'temp',
                                     '01_Delimitacion_Cuenca')

        dem_path = os.path.join(output_folder, 'DEM.tif')
        flow_dir_path = os.path.join(output_folder, 'FlowDir.tif')

        grid = Grid.from_raster(dem_path, data_name='dem')
        flow_dir = grid.read_raster(flow_dir_path)

        col, row = grid.nearest_cell(x_coor, y_coor, snap="center")
        x_new = grid.extent[0] + (col * grid.viewfinder.dy_dx[0])
        y_new = grid.extent[3] - (row * grid.viewfinder.dy_dx[0])

        watershed = grid.catchment(x=x_new, y=y_new, fdir=flow_dir, dirmap=(8, 9, 6, 3, 2, 1, 4, 7),
                                   xytype='coordinate')
        watershed = watershed * 1

        # Save and load watershed
        watershed_path = os.path.join(output_folder, 'Watershed.tif')
        grid.to_raster(watershed, watershed_path)

        watershed_shapefile = os.path.join(output_folder, 'Watershed.shp')
        processing.run("gdal:polygonize", {
            'INPUT': watershed_path,
            'BAND': 1,
            'FIELD': 'DN',
            'EIGHT_CONNECTEDNESS': False,
            'EXTRA': '',
            'OUTPUT': watershed_shapefile
        })

        watershed_layer = QgsVectorLayer(watershed_shapefile, "Watershed", "ogr")
        if watershed_layer.isValid():
            symbol = QgsFillSymbol.createSimple({'color_border': 'red', 'width_border': '1', 'style': 'no'})
            watershed_layer.renderer().setSymbol(symbol)
            QgsProject.instance().addMapLayer(watershed_layer)
        else:
            self.show_message("Error", "Failed to load Watershed layer.")

    def show_message(self, title, message):
        """Show a message box."""
        QtWidgets.QMessageBox.information(self, title, message)

    def move_to_topologia(self):
        """Move to the next widget Topologia."""
        self.toolBox.setCurrentIndex(2)
    #### Funciones Step 3 Topologia #############################
    def select_shp(self, line_edit):
        shp_path, _ = QFileDialog.getOpenFileName(self, "Select SHP file", "", "SHP Files (*.shp)")
        if shp_path:
            line_edit.setText(shp_path)
            self.load_vector_layer(shp_path, line_edit.objectName())

    def select_raster_file(self, line_edit):
        raster_path, _ = QFileDialog.getOpenFileName(self, "Select Raster file", "", "TIF Files (*.tif)")
        if raster_path:
            line_edit.setText(raster_path)
            self.load_raster_layer(raster_path, line_edit.objectName())

    def load_vector_layer(self, path, layer_name="Reservoir"):
        layer = QgsVectorLayer(path, layer_name, "ogr")
        if not layer.isValid():
            QMessageBox.critical(self, "Error", f"Failed to load layer {layer_name}.")
        else:
            QgsProject.instance().addMapLayer(layer)

    def toggle_topology_inputs(self):
        self.Path_Shp_Embalse.setEnabled(self.Check_Embalse.isChecked())
        self.Button_Load_Embalse.setEnabled(self.Check_Embalse.isChecked())

        self.Path_Shp_Cabeceras.setEnabled(self.Check_Cabeceras.isChecked())
        self.Button_Load_Cabeceras.setEnabled(self.Check_Cabeceras.isChecked())

        self.Path_Raster_Nbs.setEnabled(self.Check_Nbs.isChecked())
        self.Button_Load_NbS.setEnabled(self.Check_Nbs.isChecked())

    def run_topology_processes(self):
        output_folder = os.path.join(self.output_path.text(), self.name_project.text(), 'temp', '02_Topologia')

        if not os.path.exists(output_folder):
            os.makedirs(output_folder)

        name_project = self.name_project.text()
        x_coor = float(self.X_coor.text())
        y_coor = float(self.Y_coor.text())
        name_scenario = self.name_scenario.text()
        threshold = float(self.Threshold.text())

        embalse_path = self.Path_Shp_Embalse.text() if self.Check_Embalse.isChecked() else None
        cabeceras_path = self.Path_Shp_Cabeceras.text() if self.Check_Cabeceras.isChecked() else None
        nbs_path = self.Path_Raster_Nbs.text() if self.Check_Nbs.isChecked() else None

        dem_path = self.Path_Dem.text()
        flow_dir_path = os.path.join(self.output_path.text(), self.name_project.text(), 'temp',
                                     '01_Delimitacion_Cuenca', 'FlowDir.tif')
        flow_accum_path = os.path.join(self.output_path.text(), self.name_project.text(), 'temp',
                                       '01_Delimitacion_Cuenca', 'FlowAccumarea.tif')

        if embalse_path:
            embalse_raster_path = os.path.join(self.output_path.text(), self.name_project.text(), 'temp',
                                               'Reservoir.tif')
            # Generar raster binario de embalse (Value='' genera 1 para embalses, 0 para resto)
            PolyponToRaster(PathShp=embalse_path, PathOutput=embalse_raster_path, PathRaster=dem_path, Value='')
        else:
            embalse_raster_path = None

        # Define the criterion based on the CheckBox selections
        criteria = 1  # Default criteria
        if self.Check_Nbs.isChecked() and self.Check_Embalse.isChecked() and self.Check_Cabeceras.isChecked():
            criteria = 4
        elif self.Check_Embalse.isChecked() and self.Check_Cabeceras.isChecked():
            criteria = 3
        elif self.Check_Embalse.isChecked():
            criteria = 2

        from ..common_functions.BuildingTopology import build_topology

        try:
            build_topology(dem_path, flow_dir_path, flow_accum_path, embalse_raster_path, cabeceras_path, nbs_path,
                           x_coor, y_coor, name_scenario,name_project, output_folder, criteria,threshold)

            # Copy the topology file to the specified path
            from shutil import copyfile
            topology_file = os.path.join(output_folder, f'Topology_{name_project}.txt')
            output_pth = os.path.join(self.output_path.text(), self.name_project.text(), 'entradas', 'topologia')
            if not os.path.exists(output_pth):
                os.makedirs(output_pth)
            copyfile(topology_file, os.path.join(output_pth, f'Topology_{name_project}.txt'))

            self.show_message("Success", "Topology processes completed successfully.")
        except Exception as e:
            self.show_message("Error", f"Topology process failed: {e}")

    def move_to_series_de_tiempo(self):
        self.toolBox.setCurrentIndex(3)
    #### Funciones Step 4 Series de Tiempo #############################
    def load_shapefile_layer(self):
        shapefile_path, _ = QFileDialog.getOpenFileName(self, "Select stations file", "",
                                                        "Supported Files (*.shp *.xlsx *.xls);;SHP Files (*.shp);;Excel Files (*.xlsx *.xls)")
        if shapefile_path:
            self.Path_Shp_Stations.setText(shapefile_path)
            # Only add to QGIS if it's a shapefile
            if shapefile_path.endswith('.shp'):
                layer = QgsVectorLayer(shapefile_path, "Estaciones", "ogr")
                if not layer.isValid():
                    QMessageBox.critical(self, "Error", "Failed to load stations layer.")
                else:
                    QgsProject.instance().addMapLayer(layer)
            elif shapefile_path.endswith(('.xlsx', '.xls')):
                self.show_message("Success", "Excel file with stations loaded successfully.")

    def load_excel_file(self):
        excel_path, _ = QFileDialog.getOpenFileName(self, "Select Excel file", "", "Excel Files (*.xlsx *.xls)")
        if excel_path:
            self.Path_excel_time_series.setText(excel_path)

    def run_series_processes(self):
        try:
            output_pth = os.path.join(self.output_path.text(), self.name_project.text(), 'entradas/')
            if not os.path.exists(output_pth):
                os.makedirs(output_pth)

            path_meta = self.Path_Shp_Stations.text()
            path_df = self.Path_excel_time_series.text()
            variables = ['PV', 'Tamax', 'Tamin', 'RS', 'HR', 'Ux', 'Uy', 'TasRest', 'Descarga', 'Captacion']

            from ..common_functions.ficheros import Ficheros
            import pandas as pd
            import geopandas as gpd

            ficheros_instance = Ficheros(ruta_cuenca_SIGA=output_pth)

            # Leer metadata de estaciones (shapefile o Excel)
            if path_meta.endswith('.shp'):
                df_meta_full = gpd.read_file(path_meta)
            elif path_meta.endswith(('.xlsx', '.xls')):
                df_meta_full = pd.read_excel(path_meta)
            else:
                raise ValueError("Station file format not supported. Use .shp, .xlsx or .xls")

            # Contador de series exportadas
            series_exportadas = 0
            errores = []

            for var in variables:
                try:
                    # Verify if the field exists in the stations file
                    if var not in df_meta_full.columns:
                        continue

                    # Intentar leer la hoja de Excel (puede no existir para variables opcionales)
                    df_int = pd.read_excel(path_df, sheet_name=var, index_col=0).interpolate()

                    df_int = df_int.apply(pd.to_numeric, errors='coerce')
                    if var == 'PV':
                        df_in = df_int/1000
                    elif var == 'HR':
                        df_in = df_int/100
                    else:
                        df_in = df_int

                    # Filtrar metadata para esta variable (aceptar 1, 1.0, True, etc.)
                    df_meta = df_meta_full[df_meta_full[var].isin([1, 1.0, True, '1'])].copy()

                    # Si no hay estaciones con esta variable, saltar
                    if len(df_meta) == 0:
                        continue

                    # Mapeo de nombres de variables a nombres en inglés
                    nombre_map = {
                        'PV': 'TimeSeries_PV.txt',
                        'Tamax': 'TimeSeries_Tamax.txt',
                        'Tamin': 'TimeSeries_Tamin.txt',
                        'RS': 'TimeSeries_RS.txt',
                        'HR': 'TimeSeries_HR.txt',
                        'Ux': 'TimeSeries_Ux.txt',
                        'Uy': 'TimeSeries_Uy.txt',
                        'TasRest': 'TimeSeries_TasRest.txt',
                        'Descarga': 'TimeSeries_Qdesc.txt',
                        'Captacion': 'TimeSeries_Qcapt.txt'
                    }
                    nombre_archivo = nombre_map.get(var, 'series_' + var + '.txt')
                    ficheros_instance.ExportarSeriesSIGA(df=df_in, df_metadatos=df_meta, nombre_archivo_serie=nombre_archivo)
                    series_exportadas += 1

                except Exception as e:
                    # Si la hoja no existe o hay un error, guardar para reporte
                    errores.append(f"{var}: {str(e)}")
                    continue

            # Mostrar resultado final
            if series_exportadas > 0:
                mensaje = f"{series_exportadas} time series exported successfully."
                if len(errores) > 0:
                    mensaje += f"\nSome variables could not be exported (check that sheets exist in Excel and fields exist in stations file)."
                self.show_message("Success", mensaje)
            else:
                self.show_message("Warning", "No time series exported.\nVerify that:\n- Sheets exist in Excel\n- Fields exist in stations file (Shapefile or Excel)\n- There are stations with value 1 in each field")

        except Exception as e:
            self.show_message("Error", f"Time series process failed: {e}")

    def move_to_mapas(self):
        """Move to the next widget Mapas."""
        self.toolBox.setCurrentIndex(4)

    #### Funciones Step 5 Mapas  #############################

    def add_raster_to_qgis(self, raster_path):
        layer = QgsRasterLayer(raster_path, os.path.basename(raster_path))
        if not layer.isValid():
            self.show_message("Error", f"Failed to load raster layer: {raster_path}")
        else:
            QgsProject.instance().addMapLayer(layer)

    def load_and_resample_raster(self, path_line_edit, output_filename):
        raster_path, _ = QFileDialog.getOpenFileName(self, "Select raster file", "", "TIF Files (*.tif)")
        if raster_path:
            path_line_edit.setText(raster_path)
            output_path = os.path.join(self.output_path.text(), self.name_project.text(), 'entradas', 'mapas',
                                       self.name_scenario.text(), output_filename)
            resample_to_match(raster_path, self.Path_Dem.text(), output_path)
            self.add_raster_to_qgis(output_path)
            self.show_message("Success", f"Raster {output_filename} loaded and processed successfully.")

    def divide_raster_values_by_100(self, raster_path):
        """Divide raster values by 100."""
        with rasterio.open(raster_path, 'r+') as dataset:
            for i in range(1, dataset.count + 1):
                data = dataset.read(i)
                data = data / 100.0
                dataset.write(data, i)

    def divide_raster_values_by_1000(self, raster_path):
        """Divide raster values by 1000."""
        with rasterio.open(raster_path, 'r+') as dataset:
            for i in range(1, dataset.count + 1):
                data = dataset.read(i)
                data = data / 1000.0
                dataset.write(data, i)


    def load_and_resample_raster_from_zip(self, zip_path, zip_internal_path, output_filename):
        """Load raster from zip, resample and divide by 100."""
        zip_file_path = 'DATABASE.zip'
        # path_raster_global = f"zip://{zip_file_path}!/{zip_internal_path}"
        path_raster_global = f'/vsizip/{zip_path}/{zip_internal_path}'
        output_path = os.path.join(self.output_path.text(), self.name_project.text(), ''
                                                                                      'entradas', 'mapas',
                                   self.name_scenario.text(), output_filename)
        try:
            resample_to_match(path_raster_global, self.Path_Dem.text(), output_path)

            self.divide_raster_values_by_100(output_path)
            self.show_message("Success",
                              f"Raster {output_filename} loaded, processed and divided successfully from zip.")
            self.add_raster_to_qgis(output_path)

        except Exception as e:
            self.show_message("Error", f"Error loading and processing raster from zip: {e}")

    def load_and_resample_raster_from_zip_op2(self, zip_path, zip_internal_path, output_filename):
        """Load raster from zip, resample and divide by 100."""
        zip_file_path = 'DATABASE.zip'
        # path_raster_global = f"zip://{zip_file_path}!/{zip_internal_path}"
        path_raster_global = f'/vsizip/{zip_path}/{zip_internal_path}'
        output_path = os.path.join(self.output_path.text(), self.name_project.text(), ''
                                                                                      'entradas', 'mapas',
                                   self.name_scenario.text(), output_filename)
        try:
            resample_to_match(path_raster_global, self.Path_Dem.text(), output_path)
            self.divide_raster_values_by_1000(output_path)
            self.show_message("Success",
                              f"Raster {output_filename} loaded, processed and divided successfully from zip.")
            self.add_raster_to_qgis(output_path)

        except Exception as e:
            self.show_message("Error", f"Error loading and processing raster from zip: {e}")

    def load_lulc_raster(self):
        raster_path, _ = QFileDialog.getOpenFileName(self, "Select raster or shapefile file", "",
                                                     "TIF Files (*.tif);;SHP Files (*.shp)")
        if raster_path:
            self.Path_Raster_LULC.setText(raster_path)

#                self.add_raster_to_qgis(output_path)
            if raster_path.endswith('.tif'):
                # Load and modify raster
                raster = gdal.Open(raster_path, gdal.GA_Update)
                band = raster.GetRasterBand(1)
                arr = band.ReadAsArray()

                # Values to replace
                values_to_replace = [411, 412, 413, 421, 422, 423, 511, 512, 513, 514, 521, 523,0]
                for value in values_to_replace:
                    arr[arr == value] = 231  # Replace specified values with 231

                # Write modified array to raster
                band.WriteArray(arr)

                # Release raster from memory
                band.FlushCache()
                raster = None

                # Save modified raster as temporary file with integer data type
                modified_raster_path = os.path.join(self.output_path.text(), self.name_project.text(), 'entradas',
                                                    'mapas',
                                                    self.name_scenario.text(), "CLC_modified.tif")
                gdal.Translate(modified_raster_path, raster_path, outputType=gdal.GDT_Int16)

                # Now use the modified file in the resample function
                output_path = os.path.join(self.output_path.text(), self.name_project.text(), 'entradas', 'mapas',
                                           self.name_scenario.text(), "CLC.tif")
                resample_to_match(modified_raster_path, self.Path_Dem.text(), output_path, integer_output=True)

                # Success message and load to QGIS
                self.show_message("Success", "LULC Raster loaded, modified and processed successfully.")
                self.add_raster_to_qgis(output_path)
            elif raster_path.endswith('.shp'):
                # Convert SHP to raster
                output_path = os.path.join(self.output_path.text(), self.name_project.text(), 'entradas', 'mapas',
                                           self.name_scenario.text(), "CLC.tif")

                PolyponToRaster(PathShp =raster_path,PathOutput = output_path,PathRaster = self.Path_Dem.text(),Value = "Code" )
                self.show_message("Success", "LULC Shapefile loaded and converted to raster successfully.")
                self.add_raster_to_qgis(output_path)

    def create_usle_p_raster(self):

        output_path = os.path.join(self.output_path.text(), self.name_project.text(), 'entradas', 'mapas',
                                   self.name_scenario.text(), "P_usle.tif")

        self.create_raster_filled_with_value(output_path, 1)
        self.add_raster_to_qgis(output_path)
        self.show_message("Success", "USLE-P Raster created successfully.")

    def run_erodability(self):
        PathK = os.path.join(self.output_path.text(), self.name_project.text(), 'entradas', 'mapas',
                             self.name_scenario.text(), 'K_usle.tif')
        try:
            # Definir rutas base de los rasters en la carpeta del proyecto
            base_path = os.path.join(self.output_path.text(), self.name_project.text(), 'entradas', 'mapas',
                                    self.name_scenario.text())

            # Buscar archivos en carpeta del proyecto primero, sino usar los campos del formulario
            path_arenas = os.path.join(base_path, 'arenas.tif') if os.path.exists(os.path.join(base_path, 'arenas.tif')) else self.Path_Raster_arenas.text()
            path_limos = os.path.join(base_path, 'limos.tif') if os.path.exists(os.path.join(base_path, 'limos.tif')) else self.Path_Raster_limos.text()
            path_arcillas = os.path.join(base_path, 'arcillas.tif') if os.path.exists(os.path.join(base_path, 'arcillas.tif')) else self.Path_Raster_arcillas.text()
            path_MO = os.path.join(base_path, 'MO.tif') if os.path.exists(os.path.join(base_path, 'MO.tif')) else self.Path_Raster_OM.text()

            # Verificar que todos los archivos existen
            archivos_necesarios = [
                ('Arenas', path_arenas),
                ('Limos', path_limos),
                ('Arcillas', path_arcillas),
                ('Materia Orgánica', path_MO)
            ]

            archivos_faltantes = []
            for nombre, ruta in archivos_necesarios:
                if not ruta or not os.path.exists(ruta):
                    archivos_faltantes.append(nombre)

            if archivos_faltantes:
                self.show_message("Error", f"Missing the following files:\n" + "\n".join(archivos_faltantes) + "\n\nPlease load soil texture and organic matter maps first.")
                return

            Erodability(PathK, self.Path_Dem.text(), path_arenas, path_limos, path_arcillas, path_MO)
            self.add_raster_to_qgis(PathK)
            self.show_message("Success", "Erodability USLE-K calculated successfully.")
        except Exception as e:
            self.show_message("Error", f"Error calculating Erodability USLE-K: {e}")

    def move_to_next_step(self):
        self.toolBox.setCurrentIndex(5)

    #### Funciones Step 6 Mapas 1 ############################
    def create_raster_filled_with_value(self, output_path, value):
        with rasterio.open(self.Path_Dem.text()) as src:
            meta = src.meta.copy()
            data = src.read(1)
            data.fill(value)

            with rasterio.open(output_path, 'w', **meta) as dst:
                dst.write(data, 1)

    def create_sequential_raster(self, input_raster_path, output_raster_path):
        with rasterio.open(input_raster_path) as src:
            meta = src.meta.copy()
            data = src.read(1)
            unique_values = np.unique(data)
            value_map = {old: new for new, old in enumerate(unique_values, start=1)}

            for old, new in value_map.items():
                data[data == old] = new

            with rasterio.open(output_raster_path, 'w', **meta) as dst:
                dst.write(data, 1)

    def load_paramos_raster(self):
        raster_path, _ = QFileDialog.getOpenFileName(self, "Load Raster or Shapefile", "",
                                                     "Raster files (*.tif *.img);;Shapefile (*.shp)")
        if raster_path:
            self.Path_Raster_Paramos.setText(raster_path)
            output_path = os.path.join(self.output_path.text(), self.name_project.text(), 'entradas', 'mapas',
                                       self.name_scenario.text(), 'paramo.tif')
            if raster_path.endswith('.shp'):
                PolyponToRaster(raster_path, output_path, self.Path_Dem.text(), "Code")
            else:
                resample_to_match(raster_path, self.Path_Dem.text(), output_path)
            self.show_message("Success", "Paramos Raster loaded, modified and processed successfully.")
            self.add_raster_to_qgis(output_path)

    def create_idciclo_raster(self):
        output_path = os.path.join(self.output_path.text(), self.name_project.text(), 'entradas', 'mapas',
                                   self.name_scenario.text(), 'idCiclo.tif')
        self.create_raster_filled_with_value(output_path, 1)
        self.show_message("Success", "idCiclo Raster loaded, modified and processed successfully.")
        self.add_raster_to_qgis(output_path)

    def create_idq_raster(self):
        clc_raster_path = os.path.join(self.output_path.text(), self.name_project.text(), 'entradas', 'mapas',
                                       self.name_scenario.text(), 'CLC.tif')
        output_path = os.path.join(self.output_path.text(), self.name_project.text(), 'entradas', 'mapas',
                                   self.name_scenario.text(), 'idQ.tif')
        self.create_sequential_raster(clc_raster_path, output_path)
        self.show_message("Success", "idQ Raster loaded, modified and processed successfully.")
        self.add_raster_to_qgis(output_path)

    def create_prioridad_transicion_rasters(self):
        base_path = os.path.join(self.output_path.text(), self.name_project.text(), 'entradas', 'mapas',
                                 self.name_scenario.text())
        prioridad_path = os.path.join(base_path, 'prioridad.tif')
        transicion_path = os.path.join(base_path, 'transicion.tif')
        self.create_raster_filled_with_value(prioridad_path, 1)
        self.create_raster_filled_with_value(transicion_path, 1)
        self.show_message("Success", "Priority and Transition Rasters loaded, modified and processed successfully.")
        self.add_raster_to_qgis(prioridad_path)
        self.add_raster_to_qgis(transicion_path)

    #### Funciones Step 7 Muestreador  y Step 8 Modulos ############################

    #### Funciones Step 7 Muestreador ############################
    def add_layer_to_qgis(self, layer_path, layer_name):
        layer = QgsVectorLayer(layer_path, layer_name, "ogr")
        if not layer.isValid():
            self.show_message("Error", f"Failed to load layer: {layer_name}")
            return
        QgsProject.instance().addMapLayer(layer)

    def load_shp_points(self):
        file_path, _ = QFileDialog.getOpenFileName(self, "Select Points File", "",
                                                    "All Supported (*.shp *.xlsx *.xls *.csv);;Shapefile (*.shp);;Excel (*.xlsx *.xls);;CSV (*.csv)")
        if file_path:
            # Use get_base_csv_path to get correct folder
            path_out = self.get_base_csv_path('muestreador')
            if not os.path.exists(path_out):
                os.makedirs(path_out)
            multiformat_to_csv_muestreador(path_out, file_path)
            self.Path_shp_points.setText(file_path)
            # Only add to QGIS if it's a shapefile
            if file_path.endswith('.shp'):
                self.add_layer_to_qgis(file_path, "points")
            self.show_message("Success", "Points file loaded and converted to CSV successfully.")

    def load_shp_tramos(self):
        file_path, _ = QFileDialog.getOpenFileName(self, "Select River Stretches File", "",
                                                    "All Supported (*.shp *.xlsx *.xls *.csv);;Shapefile (*.shp);;Excel (*.xlsx *.xls);;CSV (*.csv)")
        if file_path:
            # Use get_base_csv_path to get correct folder
            path_out = self.get_base_csv_path('muestreador')
            if not os.path.exists(path_out):
                os.makedirs(path_out)
            multiformat_to_csv_muestreador(path_out, file_path)
            self.Path_shp_tramos.setText(file_path)
            # Only add to QGIS if it's a shapefile
            if file_path.endswith('.shp'):
                self.add_layer_to_qgis(file_path, "stretch of river")
            self.show_message("Success", "River stretches file loaded and converted to CSV successfully.")

    def run_muestreador(self):
        output_pth = os.path.join(self.output_path.text(), self.name_project.text(), 'entradas/')
        name_scenario = self.name_scenario.text()
        ficheros_instance = Ficheros(ruta_cuenca_SIGA=output_pth, archivo_muestreador=f'Sampler_{name_scenario}.txt')
        # Use get_base_csv_path to get correct folder
        path = self.get_base_csv_path('muestreador')
        path_json = os.path.join(os.path.dirname(os.path.dirname(__file__)), 'common_functions')
        with open(rf'{path_json}/Diccionario_ficheros.json') as json_file:
            diccionarios_ficheros = json.load(json_file)
        ficheros_instance.crear_archivo_muestreador(diccionarios_ficheros['dic_muestreador'], path)
        self.show_message("Success", "Muestreador processes completed successfully.")


    #### Funciones Step 8 Modulo ############################

    def load_mov_mass(self):
        file_path, _ = QFileDialog.getOpenFileName(self, "Select Mass Movements File", "",
                                                    "All Supported (*.xlsx *.xls *.csv *.shp);;Excel (*.xlsx *.xls);;CSV (*.csv);;Shapefile (*.shp)")
        if file_path:
            self.Path_excel_Mov_mass.setText(file_path)

    def load_vertimientos(self):
        file_path, _ = QFileDialog.getOpenFileName(self, "Select Discharges File", "",
                                                    "All Supported (*.xlsx *.xls *.csv *.shp);;Excel (*.xlsx *.xls);;CSV (*.csv);;Shapefile (*.shp)")
        if file_path:
            self.Path_excel_Vertimientos.setText(file_path)

    def load_boundary(self):
        file_path, _ = QFileDialog.getOpenFileName(self, "Select Boundary Conditions File", "",
                                                    "All Supported (*.xlsx *.xls *.csv *.shp);;Excel (*.xlsx *.xls);;CSV (*.csv);;Shapefile (*.shp)")
        if file_path:
            self.Path_excel_boundary.setText(file_path)

    def load_ciclos(self):
        file_path, _ = QFileDialog.getOpenFileName(self, "Select Cycles File", "",
                                                    "All Supported (*.xlsx *.xls *.csv *.shp);;Excel (*.xlsx *.xls);;CSV (*.csv);;Shapefile (*.shp)")
        if file_path:
            self.Path_excel_Ciclos.setText(file_path)

    def run_modulos(self):
        output_pth = os.path.join(self.output_path.text(), self.name_project.text(), 'entradas/')
        ficheros = Ficheros(ruta_cuenca_SIGA=output_pth)

        # Procesar Movimientos en Masa
        file_path_mov_mass = self.Path_excel_Mov_mass.text()
        if file_path_mov_mass:
            df = read_multiformat_file(file_path_mov_mass)

            # Asegurarse de que la columna de fecha se transforme en Año, Mes y Día
            if 'Fecha' in df.columns:
                df['Fecha'] = pd.to_datetime(df['Fecha'])
                df['Año'] = df['Fecha'].dt.year
                df['Mes'] = df['Fecha'].dt.month
                df['Día'] = df['Fecha'].dt.day
                df.drop(columns=['Fecha'], inplace=True)

            # Reordenar columnas para asegurar que Año, Mes y Día estén al principio
            column_order = ['Año', 'Mes', 'Día'] + [col for col in df.columns if col not in ['Año', 'Mes', 'Día']]
            df = df[column_order]

            # Crear el diccionario necesario
            dic_movmasa = {
                'n_deslizamientos': str(len(df)),
                'datos_faltantes': '-9999',
                'datos': df
            }
            # Crear el archivo de salida
            ficheros.crear_archivo_movmasa(dic_movmasa)

        # Procesar Vertimientos
        file_path_vertimientos = self.Path_excel_Vertimientos.text()
        if file_path_vertimientos:
            df_vertimientos = read_multiformat_file(file_path_vertimientos)

            # Crear el diccionario necesario para Vertimientos
            dic_vertimientos = {
                'n_puntos': str(len(df_vertimientos)),
                'datos_faltantes': '-9999',
                'datos': df_vertimientos
            }

            # Crear el archivo de salida Vertimientos
            nombre_proyecto = self.name_project.text()
            ficheros.crear_archivo_vertimientos(dic_vertimientos, nombre_proyecto)

        # Procesar Ciclos
        file_path_ciclos = self.Path_excel_Ciclos.text()
        if file_path_ciclos:
            df_ciclos = read_multiformat_file(file_path_ciclos)

            # Crear el diccionario necesario para Ciclos
            dic_ciclos = {
                'VARIABLE': 'Vertimientos',
                'PERIODO EN DÍAS DEL CICLO': '366',
                'NÚMERO DE CICLOS REPRESENTADOS': str(len(df_ciclos.columns[1:])),
                'RESOLUCIÓN TEMPORAL EN DÍAS': '1',
                'MODELO A PARTIR DE VARIBLE SECUNDARIA': 'ninguno',
                'datos': df_ciclos
            }

            # Crear el archivo de salida para Ciclos
            ficheros.crear_archivo_ciclo_cargas(dic_ciclos)


        # Procesar condiciones de contorno
        file_path_boundary = self.Path_excel_boundary.text()
        if file_path_boundary:
            df_boundary = read_multiformat_file(file_path_boundary)

            # Crear el diccionario necesario para Vertimientos
            dic_boundary = {
                'n_puntos': str(len(df_boundary )),
                'datos_faltantes': '-9999',
                'Tipo_CondicionCotorno':'1',
                'datos': df_boundary
            }

            # Crear el archivo de salida Vertimientos
            ficheros.crear_archivo_condiciones_frontera(dic_boundary)



        self.show_message("Success", "Modules processed successfully.")

    #### Funciones Step 9 parametros calibracion parte 1 ############################
    def load_excel_file_cal(self, line_edit):
        file_path, _ = QFileDialog.getOpenFileName(self, "Select Calibration File", "",
                                                    "All Supported (*.xlsx *.xls *.csv);;Excel (*.xlsx *.xls);;CSV (*.csv)")
        if file_path:
            line_edit.setText(file_path)

    def convert_excel_to_csv(self, checkbox, line_edit, save_name):
        if checkbox.isChecked():
            file_path = line_edit.text()
            if file_path:
                try:
                    # Use read_multiformat_file to read both Excel and CSV
                    df = read_multiformat_file(file_path)

                    # Use get_base_csv_path to get correct folder
                    path_out = self.get_base_csv_path('calibracion')
                    if not os.path.exists(path_out):
                        os.makedirs(path_out)
                    csv_path = os.path.join(path_out, save_name)
                    df.to_csv(csv_path, index=False)
                    # self.show_message("Success", f"{save_name} has been saved successfully.")
                except Exception as e:
                    self.show_message("Error", f"Failed to convert {save_name}.\n\nError: {str(e)}")
            else:
                self.show_message("Error", f"Path for {save_name} is empty.")
        # else:
        #     self.show_message("Info", f"{save_name} is not selected.")

    def run_parametros_cal(self):
        try:
            # Show processing message
            self.show_message("Processing", "Converting calibration parameters (Part 1) to CSV files. Please wait...")

            # Convert files to CSV
            self.convert_excel_to_csv(self.Check_Weather, self.Path_Excel_Weather, '01_ModeloMeteorologico.csv')
            self.convert_excel_to_csv(self.Check_restoration, self.Path_Excel_Restauration, '02_Restauracion.csv')
            self.convert_excel_to_csv(self.Check_Phenologic, self.Path_Excel_Phenologic, '03_ModeloFenologico.csv')
            self.convert_excel_to_csv(self.Check_hydrologic, self.Path_Excel_hydrologic, '04_ModeloHidrologico.csv')
            self.convert_excel_to_csv(self.Check_Sediments, self.Path_Excel_Sediments, '05_ModeloSedimentologico.csv')
            self.convert_excel_to_csv(self.Check_geotechnical, self.Path_Excel_geotechnical, '06_ModeloGeotecnico.csv')
            self.convert_excel_to_csv(self.Check_Diffuse, self.Path_Excel_Diffuse, '07_CargasDifusas.csv')
            self.convert_excel_to_csv(self.Check_DBO, self.Path_Excel_DBO, '08_DBOCarbonicea.csv')
            self.convert_excel_to_csv(self.Check_Reaeration, self.Path_Excel_Reaeration, '09_Reaireacion.csv')
            self.convert_excel_to_csv(self.Check_EColi, self.Path_Excel_Ecoli, '10_EColi.csv')
            self.convert_excel_to_csv(self.Check_Nitrogen, self.Path_Excel_Nitrogen, '11_Nitrogeno.csv')
            self.convert_excel_to_csv(self.Check_Phosphorus, self.Path_Excel_Phosphorus, '12_Fosforo.csv')

            # Show success message
            self.show_message("Success", "Calibration parameters (Part 1) converted to CSV successfully.")

        except Exception as e:
            # Show error message if something fails
            self.show_message("Error", f"Failed to process calibration parameters (Part 1).\n\nError: {str(e)}")

    #### Funciones Step 10 parametros calibracion parte 2 ############################

    def run_parametros_cal2(self):
        try:
            # Show processing message
            self.show_message("Processing", "Converting calibration parameters to CSV files. Please wait...")

            # Convert Excel files to CSV
            self.convert_excel_to_csv(self.Check_Tcoliforms, self.Path_Excel_Tcoliforms, '13_ColiformesTotales.csv')
            self.convert_excel_to_csv(self.Check_Turbidity, self.Path_Excel_Turbidity, '14_Turbiedad.csv')
            self.convert_excel_to_csv(self.Check_Conductividad, self.Path_Excel_Conductividad, '15_ConductividadElectrica.csv')
            self.convert_excel_to_csv(self.Check_SST, self.Path_Excel_SST, '16_SolidosSuspendidosTotales.csv')
            self.convert_excel_to_csv(self.Check_T_Correction, self.Path_Excel_T_Correction, '17_CorreccionTemperatura.csv')
            self.convert_excel_to_csv(self.Check_Temperature, self.Path_Excel_Temperature, '18_Temperatura.csv')
            self.convert_excel_to_csv(self.Check_ADZQUASAR, self.Path_Excel_ADZQUASAR, '19_FactoresADZQUASAR.csv')
            self.convert_excel_to_csv(self.Check_Ph, self.Path_Excel_Ph, '20_FactorespH.csv')

            # Load JSON dictionary and create calibration file
            path_json = os.path.join(os.path.dirname(os.path.dirname(__file__)), 'common_functions')
            with open(rf'{path_json}/Diccionario_ficheros.json') as json_file:
                diccionarios_ficheros_cal = json.load(json_file)

            output_pth = os.path.join(self.output_path.text(), self.name_project.text(), 'entradas/')
            nombre_proyecto = self.name_project.text()
            ficheros_instance = Ficheros(ruta_cuenca_SIGA=output_pth, archivo_fact_cal=f'Parameters_{nombre_proyecto}.txt')

            # Use get_base_csv_path to get correct folder
            path_files = self.get_base_csv_path('calibracion')
            ficheros_instance.crear_archivo_factores_calibracion(diccionarios_ficheros_cal['dic_factores_calibracion'],
                                                                 path_files)

            # Show success message
            self.show_message("Success", f"Calibration parameters processed successfully.\n\nOutput file: Parameters_{nombre_proyecto}.txt")

        except Exception as e:
            # Show error message if something fails
            self.show_message("Error", f"Failed to process calibration parameters.\n\nError: {str(e)}")

    def close_plugin(self):
        """Cerrar el plugin cuando se presiona el botón Finish."""
        self.close()

    def closeEvent(self, event):
        self.closingPlugin.emit()
        event.accept()
