# -*- coding: utf-8 -*-
"""
/***************************************************************************
 Siga_step_04_PrioriDockWidget
                                 A QGIS plugin
 plugin that develops a prioritization scheme based on the results of the model and the total intervention of the territory with NBS
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2024-11-12
        git sha              : $Format:%H$
        copyright            : (C) 2024 by The Nature Conservancy
        email                : miguel.canon@tnc.org
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
"""

import os

from qgis.PyQt import QtGui, QtWidgets, uic
from qgis.PyQt.QtCore import pyqtSignal
from qgis.core import QgsRasterLayer, QgsProject
from PyQt5.QtWidgets import QFileDialog, QMessageBox
from qgis.utils import iface
from .functions.ficheros import Ficheros, create_outputs_folders, copiar_archivo
from .functions import Fuctions_Priority as Priority
import shutil
import pandas as pd
import rasterio
import numpy as np

FORM_CLASS, _ = uic.loadUiType(os.path.join(
    os.path.dirname(__file__), 'Siga_step_04_Priori_dockwidget_base.ui'))


class Siga_step_04_PrioriDockWidget(QtWidgets.QDockWidget, FORM_CLASS):

    closingPlugin = pyqtSignal()

    def __init__(self, parent=None):
        """Constructor."""
        super(Siga_step_04_PrioriDockWidget, self).__init__(parent)

        self.setupUi(self)
        self.iface = iface

        #### Step 1 creacion de proyecto #############################
        # Connect signals to slots
        self.select_output.clicked.connect(self.select_output_folder)
        self.Button_Step_s1.clicked.connect(self.create_folders)

        #### Step 2 Simulacion Base #############################

        self.Check_Files_1.clicked.connect(self.check_file_maps)
        self.Check_Files_cal.clicked.connect(self.check_file_cal)

        self.Create_File_Exe_B.clicked.connect(lambda: self.create_file_execution(
            self.name_scenario_initial.text(),
            self.name_Execution_Base.text(),
            self.start_date_s_b,
            self.end_date_s_b
        ))
        self.Run_Simulation_B.clicked.connect(lambda: self.Run_simulations(self.name_Execution_Base.text(), self.name_scenario_initial.text()))

        self.Button_Step_s2.clicked.connect(lambda: self.toolBox.setCurrentIndex(2))

        #### Step 3 Simulacion NBS #############################

        self.Create_folder_NbS.clicked.connect(self.Copy_maps_new_escenario)

        self.select_portafolio.clicked.connect(self.select_portafolio_data)

        self.select_portafolio_2.clicked.connect(self.select_table_t)

        self.Create_new_Lulc.clicked.connect(self.create_new_lulc)

        self.Create_File_Exe.clicked.connect(lambda: self.create_file_execution(
            self.name_scenario_Nbs.text(),
            self.name_Execution_Nbs.text(),
            self.start_date_s_nbs,
            self.end_date_s_nbs
        ))

        self.Run_Simulation_NbS.clicked.connect(
            lambda: self.Run_simulations(self.name_Execution_Nbs.text(), self.name_scenario_Nbs.text()))


        #### Step Priorizacion Portafolio #############################
        self.base_flow.toggled.connect(self.toggle_topology_inputs)
        self.Sediments.toggled.connect(self.toggle_topology_inputs)
        self.Nitrogen.toggled.connect(self.toggle_topology_inputs)
        self.Fosforo.toggled.connect(self.toggle_topology_inputs)
        self.Ecoli.toggled.connect(self.toggle_topology_inputs)

        self.Run_Extrat_Inputs.connect(self.Extrat_inputos_to_process)

        self.Run_CT_CE.connect(self.Process_CT_CE)







    #### Funciones Step 1 creacion de proyecto #############################
    def select_output_folder(self):
        # Abrir un diálogo para seleccionar la carpeta de salida
        output_path = QtWidgets.QFileDialog.getExistingDirectory(self, "Select Output Folder")
        if output_path:
            self.output_path.setText(output_path)

    def create_folders(self):
        # Obtener los valores de los campos de texto
        name_project = self.name_project.text()
        name_scenario = self.name_scenario.text()
        Name_Basin = self.Name_Basin.text()
        output_path = self.output_path.text()

        if name_project and output_path:
            # Definir las rutas
            NameProcessCal = os.path.join(output_path, name_project, 'temp', '05-Prioritization')

            # Crear las carpetas necesarias
            os.makedirs(NameProcessCal, exist_ok=True)
            folders = ['DATA','FIGURES','RESULTS']
            for folder in folders:
                new_filder = os.path.join(output_path, name_project, 'temp', '04-Calibration',folder)
                os.makedirs(new_filder, exist_ok=True)

            # Llamar a la función para crear las carpetas de salida
            create_outputs_folders(output_path, name_project, name_scenario)

            ruta_origen = os.path.join(os.path.dirname(__file__), 'bin', 'cnvrtr.exe')

            ruta_origen_exe = os.path.join(os.path.dirname(__file__), 'bin', 'SIGA.exe')
            ruta_destino = output_path + os.path.sep

            # Copiar el archivo necesario
            copiar_archivo(ruta_origen, ruta_destino)

            copiar_archivo(ruta_origen_exe, ruta_destino)

            QtWidgets.QMessageBox.information(self, "Success", "Folders created successfully!")
            # Move to the next widget
            self.toolBox.setCurrentIndex(1)
        else:
            QtWidgets.QMessageBox.warning(self, "Input Error", "Please provide project name and output path.")

    #### Funciones Step 2 simulacion base #############################
    def check_file_maps(self):
        # Obtener los valores de los campos de texto
        name_project = self.name_project.text()
        name_scenario_i = self.name_scenario_initial.text()
        Name_Basin = self.Name_Basin.text()
        output_path = self.output_path.text()
        directorio = os.path.join(output_path, name_project, 'entradas', 'mapas', name_scenario_i)

        # Lista de archivos esperados
        archivos_esperados = [
            'arcillas.tif', 'arenas.tif', 'CLC.tif', 'idCiclo.tif', 'idQ.tif',
            'ki.tif', 'limos.tif', 'MO.tif', 'P_usle.tif', 'paramo.tif',
            'prioridad.tif', 'Q5a.tif', 'transicion.tif', 'Zs.tif', 'K_usle.tif'
        ]

        # Verificar si el directorio existe
        if not os.path.isdir(directorio):
            QtWidgets.QMessageBox.warning(self, "Error", f"Directory {directorio} does not exist.")
            return

        # Listar archivos en el directorio
        archivos_directorio = set(os.listdir(directorio))

        # Verificar archivos faltantes
        archivos_faltantes = [archivo for archivo in archivos_esperados if archivo not in archivos_directorio]

        # Mensaje para el usuario
        if not archivos_faltantes:
            QtWidgets.QMessageBox.information(self, "Verified Files",
                                              "All files were found correctly.")
        else:
            archivos_faltantes_str = ', '.join(archivos_faltantes)
            QtWidgets.QMessageBox.warning(self, "Missing File",
                                          f"The following files are missing: {archivos_faltantes_str}.")

    def check_file_cal(self):
        # Obtener los valores de los campos de texto
        name_project = self.name_project.text()
        name_scenario_i = self.name_scenario_initial.text()
        Name_Basin = self.Name_Basin.text()
        output_path = self.output_path.text()
        calibration_file_name = self.name_calibration_file.text()

        # Definir el directorio de calibración
        directorio_cal = os.path.join(output_path, name_project, 'entradas', 'calibracion')

        # Verificar si el directorio existe
        if not os.path.isdir(directorio_cal):
            QtWidgets.QMessageBox.warning(self, "Error", f"The directory  {directorio_cal} does not exist.")
            return

        # Listar archivos en el directorio
        archivos_directorio = os.listdir(directorio_cal)

        # Verificar si el archivo de calibración está presente
        if calibration_file_name in archivos_directorio:
            QtWidgets.QMessageBox.information(self, "Verified Files",
                                              "Calibration file was found correctly.")
        else:
            QtWidgets.QMessageBox.warning(self, "Missing File",
                                          f"Calibration file '{calibration_file_name}' not found in the directory.")


    def create_file_execution(self,escenario,file_Exe,start_date, end_date):
        # Obtener los valores de los campos de texto
        name_project = self.name_project.text()
        name_scenario = escenario
        Name_Basin = self.Name_Basin.text()
        ProjectPath = self.output_path.text()
        calibration_file_name = self.name_calibration_file.text()
        DateStart = start_date.date().toString("yyyy-MM-dd")
        DateEnd = end_date.date().toString("yyyy-MM-dd")

        name_file_exe = file_Exe

        NameSIGAModel = 'Calidad'
        paso_temporal_dias = '1'
        modelo_geotecnico = '0'
        pH_cuencacaliente = '0'

        if NameSIGAModel == 'Hy':
            tipo_ejecucion = '1'
        elif NameSIGAModel == 'Sed':
            tipo_ejecucion = '2'
        else:
            tipo_ejecucion = '3'
            if (NameSIGAModel == 'WQ_NT') | (NameSIGAModel == 'WQ_NO') | (NameSIGAModel == 'WQ_NH4') | (
                    NameSIGAModel == 'WQ_NO3'):
                NameSIGAModel1 = 'WQ_N'
            elif (NameSIGAModel == 'WQ_PT') | (NameSIGAModel == 'WQ_PO') | (NameSIGAModel == 'WQ_PI'):
                NameSIGAModel1 = 'WQ_P'
            else:
                NameSIGAModel1 = NameSIGAModel

        NameSceExe = name_scenario
        fecha_inicio = ' '.join(DateStart.split('-'))
        fecha_fin = ' '.join(DateEnd.split('-'))
        archivo_topologia = f'Topology_{name_project}.txt'
        archivo_Tmin = 'series_Tamin.txt'
        archivo_Tmax = 'series_Tamax.txt'
        archivo_HR = 'series_HR.txt'
        archivo_RS = 'series_RS.txt'
        archivo_PV = 'series_PV.txt'
        archivo_Ux = 'series_Ux.txt'
        archivo_Uy = 'series_Uy.txt'
        archivo_Qdesc = 'NA'
        archivo_Qcapt = 'NA'
        archivo_Qarc = 'NA'
        archivo_Qlim = 'NA'
        archivo_Qare = 'NA'
        archivo_movmasa = 'NA'
        archivo_fact_cal = calibration_file_name
        archivo_muestreador = 'muestreador.txt'
        archivo_tasrest = 'series_TasRest.txt'
        archivo_vertimientos = 'vertimientos.txt'
        archivo_ciclo_cargas = 'ciclos.txt'
        archivo_condiciones_frontera = 'BoundaryCondition.txt'
        # Configurar clase de ficheros

        DicFic = Ficheros(ruta_cuenca_SIGA=os.path.join(ProjectPath, name_project, 'entradas' + os.path.sep),
                          archivo_ejecucion=name_file_exe,
                          escenario=NameSceExe,
                          fecha_inicio=fecha_inicio,
                          fecha_fin=fecha_fin,
                          paso_temporal_dias=paso_temporal_dias,
                          archivo_topologia=archivo_topologia,
                          archivo_Tmin=archivo_Tmin,
                          archivo_Tmax=archivo_Tmax,
                          archivo_HR=archivo_HR,
                          archivo_RS=archivo_RS,
                          archivo_PV=archivo_PV,
                          archivo_Ux=archivo_Ux,
                          archivo_Uy=archivo_Uy,
                          archivo_Qdesc=archivo_Qdesc,
                          archivo_Qcapt=archivo_Qcapt,
                          archivo_Qarc=archivo_Qarc,
                          archivo_Qlim=archivo_Qlim,
                          archivo_Qare=archivo_Qare,
                          archivo_movmasa=archivo_movmasa,
                          archivo_fact_cal=archivo_fact_cal,
                          archivo_muestreador=archivo_muestreador,
                          archivo_tasrest=archivo_tasrest,
                          archivo_vertimientos=archivo_vertimientos,
                          archivo_ciclo_cargas=archivo_ciclo_cargas,
                          archivo_condiciones_frontera=archivo_condiciones_frontera,
                          tipo_ejecucion=tipo_ejecucion,
                          modelo_geotecnico=modelo_geotecnico,
                          pH_cuencacaliente=pH_cuencacaliente)

        # Crear archivo de ejecución para calibración
        DicFic.crear_archivo_ejecucion()

        QtWidgets.QMessageBox.information(self, "Creation of execution file",
                                          "the file was created correctly.")

    def Run_simulations(self,file_Exe,escenario):

        QMessageBox.information(self, "Simulation to start", "Please keep wait until the process is finished.")
        name_project = self.name_project.text()
        name_file_exe = file_Exe
        name_scenario = escenario
        PathExeSIGA         = os.path.join('bin','SIGA.exe')
        ProjectPath = self.output_path.text()

        Priority.ExeSIGAModel_Priori(ProjectPath, name_project, name_file_exe, PathExeSIGA, name_scenario)

        QMessageBox.information(self, "Simulation Complete",   f"Scenario simulation: '{name_scenario}' is finished.")

    #### Funciones Step 3 simulacion NBS #############################
    def Copy_maps_new_escenario(self):


        name_project = self.name_project.text()
        name_scenario_i = self.name_scenario_initial.text()
        Name_Basin = self.Name_Basin.text()
        new_escenario = self.name_scenario_Nbs.text()
        output_path = self.output_path.text()


        origen = os.path.join(output_path, name_project, 'entradas', 'mapas', name_scenario_i)

        destino = os.path.join(output_path, name_project, 'entradas', 'mapas', new_escenario)

        lista_archivos = ['arcillas.tif', 'arenas.tif', 'idCiclo.tif', 'idQ.tif', 'ki.tif', 'limos.tif', 'MO.tif',
                          'P_usle.tif'
            , 'paramo.tif', 'prioridad.tif', 'Q5a.tif', 'transicion.tif', 'Zs.tif', 'K_usle.tif']

        os.makedirs(destino, exist_ok=True)

        archivos_copiados = []
        archivos_no_encontrados = []

        # Recorrer la lista de archivos especificada
        for archivo in lista_archivos:
            ruta_archivo_origen = os.path.join(origen, archivo)

            try:
                # Verificar si el archivo existe en el origen
                if os.path.exists(ruta_archivo_origen):
                    # Copiar el archivo al destino
                    shutil.copy2(ruta_archivo_origen, destino)
                    archivos_copiados.append(archivo)
                    print(f"Archivo '{archivo}' copiado exitosamente a {destino}.")
                else:
                    archivos_no_encontrados.append(archivo)
                    QtWidgets.QMessageBox.warning(self, "Error", f"file {archivo} not found.")

            except Exception as e:
                QtWidgets.QMessageBox.warning(self, "Error", f"An error occurred while copying the file  {archivo} not found.{e}")

        QtWidgets.QMessageBox.information(self, "Copy maps Files","All the .tif files were copied.")

    def load_raster_layer(self, path, layer_name):
        """Load raster layer into QGIS."""
        layer = QgsRasterLayer(path, layer_name)
        if not layer.isValid():
            QMessageBox.critical(self, "Error", f"File could not be loaded {layer_name}.")
        else:
            QgsProject.instance().addMapLayer(layer)

    def select_portafolio_data(self):

        dem_path, _ = QFileDialog.getOpenFileName(self, "select file portfolio", "", "Files .TIF (*.tif)")
        if dem_path:
            self.Portafolio_Path.setText(dem_path)  # Actualizar QLineEdit Path_Dem
            self.load_raster_layer(dem_path, "Portfolio")

    def select_table_t(self):

        excel_path, _ = QFileDialog.getOpenFileName(self, "Select Excel file", "",
                                                    "files excel (*.xlsx *.xls)")
        if excel_path:
            self.Table_Path.setText(excel_path)

    def create_new_lulc(self):

        QMessageBox.information(self, "Process to start", "Please keep wait until the process is finished.")
        name_project = self.name_project.text()
        name_scenario_i = self.name_scenario_initial.text()
        Name_Basin = self.Name_Basin.text()
        new_escenario = self.name_scenario_Nbs.text()
        output_path = self.output_path.text()

        # nuevos directorios portafolio y tabla
        ruta_sbn_raster =  self.Portafolio_Path.text()
        ruta_tabla = self.Table_Path.text()


        ruta_clc_inicial = os.path.join(output_path, name_project, 'entradas', 'mapas', name_scenario_i,'CLC.tif')

        ruta_salida = os.path.join(output_path, name_project, 'entradas', 'mapas', new_escenario,'CLC.tif')

        # Leer la tabla de reglas
        tabla = pd.read_excel(ruta_tabla, 'Transiciones_Table')
        print("Tabla leída correctamente.")

        # Crear un diccionario de mapeo basado en la tabla
        # La clave será (lucode, SbN) y el valor será lucode_end
        mapeo = {}
        for index, row in tabla.iterrows():
            clave = (row["lucode"], row["SbN"])
            mapeo[clave] = row["lucode_end"]

        print(f"Diccionario de mapeo creado: {mapeo}")

        # Leer los rasters de entrada
        with rasterio.open(ruta_clc_inicial) as src_clc, rasterio.open(ruta_sbn_raster) as src_sbn:
            clc = src_clc.read(1)  # Leer la banda 1 del CLC inicial
            sbn = src_sbn.read(1)  # Leer la banda 1 del raster de SbN
            perfil = src_clc.profile

        # Inicializar el raster de salida con los valores del CLC inicial
        clc_final = np.copy(clc)

        # Transformar los valores usando el diccionario de mapeo
        for (lucode, sbn_value), lucode_end in mapeo.items():
            # Asignar el nuevo valor donde coincidan el lucode y el valor de SbN
            mask = (clc == lucode) & (sbn == sbn_value)
            clc_final[mask] = lucode_end

        # Guardar el nuevo raster transformado
        perfil.update(dtype="int32")

        with rasterio.open(ruta_salida, "w", **perfil) as dst:
            dst.write(clc_final, 1)

        QMessageBox.information(self, "Process Complete",  f"New land cover and land use file generated.")

    # funciones step 5 indice
    def toggle_topology_inputs(self):
        self.w_bf.setEnabled(self.base_flow.isChecked())
        self.w_s.setEnabled(self.Sediments.isChecked())
        self.w_n.setEnabled(self.Nitrogen.isChecked())
        self.w_P.setEnabled(self.Fosforo.isChecked())
        self.w_ecoli.setEnabled(self.Ecoli.isChecked())

    def Extrat_inputos_to_process(self):

        name_project = self.name_project.text()
        name_scenario = self.name_scenario_initial.text()
        Name_Basin = self.Name_Basin.text()
        new_escenario = self.name_scenario_Nbs.text()
        output_path = self.output_path.text()



        rutaCuenca = os.path.join(output_path, name_project, 'entradas', 'topologia', 'Topology_Yaque_Norte_500.txt')
        rutaMapasBase = os.path.join(output_path, name_project, 'salidas', name_scenario, 'Simulacion_Base', 'mapas/')
        rutaMapasRestauracion = os.path.join(output_path, name_project, 'salidas', new_escenario,
                                             'Simulacion_' + new_escenario, 'mapas/')
        self.cuenca = pd.DataFrame()
        self.cuenca = Priority.muestreos_escenarios(rutaCuenca,rutaMapasBase,rutaMapasRestauracion,name_scenario,new_escenario)


    def Process_CT_CE(self):


        name_project = self.name_project.text()
        name_scenario = self.name_scenario_initial.text()
        Name_Basin = self.Name_Basin.text()
        new_escenario = self.name_scenario_Nbs.text()
        output_path = self.output_path.text()

        if self.base_flow.isChecked():
            self.cuenca = Priority.proceso_flujo_base(self.cuenca,name_scenario,new_escenario)
        elif self.Sediments.isChecked():
            self.cuenca = Priority.proceso_Sedimentos(self.cuenca,name_scenario,new_escenario)
        elif self.Ecoli.isChecked():
            self.cuenca = Priority.proceso_Ecoli(self.cuenca,name_scenario,new_escenario)
        elif self.Nitrogen.isChecked():
            self.cuenca = Priority.proceso_Nitrogeno(self.cuenca,name_scenario,new_escenario)
        elif self.Fosforo.isChecked():
            self.cuenca = Priority.proceso_fosforo(self.cuenca, name_scenario, new_escenario)




















    def closeEvent(self, event):
        self.closingPlugin.emit()
        event.accept()
