# -*- coding: utf-8 -*-
"""
/***************************************************************************
 Siga_Step_01_ConfigDockWidget
                                 A QGIS plugin
 This plugin generates the previous configuration for the execution of the model. 
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2024-09-23
        git sha              : $Format:%H$
        copyright            : (C) 2024 by The Nature Conservancy
        email                : miguel.canon@tnc.org
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
"""

import os
from qgis.PyQt import QtGui, QtWidgets, uic
from qgis.PyQt.QtCore import pyqtSignal
from qgis.core import QgsRasterLayer, QgsProject, QgsVectorLayer, QgsFillSymbol
from qgis.core import QgsRasterRenderer, QgsColorRampShader, QgsSingleBandPseudoColorRenderer
from qgis.core import QgsRasterLayer, QgsProject, QgsSingleBandPseudoColorRenderer, QgsColorRampShader, QgsRasterShader, QgsColorRampShader
from PyQt5.QtWidgets import QFileDialog, QMessageBox
from qgis.core import QgsProject, QgsRasterLayer, QgsVectorLayer, QgsRasterShader, QgsColorRampShader, QgsSingleBandPseudoColorRenderer, QgsProcessingFeedback
from qgis.gui import QgsMapToolEmitPoint
from PyQt5.QtGui import QColor
import os
import numpy as np
import sys
from PyQt5.QtGui import QColor
from qgis.gui import QgsMapToolEmitPoint
from qgis.utils import iface
from PyQt5.QtWidgets import QFileDialog, QMessageBox
import processing
from pysheds.grid import Grid
from .functions.ficheros import create_outputs_folders
# from .functions.ShpToRaster import PolyponToRaster
from .functions.Functions_Raster import resample_to_match, Erodability, PolyponToRaster, shp_to_csv_muestreador
import rasterio
from rasterio.enums import Resampling
import pandas as pd
from osgeo import gdal
from numba import config
import os
import pandas as pd
import json
from PyQt5.QtWidgets import QTableWidgetItem, QFileDialog, QInputDialog
from PyQt5.QtCore import QVariant
from qgis.core import QgsField, QgsVectorLayer, QgsProject, QgsFeature, QgsGeometry, QgsPointXY, QgsVectorFileWriter
from qgis.gui import QgsMapToolEmitPoint, QgsMapTool
from .functions.ficheros import Ficheros
from qgis.core import QgsCoordinateReferenceSystem

FORM_CLASS, _ = uic.loadUiType(os.path.join(
    os.path.dirname(__file__), 'Siga_Step_01_Config_dockwidget_base.ui'))


class Siga_Step_01_ConfigDockWidget(QtWidgets.QDockWidget, FORM_CLASS):

    closingPlugin = pyqtSignal()

    def __init__(self, parent=None):
        """Constructor."""
        super(Siga_Step_01_ConfigDockWidget, self).__init__(parent)



        self.setupUi(self)
        self.iface = iface



        #### Step 1 creacion de proyecto #############################
        # Connect signals to slots
        self.select_output.clicked.connect(self.select_output_folder)
        self.Button_Step_1.clicked.connect(self.create_project_folders)

        #### Step 2 Delimitacion Cuenca #############################
        self.Button_Load_Dem.clicked.connect(self.select_dem)  # Conectar botón Button_Load_Dem
        self.Button_Run_Dem.clicked.connect(self.run_dem_processes)
        self.Button_Run_Basin.clicked.connect(self.run_basin_processes)
        self.Button_Step_2.clicked.connect(self.move_to_topologia)

        # Create a map tool to capture mouse clicks
        self.point_tool = QgsMapToolEmitPoint(self.iface.mapCanvas())
        self.point_tool.canvasClicked.connect(self.set_coordinates)

        self.X_coor.mousePressEvent = self.activate_point_tool
        self.Y_coor.mousePressEvent = self.activate_point_tool

        #### Step 3 Topologia #############################
        self.Check_Embalse.toggled.connect(self.toggle_topology_inputs)
        self.Check_Cabeceras.toggled.connect(self.toggle_topology_inputs)
        self.Check_Nbs.toggled.connect(self.toggle_topology_inputs)

        self.Button_Load_Embalse.clicked.connect(lambda: self.select_shp(self.Path_Shp_Embalse))
        self.Button_Load_Cabeceras.clicked.connect(lambda: self.select_shp(self.Path_Shp_Cabeceras))
        self.Button_Load_NbS.clicked.connect(lambda: self.select_shp(self.Path_Raster_Nbs))
        self.Button_Run_Topo.clicked.connect(self.run_topology_processes)
        self.Button_Step_3.clicked.connect(self.move_to_series_de_tiempo)

        #### Step 4 Series de Tiempo #############################
        self.Button_Load_Stations.clicked.connect(self.load_shapefile_layer)
        self.Button_Load_Excel.clicked.connect(self.load_excel_file)
        self.Button_Run_Series.clicked.connect(self.run_series_processes)
        self.Button_Step_4.clicked.connect(self.move_to_mapas)

        #### Step 5 Mapas #############################
        # Conectar botones
        self.Button_Load_arenas.clicked.connect(lambda: self.load_and_resample_raster(self.Path_Raster_arenas, "arenas.tif"))
        self.Button_Load_limos.clicked.connect(lambda: self.load_and_resample_raster(self.Path_Raster_limos, "limos.tif"))
        self.Button_Load_arcillas.clicked.connect(lambda: self.load_and_resample_raster(self.Path_Raster_arcillas, "arcillas.tif"))
        self.Button_Load_OM.clicked.connect(lambda: self.load_and_resample_raster(self.Path_Raster_OM, "MO.tif"))
        self.Button_Load_Profundidad.clicked.connect(lambda: self.load_and_resample_raster(self.Path_Raster_Profundidad, "Zs.tif"))
        self.Button_Load_Usle_P.clicked.connect(lambda: self.load_and_resample_raster(self.Path_Raster_Usle_P, "P_usle.tif"))
        self.Button_Load_Usle_K.clicked.connect(lambda: self.load_and_resample_raster(self.Path_Raster_Usle_K, "K_usle.tif"))

        #base de datos
        self.zip_file_path = os.path.join(os.path.dirname(__file__), 'DATABASE.zip')

        self.Button_Load_arena_gdb.clicked.connect(lambda: self.load_and_resample_raster_from_zip(self.zip_file_path, "Sand/Sand.tif", "arenas.tif"))
        self.Button_Load_limos_gdb.clicked.connect(lambda: self.load_and_resample_raster_from_zip(self.zip_file_path, "Silt/Silt.tif", "limos.tif"))
        self.Button_Load_arcillas_gdb.clicked.connect(lambda: self.load_and_resample_raster_from_zip(self.zip_file_path, "Clay/Clay.tif", "arcillas.tif"))
        self.Button_Load_OM_gdb.clicked.connect( lambda: self.load_and_resample_raster_from_zip(self.zip_file_path, "OM/OM.tif", "MO.tif"))
        self.Button_Load_Profundidad_gdb.clicked.connect(lambda: self.load_and_resample_raster_from_zip(self.zip_file_path, "Zs/Zs.tif", "Zs.tif"))
        self.Button_Load_K_gdb.clicked.connect(lambda: self.load_and_resample_raster_from_zip(self.zip_file_path, "K/K.tif", "K_usle.tif"))

        self.Button_Load_LULC.clicked.connect(self.load_lulc_raster)
        self.Button_Estimacion_Usle_P.clicked.connect(self.create_usle_p_raster)
        self.Button_Estimacion_Usle_K.clicked.connect(self.run_erodability)
        self.Button_Step_5.clicked.connect(self.move_to_next_step)

        #### Step 6 Mapas 1 #############################

        self.Button_Load_idCiclo.clicked.connect(lambda: self.load_and_resample_raster(self.Path_Raster_idCiclo, 'idCiclo.tif'))
        self.Button_Load_idQ.clicked.connect(lambda: self.load_and_resample_raster(self.Path_Raster_idQ, 'idQ.tif'))
        self.Button_Load_ki.clicked.connect(lambda: self.load_and_resample_raster(self.Path_Raster_ki, 'ki.tif'))
        self.Button_Load_phi.clicked.connect(lambda: self.load_and_resample_raster(self.Path_Raster_phi, 'phi.tif'))
        self.Button_Load_C.clicked.connect(lambda: self.load_and_resample_raster(self.Path_Raster_C, 'c.tif'))
        self.Button_Load_Q5a.clicked.connect(lambda: self.load_and_resample_raster(self.Path_Raster_Q5a, 'Q5a.tif'))

        self.Button_Load_Paramos.clicked.connect(self.load_paramos_raster)

        self.Button_Estimacion_ki.clicked.connect(lambda: self.load_and_resample_raster_from_zip_op2(self.zip_file_path,"Ki/Ki.tif", 'Ki.tif'))
        self.Button_Estimacion_idCiclo.clicked.connect(self.create_idciclo_raster)
        self.Button_Estimacion_idQ.clicked.connect(self.create_idq_raster)
        self.Button_Run_P_T.clicked.connect(self.create_prioridad_transicion_rasters)

        self.Button_Step_6.clicked.connect(lambda: self.toolBox.setCurrentIndex(6))

        ### step 7 muestreador y  step 8 modulos

        # Conectar botones para Step 7 Muestreador
        self.Button_Load_Points.clicked.connect(self.load_shp_points)
        self.Button_Load_tramos.clicked.connect(self.load_shp_tramos)
        self.Button_Run_Muestreador.clicked.connect(self.run_muestreador)

        # Conectar botones de Modulos 8
        self.Button_Load_Mov_mass.clicked.connect(self.load_mov_mass)
        self.Button_Load_Vertimientos.clicked.connect(self.load_vertimientos)
        self.Button_Load_Ciclos.clicked.connect(self.load_ciclos)
        self.Button_Run_Modulos.clicked.connect(self.run_modulos)



        self.Button_Step_8.clicked.connect(lambda: self.toolBox.setCurrentIndex(7))

        ### step 9 Calibracion 1

        self.Button_Load_Weather.clicked.connect(lambda: self.load_excel_file_cal(self.Path_Excel_Weather))
        self.Button_Load_Restauration.clicked.connect(lambda: self.load_excel_file_cal(self.Path_Excel_Restauration))
        self.Button_Load_Phenologic.clicked.connect(lambda: self.load_excel_file_cal(self.Path_Excel_Phenologic))
        self.Button_Load_hydrologic.clicked.connect(lambda: self.load_excel_file_cal(self.Path_Excel_hydrologic))
        self.Button_Load_Sediments.clicked.connect(lambda: self.load_excel_file_cal(self.Path_Excel_Sediments))
        self.Button_Load_geotechnical.clicked.connect(lambda: self.load_excel_file_cal(self.Path_Excel_geotechnical))
        self.Button_Load_Diffuse.clicked.connect(lambda: self.load_excel_file_cal(self.Path_Excel_Diffuse))
        self.Button_Load_DBO.clicked.connect(lambda: self.load_excel_file_cal(self.Path_Excel_DBO))
        self.Button_Load_Reaeration.clicked.connect(lambda: self.load_excel_file_cal(self.Path_Excel_Reaeration))
        self.Button_Load_EColi.clicked.connect(lambda: self.load_excel_file_cal(self.Path_Excel_Ecoli))
        self.Button_Load_Nitrogen.clicked.connect(lambda: self.load_excel_file_cal(self.Path_Excel_Nitrogen))
        self.Button_Load_Phosphorus.clicked.connect(lambda: self.load_excel_file_cal(self.Path_Excel_Phosphorus))

        self.Button_Run_Parms_Cal.clicked.connect(self.run_parametros_cal)

        self.Button_Step_9.clicked.connect(lambda: self.toolBox.setCurrentIndex(8))


        ### step 9 Calibracion 2
        self.Button_Load_Tcoliforms.clicked.connect(lambda: self.load_excel_file_cal(self.Path_Excel_Tcoliforms))
        self.Button_Load_Turbidity.clicked.connect(lambda: self.load_excel_file_cal(self.Path_Excel_Turbidity))
        self.Button_Load_Conductividad.clicked.connect(lambda: self.load_excel_file_cal(self.Path_Excel_Conductividad))
        self.Button_Load_SST.clicked.connect(lambda: self.load_excel_file_cal(self.Path_Excel_SST))
        self.Button_Load_T_Correction.clicked.connect(lambda: self.load_excel_file_cal(self.Path_Excel_T_Correction))
        self.Button_Load_Temperature.clicked.connect(lambda: self.load_excel_file_cal(self.Path_Excel_Temperature))
        self.Button_Load_ADZQUASAR.clicked.connect(lambda: self.load_excel_file_cal(self.Path_Excel_ADZQUASAR))
        self.Button_Load_Ph.clicked.connect(lambda: self.load_excel_file_cal(self.Path_Excel_Ph))

        self.Button_Run_Parms_Cal_All.clicked.connect(self.run_parametros_cal2)




    #### Funciones Step 1 creacion de proyecto #############################
    def select_output_folder(self):
        """Open a dialog to select the output folder."""
        folder = QtWidgets.QFileDialog.getExistingDirectory(self, "Select Output Folder")
        if folder:
            self.output_path.setText(folder)

    def create_project_folders(self):
        """Create the project folders based on user input and move to the next widget."""
        name_project = self.name_project.text()
        name_scenario = self.name_scenario.text()
        output_path = self.output_path.text()

        if name_project and output_path:
            create_outputs_folders(output_path, name_project, name_scenario)
            QtWidgets.QMessageBox.information(self, "Success", "Project folders created successfully.")
            # Move to the next widget
            self.toolBox.setCurrentIndex(1)
        else:
            QtWidgets.QMessageBox.warning(self, "Input Error", "Please provide project name and output path.")

    #### Funciones Step 2 Delimitacion Cuenca #############################

    def set_coordinates(self, point):
        self.X_coor.setText(str(point.x()))
        self.Y_coor.setText(str(point.y()))

    def activate_point_tool(self, event):
        self.iface.mapCanvas().setMapTool(self.point_tool)

    def select_dem(self):
        """Select DEM file and load it into QGIS."""
        dem_path, _ = QFileDialog.getOpenFileName(self, "Seleccionar archivo DEM", "", "Archivos TIF (*.tif)")
        if dem_path:
            self.Path_Dem.setText(dem_path)  # Actualizar QLineEdit Path_Dem
            self.load_raster_layer(dem_path, "DEM")

    def load_raster_layer(self, path, layer_name):
        """Load raster layer into QGIS."""
        layer = QgsRasterLayer(path, layer_name)
        if not layer.isValid():
            QMessageBox.critical(self, "Error", f"No se pudo cargar la capa {layer_name}.")
        else:
            QgsProject.instance().addMapLayer(layer)

    def run_dem_processes(self):
        """Run DEM processes and save results."""
        dem_path = self.Path_Dem.text()
        threshold = float(self.Threshold.text())
        output_folder = os.path.join(self.output_path.text(), self.name_project.text(), 'temp',
                                     '01_Delimitacion_Cuenca')

        if not os.path.exists(output_folder):
            os.makedirs(output_folder)

        grid = Grid.from_raster(dem_path, data_name='dem')
        raw_dem = grid.read_raster(dem_path)

        # flooded_dem = grid.fill_depressions(raw_dem)
        # dem = grid.resolve_flats(flooded_dem)
        dem = raw_dem
        dirmap = (8, 9, 6, 3, 2, 1, 4, 7)
        flow_dir = grid.flowdir(dem, dirmap=dirmap)

        flow_accum = grid.accumulation(flow_dir, dirmap=dirmap)

        pixel_area = (grid.viewfinder.dy_dx[0] * grid.viewfinder.dy_dx[0]) / 1E6
        accum_area = flow_accum * pixel_area
        network = (accum_area > threshold) * 1

        # Save results
        dem_path = os.path.join(output_folder, 'DEM.tif')
        flow_dir_path = os.path.join(output_folder, 'FlowDir.tif')
        flow_accum_path = os.path.join(output_folder, 'FlowAccum.tif')
        network_path = os.path.join(output_folder, 'Network.tif')

        grid.to_raster(dem, dem_path)
        grid.to_raster(flow_dir, flow_dir_path)
        grid.to_raster(flow_accum, flow_accum_path)
        grid.to_raster(network, network_path)

        # Load FlowAccum and Network into QGIS
        flow_accum_layer = QgsRasterLayer(flow_accum_path, "Flow Accumulation")
        network_layer = QgsRasterLayer(network_path, "Network")

        # if flow_accum_layer.isValid():
        #     QgsProject.instance().addMapLayer(flow_accum_layer)

        if network_layer.isValid():
            shader = QgsRasterShader()
            color_ramp = QgsColorRampShader()
            color_ramp.setColorRampType(QgsColorRampShader.Interpolated)
            color_ramp_item_list = [QgsColorRampShader.ColorRampItem(1, QColor(0, 0, 255))]
            color_ramp.setColorRampItemList(color_ramp_item_list)
            shader.setRasterShaderFunction(color_ramp)
            renderer = QgsSingleBandPseudoColorRenderer(network_layer.dataProvider(), 1, shader)
            network_layer.setRenderer(renderer)
            QgsProject.instance().addMapLayer(network_layer)

    def run_basin_processes(self):
        """Run basin delineation processes."""
        x_coor = float(self.X_coor.text())
        y_coor = float(self.Y_coor.text())
        output_folder = os.path.join(self.output_path.text(), self.name_project.text(), 'temp',
                                     '01_Delimitacion_Cuenca')

        dem_path = os.path.join(output_folder, 'DEM.tif')
        flow_dir_path = os.path.join(output_folder, 'FlowDir.tif')

        grid = Grid.from_raster(dem_path, data_name='dem')
        flow_dir = grid.read_raster(flow_dir_path)

        col, row = grid.nearest_cell(x_coor, y_coor, snap="center")
        x_new = grid.extent[0] + (col * grid.viewfinder.dy_dx[0])
        y_new = grid.extent[3] - (row * grid.viewfinder.dy_dx[0])

        watershed = grid.catchment(x=x_new, y=y_new, fdir=flow_dir, dirmap=(8, 9, 6, 3, 2, 1, 4, 7),
                                   xytype='coordinate')
        watershed = watershed * 1

        # Save and load watershed
        watershed_path = os.path.join(output_folder, 'Watershed.tif')
        grid.to_raster(watershed, watershed_path)

        watershed_shapefile = os.path.join(output_folder, 'Watershed.shp')
        processing.run("gdal:polygonize", {
            'INPUT': watershed_path,
            'BAND': 1,
            'FIELD': 'DN',
            'EIGHT_CONNECTEDNESS': False,
            'EXTRA': '',
            'OUTPUT': watershed_shapefile
        })

        watershed_layer = QgsVectorLayer(watershed_shapefile, "Watershed", "ogr")
        if watershed_layer.isValid():
            symbol = QgsFillSymbol.createSimple({'color_border': 'red', 'width_border': '1', 'style': 'no'})
            watershed_layer.renderer().setSymbol(symbol)
            QgsProject.instance().addMapLayer(watershed_layer)
        else:
            self.show_message("Error", "No se pudo cargar la capa Watershed.")

    def show_message(self, title, message):
        """Show a message box."""
        QtWidgets.QMessageBox.information(self, title, message)

    def move_to_topologia(self):
        """Move to the next widget Topologia."""
        self.toolBox.setCurrentIndex(2)
    #### Funciones Step 3 Topologia #############################
    def select_shp(self, line_edit):
        shp_path, _ = QFileDialog.getOpenFileName(self, "Seleccionar archivo SHP", "", "Archivos SHP (*.shp)")
        if shp_path:
            line_edit.setText(shp_path)
            self.load_vector_layer(shp_path, line_edit.objectName())

    def load_vector_layer(self, path, layer_name="Reservoir"):
        layer = QgsVectorLayer(path, layer_name, "ogr")
        if not layer.isValid():
            QMessageBox.critical(self, "Error", f"No se pudo cargar la capa {layer_name}.")
        else:
            QgsProject.instance().addMapLayer(layer)

    def toggle_topology_inputs(self):
        self.Path_Shp_Embalse.setEnabled(self.Check_Embalse.isChecked())
        self.Button_Load_Embalse.setEnabled(self.Check_Embalse.isChecked())

        self.Path_Shp_Cabeceras.setEnabled(self.Check_Cabeceras.isChecked())
        self.Button_Load_Cabeceras.setEnabled(self.Check_Cabeceras.isChecked())

        self.Path_Raster_Nbs.setEnabled(self.Check_Nbs.isChecked())
        self.Button_Load_NbS.setEnabled(self.Check_Nbs.isChecked())

    def run_topology_processes(self):
        output_folder = os.path.join(self.output_path.text(), self.name_project.text(), 'temp', '02_Topologia')

        if not os.path.exists(output_folder):
            os.makedirs(output_folder)

        name_project = self.name_project.text()
        x_coor = float(self.X_coor.text())
        y_coor = float(self.Y_coor.text())
        name_scenario = self.name_scenario.text()

        embalse_path = self.Path_Shp_Embalse.text() if self.Check_Embalse.isChecked() else None
        cabeceras_path = self.Path_Shp_Cabeceras.text() if self.Check_Cabeceras.isChecked() else None
        nbs_path = self.Path_Raster_Nbs.text() if self.Check_Nbs.isChecked() else None

        dem_path = self.Path_Dem.text()
        flow_dir_path = os.path.join(self.output_path.text(), self.name_project.text(), 'temp',
                                     '01_Delimitacion_Cuenca', 'FlowDir.tif')
        flow_accum_path = os.path.join(self.output_path.text(), self.name_project.text(), 'temp',
                                       '01_Delimitacion_Cuenca', 'FlowAccum.tif')

        if embalse_path:
            embalse_raster_path = os.path.join(self.output_path.text(), self.name_project.text(), 'temp',
                                               'Reservoir.tif')
            PolyponToRaster(PathShp=embalse_path, PathOutput=embalse_raster_path, PathRaster=dem_path, Value='Id')
        else:
            embalse_raster_path = None

        # Definir el criterio basado en las selecciones de los CheckBoxes
        criteria = 1  # Default criteria
        if self.Check_Nbs.isChecked() and self.Check_Embalse.isChecked() and self.Check_Cabeceras.isChecked():
            criteria = 4
        elif self.Check_Embalse.isChecked() and self.Check_Cabeceras.isChecked():
            criteria = 3
        elif self.Check_Embalse.isChecked():
            criteria = 2

        from .functions.BuildingTopology import build_topology

        try:
            build_topology(dem_path, flow_dir_path, flow_accum_path, embalse_raster_path, cabeceras_path, nbs_path,
                           x_coor, y_coor, name_scenario,name_project, output_folder, criteria)

            # Copiar el archivo de topología a la ruta especificada
            from shutil import copyfile
            topology_file = os.path.join(output_folder, f'Topology_{name_project}.txt')
            output_pth = os.path.join(self.output_path.text(), self.name_project.text(), 'entradas', 'topologia')
            if not os.path.exists(output_pth):
                os.makedirs(output_pth)
            copyfile(topology_file, os.path.join(output_pth, f'Topology_{name_project}.txt'))

            self.show_message("Success", "Topology processes completed successfully.")
        except Exception as e:
            self.show_message("Error", f"Topology process failed: {e}")

    def move_to_series_de_tiempo(self):
        self.toolBox.setCurrentIndex(3)
    #### Funciones Step 4 Series de Tiempo #############################
    def load_shapefile_layer(self):
        shapefile_path, _ = QFileDialog.getOpenFileName(self, "Seleccionar archivo de estaciones (SHP)", "",
                                                        "Archivos SHP (*.shp)")
        if shapefile_path:
            self.Path_Shp_Stations.setText(shapefile_path)
            layer = QgsVectorLayer(shapefile_path, "Estaciones", "ogr")
            if not layer.isValid():
                QMessageBox.critical(self, "Error", "No se pudo cargar la capa de estaciones.")
            else:
                QgsProject.instance().addMapLayer(layer)

    def load_excel_file(self):
        excel_path, _ = QFileDialog.getOpenFileName(self, "Seleccionar archivo Excel", "", "Archivos Excel (*.xlsx *.xls)")
        if excel_path:
            self.Path_excel_time_series.setText(excel_path)

    def run_series_processes(self):
        try:
            output_pth = os.path.join(self.output_path.text(), self.name_project.text(), 'entradas/')
            if not os.path.exists(output_pth):
                os.makedirs(output_pth)

            path_meta = self.Path_Shp_Stations.text()
            path_df = self.Path_excel_time_series.text()
            variables = ['PV', 'TAmax', 'TAmin', 'RS', 'HR', 'Ux', 'Uy']

            from .functions.ficheros import Ficheros
            import pandas as pd
            import geopandas as gpd
            ficheros_instance = Ficheros(ruta_cuenca_SIGA=output_pth)



            for var in variables:
                print(var)
                df_in = pd.read_excel(path_df, var, index_col=0)
                df_meta = gpd.read_file(path_meta)
                df_meta = df_meta[df_meta[var] == 1]
                ficheros_instance.ExportarSeriesSIGA(df=df_in, df_metadatos=df_meta, nombre_archivo_serie='series_' + var + '.txt')


            self.show_message("Success", "Series de tiempo exportadas correctamente.")
        except Exception as e:
            self.show_message("Error", f"Proceso de series de tiempo fallido: {e}")

    def move_to_mapas(self):
        """Move to the next widget Mapas."""
        self.toolBox.setCurrentIndex(4)

    #### Funciones Step 5 Mapas  #############################

    def add_raster_to_qgis(self, raster_path):
        layer = QgsRasterLayer(raster_path, os.path.basename(raster_path))
        if not layer.isValid():
            self.show_message("Error", f"Failed to load raster layer: {raster_path}")
        else:
            QgsProject.instance().addMapLayer(layer)

    def load_and_resample_raster(self, path_line_edit, output_filename):
        raster_path, _ = QFileDialog.getOpenFileName(self, "Seleccionar archivo raster", "", "Archivos TIF (*.tif)")
        if raster_path:
            path_line_edit.setText(raster_path)
            output_path = os.path.join(self.output_path.text(), self.name_project.text(), 'entradas', 'mapas',
                                       self.name_scenario.text(), output_filename)
            resample_to_match(raster_path, self.Path_Dem.text(), output_path)
            self.add_raster_to_qgis(output_path)
            self.show_message("Success", f"Raster {output_filename} cargado y procesado correctamente.")

    def divide_raster_values_by_100(self, raster_path):
        """Divide raster values by 100."""
        with rasterio.open(raster_path, 'r+') as dataset:
            for i in range(1, dataset.count + 1):
                data = dataset.read(i)
                data = data / 100.0
                dataset.write(data, i)

    def load_and_resample_raster_from_zip(self, zip_path, zip_internal_path, output_filename):
        """Load raster from zip, resample and divide by 100."""
        zip_file_path = 'DATABASE.zip'
        # path_raster_global = f"zip://{zip_file_path}!/{zip_internal_path}"
        path_raster_global = f'/vsizip/{zip_path}/{zip_internal_path}'
        output_path = os.path.join(self.output_path.text(), self.name_project.text(), ''
                                                                                      'entradas', 'mapas',
                                   self.name_scenario.text(), output_filename)
        try:
            resample_to_match(path_raster_global, self.Path_Dem.text(), output_path)

            self.divide_raster_values_by_100(output_path)
            self.show_message("Success",
                              f"Raster {output_filename} cargado, procesado y dividido correctamente desde el zip.")
            self.add_raster_to_qgis(output_path)

        except Exception as e:
            self.show_message("Error", f"Error al cargar y procesar el raster desde el zip: {e}")

    def load_and_resample_raster_from_zip_op2(self, zip_path, zip_internal_path, output_filename):
        """Load raster from zip, resample and divide by 100."""
        zip_file_path = 'DATABASE.zip'
        # path_raster_global = f"zip://{zip_file_path}!/{zip_internal_path}"
        path_raster_global = f'/vsizip/{zip_path}/{zip_internal_path}'
        output_path = os.path.join(self.output_path.text(), self.name_project.text(), ''
                                                                                      'entradas', 'mapas',
                                   self.name_scenario.text(), output_filename)
        try:
            resample_to_match(path_raster_global, self.Path_Dem.text(), output_path)
            self.show_message("Success",
                              f"Raster {output_filename} cargado, procesado y dividido correctamente desde el zip.")
            self.add_raster_to_qgis(output_path)

        except Exception as e:
            self.show_message("Error", f"Error al cargar y procesar el raster desde el zip: {e}")

    def load_lulc_raster(self):
        raster_path, _ = QFileDialog.getOpenFileName(self, "Seleccionar archivo raster o shapefile", "",
                                                     "Archivos TIF (*.tif);;Archivos SHP (*.shp)")
        if raster_path:
            self.Path_Raster_LULC.setText(raster_path)
            if raster_path.endswith('.tif'):
                # Cargar y modificar raster
                raster = gdal.Open(raster_path, gdal.GA_Update)
                band = raster.GetRasterBand(1)
                arr = band.ReadAsArray()
                values_to_replace = [411, 412, 413, 421, 422, 423, 511, 512, 513, 514, 521, 523]
                for value in values_to_replace:
                    arr[arr == value] = 231
                band.WriteArray(arr)
                output_path = os.path.join(self.output_path.text(), self.name_project.text(), 'entradas', 'mapas',
                                           self.name_scenario.text(), "CLC.tif")
                resample_to_match(raster_path, self.Path_Dem.text(), output_path)
                self.show_message("Success", "Raster LULC cargado, modificado y procesado correctamente.")
                self.add_raster_to_qgis(output_path)
            elif raster_path.endswith('.shp'):
                # Convertir SHP a raster
                output_path = os.path.join(self.output_path.text(), self.name_project.text(), 'entradas', 'mapas',
                                           self.name_scenario.text(), "CLC.tif")

                PolyponToRaster(PathShp =raster_path,PathOutput = output_path,PathRaster = self.Path_Dem.text(),Value = "Code" )
                self.show_message("Success", "Shapefile LULC cargado y convertido a raster correctamente.")
                self.add_raster_to_qgis(output_path)

    def create_usle_p_raster(self):

        output_path = os.path.join(self.output_path.text(), self.name_project.text(), 'entradas', 'mapas',
                                   self.name_scenario.text(), "P_usle.tif")

        self.create_raster_filled_with_value(output_path, 1)
        self.add_raster_to_qgis(output_path)
        self.show_message("Success", "Raster USLE-P creado correctamente.")

    def run_erodability(self):
        PathK = os.path.join(self.output_path.text(), self.name_project.text(), 'entradas', 'mapas',
                             self.name_scenario.text(), 'K_usle.tif')
        try:
            Erodability(PathK, self.Path_Dem.text(), self.Path_Raster_arenas.text(), self.Path_Raster_limos.text(),
                        self.Path_Raster_arcillas.text(), self.Path_Raster_OM.text())
            self.add_raster_to_qgis(PathK)
            self.show_message("Success", "Erodability USLE-K calculado correctamente.")
        except Exception as e:
            self.show_message("Error", f"Error en el cálculo de Erodability USLE-K: {e}")

    def move_to_next_step(self):
        self.toolBox.setCurrentIndex(5)

    #### Funciones Step 6 Mapas 1 ############################
    def create_raster_filled_with_value(self, output_path, value):
        with rasterio.open(self.Path_Dem.text()) as src:
            meta = src.meta.copy()
            data = src.read(1)
            data.fill(value)

            with rasterio.open(output_path, 'w', **meta) as dst:
                dst.write(data, 1)

    def create_sequential_raster(self, input_raster_path, output_raster_path):
        with rasterio.open(input_raster_path) as src:
            meta = src.meta.copy()
            data = src.read(1)
            unique_values = np.unique(data)
            value_map = {old: new for new, old in enumerate(unique_values, start=1)}

            for old, new in value_map.items():
                data[data == old] = new

            with rasterio.open(output_raster_path, 'w', **meta) as dst:
                dst.write(data, 1)

    def load_paramos_raster(self):
        raster_path, _ = QFileDialog.getOpenFileName(self, "Load Raster or Shapefile", "",
                                                     "Raster files (*.tif *.img);;Shapefile (*.shp)")
        if raster_path:
            self.Path_Raster_Paramos.setText(raster_path)
            output_path = os.path.join(self.output_path.text(), self.name_project.text(), 'entradas', 'mapas',
                                       self.name_scenario.text(), 'paramos.tif')
            if raster_path.endswith('.shp'):
                PolyponToRaster(raster_path, output_path, self.Path_Dem.text(), "Code")
            else:
                resample_to_match(raster_path, self.Path_Dem.text(), output_path)
            self.show_message("Success", "Raster Paramos cargado, modificado y procesado correctamente.")
            self.add_raster_to_qgis(output_path)

    def create_idciclo_raster(self):
        output_path = os.path.join(self.output_path.text(), self.name_project.text(), 'entradas', 'mapas',
                                   self.name_scenario.text(), 'idCiclo.tif')
        self.create_raster_filled_with_value(output_path, 1)
        self.show_message("Success", "Raster idCiclo cargado, modificado y procesado correctamente.")
        self.add_raster_to_qgis(output_path)

    def create_idq_raster(self):
        clc_raster_path = os.path.join(self.output_path.text(), self.name_project.text(), 'entradas', 'mapas',
                                       self.name_scenario.text(), 'CLC.tif')
        output_path = os.path.join(self.output_path.text(), self.name_project.text(), 'entradas', 'mapas',
                                   self.name_scenario.text(), 'idQ.tif')
        self.create_sequential_raster(clc_raster_path, output_path)
        self.show_message("Success", "Raster idq cargado, modificado y procesado correctamente.")
        self.add_raster_to_qgis(output_path)

    def create_prioridad_transicion_rasters(self):
        base_path = os.path.join(self.output_path.text(), self.name_project.text(), 'entradas', 'mapas',
                                 self.name_scenario.text())
        prioridad_path = os.path.join(base_path, 'prioridad.tif')
        transicion_path = os.path.join(base_path, 'transicion.tif')
        self.create_raster_filled_with_value(prioridad_path, 1)
        self.create_raster_filled_with_value(transicion_path, 1)
        self.show_message("Success", "Raster Prioridad y Transicion cargados, modificado y procesado correctamente.")
        self.add_raster_to_qgis(prioridad_path)
        self.add_raster_to_qgis(transicion_path)

    #### Funciones Step 7 Muestreador  y Step 8 Modulos ############################

    #### Funciones Step 7 Muestreador ############################
    def add_layer_to_qgis(self, layer_path, layer_name):
        layer = QgsVectorLayer(layer_path, layer_name, "ogr")
        if not layer.isValid():
            self.show_message("Error", f"Failed to load layer: {layer_name}")
            return
        QgsProject.instance().addMapLayer(layer)

    def load_shp_points(self):
        shp_path, _ = QFileDialog.getOpenFileName(self, "Seleccionar archivo SHP de puntos", "", "Archivos SHP (*.shp)")
        if shp_path:
            path_out = os.path.join(os.path.dirname(__file__), 'archivos_csv', 'muestreador/')
            if not os.path.exists(path_out):
                os.makedirs(path_out)
            shp_to_csv_muestreador(path_out, shp_path)
            self.Path_shp_points.setText(shp_path)
            self.add_layer_to_qgis(shp_path, "shp_points")
            self.show_message("Success", "Archivo de puntos cargado y convertido a CSV exitosamente.")

    def load_shp_tramos(self):
        shp_path, _ = QFileDialog.getOpenFileName(self, "Seleccionar archivo SHP de tramos", "", "Archivos SHP (*.shp)")
        if shp_path:
            path_out = os.path.join(os.path.dirname(__file__), 'archivos_csv', 'muestreador/')
            if not os.path.exists(path_out):
                os.makedirs(path_out)
            shp_to_csv_muestreador(path_out, shp_path)
            self.Path_shp_tramos.setText(shp_path)
            self.add_layer_to_qgis(shp_path, "shp_stretch of river")
            self.show_message("Success", "Archivo de tramos cargado y convertido a CSV exitosamente.")

    def run_muestreador(self):
        output_pth = os.path.join(self.output_path.text(), self.name_project.text(), 'entradas/')
        ficheros_instance = Ficheros(ruta_cuenca_SIGA=output_pth, archivo_muestreador='muestreador.txt')
        path = os.path.join(os.path.dirname(__file__), 'archivos_csv', 'muestreador/')
        path_json = os.path.join(os.path.dirname(__file__), 'functions')
        with open(rf'{path_json}/Diccionario_ficheros.json') as json_file:
            diccionarios_ficheros = json.load(json_file)
        ficheros_instance.crear_archivo_muestreador(diccionarios_ficheros['dic_muestreador'], path)
        self.show_message("Success", "Muestreador processes completed successfully.")

    #### Funciones Step 8 Modulo ############################

    def load_mov_mass(self):
        excel_path, _ = QFileDialog.getOpenFileName(self, "Seleccionar archivo Excel", "",
                                                    "Archivos Excel (*.xlsx *.xls)")
        if excel_path:
            self.Path_excel_Mov_mass.setText(excel_path)

    def load_vertimientos(self):
        excel_path, _ = QFileDialog.getOpenFileName(self, "Seleccionar archivo Excel", "",
                                                    "Archivos Excel (*.xlsx *.xls)")
        if excel_path:
            self.Path_excel_Vertimientos.setText(excel_path)

    def load_ciclos(self):
        excel_path, _ = QFileDialog.getOpenFileName(self, "Seleccionar archivo Excel", "",
                                                    "Archivos Excel (*.xlsx *.xls)")
        if excel_path:
            self.Path_excel_Ciclos.setText(excel_path)

    def run_modulos(self):
        output_pth = os.path.join(self.output_path.text(), self.name_project.text(), 'entradas/')
        ficheros = Ficheros(ruta_cuenca_SIGA=output_pth)

        # Procesar Movimientos en Masa
        excel_path_mov_mass = self.Path_excel_Mov_mass.text()
        if excel_path_mov_mass:
            df = pd.read_excel(excel_path_mov_mass, engine='openpyxl')

            # Asegurarse de que la columna de fecha se transforme en Año, Mes y Día
            if 'Fecha' in df.columns:
                df['Fecha'] = pd.to_datetime(df['Fecha'])
                df['Año'] = df['Fecha'].dt.year
                df['Mes'] = df['Fecha'].dt.month
                df['Día'] = df['Fecha'].dt.day
                df.drop(columns=['Fecha'], inplace=True)

            # Reordenar columnas para asegurar que Año, Mes y Día estén al principio
            column_order = ['Año', 'Mes', 'Día'] + [col for col in df.columns if col not in ['Año', 'Mes', 'Día']]
            df = df[column_order]

            # Crear el diccionario necesario
            dic_movmasa = {
                'n_deslizamientos': str(len(df)),
                'datos_faltantes': '-9999',
                'datos': df
            }
            # Crear el archivo de salida
            ficheros.crear_archivo_movmasa(dic_movmasa)

        # Procesar Vertimientos
        excel_path_vertimientos = self.Path_excel_Vertimientos.text()
        if excel_path_vertimientos:
            df_vertimientos = pd.read_excel(excel_path_vertimientos, engine='openpyxl')

            # Crear el diccionario necesario para Vertimientos
            dic_vertimientos = {
                'n_puntos': str(len(df_vertimientos)),
                'datos_faltantes': '-9999',
                'datos': df_vertimientos
            }

            # Crear el archivo de salida Vertimientos
            ficheros.crear_archivo_vertimientos(dic_vertimientos)

        # Procesar Ciclos
        excel_path_ciclos = self.Path_excel_Ciclos.text()
        if excel_path_ciclos:
            df_ciclos = pd.read_excel(excel_path_ciclos, engine='openpyxl')

            # Crear el diccionario necesario para Ciclos
            dic_ciclos = {
                'VARIABLE': 'Vertimientos',
                'PERIODO EN DÍAS DEL CICLO': '366',
                'NÚMERO DE CICLOS REPRESENTADOS': str(len(df_ciclos.columns[1:])),
                'RESOLUCIÓN TEMPORAL EN DÍAS': '1',
                'MODELO A PARTIR DE VARIBLE SECUNDARIA': 'ninguno',
                'datos': df_ciclos
            }

            # Crear el archivo de salida para Ciclos
            ficheros.crear_archivo_ciclo_cargas(dic_ciclos)

        self.show_message("Success", "Modules processed successfully.")

    #### Funciones Step 9 parametros calibracion parte 1 ############################
    def load_excel_file_cal(self, line_edit):
        excel_path, _ = QFileDialog.getOpenFileName(self, "Seleccionar archivo Excel", "",
                                                    "Archivos Excel (*.xlsx *.xls)")
        if excel_path:
            line_edit.setText(excel_path)

    def convert_excel_to_csv(self, checkbox, line_edit, save_name):
        if checkbox.isChecked():
            excel_path = line_edit.text()
            if excel_path:
                df = pd.read_excel(excel_path, engine='openpyxl')
                path_out = os.path.join(os.path.dirname(__file__), 'archivos_csv', 'calibracion/')
                if not os.path.exists(path_out):
                    os.makedirs(path_out)
                csv_path = os.path.join(path_out, save_name)
                df.to_csv(csv_path, index=False)
                self.show_message("Success", f"{save_name} has been saved successfully.")
            else:
                self.show_message("Error", f"Path for {save_name} is empty.")
        # else:
        #     self.show_message("Info", f"{save_name} is not selected.")

    def run_parametros_cal(self):
        self.convert_excel_to_csv(self.Check_Weather, self.Path_Excel_Weather, '01_ModeloMeteorologico.csv')
        self.convert_excel_to_csv(self.Check_restoration, self.Path_Excel_Restauration, '02_Restauracion.csv')
        self.convert_excel_to_csv(self.Check_Phenologic, self.Path_Excel_Phenologic, '03_ModeloFenologico.csv')
        self.convert_excel_to_csv(self.Check_hydrologic, self.Path_Excel_hydrologic, '04_ModeloHidrologico.csv')
        self.convert_excel_to_csv(self.Check_Sediments, self.Path_Excel_Sediments, '05_ModeloSedimentologico.csv')
        self.convert_excel_to_csv(self.Check_geotechnical, self.Path_Excel_geotechnical, '06_ModeloGeotecnico.csv')
        self.convert_excel_to_csv(self.Check_Diffuse, self.Path_Excel_Diffuse, '07_CargasDifusas.csv')
        self.convert_excel_to_csv(self.Check_DBO, self.Path_Excel_DBO, '08_DBOCarbonicea.csv')
        self.convert_excel_to_csv(self.Check_Reaeration, self.Path_Excel_Reaeration, '09_Reaireacion.csv')
        self.convert_excel_to_csv(self.Check_EColi, self.Path_Excel_Ecoli, '10_EColi.csv')
        self.convert_excel_to_csv(self.Check_Nitrogen, self.Path_Excel_Nitrogen, '11_Nitrogeno.csv')
        self.convert_excel_to_csv(self.Check_Phosphorus, self.Path_Excel_Phosphorus, '12_Fosforo.csv')

    #### Funciones Step 10 parametros calibracion parte 2 ############################

    def run_parametros_cal2(self):
        self.convert_excel_to_csv(self.Check_Tcoliforms, self.Path_Excel_Tcoliforms, '13_ColiformesTotales.csv')
        self.convert_excel_to_csv(self.Check_Turbidity, self.Path_Excel_Turbidity, '14_Turbiedad.csv')
        self.convert_excel_to_csv(self.Check_Conductividad, self.Path_Excel_Conductividad, '15_ConductividadElectrica.csv')
        self.convert_excel_to_csv(self.Check_SST, self.Path_Excel_SST, '16_SolidosSuspendidosTotales.csv')
        self.convert_excel_to_csv(self.Check_T_Correction, self.Path_Excel_T_Correction, '17_CorreccionTemperatura.csv')
        self.convert_excel_to_csv(self.Check_Temperature, self.Path_Excel_Temperature, '18_Temperatura.csv')
        self.convert_excel_to_csv(self.Check_ADZQUASAR, self.Path_Excel_ADZQUASAR, '19_FactoresADZQUASAR.csv')
        self.convert_excel_to_csv(self.Check_Ph, self.Path_Excel_Ph, '20_FactorespH.csv')

        path_json = os.path.join(os.path.dirname(__file__), 'functions')
        with open(rf'{path_json}/Diccionario_ficheros.json') as json_file:
            diccionarios_ficheros_cal = json.load(json_file)
        output_pth = os.path.join(self.output_path.text(), self.name_project.text(), 'entradas/')
        ficheros_instance = Ficheros(ruta_cuenca_SIGA=output_pth, archivo_fact_cal='Parametros.txt')
        path_files = os.path.join(os.path.dirname(__file__), 'archivos_csv', 'calibracion/')
        ficheros_instance.crear_archivo_factores_calibracion(diccionarios_ficheros_cal['dic_factores_calibracion'],
                                                             path_files)

        self.show_message("Success", "Calibration parameters processed successfully.")

    def closeEvent(self, event):
        self.closingPlugin.emit()
        event.accept()
